AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/ReconcileAndLocalSaveOperationTests.swift

Unit tests for ReconcileAndLocalSaveOperationTests

---

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/OutgoingMutationQueue.swift
AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/OutgoingMutationQueueTestsWithMockStateMachine.swift
AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/ReconcileAndLocalSaveOperationTests.swift
AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/TestSupport/MockStateMachine.swift
AmplifyPlugins/DataStore/DataStoreCategoryPlugin.xcodeproj/project.pbxproj

Added Unit tests for OutgoingMutationQueue state and minor refactor

---

Amplify/Categories/API/Request/RESTOperationRequest.swift
Amplify/Categories/API/Request/RESTRequest.swift
AmplifyPlugins/API/AWSAPICategoryPlugin/Operation/AWSRESTOperation.swift
AmplifyPlugins/API/AWSAPICategoryPlugin/Support/Utils/RESTOperationRequest+RESTRequest.swift
AmplifyPlugins/API/AWSAPICategoryPlugin/Support/Utils/RESTOperationRequestUtils.swift

Added Header map to Rest request

---

AWSPredictionsPlugin.podspec
AmplifyPlugins.podspec
AmplifyPlugins/Predictions/Podfile
fastlane/Fastfile

Moved out predictions podspec

---

AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/AWSMutationDatabaseAdapterTests.swift
AmplifyPlugins/DataStore/DataStoreCategoryPlugin.xcodeproj/project.pbxproj

 Adding unit tests for AWSMutationDatabaseAdapterTests

---

README.md

- consolidated API
- updated development instructions

Update wording on README.md

---

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/AWSDataStorePlugin+DefaultLogger.swift

Adding some content to this class so that swift format will not crash

---

README.md

Updated readme in `develop` branch. Since we are currently still merging to master, i'm merging to master so the readme on the front page reflects the updated content. 

Update wording on README.md (#235)

---

CHANGELOG.md

Update changelog with commits since 0.9.0 release: https://github.com/aws-amplify/amplify-ios/compare/0.9.0...master

Update changelog.md 0.10.0

---

Amplify.xcodeproj/project.pbxproj
Amplify/Categories/API/ClientBehavior/APICategoryClientBehavior.swift
Amplify/Categories/API/ClientBehavior/APICategoryReachabilityBehavior.swift
Amplify/Categories/API/ClientBehavior/AmplifyAPICategory+ReachabilityBehavior.swift
AmplifyPlugins/API/APICategoryPlugin.xcodeproj/project.pbxproj
AmplifyPlugins/API/AWSAPICategoryPlugin/AWSAPIPlugin+Reachability.swift
AmplifyPlugins/API/AWSAPICategoryPlugin/AWSAPIPlugin+Resettable.swift
AmplifyPlugins/API/AWSAPICategoryPlugin/AWSAPIPlugin.swift
AmplifyPlugins/API/AWSAPICategoryPlugin/Reachability/NetworkReachabilityNotifier.swift
AmplifyPlugins/API/AWSAPICategoryPluginTests/Reachability/NetworkReachabilityNotifierTests.swift
AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/OutgoingMutationQueue/MutationRetryNotifier.swift
AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/OutgoingMutationQueue/OutgoingMutationQueue.swift
AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/OutgoingMutationQueue/SyncMutationToCloudOperation.swift
AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/MutationQueue/SyncMutationToCloudOperationTests.swift
AmplifyTestCommon/Mocks/MockAPICategoryPlugin.swift

Exposed reachability in API category and using for OutgoingMutationQueue retries

---

AWSPluginsCore.podspec
AWSPredictionsPlugin.podspec
Amplify.podspec
Amplify/Info.plist
AmplifyFunctionalTests/Info.plist
AmplifyPlugins.podspec
AmplifyPlugins/API/AWSAPICategoryPlugin/Info.plist
AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/Resources/Info.plist
AmplifyPlugins/Core/AWSPluginsCore/Info.plist
AmplifyPlugins/Core/AWSPluginsCore/ServiceConfiguration/AmplifyAWSServiceConfiguration.swift
AmplifyPlugins/Core/AWSPluginsCoreTests/Info.plist
AmplifyPlugins/Core/AWSPluginsTestCommon/Info.plist
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Resources/Info.plist
AmplifyPlugins/Predictions/CoreMLPredictionsPlugin/Resources/Info.plist
AmplifyPlugins/Storage/AWSS3StoragePlugin/Resources/Info.plist
AmplifyTestApp/Info.plist
AmplifyTestCommon.podspec
AmplifyTestCommon/Info.plist
AmplifyTests/Info.plist
CoreMLPredictionsPlugin.podspec
fastlane/Fastfile

Bump version to 0.10.0

---

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngine+Action.swift
AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngine+IncomingEventReconciliationQueueEvent.swift
AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngine+Resolver.swift
AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngine+Retryable.swift
AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngine+State.swift
AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngine.swift
AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/AWSIncomingEventReconciliationQueue.swift

Addressing comments from PRs 321-324

---

CHANGELOG.md

*Description of changes:* updating changelog to reflect predictions changes

Update CHANGELOG.md for Upcoming Release

---

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/StorageEngineAdapter+SQLite.swift

royjit@ - Thank you so much for calling this out!!

Set excludeFromBackup flag to avoid backing up sqlite3 db

---

AmplifyPlugins/Auth/AWSAuthPlugin.xcodeproj/project.pbxproj
AmplifyPlugins/Auth/AWSAuthPlugin.xcodeproj/xcshareddata/xcschemes/AWSAuthPlugin.xcscheme
AmplifyPlugins/Auth/AWSAuthPlugin.xcodeproj/xcshareddata/xcschemes/AWSAuthPluginIntegrationTests.xcscheme
AmplifyPlugins/Auth/AWSAuthPlugin.xcodeproj/xcshareddata/xcschemes/HostApp.xcscheme
AmplifyPlugins/Auth/AWSAuthPlugin/AWSAuthPlugin.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Resources/Info.plist
AmplifyPlugins/Auth/AWSAuthPluginIntegrationTests/AWSAuthPluginIntegrationTests.swift
AmplifyPlugins/Auth/AWSAuthPluginIntegrationTests/Info.plist
AmplifyPlugins/Auth/AWSAuthPluginTests/AWSAuthPluginTests.swift
AmplifyPlugins/Auth/AWSAuthPluginTests/Info.plist
AmplifyPlugins/Auth/HostApp/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
AmplifyPlugins/Auth/HostApp/Resources/Assets.xcassets/Contents.json
AmplifyPlugins/Auth/HostApp/Resources/Base.lproj/LaunchScreen.storyboard
AmplifyPlugins/Auth/HostApp/Resources/Base.lproj/Main.storyboard
AmplifyPlugins/Auth/HostApp/Resources/Info.plist
AmplifyPlugins/Auth/HostApp/Source/AppDelegate.swift
AmplifyPlugins/Auth/HostApp/Source/SceneDelegate.swift
AmplifyPlugins/Auth/HostApp/Source/ViewController.swift
AmplifyPlugins/Auth/Podfile

- Initial setup fro auth plugin implementation.
- Targets created for AWSAuthPlugin, unit test and integration test.

[DONOT merge to master]Bare bone setup for Auth Plugin

---

CHANGELOG.md

Updating changelog for changes after 0.10.0 tag

Update CHANGELOG.md after 0.10.0 for API/DataStore/general

---

CHANGELOG.md

Additional datastore change log since 0.10.0

---

CHANGELOG.md

Added Changelogs for DataStore and reordered items in Changelog

---

Amplify.xcodeproj/project.pbxproj
Amplify/Categories/API/APICategory.swift
Amplify/Categories/API/APICategoryPlugin.swift
Amplify/Categories/API/ClientBehavior/APICategoryBehavior.swift
Amplify/Categories/Analytics/AnalyticsCategory+ClientBehavior.swift
Amplify/Categories/Analytics/AnalyticsCategoryBehavior.swift
Amplify/Categories/Analytics/AnalyticsCategoryPlugin.swift
Amplify/Categories/Hub/HubCategory+ClientBehavior.swift
Amplify/Categories/Hub/HubCategoryBehavior.swift
Amplify/Categories/Hub/HubCategoryPlugin.swift
Amplify/Categories/Predictions/PredictionsCategory+ClientBehavior.swift
Amplify/Categories/Predictions/PredictionsCategoryBehavior.swift
Amplify/Categories/Predictions/PredictionsCategoryPlugin.swift
Amplify/Categories/Storage/StorageCategory+ClientBehavior.swift
Amplify/Categories/Storage/StorageCategoryBehavior.swift
Amplify/Categories/Storage/StorageCategoryPlugin.swift
AmplifyPlugins/Core/AWSPluginsCore/Model/Support/QueryPredicate+GraphQL.swift
AmplifyTestCommon/Mocks/MockDataStoreCategoryPlugin.swift
Podfile.lock
Pods/Manifest.lock
Pods/Target Support Files/Pods-Amplify/Pods-Amplify-acknowledgements.markdown
Pods/Target Support Files/Pods-Amplify/Pods-Amplify-acknowledgements.plist

Renamed <Category>ClientBehavior to <Category>Behavior 

---

Amplify.xcodeproj/project.pbxproj
Amplify/Categories/Auth/Error/AmplifyAuthError.swift
AmplifyPlugins/Auth/AWSAuthPlugin.xcodeproj/project.pbxproj
AmplifyPlugins/Auth/AWSAuthPlugin/Models/Error/AWSCognitoAuthError.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Support/Constants/AuthPluginErrorConstants.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Support/Utils/AuthErrorHelper.swift

Auth - Mapping of AWSMobileClient error to Auth Error

---

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/InitialSync/InitialSyncOperation.swift
AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/InitialSync/InitialSyncOperationTests.swift

feat: Using config to decide base query or delta query

---

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/InitialSync/InitialSyncOperation.swift
AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/InitialSync/InitialSyncOperationTests.swift

feat: Datastore use configurable syncMaxRecords and syncPageSize

---

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/AWSDataStorePlugin.swift

refactor: Rename configuration to dataStoreConfiguration

---

Amplify/Categories/Auth/AuthCategory+ClientBehavior.swift
Amplify/Categories/Auth/AuthCategoryBehavior.swift
Amplify/Categories/Auth/Request/AuthSignInRequest.swift
Amplify/Categories/Auth/Result/AuthSignInResult.swift
AmplifyPlugins/Auth/AWSAuthPlugin.xcodeproj/project.pbxproj
AmplifyPlugins/Auth/AWSAuthPlugin/AWSAuthPlugin+ClientBehavior.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Dependency/AuthenticationProviderAdapter+SignIn.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Dependency/AuthenticationProviderBehavior.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Models/Options/AWSAuthSignInOptions.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Models/SignInResult+Extension.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Operations/AWSAuthSignInOperation.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Request/AuthSignInRequest+Validate.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Service/AWSMobileClient/AWSMobileClientAdapter.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Service/AWSMobileClient/AWSMobileClientBehavior.swift

Implemented signIn operation for username / password flow. Internally this uses AWSMobileClient.

Auth - SignIn with SRPA using wrapper

---

Amplify.xcodeproj/project.pbxproj
Amplify/Categories/Auth/AuthCategory+ClientBehavior.swift
Amplify/Categories/Auth/AuthCategoryBehavior.swift
Amplify/Categories/Auth/Operation/AuthConfirmSignInOperation.swift
Amplify/Categories/Auth/Request/AuthConfirmSignInRequest.swift
AmplifyPlugins/Auth/AWSAuthPlugin.xcodeproj/project.pbxproj
AmplifyPlugins/Auth/AWSAuthPlugin/AWSAuthPlugin+ClientBehavior.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Dependency/AuthenticationProviderAdapter+SignIn.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Dependency/AuthenticationProviderBehavior.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Models/Options/AWSAuthConfirmSignInOptions.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Models/SignInResult+Extension.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Operations/AWSAuthConfirmSignInOperation.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Request/AuthConfirmSignInRequest+Validate.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Service/AWSMobileClient/AWSMobileClientAdapter.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Service/AWSMobileClient/AWSMobileClientBehavior.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Support/Constants/AuthPluginErrorConstants.swift
Podfile.lock
Pods/Manifest.lock

Auth - ConfirmSignIn implementation

---

Amplify.xcodeproj/project.pbxproj
Amplify/Categories/Auth/AuthCategory+ClientBehavior.swift
Amplify/Categories/Auth/AuthCategoryBehavior.swift
Amplify/Categories/Auth/Operation/AuthSignOutOperation.swift
Amplify/Categories/Auth/Request/AuthSignOutRequest.swift
AmplifyPlugins/Auth/AWSAuthPlugin.xcodeproj/project.pbxproj
AmplifyPlugins/Auth/AWSAuthPlugin/AWSAuthPlugin+ClientBehavior.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Dependency/AuthenticationProviderAdapter+SignOut.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Dependency/AuthenticationProviderBehavior.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Operations/AWSAuthSignOutOperation.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Service/AWSMobileClient/AWSMobileClientAdapter.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Service/AWSMobileClient/AWSMobileClientBehavior.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Service/Predictions/AWSPredictionsService+Rekognition.swift

feat(Auth): - Implemetation of signout api

---

Amplify.xcodeproj/project.pbxproj
Amplify/Categories/Auth/AuthCategory+ClientBehavior.swift
Amplify/Categories/Auth/AuthCategoryBehavior.swift
Amplify/Categories/Auth/Models/AuthSocialProvider.swift
Amplify/Categories/Auth/Request/AuthWebUISignInRequest.swift
AmplifyPlugins/Auth/AWSAuthPlugin.xcodeproj/project.pbxproj
AmplifyPlugins/Auth/AWSAuthPlugin/AWSAuthPlugin+ClientBehavior.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Support/Utils/AuthProvider+AWSMobileClient.swift

*Issue #426 
Will refactor back ones the issue is resolved.

refactor(Auth): Renamed AuthProvider to AuthNProvider

---

Amplify.xcodeproj/project.pbxproj
Amplify/Categories/Auth/AuthCategory+DeviceBehavior.swift
Amplify/Categories/Auth/AuthCategoryBehavior.swift
Amplify/Categories/Auth/AuthCategoryDeviceBehavior.swift
Amplify/Categories/Auth/Models/AuthDevice.swift
Amplify/Categories/Auth/Operation/AuthFetchDevicesOperation.swift
Amplify/Categories/Auth/Operation/AuthForgetDeviceOperation.swift
Amplify/Categories/Auth/Operation/AuthRememberDeviceOperation.swift
Amplify/Categories/Auth/Request/AuthFetchDevicesRequest.swift
Amplify/Categories/Auth/Request/AuthForgetDeviceRequest.swift
Amplify/Categories/Auth/Request/AuthRememberDeviceRequest.swift
AmplifyPlugins/Auth/AWSAuthPlugin.xcodeproj/project.pbxproj
AmplifyPlugins/Auth/AWSAuthPlugin/AWSAuthPlugin+DeviceBehavior.swift
AmplifyPlugins/Auth/AWSAuthPlugin/AWSAuthPlugin.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Dependency/AuthDeviceServiceAdapter.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Dependency/AuthDeviceServiceBehavior.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Models/AWSAuthDevice.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Operations/AWSAuthFetchDevicesOperation.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Operations/AWSAuthForgetDeviceOperation.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Operations/AWSAuthRememberDeviceOperation.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Service/AWSMobileClient/AWSMobileClientAdapter.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Service/AWSMobileClient/AWSMobileClientBehavior.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Support/Utils/Device+Extension.swift

feat(Auth): Implementation of Device operations

---

Amplify.xcodeproj/project.pbxproj
AmplifyTestCommon/Mocks/MockAuthCategoryPlugin.swift
AmplifyTests/CategoryTests/Auth/AuthCategoryConfigurationTests.swift

- Fixes the build failure in unit test
- Re-organized the files 

fix(Auth): Fix build failure in Amplify unit test

---

AmplifyPlugins/Auth/AWSAuthPlugin/AWSAuthPlugin+ClientBehavior.swift

fix(Auth): Added operations for confirmSignup and resendSignUpCode api

---

AmplifyPlugins/Auth/AWSAuthPlugin/Models/AWSAuthService.swift
AmplifyPlugins/Core/AWSPluginsCore/Auth/Provider/AmplifyAWSCredentialsProvider.swift

- Removed unused service from auth plugin
- Spelling fix

refactor(Auth): Removed unused service from auth plugin

---

AmplifyPlugins/Auth/AWSAuthPlugin.xcodeproj/project.pbxproj
AmplifyPlugins/Auth/AWSAuthPlugin/ClientBehavior/AWSAuthPlugin+ClientBehavior.swift
AmplifyPlugins/Auth/AWSAuthPlugin/ClientBehavior/AWSAuthPlugin+DeviceBehavior.swift
AmplifyPlugins/Auth/AWSAuthPlugin/ClientBehavior/AWSAuthPlugin+UserBehavior.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Dependency/AuthUserServiceBehavior.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Operations/AWSAuthConfirmResetPasswordOperation.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Operations/AWSAuthConfirmSignInOperation.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Operations/AWSAuthConfirmSignUpOperation.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Operations/AWSAuthFetchDevicesOperation.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Operations/AWSAuthFetchSessionOperation.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Operations/AWSAuthForgetDeviceOperation.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Operations/AWSAuthRememberDeviceOperation.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Operations/AWSAuthResendSignUpCodeOperation.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Operations/AWSAuthResetPasswordOperation.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Operations/AWSAuthSignInOperation.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Operations/AWSAuthSignOutOperation.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Operations/AWSAuthSignUpOperation.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Operations/AWSAuthSocialWebUISignInOperation.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Operations/AWSAuthWebUISignInOperation.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Operations/UserOperations/AWSAuthAttributeResendConfirmationCodeOperation.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Operations/UserOperations/AWSAuthChangePasswordOperation.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Operations/UserOperations/AWSAuthConfirmUserAttributeOperation.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Operations/UserOperations/AWSAuthFetchUserAttributeOperation.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Operations/UserOperations/AWSAuthUpdateUserAttributeOperation.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Operations/UserOperations/AWSAuthUpdateUserAttributesOperation.swift
AmplifyPlugins/Auth/AWSAuthPlugin/Service/AWSMobileClient/AWSMobileClientBehavior.swift

refactor: Convert AWSAuthPlugin to use Result instead of AsyncOperation

---

AmplifyPlugins/API/APICategoryPlugin.xcodeproj/project.pbxproj
AmplifyPlugins/API/AWSAPICategoryPluginIntegrationTests/GraphQL/GraphQLWithUserPoolIntegrationTests/AuthDirective/GraphQLAuthDirectiveIntegrationTests+Auth.swift
AmplifyPlugins/API/AWSAPICategoryPluginIntegrationTests/GraphQL/GraphQLWithUserPoolIntegrationTests/AuthDirective/GraphQLAuthDirectiveIntegrationTests+Support.swift
AmplifyPlugins/API/AWSAPICategoryPluginIntegrationTests/GraphQL/GraphQLWithUserPoolIntegrationTests/AuthDirective/GraphQLAuthDirectiveIntegrationTests.swift
AmplifyPlugins/API/AWSAPICategoryPluginIntegrationTests/GraphQL/GraphQLWithUserPoolIntegrationTests/AuthDirective/README.md
AmplifyPlugins/API/Podfile

This migrates the set up for AuthDirective integration tests to use Amplify.Auth

feat: [API][Integ] AuthDirective tests to use Amplify.Auth

---

AmplifyPlugins/Storage/AWSS3StoragePluginFunctionalTests/AWSS3StoragePluginAccessLevelTests.swift
AmplifyPlugins/Storage/AWSS3StoragePluginFunctionalTests/AWSS3StoragePluginBasicIntegrationTests.swift
AmplifyPlugins/Storage/AWSS3StoragePluginFunctionalTests/AWSS3StoragePluginConfigurationTests.swift
AmplifyPlugins/Storage/AWSS3StoragePluginFunctionalTests/AWSS3StoragePluginNegativeTests.swift
AmplifyPlugins/Storage/AWSS3StoragePluginFunctionalTests/AWSS3StoragePluginOptionsUsabilityTests.swift
AmplifyPlugins/Storage/AWSS3StoragePluginFunctionalTests/AWSS3StoragePluginTestBase.swift
AmplifyPlugins/Storage/AWSS3StoragePluginFunctionalTests/README.md
AmplifyPlugins/Storage/AWSS3StoragePluginFunctionalTests/ResumabilityTests/AWSS3StoragePluginDownloadFileResumabilityTests.swift
AmplifyPlugins/Storage/AWSS3StoragePluginFunctionalTests/ResumabilityTests/AWSS3StoragePluginGetDataResumabilityTests.swift
AmplifyPlugins/Storage/AWSS3StoragePluginFunctionalTests/ResumabilityTests/AWSS3StoragePluginPutDataResumabilityTests.swift
AmplifyPlugins/Storage/AWSS3StoragePluginFunctionalTests/ResumabilityTests/AWSS3StoragePluginUploadFileResumabilityTests.swift
AmplifyPlugins/Storage/Podfile
AmplifyPlugins/Storage/StoragePlugin.xcodeproj/project.pbxproj

Update Storage Integration tests to use Amplify.Auth

feat: [Storage] use Amplify.Auth in storage integration tests

---

AmplifyPlugins/Auth/AWSCognitoAuthPlugin/AWSCognitoAuthPlugin.swift
AmplifyPlugins/Auth/AWSCognitoAuthPlugin/ClientBehavior/AWSCognitoAuthPlugin+ClientBehavior.swift
AmplifyPlugins/Auth/AWSCognitoAuthPlugin/ClientBehavior/AWSCognitoAuthPlugin+UserBehavior.swift
AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Dependency/AuthenticationProviderAdapter.swift
AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Dependency/AuthenticationProviderBehavior.swift
AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Models/AWSAuthUser.swift
AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Service/AWSMobileClient/AWSMobileClientAdapter.swift
AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Service/AWSMobileClient/AWSMobileClientBehavior.swift
Podfile.lock
Pods/Manifest.lock

This PR is dependent on userSub api in AWSMobileClient - https://github.com/aws-amplify/aws-sdk-ios/pull/2599/

feat(Auth): Implementation of getCurrentUser api

---

AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Dependency/AuthUserServiceAdapter.swift
AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Operations/AWSAuthConfirmSignInOperation.swift
AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Operations/AWSAuthFetchDevicesOperation.swift
AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Operations/AWSAuthFetchSessionOperation.swift
AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Operations/AWSAuthForgetDeviceOperation.swift
AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Operations/AWSAuthRememberDeviceOperation.swift
AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Operations/AWSAuthSignOutOperation.swift
AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Operations/AWSAuthSocialWebUISignInOperation.swift
AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Operations/AWSAuthWebUISignInOperation.swift
AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Operations/UserOperations/AWSAuthAttributeResendConfirmationCodeOperation.swift
AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Operations/UserOperations/AWSAuthChangePasswordOperation.swift
AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Operations/UserOperations/AWSAuthConfirmUserAttributeOperation.swift
AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Operations/UserOperations/AWSAuthFetchUserAttributeOperation.swift
AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Operations/UserOperations/AWSAuthUpdateUserAttributeOperation.swift
AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Operations/UserOperations/AWSAuthUpdateUserAttributesOperation.swift
AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Support/Constants/AuthPluginErrorConstants.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/AuthDeviceTests/AuthDeviceOperationTests.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/AuthUserTests/AuthUserTests.swift

- Added unit test for user operation apis
- Fixed signOut error to be passed if the user is signedout
- Added operation cancel logic for missing operations

test(Auth): Integration test for user operations

---

AmplifyTools/amplify-tools.sh

*Issue #, if available:* #486 

fix(tools): add npx to amplify-app and fix typo - fixes #486

---

AWSPluginsCore.podspec
AWSPredictionsPlugin.podspec
Amplify.podspec
Amplify/Info.plist
AmplifyFunctionalTests/Info.plist
AmplifyPlugins.podspec
AmplifyPlugins/API/AWSAPICategoryPlugin/Info.plist
AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/Resources/Info.plist
AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Resources/Info.plist
AmplifyPlugins/Core/AWSPluginsCore/Info.plist
AmplifyPlugins/Core/AWSPluginsCore/ServiceConfiguration/AmplifyAWSServiceConfiguration.swift
AmplifyPlugins/Core/AWSPluginsCoreTests/Info.plist
AmplifyPlugins/Core/AWSPluginsTestCommon/Info.plist
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Resources/Info.plist
AmplifyPlugins/Predictions/CoreMLPredictionsPlugin/Resources/Info.plist
AmplifyPlugins/Storage/AWSS3StoragePlugin/Resources/Info.plist
AmplifyTestApp/Info.plist
AmplifyTestCommon.podspec
AmplifyTestCommon/Info.plist
AmplifyTests/Info.plist
CHANGELOG.md
CoreMLPredictionsPlugin.podspec
Podfile.lock
Pods/Manifest.lock

chore(release): Prep 1.0.1 release

---

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/InitialSync/InitialSyncOperation.swift
AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginIntegrationTests/README.md
CHANGELOG.md
CONTRIBUTING.md

chore: Changed the repo's default branch to 'main'

---

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/DataStoreConfiguration.swift

bug: Update DataStore comment for syncInterval

---

.gitignore
CHANGELOG.md
Gemfile.lock
fastlane/Fastfile
fastlane/README.md

ci: fastlane release lane fixes

---

fastlane/Fastfile

ci(fastfile): ignore duplicate pod push error

---

fastlane/Fastfile

chore: bump unstable pods

---

fastlane/Fastfile

ci(fastlane): fix ruby env vars

---

CHANGELOG.md

chore: Updated the changelog for release 2.14.0

---

AmplifyPlugins/API/Podfile.lock
AmplifyPlugins/Analytics/Podfile.lock
AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Resources/Info.plist
AmplifyPlugins/Auth/Podfile.lock
AmplifyPlugins/Core/AWSPluginsCore/ServiceConfiguration/AmplifyAWSServiceConfiguration.swift
AmplifyPlugins/DataStore/Podfile.lock
AmplifyPlugins/Predictions/Podfile.lock
AmplifyPlugins/Storage/Podfile.lock
AmplifyTestCommon.podspec
build-support/dependencies.rb

refactor: Updated Infoplist and service configuration to 1.0.4

---

README.md

broken link in README.md - fixes #620

---

Amplify.xcodeproj/project.pbxproj
Amplify/DevMenu/Amplify+DevMenu.swift
Amplify/DevMenu/AmplifyDevMenu.swift
Amplify/DevMenu/Data/AmplifyDevMenuItem.swift
Amplify/DevMenu/DevMenuBehavior.swift
Amplify/DevMenu/DevMenuPresentationContextProvider.swift
Amplify/DevMenu/LongPressGestureRecognizer.swift
Amplify/DevMenu/TriggerDelegate.swift
Amplify/DevMenu/TriggerRecognizer.swift
Amplify/DevMenu/View/AmplifyDevMenuList.swift
Amplify/DevMenu/View/AmplifyDevMenuRow.swift

*Issue #, if available:* None 
1) Added protocols for DevMenuBehavior, Trigger Recognizer and TriggerDelegate
2) Added documentation
3) Minor fix to handle multiple long press events detected

refactor: Updated protocols for initial setup and added documentation

---

Amplify.xcodeproj/project.pbxproj
Amplify/DevMenu/Data/LogEntryHelper.swift
Amplify/DevMenu/Data/LogEntryItem.swift
Amplify/DevMenu/Logging/PersistentLogWrapper.swift
Amplify/DevMenu/Logging/PersistentLoggingPlugin.swift
Amplify/DevMenu/View/DetailViewFactory.swift
Amplify/DevMenu/View/LogEntryRow.swift
Amplify/DevMenu/View/LogViewer.swift

Log Viewer screen in Developer Menu

feat(log-viewer): Log Viewer Screen in Developer Menu

---

README.md

- added badges
- fixed code formatting/syntax
- updated category description

update readme with current info and badges

---

Amplify.xcodeproj/project.pbxproj
Amplify/Categories/Logging/LoggingCategory.swift
Amplify/DevMenu/Amplify+DevMenu.swift
Amplify/DevMenu/AmplifyDevMenu.swift
Amplify/DevMenu/Data/EnvironmentInfoHelper.swift
Amplify/DevMenu/Data/IssueInfo.swift
Amplify/DevMenu/Data/IssueInfoHelper.swift
Amplify/DevMenu/Data/LogEntryHelper.swift
Amplify/DevMenu/Data/LogEntryItem.swift
Amplify/DevMenu/DevMenuStringConstants.swift
Amplify/DevMenu/Logging/PersistentLogWrapper.swift
Amplify/DevMenu/Logging/PersistentLoggingPlugin.swift
Amplify/DevMenu/View/DetailViewFactory.swift
Amplify/DevMenu/View/DevMenuList.swift
Amplify/DevMenu/View/EnvironmentInfoDetailView.swift
Amplify/DevMenu/View/IssueReporter.swift
Amplify/DevMenu/View/LogEntryRow.swift

None 
1. Report issue screen in developer menu
2. Added code to fetch environment info from json file
3. Added code to wrap customer supplied LoggingCategoryPlugin inside PersistentLoggingPlugin

feat(report-issue-screen): Report Issue Screen in Developer Menu

---

AmplifyPlugins.podspec
AmplifyPlugins/API/Podfile

Update AppSyncRealTimeClient
Refs: #677

fix: Update AppSyncRealTimeClient dependency

---

Gemfile.lock
fastlane/Fastfile

* Fastfile correction found by: @kaichengyan 
* Update Fastlane and other gems

ci(fastlane): correct ruby block in Fastfile (missing end)

---

Amplify.xcodeproj/project.pbxproj
Amplify/DevMenu/Logging/PersistentLogWrapper.swift
AmplifyTestCommon/Mocks/MockDevMenuContextProvider.swift
AmplifyTests/DevMenuTests/GestureRecognizerTests.swift
AmplifyTests/DevMenuTests/PersistentLogWrapperTests.swift
AmplifyTests/DevMenuTests/PersistentLoggingPluginTests.swift

None
Unit tests for PersistentLoggingPlugin and GestureRecognizer

test(dev-menu): Unit tests for PersistentLoggingPlugin and GestureRecognizer

---

Amplify.xcodeproj/project.pbxproj
Amplify/Core/Configuration/AmplifyConfiguration.swift
Amplify/Core/Configuration/Internal/AmplifyConfigurationInitialization.swift
AmplifyFunctionalTests/AmplifyConfigurationInitFromFileTests.swift
AmplifyFunctionalTests/AmplifyConfigurationTests.swift
AmplifyFunctionalTests/Hub/SerialDispatcherPerformanceTests.swift

feat: Add AmplifyConfiguration file-based initializer

---

Amplify/Categories/API/ClientBehavior/APICategoryGraphQLBehavior.swift
Amplify/Categories/API/ClientBehavior/APICategoryRESTBehavior.swift
Amplify/Categories/Auth/AuthCategoryBehavior.swift
Amplify/Categories/Auth/AuthCategoryDeviceBehavior.swift
Amplify/Categories/Auth/AuthCategoryUserBehavior.swift
Amplify/Categories/Predictions/PredictionsCategoryBehavior.swift
Amplify/Categories/Storage/StorageCategoryBehavior.swift
AmplifyTests/CategoryTests/API/APICategoryClientRESTTests.swift

feat: Mark APIs that return operations with @discardableResult

---

.circleci/config.yml

ci: invalidate repo cache

---

README.md

https://github.com/aws-amplify/amplify-ios/issues/717

chore: Update Xcode version in README

---

README-combine-support.md

fix: typo in iOS Combine docs

---

AmplifyPlugins/API/Podfile.lock
AmplifyPlugins/Analytics/Podfile.lock
AmplifyPlugins/Auth/Podfile.lock
AmplifyPlugins/DataStore/Podfile.lock
AmplifyPlugins/Predictions/Podfile.lock
AmplifyPlugins/Storage/Podfile.lock
Podfile.lock

Updates dependencies to latest versions, in preparation for release to fix https://github.com/aws-amplify/amplify-ios/issues/640

chore: Update dependencies

---

Amplify.xcodeproj/project.pbxproj
Amplify/Categories/DataStore/Model/Internal/Schema/AuthRule.swift
AmplifyPlugins/Analytics/AWSPinpointAnalyticsPluginTests/Mocks/MockAWSAuthService.swift
AmplifyPlugins/Core/AWSPluginsCore/Auth/AWSAuthService.swift
AmplifyPlugins/Core/AWSPluginsCore/Auth/AWSAuthServiceBehavior.swift
AmplifyPlugins/Core/AWSPluginsCore/Model/Decorator/AuthRuleDecorator.swift
AmplifyPlugins/Core/AWSPluginsCore/Model/GraphQLRequest/GraphQLRequest+AnyModelWithSync.swift
AmplifyPlugins/Core/AWSPluginsCore/Model/Support/AuthRule+Extension.swift
AmplifyPlugins/Core/AWSPluginsCoreTests/Auth/AWSAuthServiceTests.swift
AmplifyPlugins/Core/AWSPluginsCoreTests/Model/Decorator/AuthRuleDecorator/ModelMultipleOwnerAuthRuleTests.swift
AmplifyPlugins/Core/AWSPluginsCoreTests/Model/Decorator/AuthRuleDecorator/ModelReadUpdateAuthRuleTests.swift
AmplifyPlugins/Core/AWSPluginsCoreTests/Model/Decorator/AuthRuleDecorator/ModelWithOwnerFieldAuthRuleTests.swift
AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLRequest/GraphQLRequestAuthIdentityClaimTests.swift
AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLRequest/GraphQLRequestAuthRuleTests.swift
AmplifyPlugins/Core/AWSPluginsTestCommon/MockAWSAuthService.swift
AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/IncomingAsyncSubscriptionEventPublisher.swift

To be in sync with:
https://github.com/aws-amplify/amplify-android/pull/889

fix(Core): support for custom identity claim

---

AmplifyPlugins/Auth/AWSCognitoAuthPlugin/ClientBehavior/AWSCognitoAuthPlugin+ClientBehavior.swift
AmplifyPlugins/Core/AWSPluginsCore/Model/Support/Model+GraphQL.swift
AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLRequest/GraphQLRequestEmbeddableTypeTests.swift
AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/AWSDataStorePlugin+DataStoreBaseBehavior.swift
AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/StorageEngine+SyncRequirement.swift
AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/StorageEngine.swift
AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/OutgoingMutationQueue/ProcessMutationErrorFromCloudOperation.swift
AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/ReconcileAndLocalSave/ReconcileAndLocalSaveOperation.swift

- Added a new escape hatch api for delete by id
- Fixed graphql request decorator while using a dependent model.

refactor(datastore): Added delete by id option that takes ModelSchema

---

.github/workflows/stale.yml

- improve messaging
- add `pending release` and `rfc` to the exempt labels

update the stale github action config

---

.circleci/config.yml
AmplifyPlugins/Core/AWSPluginsCore/Model/Support/Model+GraphQL.swift

- The value returned by subscript or jsonValue is Any?? and we need to check it properly to get the right value out.
- Enabled AWSPluginsCore test in the CircleCI pipeline

fix(datastore): Issue with graphqlInput not being generated correctly

---

AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/InitialSync/SyncEventEmitterTests.swift

fix(datastore): Fix SyncEventEmitterTests

---

AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Core/SQLiteStorageEngineAdapterJsonTests.swift
AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Core/SQLiteStorageEngineAdapterTests.swift
AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/TestSupport/Mocks/TestModelRegistration.swift

test(datastore): Added more test for json non modeltypes

---

README.md

remove Carthage info from the README

---

CHANGELOG.md

chore: Add deprecated warning to 1.4.1 release

---

AmplifyPlugins/Auth/AWSCognitoAuthPlugin.xcodeproj/project.pbxproj
AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/AWSAuthBaseTest.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/AuthDeviceTests/AuthDeviceOperationTests.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/AuthSessionTests/SignedInAuthSessionTests.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/AuthSessionTests/SignedOutAuthSessionTests.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/AuthSignInTests/AuthUsernamePasswordSignInTests.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/AuthSignOutTests/AuthSignOutTests.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/AuthSignUpTests/AuthConfirmSignUpTests.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/AuthSignUpTests/AuthResendSignUpCodeTests.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/AuthSignUpTests/AuthSignUpTests.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/AuthUserAttributesTests/AuthUserAttributesTests.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/AuthUserTests/AuthUserTests.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/README.md
AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/Support/AuthSignInHelper.swift
AmplifyPlugins/Auth/Podfile.lock

- Removed empty enum violation 
- Added email in the signUp call to avoid no attribute error
- Added a second email to test update attribute
- Current coverage 56%

test(auth): Fix integration test for auth

---

Amplify/Categories/Auth/Request/AuthChangePasswordRequest.swift
AmplifyPlugins/Auth/AWSCognitoAuthPlugin.xcodeproj/project.pbxproj
AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/ClientBehaviorAPITests/AWSCognitoAuthClientBehaviorTests.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/ClientBehaviorAPITests/AWSCognitoAuthDeviceBehaviorTests.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/ClientBehaviorAPITests/AWSCognitoAuthUserBehaviorTests.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/Mocks/MockAuthDeviceServiceBehavior.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/Mocks/MockAuthHubEventBehavior.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/Mocks/MockAuthUserServiceBehavior.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/Mocks/MockAuthenticationProviderBehavior.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/Mocks/MockAuthorizationProviderBehavior.swift

test(auth): Unit test coverage for the publi apis

---

AmplifyPlugins/Auth/AWSCognitoAuthPlugin.xcodeproj/project.pbxproj
AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthenticationProviderTests/AuthenticationProviderConfirmResetPasswordTests.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthenticationProviderTests/AuthenticationProviderConfirmSigninTests.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthenticationProviderTests/AuthenticationProviderResendSignupCodeTests.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthenticationProviderTests/AuthenticationProviderResetPasswordTests.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthenticationProviderTests/AuthenticationProviderSigninTests.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthenticationProviderTests/AuthenticationProviderSigninWithSocialWebUITests.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthenticationProviderTests/AuthenticationProviderSigninWithWebUITests.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthenticationProviderTests/AuthenticationProviderSignoutTests.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthenticationProviderTests/AuthenticationProviderSignupTests.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthenticationProviderTests/BaseAuthenticationProviderTest.swift

test(auth): Added base class authenticationProvider tests

---

AmplifyPlugins/Auth/AWSCognitoAuthPlugin.xcodeproj/project.pbxproj
AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthenticationProviderTests/AuthenticationProviderConfirmResetPasswordTests.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthenticationProviderTests/AuthenticationProviderConfirmSigninTests.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthenticationProviderTests/AuthenticationProviderConfirmSignupTests.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthenticationProviderTests/AuthenticationProviderResendSignupCodeTests.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthenticationProviderTests/AuthenticationProviderResetPasswordTests.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthenticationProviderTests/AuthenticationProviderSigninTests.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthenticationProviderTests/AuthenticationProviderSigninWithSocialWebUITests.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthenticationProviderTests/AuthenticationProviderSigninWithWebUITests.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthenticationProviderTests/AuthenticationProviderSignoutTests.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthenticationProviderTests/AuthenticationProviderSignupTests.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthenticationProviderTests/BaseAuthenticationProviderTest.swift

*Issues:*
1. Seeing some changes that were already merged in `main` showing up in `Files changed`. I have seen this before, should be a Github bug, if it is showing correctly when you are reviewing this PR, pleas ignore this message.
1. Implemented confirmSignUp apis unit tests

test(Auth): confirmSignUp unit tests

---

AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthenticationProviderTests/AuthenticationProviderConfirmResetPasswordTests.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthenticationProviderTests/AuthenticationProviderConfirmSignupTests.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthenticationProviderTests/AuthenticationProviderResendSignupCodeTests.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/Mocks/MockAWSMobileClient.swift

test(Auth): ConfirmResetPassword unit tests

---

CHANGELOG.md

Update Changelog.md for datastore start/stop

---

AmplifyPlugins/Auth/AWSCognitoAuthPlugin.xcodeproj/project.pbxproj
AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthDeviceBehaviorTests/AuthDeviceFetchDevicesTests.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthDeviceBehaviorTests/AuthDeviceForgetDeviceTests.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthDeviceBehaviorTests/AuthDeviceRememberDeviceTests.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthDeviceBehaviorTests/BaseAuthDeviceTest.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/Mocks/MockAWSMobileClient.swift

test(Auth): AuthDevice unit tests (fetchDevices, forgetDevice, rememberDevice)

---

AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Dependency/AuthenticationProviderAdapter+SignIn.swift
AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Request/AuthConfirmSignInRequest+Validate.swift
AmplifyPlugins/Auth/Podfile.lock

bug(auth): Return the right message for confirmSignIn validation

---

AmplifyPlugins/Auth/AWSCognitoAuthPlugin.xcodeproj/project.pbxproj
AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthUserBehaviorTests/BaseUserBehaviorTest.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthUserBehaviorTests/UserBehaviorChangePasswordTests.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthUserBehaviorTests/UserBehaviorConfirmAttributeTests.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthUserBehaviorTests/UserBehaviorFetchAttributeTests.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthUserBehaviorTests/UserBehaviorResendCodeTests.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthUserBehaviorTests/UserBehaviorUpdateAttributeTests.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/Mocks/MockAWSMobileClient.swift

Unit tests for
- FetchUserAttributes
- UpdateUserAttributes
- ConfirmUserAttributes

test(Auth): UserAttributes unit tests

---

AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthUserBehaviorTests/UserBehaviorChangePasswordTests.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/Mocks/MockAWSMobileClient.swift

test(Auth): changePassword unit test

---

AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Dependency/AuthenticationProviderAdapter+SignIn.swift
AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Dependency/AuthorizationProviderAdapter+SignedInSession.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthenticationProviderTests/AuthenticationProviderSigninWithWebUITests.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthenticationProviderTests/AuthenticationProviderSignoutTests.swift
AmplifyPlugins/Auth/Podfile.lock

test(auth): Added unit test to hostedUI signIn and signOut

---

AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthUserBehaviorTests/UserBehaviorResendCodeTests.swift

test(Auth): resendConfirmationCode unit test

---

AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthenticationProviderTests/AuthenticationProviderResetPasswordTests.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/Mocks/MockAWSMobileClient.swift

test(Auth): resetPassword unit tests

---

.github/ISSUE_TEMPLATE/bug_report.md

chore: Update bug_report.md cli, and versions

---

CHANGELOG.md

chore: Updated the changelog to reflect new auth changes

---

Amplify.podspec

Remove `AmplifyTools` podspec references

chore: remove AmplifyTools podspec

---

Amplify.podspec
AmplifyTools/README.md
AmplifyTools/amplify-tools.sh

`AmplifyTools` deprecation path

chore(amplifytools): amplifytools deprecation notice

---

.github/PULL_REQUEST_TEMPLATE.md

*Description of changes:* Change PR template to resemble like the one you see here.

chore: Add check list to the pr template

---

AmplifyPlugins/Predictions/AWSPredictionsPlugin/AWSPredictionsPlugin.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Requests/PredictionsIdentifyRequest+Validate.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Service/CoreML/CoreMLPredictionService.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Service/MultiService/IdentifyMultiService.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Service/Predictions/AWSPredictionsService+Rekognition.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Service/Predictions/AWSPredictionsService+Transcribe.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Support/Constants/AWSRekognitionErrorMessage.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Support/Constants/AWSServiceErrorMessage.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Support/Constants/AWSTextractErrorMessage.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Support/Constants/AWSTranslateErrorMessage.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Support/Constants/ConvertMultiServiceErrorMessage.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Support/Constants/InterpretMultiServiceErrorMessage.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Support/Internal/NativeWebSocketProvider.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Support/Utils/IdentifyTextResultTransformers+KeyValueSet.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Support/Utils/IdentifyTextResultTransformers+Tables.swift
AmplifyPlugins/Predictions/CoreMLPredictionsPlugin/Dependency/CoreMLVisionAdapter.swift
AmplifyPlugins/Predictions/CoreMLPredictionsPlugin/Operation/CoreMLIdentifyOperation.swift
AmplifyPlugins/Predictions/CoreMLPredictionsPlugin/Operation/CoreMLInterpretTextOperation.swift
AmplifyPlugins/Predictions/Podfile.lock
AmplifyPlugins/Predictions/PredictionsCategoryPlugin.xcodeproj/project.pbxproj

~- [] Added new tests to cover change, if needed~
~- [] Documentation update for the change if required~

chore(Predictions): Cleanup build warnings

---

.github/ISSUE_TEMPLATE/bug_report.md

chore: add regression bug question to the template

---

.github/ISSUE_TEMPLATE/bug_report.md

Update bug report template to include SPM and more environment info.

chore: update bug report

---

.github/workflows/stale.yml

chore: Exempt 'work in progress' label from stale

---

AmplifyPlugins/API/AWSAPICategoryPluginIntegrationTests/GraphQL/GraphQLWithUserPoolIntegrationTests/AuthDirective/GraphQLAuthDirectiveIntegrationTests.swift
AmplifyPlugins/API/AWSAPICategoryPluginIntegrationTests/GraphQL/GraphQLWithUserPoolIntegrationTests/GraphQLWithUserPoolIntegrationTests.swift
AmplifyPlugins/API/AWSAPICategoryPluginIntegrationTests/REST/RESTWithIAMIntegrationTests/README.md
AmplifyPlugins/API/AWSAPICategoryPluginIntegrationTests/REST/RESTWithIAMIntegrationTests/RESTWithIAMIntegrationTests.swift
AmplifyPlugins/API/AWSAPICategoryPluginTests/Operation/GraphQLSubscribeCombineTests.swift

Fix outdated integration tests

chore(api): fix outdated integration tests

---

AmplifyPlugins/API/APICategoryPlugin.xcodeproj/project.pbxproj
AmplifyPlugins/API/APICategoryPlugin.xcodeproj/xcshareddata/xcschemes/AWSAPICategoryPluginFunctionalTests.xcscheme
AmplifyPlugins/API/AWSAPICategoryPluginFunctionalTests/GraphQLSyncBased/GraphQLSyncCustomPrimaryKeyTests.swift
AmplifyPlugins/API/AWSAPICategoryPluginFunctionalTests/GraphQLSyncBased/README.md

*Description of changes:* API sync integration tests for custom primary key 

chore: Custom Primary key API sync based integration tests

---

Amplify.xcodeproj/project.pbxproj
Amplify/Categories/DataStore/Model/Internal/Schema/ModelSchema.swift
AmplifyPlugins/API/APICategoryPlugin.xcodeproj/project.pbxproj
AmplifyPlugins/API/APICategoryPlugin.xcodeproj/xcshareddata/xcschemes/AWSAPICategoryPluginFunctionalTests.xcscheme
AmplifyPlugins/API/AWSAPICategoryPluginFunctionalTests/GraphQLSyncBased/GraphQLSyncCustomPrimaryKeyTests.swift
AmplifyPlugins/API/AWSAPICategoryPluginFunctionalTests/GraphQLSyncBased/README.md
AmplifyPlugins/Core/AWSPluginsCore/Model/Decorator/ModelIdDecorator.swift
AmplifyPlugins/Core/AWSPluginsCore/Model/GraphQLRequest/GraphQLRequest+AnyModelWithSync.swift
AmplifyPlugins/Core/AWSPluginsCore/Model/GraphQLRequest/GraphQLRequest+Model.swift
AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLRequest/GraphQLRequestAnyModelWithSyncTests.swift
AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLRequest/GraphQLRequestAuthRuleTests.swift
AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLRequest/GraphQLRequestSyncCustomPrimaryKeyTests.swift
AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/OutgoingMutationQueue/ProcessMutationErrorFromCloudOperation.swift
AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/OutgoingMutationQueue/SyncMutationToCloudOperation.swift
AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginIntegrationTests/DataStoreCustomPrimaryKeyTests.swift
AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginIntegrationTests/README.md
AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginIntegrationTests/TestSupport/TestModelRegistration.swift
AmplifyPlugins/DataStore/DataStoreCategoryPlugin.xcodeproj/project.pbxproj
AmplifyTestCommon/Models/CustomerOrder+Schema.swift
AmplifyTestCommon/Models/CustomerOrder.swift

*Description of changes:*  This is a merge PR for 
https://github.com/aws-amplify/amplify-ios/pull/1256 
https://github.com/aws-amplify/amplify-ios/pull/1246 
https://github.com/aws-amplify/amplify-ios/pull/1228

feat(Datastore/API): custom primary keys support for delete and update

---

AmplifyPlugins/DataStore/DataStoreCategoryPlugin.xcodeproj/project.pbxproj

chore(DataStore): clean up extra AmplifyConfig folder

---

fastlane/Fastfile

See related https://github.com/aws-amplify/amplify-ios/pull/1207
Tested the one line change (commenting out other lines) via fastlane execution, ran `fastlane ios post_release`

chore: add SPM update in post release

---

Amplify/Categories/API/APICategory+HubPayloadEventName.swift
Amplify/Categories/API/APICategory.swift
Amplify/Categories/API/APICategoryConfiguration.swift
Amplify/Categories/API/APICategoryPlugin.swift
Amplify/Categories/API/AmplifyAPICategory+APICategory.swift
Amplify/Categories/API/AuthProvider/APIAuthProviderFactory.swift
Amplify/Categories/API/ClientBehavior/APICategoryAuthProviderFactoryBehavior.swift
Amplify/Categories/API/ClientBehavior/APICategoryReachabilityBehavior.swift
Amplify/Categories/API/ClientBehavior/AmplifyAPICategory+AuthProviderFactoryBehavior.swift
Amplify/Categories/API/ClientBehavior/AmplifyAPICategory+GraphQLBehavior+Combine.swift
Amplify/Categories/API/ClientBehavior/AmplifyAPICategory+ReachabilityBehavior.swift
Amplify/Categories/API/Error/APIError.swift
Amplify/Categories/API/Operation/GraphQLOperation.swift
Amplify/Categories/API/Operation/RESTOperation.swift
Amplify/Categories/API/Reachability/ReachabilityUpdate.swift
Amplify/Categories/API/Request/GraphQLOperationRequest.swift
Amplify/Categories/API/Request/GraphQLOperationType.swift
Amplify/Categories/API/Request/GraphQLRequest.swift
Amplify/Categories/API/Request/RESTOperationRequest.swift
Amplify/Categories/API/Request/RESTOperationType.swift
Amplify/Categories/API/Request/RESTRequest.swift
Amplify/Categories/API/Response/GraphQLError.swift
Amplify/Categories/API/Response/GraphQLResponse.swift
Amplify/Categories/API/Response/SubscriptionConnectionState.swift

chore(API): add doc comments

---

Amplify/Categories/Analytics/AnalyticsCategory+HubPayloadEventName.swift
Amplify/Categories/Analytics/AnalyticsCategory.swift
Amplify/Categories/Analytics/AnalyticsCategoryBehavior.swift
Amplify/Categories/Analytics/AnalyticsCategoryConfiguration.swift
Amplify/Categories/Analytics/AnalyticsCategoryPlugin.swift
Amplify/Categories/Analytics/AnalyticsProfile.swift
Amplify/Categories/Analytics/Error/AnalyticsError.swift
Amplify/Categories/Analytics/Event/AnalyticsEvent.swift
Amplify/Categories/Analytics/Event/BasicAnalyticsEvent.swift

Added missing doc comments for Analytics category.

chore(Analytics): add doc comments

---

Amplify.xcodeproj/project.pbxproj
AmplifyPlugins/API/AWSAPICategoryPluginFunctionalTests/GraphQLModelBased/GraphQLScalarTests.swift
AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginIntegrationTests/DataStoreScalarTests.swift
AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginIntegrationTests/TestSupport/TestModelRegistration.swift
AmplifyTestCommon/Models/Scalar/EnumTestModel+Schema.swift
AmplifyTestCommon/Models/Scalar/EnumTestModel.swift
AmplifyTestCommon/Models/Scalar/ListIntContainer+Schema.swift
AmplifyTestCommon/Models/Scalar/ListIntContainer.swift
AmplifyTestCommon/Models/Scalar/ListStringContainer+Schema.swift
AmplifyTestCommon/Models/Scalar/ListStringContainer.swift
AmplifyTestCommon/Models/Scalar/NestedTypeTestModel+Schema.swift
AmplifyTestCommon/Models/Scalar/NestedTypeTestModel.swift

codegen issue: https://github.com/aws-amplify/amplify-codegen/issues/104
iOS issue: https://github.com/aws-amplify/amplify-ios/issues/1116
This applies the proposed codegen changes from this PR: https://github.com/aws-amplify/amplify-codegen/pull/142 
doc updates: https://github.com/aws-amplify/docs/pull/3306
*Testing done:*

fix(Model): Apply codegen changes test models

---

AmplifyPlugins/Storage/AWSS3StoragePlugin/AWSS3StoragePlugin+ClientBehavior.swift
AmplifyPlugins/Storage/AWSS3StoragePlugin/AWSS3StoragePlugin.swift
AmplifyPlugins/Storage/AWSS3StoragePlugin/Dependency/AWSS3Adapter.swift
AmplifyPlugins/Storage/AWSS3StoragePlugin/Dependency/AWSS3Behavior.swift
AmplifyPlugins/Storage/AWSS3StoragePlugin/Dependency/AWSS3PreSignedURLBuilderAdapter.swift
AmplifyPlugins/Storage/AWSS3StoragePlugin/Dependency/AWSS3PreSignedURLBuilderBehavior.swift
AmplifyPlugins/Storage/AWSS3StoragePlugin/Dependency/AWSS3TransferUtilityAdapter.swift
AmplifyPlugins/Storage/AWSS3StoragePlugin/Operation/AWSS3StorageDownloadDataOperation.swift
AmplifyPlugins/Storage/AWSS3StoragePlugin/Operation/AWSS3StorageDownloadFileOperation.swift
AmplifyPlugins/Storage/AWSS3StoragePlugin/Operation/AWSS3StorageGetURLOperation.swift
AmplifyPlugins/Storage/AWSS3StoragePlugin/Operation/AWSS3StorageListOperation.swift
AmplifyPlugins/Storage/AWSS3StoragePlugin/Operation/AWSS3StorageRemoveOperation.swift
AmplifyPlugins/Storage/AWSS3StoragePlugin/Operation/AWSS3StorageUploadDataOperation.swift
AmplifyPlugins/Storage/AWSS3StoragePlugin/Operation/AWSS3StorageUploadFileOperation.swift
AmplifyPlugins/Storage/AWSS3StoragePlugin/Support/Utils/StorageRequestUtils+Getter.swift
OPERATIONS.md

chore(Storage): add doc comments (#1280)
chore(Storage): document Operations
#1280
https://github.com/aws-amplify/docs/issues/2540

chore(Storage): add doc comments (#1280)

---

.github/workflows/stale.yml

Update stale workflow with new labels

chore: update stale workflow w/ new labels

---

AmplifyPlugins/API/AWSAPICategoryPluginIntegrationTests/GraphQL/GraphQLWithUserPoolIntegrationTests/AuthDirective/GraphQLAuthDirectiveIntegrationTests+Support.swift

Fix outdated integration tests

chore: fix integration tests

---

Amplify/Categories/API/ClientBehavior/APICategoryGraphQLBehavior.swift
Amplify/Categories/Auth/AuthCategoryDeviceBehavior.swift
Amplify/Categories/Auth/AuthCategoryUserBehavior.swift
Amplify/Core/Category/Category.swift
Amplify/Core/Configuration/Internal/CategoryConfigurable.swift
Amplify/DefaultPlugins/AWSHubPlugin/Internal/HubChannelDispatcher.swift
AmplifyPlugins/API/AWSAPICategoryPlugin/Reachability/NetworkReachability.swift
AmplifyPlugins/API/AWSAPICategoryPlugin/URLSessionBehavior/URLSessionBehaviorDelegate.swift
AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Dependency/AuthUserServiceBehavior.swift
AmplifyPlugins/Core/AWSPluginsCore/Auth/AWSAuthServiceBehavior.swift
AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/StorageEngineAdapter.swift
AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/StorageEngineBehavior.swift
AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/MutationEvent/MutationEventIngester.swift
AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/MutationEvent/MutationEventPublisher.swift
AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/MutationEvent/MutationEventSource.swift
AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/OutgoingMutationQueue/OutgoingMutationQueue.swift
AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngineBehavior.swift
AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/IncomingEventReconciliationQueue.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Service/CoreML/CoreMLPredictionBehavior.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Service/MultiService/MultiServiceBehavior.swift
AmplifyPlugins/Predictions/CoreMLPredictionsPlugin/Dependency/CoreMLNaturalLanguageBehavior.swift
AmplifyPlugins/Predictions/CoreMLPredictionsPlugin/Dependency/CoreMLSpeechBehavior.swift
AmplifyPlugins/Predictions/CoreMLPredictionsPlugin/Dependency/CoreMLVisionBehavior.swift

#1293
Replaces `class` with `AnyObject`

chore: replaces deprecated class reserved word with AnyObject (#1293)

---

README.md

https://github.com/aws-amplify/amplify-ios/issues/1298
Update escape hatch snippet as per docs https://docs.amplify.aws/lib/predictions/escapehatch/q/platform/ios

chore: update escape hatch snippet

---

.github/workflows/stale.yml

- add first-time-contributor and open-for-contribution labels
- remove enchancement label
- 

Update stale.yml with first time/open for contribution label

---

.github/ISSUE_TEMPLATE/bug_report.yaml

Update bug report template.
- Amplify category is now required
- no default labels
- ~[ ] All unit tests pass~

chore: update bug report form [skip ci]

---

.github/ISSUE_TEMPLATE/feature_request.yaml

~- [ ] Added new tests to cover change, if needed~
~- [ ] All unit tests pass~
~- [ ] All integration tests pass~

chore: update feature_request form [ci skip]

---

README.md

chore: minor change to REAMDE.md

---

Amplify/Categories/Logging/LoggingCategory.swift

See https://github.com/aws-amplify/amplify-ios/issues/1432 for stack trace
Adding lock to perform changes on `logLevel` synchronously 

fix(Logging): fix concurrency issues with logLevel

---

.circleci/config.yml

The PR is aimed at updating the CircleCI config to point to XCode 13 for future integrations. 

Updated Circleci config to support XCode 13

---

AmplifyPlugins/API/AWSAPICategoryPluginFunctionalTests/GraphQLModelBased/GraphQLConnectionScenario4Tests.swift
AmplifyPlugins/API/AWSAPICategoryPluginFunctionalTests/GraphQLModelBased/GraphQLConnectionScenario6Tests.swift
AmplifyPlugins/API/AWSAPICategoryPluginFunctionalTests/GraphQLModelBased/GraphQLModelBasedTests+Concurrency.swift
AmplifyPlugins/API/AWSAPICategoryPluginFunctionalTests/GraphQLModelBased/GraphQLModelBasedTests+List.swift
AmplifyPlugins/API/Podfile
AmplifyPlugins/API/Podfile.lock

chore: Cleanup API test, removes unused imports

---

AmplifyPlugins/Predictions/AWSPredictionsPlugin/AWSPredictionsPlugin+ClientBehavior.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/AWSPredictionsPlugin+Reset.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Operation/AWSPollyOperation.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Operation/AWSTranscribeOperation.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Operation/AWSTranslateOperation.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Operation/IdentifyOperation.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Operation/InterpretTextOperation.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Service/Predictions/AWSPredictionsService+Transcribe.swift
AmplifyPlugins/Predictions/Podfile
AmplifyPlugins/Predictions/Podfile.lock
AmplifyPlugins/Predictions/PredictionsCategoryPlugin.xcodeproj/project.pbxproj

chore(predictions): Remove unused imports and variables

---

README.md

feat(geo): Add Geo category to README.

---

CHANGELOG.md

chore(geo): Update changelog to add Amplify Geo Category

chore(geo): Update changelog to add Amplify Geo Category [skip ci]

---

AmplifyPlugins/Geo/AWSLocationGeoPlugin/Resources/Info.plist
fastlane/amplify_pods.rb

Add support to update AWSLocationGeoPlugin plist version via Fastlane.

chore(geo): Add support to update AWSLocationGeoPlugin plist version via Fastlane.

---

.circleci/config.yml

Add AWSLocationGeoPlugin tests to Circle CI config.

chore(geo): Add AWSLocationGeoPlugin tests to Circle CI config.

---

AmplifyPlugins/Geo/Podfile.lock

chore(geo): Update Geo pod dependencies.

---

AmplifyPlugins/Core/AWSPluginsTestCommon/MockAWSAuthService.swift
AmplifyTestCommon/Models/ReservedWords/Group+Schema.swift
AmplifyTestCommon/Models/ReservedWords/Group.swift
AmplifyTestCommon/Models/ReservedWords/Row+Schema.swift
AmplifyTestCommon/Models/ReservedWords/Row.swift

Fix file headers that didn't get formatted/linted properly at some point.

chore: fix file headers

---

CHANGELOG.md

This is a placeholder PR to reference https://github.com/aws-amplify/amplify-ios/pull/1582

feat(auth): add deleteUser API

---

AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Dependency/AuthorizationProviderAdapter+SignedInSession.swift

chore(auth): improved error handling for userNotFound error when fetching a signed in session

chore(auth): improved error handling for userNotFound error when fetching a signed in session

---

NOTICE

chore: Added attribution notice for 3P libraries [ci skip]

---

Amplify/Categories/Auth/Operation/AmplifyOperation+AuthPublishers.swift

*Issue #1647 * 
*Description of changes:* fix deleteUser Combine support

fix(auth): fix deleteUser Combine support

---

AmplifyPlugins/Core/AWSPluginsCore/ServiceConfiguration/AmplifyAWSServiceConfiguration.swift

chore: Update the version number to 1.22.0-dev-preview.0

---

.circleci/config.yml
CircleciScripts/jazzy_doc_gen.sh
Gemfile
Gemfile.lock

N/A
Adds a script to generate API documentation using jazzy as part of our CI release workflow.

chore(ci): add jazzy doc gen script

---

.github/workflows/issue_comment.yml
.github/workflows/new_issue.yml
.github/workflows/release.yml

Adding workflows that will notify the slack channel of:
- new issues
- new releases
- new comments on issues that are pending-response or closing-soon

chore(workflows): add workflows to notify actions

---

AmplifyPlugins/Storage/AWSS3StoragePlugin/Support/Internal/StorageTransferTask.swift

Fixes guard statement in fail function 

---

.github/workflows/issue_comment.yml

This reverts commit b8e1cb88506c47b156a0d5f3f87720db9f80495e, reversing
changes made to bf480cb032ac9fe58b1d1a4bea5b9e2ca0283c3f.

Revert "Merge branch 'main' into main"

---

.github/workflows/issue_comment.yml

Fixing issue when the new comment had multilines that resulted in multiple messages posted.
This was done by calling toJson in order to escape special characters (such as line breaks)
- ~[ ] Build succeeds with all target using Swift Package Manager~
- ~[ ] All unit tests pass~
- ~[ ] PR title conforms to conventional commit style~
- ~[ ] If breaking change, documentation/changelog update with migration instructions~

chore(workflows): updating new comment workflow

---

.github/workflows/new_issue.yml

Using an environment variable to escape the Title instead of `sed`.
~- [ ] Added new tests to cover change, if needed~
~- [ ] Build succeeds with all target using Swift Package Manager~
~- [ ] All unit tests pass~
~- [ ] All integration tests pass~
~- [ ] PR title conforms to conventional commit style~

chore(workflows): updating new issue workflow

---

README.md

Update dev-preview readme with blurb from docs site.
- ~~[ ] Build succeeds with all target using Swift Package Manager~~

chore: update dev-preview readme

---

Gemfile.lock

chore: Update Gemfile.lock to new version of ci-support

---

AmplifyPlugins/API/AWSAPICategoryPlugin/Interceptor/RequestInterceptor/APIKeyURLRequestInterceptor.swift
AmplifyPlugins/Core/AWSPluginsCore/Auth/Configuration/AWSAuthorizationConfiguration.swift

chore: Typo change in the error message

---

AmplifyPlugins.podspec
AmplifyPlugins/DataStore/Podfile
AmplifyPlugins/DataStore/Podfile.lock
Package.resolved
Package.swift

*Issue:* #1688 
Update SQLite dependency to 0.13.2

fix: update SQLite dependency to 0.13.2

---

.github/PULL_REQUEST_TEMPLATE.md

Adding new item to the PR checklist mentioning Security practices

chore(template): updating PR template to mention Security practices.

---

Gemfile.lock

chore: Update the cocoapods downloader to latest version

---

Gemfile

*Description of changes:* Adding a sample PR to trigger release work flow

chore: Format GemFile

---

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/ModelSchema+SQLite.swift

https://github.com/aws-amplify/amplify-flutter/issues/1512
Fixes build error on Xcode 12.4

fix(build): remove ungated  >= Swift 5.4 features to allow building on Xcode 12

---

.github/composite_actions/download_test_configuration/action.yml
.github/composite_actions/run_xcodebuild_test/action.yml
.github/workflows/integ_test.yml

test: Add integration test to GitHub Action

---

AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/README.md
AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/Support/AuthSessionHelper.swift
AmplifyPlugins/Predictions/AWSPredictionsPluginIntegrationTests/AWSPredictionsPluginTestBase.swift
AmplifyPlugins/Predictions/Podfile
AmplifyPlugins/Predictions/Podfile.lock
AmplifyPlugins/Predictions/PredictionsCategoryPlugin.xcodeproj/project.pbxproj
AmplifyPlugins/Storage/AWSS3StoragePluginFunctionalTests/README.md

test: Fix Prediction test in CI

---

AmplifyPlugins/Predictions/AWSPredictionsPluginIntegrationTests/AWSPredictionsPluginTestBase.swift
AmplifyPlugins/Predictions/AWSPredictionsPluginIntegrationTests/IdentifyBasicIntegrationTests.swift
AmplifyPlugins/Predictions/PredictionsCategoryPlugin.xcodeproj/xcshareddata/xcschemes/AWSPredictionsPluginIntegrationTests.xcscheme

test: Update predictions test to fix failures

---

AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginAuthIntegrationTests/DefaultAuthCognito/README.md
AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginAuthIntegrationTests/DefaultAuthIAM/README.md
AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginAuthIntegrationTests/MultiAuth/README.md
AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginIntegrationTests/README.md
AmplifyPlugins/DataStore/DataStoreCategoryPlugin.xcodeproj/project.pbxproj

test: Updated datastore Readme for integration test

---

AmplifyPlugins/API/AWSAPICategoryPluginIntegrationTests/GraphQL/GraphQLWithIAMIntegrationTests/GraphQLWithIAMIntegrationTests.swift
AmplifyPlugins/API/AWSAPICategoryPluginIntegrationTests/GraphQL/GraphQLWithIAMIntegrationTests/README.md
AmplifyPlugins/API/AWSAPICategoryPluginIntegrationTests/GraphQL/GraphQLWithLambdaAuthIntegrationTests/README.md
AmplifyPlugins/API/AWSAPICategoryPluginIntegrationTests/GraphQL/GraphQLWithUserPoolIntegrationTests/AuthDirective/GraphQLAuthDirectiveIntegrationTests.swift
AmplifyPlugins/API/AWSAPICategoryPluginIntegrationTests/GraphQL/GraphQLWithUserPoolIntegrationTests/README.md
AmplifyPlugins/API/AWSAPICategoryPluginIntegrationTests/REST/RESTWithUserPoolIntegrationTests/README.md
AmplifyPlugins/API/AWSAPICategoryPluginIntegrationTests/REST/RESTWithUserPoolIntegrationTests/RESTWithUserPoolIntegrationTests.swift

test(api): Updated the API plugin test with instructions

---

.github/workflows/notify_issue_comment.yml
.github/workflows/notify_new_issue.yml
.github/workflows/notify_release.yml

Adding workflows to post notifications for:
- New issues
- New comments on pending issues
- New releases

chore(workflows): Adding notification workflows

---

.github/workflows/integ_test.yml

chore: update integration test workflow to run on main

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/feature_request.yaml

N/A
Adds the Geo category to the issue and feature request templates.

chore: add Geo to issue template categories list [skip ci]

---

.circleci/config.yml

chore: Change deploy to use user key rather than deploy key

---

.github/workflows/block_manual_pr_release.yml
.github/workflows/release.yml

#1812 #1813 
chore: add GitHub Actions to kick-off release and block manual creation of PRs to the release branch
- ~~[ ] Build succeeds with all target using Swift Package Manager~~

chore: add GitHub Actions to kick-off release and block manual creation of PRs to the release branch

---

Amplify.xcodeproj/project.pbxproj
AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginIntegrationTests/PrimaryKey/AWSDataStorePrimaryKeyBaseTest.swift
AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginIntegrationTests/PrimaryKey/AWSDataStorePrimaryKeyTests.swift
AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginIntegrationTests/PrimaryKey/README.md
AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginIntegrationTests/PrimaryKey/schema.graphql
AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Core/SQLStatementTests.swift
AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Storage/CascadeDeleteOperationTests.swift
AmplifyPlugins/DataStore/DataStoreCategoryPlugin.xcodeproj/project.pbxproj
AmplifyTestCommon/Helpers/AuthSignInHelper.swift
AmplifyTestCommon/Models/CustomPrimaryKey/ModelCompositeIntPk+Schema.swift
AmplifyTestCommon/Models/CustomPrimaryKey/ModelCompositeIntPk.swift
AmplifyTestCommon/Models/CustomPrimaryKey/ModelCustomPkDefined+Schema.swift
AmplifyTestCommon/Models/CustomPrimaryKey/ModelExplicitCustomPk+Schema.swift
AmplifyTestCommon/Models/CustomPrimaryKey/ModelExplicitDefaultPk+Schema.swift

DataStore Custom Primary Key tests
~- [ ] Added new tests to cover change, if needed~
~- [ ] Security oriented best practices and standards are followed (e.g. using input sanitization, principle of least privilege, etc)~

test(datastore): custom pk tests

---

.github/workflows/notify_issue_comment.yml

- Removing the restriction to only notify comments in pending/closing soon issues
- Filtering out comments made by the Amplify team.

chore(workflows): Notifying all comments in issues

---

.github/workflows/cleanup_labels_issue_close.yml

N/A
Remove labels on issue close:
- `closing soon`
- `pending-response`
- `pending-release`

chore: add action to remove extra labels on issue close [skip ci]

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/AWSAuthConfirmSignUpOperation.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/AWSAuthSignInOperation.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/AWSAuthSignUpOperation.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/OperationTests/AWSAuthSignUpOperationTests.swift

chore: Cleanup operations to stop relying on configuration state

---

.github/workflows/cleanup_labels_issue_close.yml

Fixes typo in `cleanup_labels_issue_close` action.

chore(action): fix typo in `cleanup_labels_issue_close` action

---

.github/workflows/release_merge_pr.yml

fixes a bug with the release merge action that prevented it from being limited to PRs targeting the release branch

chore: fix release merge action

---

.swiftlint.yml
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/Authentication/SignInComplete.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Service/ErrorMapping/SdkError+AuthError.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Data/RespondToAuthChallenge.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Events/AuthenticationEvent.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/States/DebugInfo/SignInChallengeState+Debug.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/States/SignInChallengeState.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/States/SignInState.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/Authentication/AuthenticationState+Resolver.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/SRP/SRPSignInState+Resolver.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/SignIn/SignInState+Resolver.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/OperationTests/AWSAuthConfirmSignUpOperationTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/OperationTests/AWSAuthSignUpOperationTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/Support/DefaultConfig.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/Support/MockIdentityProvider.swift

chore(auth): Cleanup signIn flow and separated SignInState

---

.github/codeql/config.yml
.github/codeql/enable_codeql.js
.github/workflows/codeql.yml

Enable code scanning to monitor for security vulnerabilities in GitHub Actions workflows.
- ~~[ ] Build succeeds with all target using Swift Package Manager~~

chore: enable code scanning

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SRPAuth/CancelSignIn.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignUp/CancelSignUp.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/AWSAuthConfirmSignUpOperation.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/AWSAuthSignInOperation.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/AWSAuthSignOutOperation.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/AWSAuthSignUpOperation.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Events/AuthenticationEvent.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/States/AuthenticationState.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/States/DebugInfo/AuthenticationState+Debug.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/Authentication/AuthenticationState+Resolver.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/OperationTests/AWSAuthConfirmSignUpOperationTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/OperationTests/AWSAuthSignUpOperationTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ResolverTests/AuthTestData.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/Support/AWSAuthCognitoSessionTests.swift

chore(auth): Remove configuration from authenticaiton state

---

AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/Dependency/Pinpoint/Analytics/AnalyticsClient.swift
AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/Dependency/Pinpoint/Analytics/EventRecorder.swift
AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/Dependency/Pinpoint/Analytics/PinpointEvent+PinpointClientTypes.swift
AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/Dependency/Pinpoint/Analytics/PinpointEvent.swift
AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/Dependency/Pinpoint/Analytics/SdkError+IsRetryable.swift
AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/Dependency/Pinpoint/PinpointContext.swift
AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/Dependency/Pinpoint/Session/SessionTracker.swift
AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/LocalStorage/AnalyticsEventSQLStorage.swift
AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/LocalStorage/AnalyticsEventStorage.swift
AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/LocalStorage/PinpointEvent+Bindings.swift
AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/LocalStorage/SQLiteLocalStorageAdapter.swift

* Initial implementation of saving local pinpoint events and submitting events to Pinpoint via pinpoint client
* Unit tests and open TODOs are in-progress/pending work yet to be completed.
- [] ~Documentation update for the change if required~

feat(analytics): add pinpoint event submission

---

AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/Dependency/Pinpoint/Analytics/AnalyticsClient.swift
AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/Dependency/Pinpoint/Session/SessionTracker.swift

Fix build errors as a result of previous PR merge

chore: fix build error from merge

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SRPAuth/VerifyPasswordSRP.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/ClientBehavior/AWSCognitoAuthPlugin+ClientBehavior.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/AmplifyConfirmSignInOperation.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Data/RespondToAuthChallenge.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Events/SignInEvent.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/States/DebugInfo/SignInChallengeState+Debug.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/SignIn/SignInState+Resolver.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/OperationTests/AWSAuthSignInOperationTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ResolverTests/SRPSignInState/SRPTestData.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/Support/DefaultConfig.swift

feat(auth): Adds confirmSignIn api and operation

---

Amplify/Categories/DataStore/Model/Temporal/Temporal+Cache.swift

Creates a pointer to the `os_unfair_lock` used by `Temporal` to ensure proper locking. The previous implementation was unsafe to use from Swift because the `&` automatic pointer conversion syntax permits the compiler to move the value to a more convenient before making a pointer, then move it back. This can result in `os_unfair_lock_lock(&lock)` locking a copy of the `os_unfair_lock`. Moving to the pointer approach allocates on the heap with a stable memory address and prevents any copying from occurring. 
[Example](https://github.com/apple/swift-corelibs-foundation/blob/main/Sources/Foundation/AttributedString/AttributedString+Locking.swift#L18-L22) of approach in `swift-corelibs-foundation`.
*Check points: (check or cross out if not …

fix(datastore): temporal locking

---

AmplifyPlugins/DataStore/DataStoreCategoryPlugin.xcodeproj/xcshareddata/xcschemes/AWSDataStoreCategoryPlugin.xcscheme

chore: disable flaky datastore tests

---

AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/Dependency/Pinpoint/Analytics/EventRecorder.swift
AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/Dependency/Pinpoint/PinpointContext.swift
AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/LocalStorage/AnalyticsEventSQLStorage.swift
AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/LocalStorage/AnalyticsEventStorage.swift
AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/LocalStorage/SQLStorageProtocol.swift
AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/LocalStorage/SQLiteLocalStorageAdapter.swift
AmplifyPlugins/Analytics/AWSPinpointAnalyticsPluginTests/AnalyticsEventStorageTests.swift
AmplifyPlugins/Analytics/AWSPinpointAnalyticsPluginTests/Mocks/MockSQLiteLocalStorageAdapter.swift
AmplifyPlugins/Analytics/AWSPinpointAnalyticsPluginTests/SQLiteLocalStorageAdapterTests.swift

Add logic to check size of analytics local storage clean up storage to reduce size if it is over the limit

feature(analytics): add analytics local storage size limit and cleanup

---

Amplify/Categories/Geo/GeoCategory+ClientBehavior.swift
Amplify/Categories/Geo/GeoCategoryBehavior.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/CredentialStore/MigrateLegacyCredentialStore.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/FetchAuthorizationSession/InitializeFetchAuthSessionWithUserPool.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/FetchAuthorizationSession/UserPool/RefreshUserPoolTokens.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/ClientBehavior/AWSCognitoAuthPlugin+UserBehavior.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/CredentialStorage/AmplifyCredentials.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/AuthConfigureOperation.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/Helpers/FetchAuthSessionOperationHelper.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/UserOperations/AWSAuthAttributeResendConfirmationCodeOperation.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Service/CognitoUserPoolBehavior.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Service/ErrorMapping/GetUserAttributeVerificationCodeOutputError+AuthError.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Data/LoginsMapProvider.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/Authorization/AuthorizationState+Resolver.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/FetchAuthSession/FetchAuthSessionState+Resolver.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/StateMachineSupport/AWSCognitoAuthPlugin+StateMachine.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/Support/MockIdentityProvider.swift
AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/AuthUserAttributesTests/AuthUserAttributesTests.swift
AmplifyPlugins/Geo/AWSLocationGeoPlugin/AWSLocationGeoPlugin+ClientBehavior.swift
AmplifyPlugins/Geo/AWSLocationGeoPlugin/Support/Utils/GeoErrorHelper.swift
AmplifyPlugins/Geo/AWSLocationGeoPluginTests/AWSLocationGeoPluginClientBehaviorTests.swift
AmplifyPlugins/Geo/AWSLocationGeoPluginTests/AWSLocationGeoPluginTestBase.swift
AmplifyPlugins/Geo/AWSLocationGeoPluginTests/Mocks/MockAWSClientConfiguration.swift
AmplifyPlugins/Geo/AWSLocationGeoPluginTests/Mocks/MockAWSLocation+ClientBehavior.swift
AmplifyPlugins/Geo/AWSLocationGeoPluginTests/Mocks/MockAWSLocation.swift
AmplifyPlugins/Geo/GeoHostApp/AWSLocationGeoPluginIntegrationTests/AWSLocationGeoPluginIntegrationTests.swift
AmplifyTestCommon/Mocks/MockGeoCategoryPlugin.swift
AmplifyTests/CategoryTests/Geo/GeoCategoryClientAPITests.swift
AmplifyTests/CategoryTests/Geo/GeoCategoryConfigurationTests.swift
Package.swift

*Description of changes:* Fixes swift lint

chore: Swift lint edits

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/ClientBehavior/AWSCognitoAuthPlugin+UserBehavior.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/UserOperations/AWSAuthFetchUserAttributesOperation.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Service/CognitoUserPoolBehavior.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Service/ErrorMapping/GetUserOutputError+AuthError.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/Support/MockIdentityProvider.swift
AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/AuthUserAttributesTests/AuthUserAttributesTests.swift

The PR aims at adding the implementation for fetching the user attributes when signed in. 

feat(Auth): Adding FetchUserAttribute API implementation

---

AmplifyTests/CategoryTests/Geo/GeoCategoryConfigurationTests.swift

*Description of changes:* Update previously failing Geo unit tests with preConditionFailure.

chore(geo): Fix unit tests with preConditionFailure

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/ClientBehavior/AWSCognitoAuthPlugin+UserBehavior.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/UserOperations/AWSAuthAttributeResendConfirmationCodeOperation.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/UserOperations/AWSAuthUpdateUserAttributeOperation.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Service/CognitoUserPoolBehavior.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Service/ErrorMapping/UpdateUserAttributesOutputError+AuthError.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Service/Helpers/AuthUserAttribute+Helper.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/Support/MockIdentityProvider.swift
AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/AuthUserAttributesTests/AuthUserAttributesTests.swift

The purpose of the PR is to add implementation of Update User Attribute API. 

feat(Auth): Adding UpdateUserAttribute API implementation

---

AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/LocalStorage/PinpointEvent+Bindings.swift
AmplifyPlugins/Analytics/AWSPinpointAnalyticsPluginTests/AnalyticsEventStorageTests.swift
AmplifyPlugins/Analytics/AWSPinpointAnalyticsPluginTests/SQLiteLocalStorageAdapterTests.swift

* Add unit tests to cover analytics event storage

chore(Analytics): add unit test for analytics storage

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/UserOperations/AWSAuthUpdateUserAttributesOperation.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/States/DebugInfo/AuthorizationState+Debug.swift

*Description of changes:* Fix the user behavior api in preparation to merge the feature branch to dev-preview. 
This is the continuation of the PRs from: 
https://github.com/aws-amplify/amplify-ios/pull/1920 fix: Migration of legacy store with new authorization flow 
https://github.com/aws-amplify/amplify-ios/pull/1919 fix: SignIn, signOut and confirmsignIn with new authorizationflow
https://github.com/aws-amplify/amplify-ios/pull/1916 chore: Fix fetchauthsession helper
https://github.com/aws-amplify/amplify-ios/pull/1914 test(auth): Fix unit test errors for authorization statemachine refctor
https://github.com/aws-amplify/amplify-ios/pull/1897 chore: Refactor authorization flow, adds refresh flow
https://github.com/aws-amplify/amplify-ios/pull/1872 chore: Change …

fix(auth): Fix the user behavior api

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/ClientBehavior/AWSCognitoAuthPlugin+UserBehavior.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/UserOperations/AWSAuthAttributeResendConfirmationCodeOperation.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/UserOperations/AWSAuthConfirmUserAttributeOperation.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/UserOperations/AWSAuthFetchUserAttributesOperation.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/UserOperations/AWSAuthUpdateUserAttributeOperation.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/UserOperations/AWSAuthUpdateUserAttributesOperation.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Service/CognitoUserPoolBehavior.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Service/ErrorMapping/VerifyUserAttributeOutputError+AuthError.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/Support/MockIdentityProvider.swift

feat(Auth): Adding VerifyUserAttribute API implementation

---

AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/CredentialStore/CredentialStoreConfigurationTests.swift
AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/Helpers/AuthSessionHelper.swift

test(auth): Fix integration test after the refactor

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/AWSCognitoAuthPlugin+Configure.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/AWSCognitoAuthPlugin+EscapeHatch.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/AWSCognitoAuthPlugin.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/ClientBehavior/AWSCognitoAuthPlugin+UserBehavior.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Environment/AuthorizationEnvironment.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/Helpers/FetchAuthSessionOperationHelper.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Service/ErrorMapping/ChangePasswordOutputError+AuthError.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/Mocks/MockAuthHubEventBehavior.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/OperationTests/AWSAuthSignInOperationTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/OperationTests/UserBehaviourTests/BaseUserBehaviorTest.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/OperationTests/UserBehaviourTests/UserBehaviorChangePasswordTests.swift
AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/AuthUserAttributesTests/AuthUserAttributesTests.swift

feat(Auth): Adding unit tests for User Behaviour Change Password

---

AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/OperationTests/UserBehaviourTests/AWSCognitoAuthUserBehaviorTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/OperationTests/UserBehaviourTests/BaseUserBehaviorTest.swift

feat(Auth): Adding unit tests for User Behaviour Operations

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/CredentialStorage/AmplifyCredentials+CognitoSession.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/AWSAuthSignOutOperation.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/Helpers/FetchAuthSessionOperationHelper.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Helpers/AuthCognitoSignedOutSessionHelper.swift
AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/AWSAuthBaseTest.swift
AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/AuthEventTests/AuthEventIntegrationTests.swift
AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/SessionTests/SignedInAuthSessionTests.swift

test(auth): Fix integration test for signedOut

---

AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/Dependency/Pinpoint/Endpoint/Device.swift

Adding empty implementation of `Device`

feat(Analytics): Adding empty device implementation.

---

.swiftpm/xcode/xcshareddata/xcschemes/Amplify-Package.xcscheme
AmplifyPlugins/Analytics/AWSPinpointAnalyticsPluginTests/Pinpoint/UIActivityTrackerTests.swift

fix(analytics): update analytics test

---

AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/OperationTests/UserBehaviourTests/AWSCognitoAuthUserBehaviorTests.swift

fix race condition in AWSCognitoAuthUserBehaviorTests

fix(auth): fix race condition in AWSCognitoAuthUserBehaviorTests

---

AmplifyPlugins/API/AWSAPICategoryPluginTests/AWSAPICategoryPlugin+GraphQLBehaviorTests.swift
AmplifyPlugins/API/AWSAPICategoryPluginTests/AWSAPICategoryPlugin+RESTClientBehaviorTests.swift
AmplifyPlugins/API/AWSAPICategoryPluginTests/AWSAPICategoryPluginTestBase.swift

*Issue #1944*
fix(api): fix race conditions in API tests

fix(api): fix race conditions in API tests

---

canaries/example/MyAmplifyApp/ContentView.swift
canaries/example/MyAmplifyApp/MyAmplifyAppApp.swift
canaries/example/MyAmplifyAppUITests/MyAmplifyAppUITests.swift

chore: Added license headers to canary sample app

chore: Added license headers to canary sample app

---

.swiftpm/xcode/xcshareddata/xcschemes/Amplify-Package.xcscheme
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/FetchAuthorizationSession/InformSessionError.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/Helpers/FetchAuthSessionOperationHelper.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Errors/AuthorizationError.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Events/AuthorizationEvent.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Events/FetchAuthSessionEvent.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Events/RefreshSessionEvent.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/States/DebugInfo/RefreshSessionState+Debug.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/States/RefreshSessionState.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/Authorization/AuthorizationState+Resolver.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/RefreshSession/RefreshSessionState+Resolver.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Helpers/AuthCognitoSignedInSessionHelper.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ActionTests/FetchAuthSession/InitializeFetchAuthSessionTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/OperationTests/AuthorizationTests/AWSAuthFetchSignInSessionOperationTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ResolverTests/AuthTestData.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ResolverTests/AuthorizationState/AuthorizationTestData.swift

test: Add test to fetchsession and handle error

---

.github/workflows/feature_request.yml

N/A
Adds GitHub Action that posts the following message to an issue after it is labeled `feature-request`.
> This has been identified as a feature request. If this feature is important to you, we strongly encourage you to give a 👍 reaction on the request. The feedback we receive from the community is a large factor in helping us prioritize new features.

chore: add action that comments on feature request label event

---

AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/Dependency/AWSPinpointAdapter.swift
AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/Dependency/AWSPinpointBehavior.swift
AmplifyPlugins/Analytics/AWSPinpointAnalyticsPluginTests/Mocks/MockAWSPinpoint.swift

Fixing a typo: `analytisClient` -> `analyticsClient`

chore(Analytics): Fixing typo in "analyticsClient".

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/Persistence/ConfigureAuthentication.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SRPAuth/StartSRPFlow.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/IntializeSignInFlow.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Models/Options/AWSAuthSignInOptions.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Data/SignInEventData.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Data/SignInMethod.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Data/UserPoolConfigurationData.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Events/SignInEvent.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/States/SignInState.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/Authentication/AuthenticationState+Resolver.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/SRP/SRPSignInState+Resolver.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/SignIn/SignInState+Resolver.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Helpers/UserPoolSignInHelper.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/OperationTests/ClientBehaviorTests/AWSCognitoAuthClientBehaviorTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/OperationTests/UserBehaviourTests/BaseUserBehaviorTest.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ResolverTests/AuthTestData.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ResolverTests/SRPSignInState/NotStartedTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ResolverTests/SRPSignInState/SRPTestData.swift

fix(auth): Change signInState state machine with new events

---

AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/Dependency/Pinpoint/Analytics/AnalyticsClient.swift
AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/Dependency/Pinpoint/Analytics/EventRecorder.swift
AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/LocalStorage/AnalyticsEventSQLStorage.swift
AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/LocalStorage/AnalyticsEventStorage.swift
AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/LocalStorage/PinpointEvent+Bindings.swift
AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/Notifications/AWSPinpointAnalyticsNotifications.swift
AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/Notifications/AWSPinpointAnalyticsNotificationsBehavior.swift
AmplifyPlugins/Analytics/AWSPinpointAnalyticsPluginTests/AWSPinpointAnalyticsNotificationsTests.swift
AmplifyPlugins/Analytics/AWSPinpointAnalyticsPluginTests/AnalyticsEventStorageTests.swift
AmplifyPlugins/Analytics/AWSPinpointAnalyticsPluginTests/Mocks/MockAnalyticsEventStorage.swift
AmplifyPlugins/Analytics/AWSPinpointAnalyticsPluginTests/Mocks/Pinpoint/MockAnalyticsClient.swift
AmplifyPlugins/Analytics/AWSPinpointAnalyticsPluginTests/Mocks/Pinpoint/MockEventRecorder.swift
AmplifyPlugins/Analytics/AWSPinpointAnalyticsPluginTests/Mocks/Pinpoint/MockUserDefaults.swift

~- [ ] All integration tests pass~
~- [ ] Security oriented best practices and standards are followed (e.g. using input sanitization, principle of least privilege, etc)~

feat(analytics): analytics migration - notifications

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/ClientBehavior/AWSCognitoAuthPlugin+DeviceBehavior.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Models/AWSAuthDevice.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/AWSAuthFetchDevicesOperation.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Service/CognitoUserPoolBehavior.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Service/ErrorMapping/ListDevicesOutputError+AuthError.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Service/Helpers/ListDevicesOutputResponse+Helper.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/OperationTests/DeviceBehaviorTests/AWSAuthDeviceBehaviorTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/OperationTests/DeviceBehaviorTests/DeviceBehaviorFetchDevicesTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/Support/MockIdentityProvider.swift
AmplifyPlugins/Auth/Tests/AuthHostApp/AuthHostApp.xcodeproj/project.pbxproj
AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/DeviceTests/AuthFetchDeviceTests.swift
AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/README.md

*Description of changes:* Add Fetch Devices API implementation based on `aws-sdk-swift`

feat(auth): Add Fetch Devices API implementation

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Models/AuthChallengeType.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Models/AuthFlowType.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/AWSAuthConfirmSignInOperation.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Events/SignInEvent.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/States/DebugInfo/SignInState+Debug.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/States/SignInState.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/SignIn/SignInState+Resolver.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Helpers/UserPoolSignInHelper.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/OperationTests/AWSAuthConfirmSignInOperationTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/OperationTests/AWSAuthSignInPluginTests.swift

Adding support for newPasswordRequired challenge when signing into Cognito.

feat(Auth): Adding support for newPasswordRequired challenge

---

.github/ISSUE_TEMPLATE/bug_report.yaml
LogsGuidance.md

adds logs guidance for new bug reports

---

.github/ISSUE_TEMPLATE/bug_report.yaml

updates issue template to change placeholder to value

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/ClientBehavior/AWSCognitoAuthPlugin+DeviceBehavior.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/AWSAuthForgetDeviceOperation.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Service/CognitoUserPoolBehavior.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Service/ErrorMapping/ForgetDeviceOutputError+AuthError.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/OperationTests/DeviceBehaviorTests/DeviceBehaviorForgetDeviceTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/Support/MockIdentityProvider.swift
AmplifyPlugins/Auth/Tests/AuthHostApp/AuthHostApp.xcodeproj/project.pbxproj
AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/DeviceTests/AuthForgetDeviceTests.swift

*Description of changes:* Add `forgetDevice` API implementation based on `aws-swift-sdk`

feat(auth): Add Forget Device API implementation

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/HostedUI/FetchHostedUISignInToken.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/HostedUI/InitializeHostedUISignIn.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/HostedUI/ShowHostedUI.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Models/AWSAuthUser.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/AWSAuthWebUISignInOperation.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Data/HostedUIConfigurationData.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Data/HostedUIOptions.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Data/HostedUIResult.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Data/SignInMethod.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Errors/HostedUIError.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Errors/SignInError.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Events/HostedUIEvent.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/States/DebugInfo/SignInState+Debug.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/States/HostedUISignInState.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/ErrorMapping/SRPSignInError+Helper.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/Authorization/AuthorizationState+Resolver.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/SignIn/HostedUISignInState+Resolver.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/SignIn/SignInState+Resolver.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Helpers/ConfigurationHelper.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Helpers/TokenParserHelper.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Helpers/UserPoolSignInHelper.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/StateMachineSupport/StateMachineEvent+Type.swift

Added implementation for the hosted UI flows.

 feat(auth): Implementation of hostedUI flow

---

Package.swift

Fixes warnings in Package.swift

---

Amplify/Categories/Auth/AuthCategory+UserBehavior.swift
Amplify/Categories/Auth/AuthCategoryUserBehavior.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/ClientBehavior/AWSCognitoAuthPlugin+UserBehavior.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Models/AWSCognitoAuthUser.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/hierarchical-state-machine-swift/StateMachine.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ClientBehaviorTests/AuthCategoryUserBehaviorTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/Mocks/MockAuthStateMachine.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/Support/DefaultConfig.swift
AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngine+AuthModeStrategyDelegate.swift
AmplifyTestCommon/Mocks/MockAuthCategoryPlugin.swift

#1829 
Implements `getCurrentUser` function and adds unit tests.

feat(auth): implements get current user

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/HostedUI/InitializeHostedUISignIn.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/HostedUI/ShowHostedUI.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Models/Options/AWSAuthWebUISignInOptions.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/AWSAuthSocialWebUISignInOperation.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/Helpers/HostedUISignInHelper.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Data/HostedUIOptions.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Data/HostedUIProviderInfo.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Helpers/AuthProvider+Cognito.swift

feat(auth): Add authprovider for hostedui signIn

---

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/AWSDataStorePlugin.swift
AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/InitialSync/InitialSyncOrchestrator.swift
AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/InitialSync/ModelSyncedEventEmitter.swift
AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/InitialSync/SyncEventEmitter.swift
AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngine+IncomingEventReconciliationQueueEvent.swift
AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngine.swift
AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginAuthIntegrationTests/Common/AWSDataStoreAuthBaseTest.swift
AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginAuthIntegrationTests/DefaultAuthCognito/AWSDataStoreCategoryPluginAuthIntegrationTests.swift
AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginIntegrationTests/DataStoreEndToEndTests.swift

fix(datastore): Fix ModelSyncedEventEmitter, add lifecycle events logging

---

CHANGELOG.md

Updating changelog, it wasn't added automatically because of a missing `:` in the commit message.

chore: Updating changelog [skip ci]

---

.swiftpm/xcode/xcshareddata/xcschemes/Amplify-Package.xcscheme
Amplify/Categories/Auth/Request/AuthSignOutRequest.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/HostedUI/ShowHostedUISignIn.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignOut/InitiateSignOut.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignOut/ShowHostedUISignOut.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/ClientBehavior/AWSCognitoAuthPlugin+ClientBehavior.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/AWSAuthSignOutOperation.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Events/SignOutEvent.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/States/SignOutState.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/SignIn/HostedUISignInState+Resolver.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/SignOut/SignOutState+Resolver.swift

feat(auth): HostedUI signOut implementation

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/AWSCognitoAuthPlugin+Configure.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/HostedUI/FetchHostedUISignInToken.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/HostedUI/InitializeHostedUISignIn.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/HostedUI/ShowHostedUISignIn.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignOut/ShowHostedUISignOut.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Environment/AuthEnvironment.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Environment/AuthenticationEnvironment.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Environment/HostedUIEnvironemt.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Errors/HostedUIError.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/ErrorMapping/SRPSignInError+Helper.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Helpers/TokenParserHelper.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/HostedUI/HostedUIASWebAuthenticationSession.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/HostedUI/HostedUIRequestHelper.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/HostedUI/HostedUISessionBehavior.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/HostedUI/RandomStringBehavior.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/HostedUI/RandomStringGenerator.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/Mocks/MockData/AWSCognitoUserPoolTokens.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/Mocks/MockHostedUISession.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/Mocks/MockRandomStringGenerator.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/Mocks/MockURLProtocol.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/OperationTests/HostedUITests/AWSAuthHostedUISignInTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ResolverTests/SignOutState/SignOutStateNotStartedTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ResolverTests/SignOutState/SignOutStateRevokingTokenTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ResolverTests/SignOutState/SignOutStateSigningOutGloballyTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ResolverTests/SignOutState/SignOutStateSigningOutLocallyTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/Support/DefaultConfig.swift

*Description of changes:* Test setup for hostedUI, will followup PR with more test.

test(auth): Add unit testing to hostedUI signIn

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/AWSAuthSignInOperation.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/AWSAuthSignOutOperation.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/Helpers/FetchAuthSessionOperationHelper.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/States/DebugInfo/FetchAuthSessionState+Debug.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/States/FetchAuthSessionState.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/Authorization/AuthorizationState+Resolver.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/FetchAuthSession/FetchAuthSessionState+Resolver.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/RefreshSession/RefreshSessionState+Resolver.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Helpers/UserPoolSignInHelper.swift

fix(Auth): Fixing FetchAuthSession, SignOut operations bugs

---

Amplify/Categories/Auth/AuthCategory+ClientBehavior.swift
Amplify/Categories/Auth/Request/AuthSignOutRequest.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignOut/ShowHostedUISignOut.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/AWSAuthSignOutOperation.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Data/SignOutEventData.swift

chore(auth): Add optional presentation anchor to signOut flow

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/HostedUI/FetchHostedUISignInToken.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/HostedUI/ShowHostedUISignIn.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/States/DebugInfo/HostedUISignInState+Debug.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/ErrorMapping/SignInError+Helper.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Constants/AuthPluginErrorConstants.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/OperationTests/AWSAuthConfirmSignUpOperationTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/OperationTests/AWSAuthSignInOperationTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/OperationTests/AWSAuthSignUpOperationTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/OperationTests/HostedUITests/AWSAuthHostedUISignInTests.swift

test(auth): Added more hostedUI test cases

---

Amplify/Categories/Auth/Models/AuthUserAttribute.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Utils/AuthUserAttributeKey+RawValue.swift

* Add support for all openID attributes to `AuthUserAttribute`

chore(Auth): add missing openID attributes to AuthUserAttribute

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/HubEvents/AuthHubEventHandler.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/HubEventTests/AuthHubEventHandlerTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/Support/DefaultConfig.swift

chore(auth): Enabled HostedUI hub events

---

AmplifyPlugins/Storage/AWSS3StoragePlugin/Service/Storage/AWSS3StorageService.swift

#2047
Race condition reported by Thread Sanitizer.

fixes race condition in Storage category 

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/ASF/ASFAppInfo.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/ASF/ASFUIDeviceInfo.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/ASF/AdvancedSecurityBehavior.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/ASF/CognitoUserPoolASF.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/AWSCognitoAuthPlugin+Configure.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Environment/UserPoolEnvironment.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ActionTests/FetchAuthSession/FetchUserPoolTokens/RefreshUserPoolTokensTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ActionTests/SignOut/RevokeTokenTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ActionTests/SignOut/SignOutGloballyTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/CognitoASFTests/ASFCognitoTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/CognitoASFTests/ASFUIDeviceInfoTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/CognitoASFTests/CognitoUserPoolASFTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ResolverTests/SignUpState/ConfirmSignUpStateTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ResolverTests/SignUpState/SignUpStateTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/Support/DefaultConfig.swift

feat(auth): Added implementation for ASF logic

---

AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/Notifications/AWSPinpointAnalyticsNotifications.swift

Fixing a compilation issue when UIKit can't be imported.

fix(Analytics): Fixing compilation issue in Notifications

---

.swiftpm/xcode/xcshareddata/xcschemes/Amplify-Package.xcscheme
Amplify/Categories/API/AuthProvider/APIAuthProviderFactory.swift
AmplifyPlugins/API/Sources/AWSAPIPlugin/Interceptor/RequestInterceptor/AuthTokenProviderWrapper.swift
AmplifyPlugins/API/Tests/AWSAPIPluginTests/Interceptor/SubscriptionInterceptor/AuthenticationTokenAuthInterceptorTests.swift
AmplifyPlugins/Analytics/AWSPinpointAnalyticsPluginTests/Mocks/MockAWSAuthService.swift
AmplifyPlugins/Core/AWSPluginsCore/Auth/AWSAuthService.swift
AmplifyPlugins/Core/AWSPluginsCore/Auth/AWSAuthServiceBehavior.swift
AmplifyPlugins/Core/AWSPluginsTestCommon/MockAWSAuthService.swift
AmplifyTestCommon/Mocks/MockAPICategoryPlugin.swift

remove deprecated auth core methods

fix: remove deprecated auth core methods

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/CredentialStore/ClearCredentialStore.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/CredentialStorage/CredentialStoreOperationClient.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Events/CredentialStoreEvent.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/States/CredentialStoreState.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/States/DebugInfo/CredentialStoreState+Debug.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/CredentialStore/CredentialStoreState+Resolver.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ResolverTests/CredentialStoreState/CredentialStoreStateResolverTests.swift

chore(auth): Change the delete credential logic

---

AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/Base/HubListenerTestUtilities.swift
AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/Connection/DataStoreConnectionScenario1Tests.swift
AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/Connection/DataStoreConnectionScenario2Tests.swift
AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/Connection/DataStoreConnectionScenario3Tests.swift
AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/DataStoreConsecutiveUpdatesTests.swift
AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/DataStoreCustomPrimaryKeyTests.swift
AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/DataStoreEndToEndTests.swift
AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/SubscriptionEndToEndTests.swift
AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/TestSupport/SyncEngineIntegrationTestBase.swift
AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/TestSupport/SyncEngineIntegrationV2TestBase.swift

chore(datastore): HubListenerTestUtilities.waitForListener async

---

.swiftpm/xcode/xcshareddata/xcschemes/Amplify-Package.xcscheme
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/ASF/CognitoUserPoolASF+KeyChain.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/AWSCognitoAuthPlugin+Configure.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/CredentialStore/ClearCredentialStore.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/CredentialStore/LoadCredentialStore.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/CredentialStore/StoreCredentials.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/CustomSignIn/InitiateCustomAuth.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/MigrateAuth/InitiateMigrateAuth.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/SRPAuth/InitiateAuthSRP.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/CredentialStorage/AWSCognitoAuthCredentialStore.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/CredentialStorage/AmplifyAuthCredentialStoreBehavior.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/CredentialStorage/CredentialStoreOperationClient.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Environment/UserPoolEnvironment.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Events/CredentialStoreEvent.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/SRP/DeviceSRPState+Resolver.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Utils/InitiateAuthInput+Amplify.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ActionTests/CredentialStore/MockAmplifyCredentialStoreBehavior.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/OperationTests/UserBehaviourTests/UserBehaviorUpdateAttributeTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ResolverTests/AuthorizationState/AuthorizationStateResolverTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/Support/DefaultConfig.swift

feat(auth): Add advanced security feature to initiateAuth

---

AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Sync/SubscriptionSync/ModelReconciliationDeleteTests.swift

fix(datastore): replace thread sleep with task sleep

fix(datastore): replace thread sleep with task sleep

---

.swiftpm/xcode/xcshareddata/xcschemes/Amplify-Package.xcscheme
AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Core/SQLiteStorageEngineAdapterJsonTests.swift
AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Sync/RemoteSync/RemoteSyncAPIInvocationTests.swift
AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/TestSupport/BaseDataStoreTests.swift
AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginFlutterTests/DataStoreFlutterConsecutiveUpdatesTests.swift
AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/TestSupport/HubEventsIntegrationTestBase.swift
AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/TestSupport/SyncEngineIntegrationTestBase.swift
AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/TestSupport/SyncEngineIntegrationV2TestBase.swift

remove unnecessary sleeps from tests

chore(datastore): remove unnecessary sleeps from tests

---

AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/RemoteSyncEngine+AuthModeStrategyDelegate.swift

fix(datastore): Remove DispatchGroup - RemoteSyncEngine.isUserLoggedIn() async -> Bool

---

Amplify/Categories/DataStore/Model/ModelIdentifiable.swift
AmplifyPlugins/Core/AWSPluginsCore/Sync/MutationSync/MutationSyncMetadata+Schema.swift
AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Core/SQLStatementTests.swift
AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Models/SQLModelValueConverterTests.swift
AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Storage/CascadeDeleteOperationTests.swift
AmplifyTestCommon/Models/CustomPrimaryKey/CommentWithCompositeKey+Schema.swift
AmplifyTestCommon/Models/CustomPrimaryKey/CommentWithCompositeKeyAndIndex+Schema.swift
AmplifyTestCommon/Models/CustomPrimaryKey/CommentWithCompositeKeyUnidirectional+Schema.swift
AmplifyTestCommon/Models/CustomPrimaryKey/ModelCompositeIntPk+Schema.swift
AmplifyTestCommon/Models/CustomPrimaryKey/ModelCompositePk+Schema.swift
AmplifyTestCommon/Models/CustomPrimaryKey/ModelCompositePkBelongsTo+Schema.swift
AmplifyTestCommon/Models/CustomPrimaryKey/ModelCompositePkWithAssociation+Schema.swift
AmplifyTestCommon/Models/CustomPrimaryKey/ModelCustomPkDefined+Schema.swift
AmplifyTestCommon/Models/CustomPrimaryKey/ModelExplicitCustomPk+Schema.swift
AmplifyTestCommon/Models/CustomPrimaryKey/ModelExplicitDefaultPk+Schema.swift
AmplifyTestCommon/Models/CustomPrimaryKey/ModelImplicitDefaultPk+Schema.swift
AmplifyTestCommon/Models/CustomPrimaryKey/PostTagsWithCompositeKey+Schema.swift
AmplifyTestCommon/Models/CustomPrimaryKey/PostWithCompositeKey+Schema.swift
AmplifyTestCommon/Models/CustomPrimaryKey/PostWithCompositeKeyAndIndex+Schema.swift
AmplifyTestCommon/Models/CustomPrimaryKey/PostWithCompositeKeyUnidirectional+Schema.swift
AmplifyTestCommon/Models/CustomPrimaryKey/PostWithTagsCompositeKey+Schema.swift
AmplifyTestCommon/Models/CustomPrimaryKey/TagWithCompositeKey+Schema.swift

This is a cherry-pick of the commit added to `main` from #2077 

fix(datastore): Rename ModelIdentifiable.Identifier to IdentifierProtocol (#2077)

---

AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/Base/TestConfigHelper.swift
AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/Models/CommentWithCompositeKey+Schema.swift
AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/Models/CommentWithCompositeKeyAndIndex+Schema.swift
AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/Models/CommentWithCompositeKeyUnidirectional+Schema.swift
AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/Models/ModelCompositeIntPk+Schema.swift
AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/Models/ModelCompositePk+Schema.swift
AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/Models/ModelCompositePkBelongsTo+Schema.swift
AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/Models/ModelCompositePkWithAssociation+Schema.swift
AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/Models/ModelCustomPkDefined+Schema.swift
AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/Models/ModelExplicitCustomPk+Schema.swift
AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/Models/ModelExplicitDefaultPk+Schema.swift
AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/Models/ModelImplicitDefaultPk+Schema.swift
AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/Models/PostTagsWithCompositeKey+Schema.swift
AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/Models/PostWithCompositeKey+Schema.swift
AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/Models/PostWithCompositeKeyAndIndex+Schema.swift
AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/Models/PostWithCompositeKeyUnidirectional+Schema.swift
AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/Models/PostWithTagsCompositeKey+Schema.swift
AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/Models/TagWithCompositeKey+Schema.swift
AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/PrimaryKey/AWSDataStorePrimaryKeyBaseTest.swift
AmplifyPlugins/DataStore/Tests/DataStoreHostApp/DataStoreHostApp.xcodeproj/project.pbxproj

This updates the CPK models to the latest expected codegen process and runs CPK integration tests successfully.

chore(datastore): CPK integration tests

---

AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Subscribe/DataStoreObserveQueryOperation.swift

fix data race in DataStoreObserveQueryOperation

fix(datastore): fix data race in DataStoreObserveQueryOperation

---

Amplify/Core/Support/TaskQueue.swift
AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/RemoteSyncEngine+Retryable.swift
AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/RemoteSyncEngine.swift

fix(datastore): fix data race in RemoteSyncEngine

fix(datastore): fix data race in RemoteSyncEngine

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/ASF/CognitoUserPoolASF+KeyChain.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/CustomSignIn/InitiateCustomAuth.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/DeviceSRPAuth/InitiateAuthDeviceSRP.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/DeviceSRPAuth/VerifyDevicePasswordSRP+Calculations.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/DeviceSRPAuth/VerifyDevicePasswordSRP.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/MigrateAuth/InitiateMigrateAuth.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/SRPAuth/InitiateAuthSRP.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/SRPAuth/VerifyPasswordSRP+Calculations.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/SRPAuth/VerifyPasswordSRP.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/VerifySignInChallenge.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignUp/ConfirmSignUp.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignUp/InitiateSignUp.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/ClientBehavior/AWSCognitoAuthPlugin+ClientBehavior.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/UserOperations/AWSAuthConfirmResetPasswordOperation.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/UserOperations/AWSAuthResendSignUpCodeOperation.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/UserOperations/AWSAuthResetPasswordOperation.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/StateMachineSupport/Environment+Type.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Utils/ConfirmSignUpInput+Amplify.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Utils/Date+UTC.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Utils/InitiateAuthInput+Amplify.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Utils/RespondToAuthChallengeInput+Amplify.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Utils/SignUpInput+Amplify.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ResolverTests/SignUpState/SignUpInputTests.swift

feat(auth): ASF feature to rest of auth api

---

Package.swift

chore: exclude schema from AmplifyTestCommon

---

AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/DataStoreConfigurationTests.swift
AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/DataStoreEndToEndTests.swift

chore(datastore): Fix configuration and EndToEnd integ tests

---

AmplifyPlugins/API/Sources/AWSAPIPlugin/AWSAPIPlugin.swift

fix(api): set minimum and maximum supported TLS versions.

fix(api): set minimum and maximum supported TLS versions.

---

AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Storage/CascadeDeleteOperation.swift

fix race condition in CascadeDeleteOperation

fix(datastore): fix race condition in CascadeDeleteOperation

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/AWSCognitoAuthPlugin+Configure.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/Action+Logging.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/CredentialStore/LoadCredentialStore.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/CredentialStorage/CredentialStoreOperationClient.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Environment/AuthEnvironment.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Environment/CredentialStoreEnvironment.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ActionTests/CredentialStore/ClearCredentialsTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ActionTests/CredentialStore/LoadCredentialsTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ActionTests/CredentialStore/MigrateLegacyCredentialStoreTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/Support/DefaultConfig.swift

fix(auth): Credential store not waiting to move to idle before next operation

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/HostedUI/InitializeHostedUISignIn.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignUp/InitiateSignUp.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/HostedUI/HostedUIRequestHelper.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ResolverTests/SignUpState/SignUpStateTests.swift

fix(auth): Fix ASF for signUp and hostedUI

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/Authorization/AuthorizationState+Resolver.swift

fixI(auth): Fetching credentials for a signOut user

---

Amplify/Core/Support/DeviceInfo.swift

Adding a new `DeviceInfo` struct with relevant information.

feat(Core): Implementing DeviceInfo

---

Amplify/Categories/API/AuthProvider/APIAuthProviderFactory.swift
AmplifyPlugins/API/Sources/AWSAPIPlugin/Interceptor/RequestInterceptor/AuthTokenProviderWrapper.swift
AmplifyPlugins/API/Sources/AWSAPIPlugin/Interceptor/SubscriptionInterceptor/AuthenticationTokenAuthInterceptor.swift
AmplifyPlugins/API/Sources/AWSAPIPlugin/Interceptor/SubscriptionInterceptor/OIDCAuthProviderWrapper.swift
AmplifyPlugins/API/Tests/AWSAPIPluginTests/Interceptor/SubscriptionInterceptor/AuthenticationTokenAuthInterceptorTests.swift
AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/RemoteSyncEngine+AuthModeStrategyDelegate.swift
AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/SubscriptionSync/IncomingAsyncSubscriptionEventPublisher.swift
AmplifyTestCommon/Mocks/MockAPICategoryPlugin.swift

fix: rename to AuthProvider.getLatestAuthToken

---

AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/Connection/DataStoreConnectionScenario1Tests.swift
AmplifyPlugins/DataStore/Tests/DataStoreHostApp/DataStoreHostApp.xcodeproj/xcshareddata/xcschemes/AWSDataStorePluginIntegrationTests.xcscheme

chore(datastore): Fix ConnectionScenario1 integ tests

---

AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/Dependency/Pinpoint/Endpoint/EndpointInformation.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Service/ErrorMapping/ForgotPasswordOutputError+AuthError.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Service/ErrorMapping/VerifyUserAttributeOutputError+AuthError.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/OperationTests/ClientBehaviorTests/ClientBehaviorResetPasswordTests.swift
Package.resolved
Package.swift

fix(Auth): Fixing compilation errors because of swift-sdk 0.2.6 release

---

.github/workflows/unittest.yml

chore: update github actions unit test runners to macOS 12

---

Amplify/Categories/Auth/Models/AuthProvider.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/AWSCognitoAuthPlugin+EscapeHatch.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/AWSCognitoAuthPlugin.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/AWSCognitoAuthPluginBehavior.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/Federation/ClearFederationToIdentityPool.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/Persistence/ConfigureAuthentication.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/IntializeSignInFlow.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/CredentialStorage/AmplifyCredentials.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Models/FederateToIdentityPoolResult.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/AWSAuthClearFederationToIdentityPoolOperation.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/AWSAuthFederateToIdentityPoolOperation.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Request/AuthClearFederationToIdentityPoolRequest.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Request/AuthFederateToIdentityPoolRequest.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Data/FederatedToken.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Data/SignInMethod.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Events/AuthenticationEvent.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/States/AuthenticationState.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/States/AuthorizationState.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/States/DebugInfo/AuthenticationState+Debug.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/States/DebugInfo/AuthorizationState+Debug.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/Authentication/AuthenticationState+Resolver.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/Authorization/AuthorizationState+Resolver.swift

feat(Auth): Adding implementation for clearing federation

---

Amplify/Categories/API/Operation/GraphQLOperation.swift
Amplify/Core/Support/AmplifySequence.swift
Amplify/Core/Support/AmplifyTask+OperationTaskAdapters.swift
Amplify/Core/Support/AmplifyTask.swift
Amplify/Core/Support/ChildTask.swift
AmplifyTests/CoreTests/AmplifySequenceTests.swift

renames AsyncChannel to AmplifySequence

---

Amplify/Core/Support/AmplifyAsyncThrowingSequence.swift
AmplifyTests/CoreTests/AmplifyAsyncSequenceTests.swift

Revises async throwing sequence to match AmplifyAsyncSequence behavior

---

Amplify/Core/Support/Amplify+Publisher.swift
AmplifyTests/CoreTests/AmplifyPublisherTests.swift

add support for AsyncSequence Amplify.Publisher

feat: add support for AsyncSequence Amplify.Publisher

---

AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Support/Internal/StorageTransferDatabaseTests.swift

Fixes flaky unit test in Storage

---

AmplifyTestCommon/AsyncExpectation.swift
AmplifyTestCommon/AsyncTesting.swift
AmplifyTestCommon/XCTestCase+AsyncTesting.swift
AmplifyTests/CoreTests/AmplifyAsyncSequenceTests.swift
AmplifyTests/CoreTests/AmplifyPublisherTests.swift
AmplifyTests/CoreTests/AsyncExpectationTests.swift

revises implementation of AsyncExpectation and adds extension to XCTestCase

---

AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Support/Internal/StorageTransferDatabaseTests.swift

fixes tests after 2 PRs were merged with incompatible changes

---

AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Subscribe/DataStoreObserveQueryOperationTests.swift
AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Sync/SubscriptionSync/ModelReconciliationQueueBehaviorTests.swift
AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Sync/SubscriptionSync/ReconcileAndSaveQueueTests.swift

fix: sink never used warnings

---

Amplify/Categories/DataStore/Model/Internal/Schema/ModelSchema.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ResolverTests/AuthorizationState/FetchAuthSessionStateResolverTests.swift
AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/AWSDataStorePlugin+DataStoreBaseBehavior.swift
AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Core/AWSDataStorePluginTests.swift
AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Core/SQLiteStorageEngineAdapterTests.swift
AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Storage/StorageEngineTestsHasOne.swift
AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Sync/InitialSync/InitialSyncOperationSyncExpressionTests.swift
AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Sync/InitialSync/SyncEventEmitterTests.swift
AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Sync/SubscriptionSync/ReconcileAndLocalSaveOperationTests.swift

fix: value unused warnings

---

AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ConfigurationTests/EscapeHatchTests.swift
AmplifyPlugins/Core/AWSPluginsCoreTests/Model/Support/AuthRuleExtensionTests.swift
AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Sync/SubscriptionSync/ReconcileAndLocalSaveOperationTests.swift

fix code after throws warnings

fix: code after throws warnings

---

Amplify/DevMenu/Data/PluginInfoHelper.swift
AmplifyTests/CategoryTests/API/APICategoryConfigurationTests.swift

fix api category casting warning

fix(api): fix api category casting warnings

---

AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginV2Tests/TransformerV2/DataStoreConnectionScenario2V2Tests.swift
AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginV2Tests/TransformerV2/DataStoreConnectionScenario3V2Tests.swift
AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginV2Tests/TransformerV2/DataStoreConnectionScenario3aV2Tests.swift
AmplifyPlugins/DataStore/Tests/DataStoreHostApp/DataStoreHostApp.xcodeproj/project.pbxproj
AmplifyPlugins/DataStore/Tests/DataStoreHostApp/DataStoreHostApp.xcodeproj/xcshareddata/xcschemes/AWSDataStorePluginV2Tests.xcscheme

*Description of changes:* Fix DataStoreConnectionScenario2V2Tests, DataStoreConnectionScenario3V2Tests, DataStoreConnectionScenario3aV2Tests and update them with `async` APIs

chore(datastore): Fix DataStoreConnectionScenario2,Scenario3,Scenario3a V2 Tests

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Data/HostedUIProviderInfo.swift
AmplifyPlugins/Auth/Sources/libtommath/amplify_bn_mp_set_double.c
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ResolverTests/SignUpState/SignUpInputTests.swift

fix(auth): fix auth warnings

---

AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginV2Tests/TransformerV2/DataStoreConnectionScenario4V2Tests.swift
AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginV2Tests/TransformerV2/DataStoreConnectionScenario5V2Tests.swift
AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginV2Tests/TransformerV2/DataStoreConnectionScenario6V2Tests.swift
AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginV2Tests/TransformerV2/DataStoreConnectionScenario7V2Tests.swift
AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginV2Tests/TransformerV2/DataStoreConnectionScenario8V2Tests.swift
AmplifyPlugins/DataStore/Tests/DataStoreHostApp/DataStoreHostApp.xcodeproj/project.pbxproj
AmplifyPlugins/DataStore/Tests/DataStoreHostApp/DataStoreHostApp.xcodeproj/xcshareddata/xcschemes/AWSDataStorePluginV2Tests.xcscheme

*Description of changes:* Fix and update DataStoreConnectionScenario4-DataStoreConnectionScenario8 V2Tests with `async` APIs.

chore(datastore): Fix DataStoreConnectionScenario4-DataStoreConnectionScenario8 V2 Tests

---

Amplify/Core/Support/AmplifyTask+OperationTaskAdapters.swift
Amplify/Core/Support/AmplifyTask.swift

minor adjustment to revise AmplifyTask the Task Adapters

---

AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/SubscriptionSync/ReconcileAndLocalSave/AWSModelReconciliationQueue.swift
AmplifyTests/CategoryTests/Hub/DefaultPluginTests/DefaultHubPluginTests.swift

fix: fix hub test sleep bug and checkedContinuation issue

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/IntializeSignInFlow.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Models/AuthFlowType.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Utils/InitiateAuthInput+Amplify.swift

feat(Auth): Add explicit cases in AuthFlowType for customWithSRP and customWithoutSRP

---

Amplify/Categories/Storage/StorageCategory+ClientBehavior.swift
Amplify/Categories/Storage/StorageCategoryBehavior.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/AWSS3StoragePlugin+AsyncClientBehavior.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Operation/AWSS3StorageGetURLOperation.swift
AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/AWSS3StoragePluginAsyncBehaviorTests.swift
AmplifyTestCommon/Mocks/MockStorageCategoryPlugin.swift
AmplifyTests/CategoryTests/Hub/AmplifyOperationHubTests.swift

adds async function for getURL in Storage Plugin

---

Amplify/Core/Support/AmplifyAsyncSequence.swift
Amplify/Core/Support/AmplifyAsyncThrowingSequence.swift
Amplify/Core/Support/AmplifyTask+OperationTaskAdapters.swift
Amplify/Core/Support/AmplifyTask.swift
Amplify/Core/Support/AmplifyTaskGateway.swift
Amplify/Core/Support/Cancellable.swift
Amplify/Core/Support/Internal/InternalTask+AsyncSequence.swift
Amplify/Core/Support/Internal/InternalTask+Hub.swift
Amplify/Core/Support/Internal/InternalTask+Result.swift
Amplify/Core/Support/Internal/InternalTask.swift
Amplify/Core/Support/WeakRef.swift
AmplifyTests/CoreTests/InternalTaskTests.swift
AmplifyTests/CoreTests/Operations/FastOperation.swift
AmplifyTests/CoreTests/Operations/LongOperation.swift
AmplifyTests/CoreTests/Tasks/InternalTasks.swift

creates Task Runner with Task Internal support with protocols and extensions

---

Amplify/Categories/Storage/StorageCategory+ClientBehavior.swift
Amplify/Categories/Storage/StorageCategoryBehavior.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/AWSS3StoragePlugin+AsyncClientBehavior.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Operation/AWSS3StorageRemoveOperation.swift
AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/AWSS3StoragePluginAsyncBehaviorTests.swift
AmplifyTestCommon/Mocks/MockStorageCategoryPlugin.swift
AmplifyTests/CategoryTests/Hub/AmplifyOperationHubTests.swift

adds async function for remove in Storage Plugin

---

Amplify/Categories/Storage/StorageCategory+ClientBehavior.swift
Amplify/Categories/Storage/StorageCategoryBehavior.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/AWSS3StoragePlugin+AsyncClientBehavior.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Operation/AWSS3StorageListOperation.swift
AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/AWSS3StoragePluginAsyncBehaviorTests.swift
AmplifyTestCommon/Mocks/MockStorageCategoryPlugin.swift
AmplifyTests/CategoryTests/Hub/AmplifyOperationHubTests.swift

adds async function for list in Storage Plugin

---

Amplify/Categories/Storage/Operation/StorageDownloadDataOperation.swift
Amplify/Categories/Storage/StorageCategory+ClientBehavior.swift
Amplify/Categories/Storage/StorageCategoryBehavior.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/AWSS3StoragePlugin+AsyncClientBehavior.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/AWSS3StoragePlugin+ClientBehavior.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Operation/AWSS3StorageDownloadDataOperation.swift
AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/AWSS3StoragePluginAsyncBehaviorTests.swift
AmplifyTestCommon/Mocks/MockStorageCategoryPlugin.swift
AmplifyTests/CategoryTests/Hub/AmplifyOperationHubTests.swift

adds async function for downloadData in Storage Plugin

---

.swiftpm/xcode/xcshareddata/xcschemes/Amplify-Package.xcscheme
.swiftpm/xcode/xcshareddata/xcschemes/HSM.xcscheme
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/hierarchical-state-machine-swift/Action.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/hierarchical-state-machine-swift/ConcurrentEffectExecutor.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/hierarchical-state-machine-swift/EffectExecutor.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/hierarchical-state-machine-swift/EventDispatcher.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/hierarchical-state-machine-swift/StateAsyncSequence.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/hierarchical-state-machine-swift/StateMachine.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/hierarchical-state-machine-swiftTests/CombinedStateTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/hierarchical-state-machine-swiftTests/StateMachineListenerTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/hierarchical-state-machine-swiftTests/StateMachineTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/hierarchical-state-machine-swiftTests/Support/Color.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/hierarchical-state-machine-swiftTests/Support/ColorCounter.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/hierarchical-state-machine-swiftTests/Support/Counter+Event.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/hierarchical-state-machine-swiftTests/Support/Counter+Resolver.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/hierarchical-state-machine-swiftTests/Support/Counter.swift
Package.swift

chore(auth): Changes the internal statemachine to structure code

---

Amplify/Categories/Storage/Operation/StorageDownloadFileOperation.swift
Amplify/Categories/Storage/StorageCategory+ClientBehavior.swift
Amplify/Categories/Storage/StorageCategoryBehavior.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/AWSS3StoragePlugin+AsyncClientBehavior.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Operation/AWSS3StorageDownloadFileOperation.swift
AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/AWSS3StoragePluginAsyncBehaviorTests.swift
AmplifyTestCommon/Mocks/MockStorageCategoryPlugin.swift
AmplifyTests/CategoryTests/Hub/AmplifyOperationHubTests.swift

adds async function for downloadFile in Storage Plugin

---

AmplifyPlugins/Analytics/Sources/AWSPinpointAnalyticsPlugin/Dependency/Pinpoint/Analytics/AnalyticsClient.swift
AmplifyPlugins/Analytics/Sources/AWSPinpointAnalyticsPlugin/Dependency/Pinpoint/Endpoint/EndpointClient.swift

update AnalyticsClient actor to build cleanly with swift 5.6+

fix(analytics): update AnalyticsClient actor to build cleanly with swift 5.6+

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/RefreshAuthorizationSession/UserPool/RefreshHostedUITokens.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Models/AWSAuthCognitoSession.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Models/AuthAWSCognitoCredentials.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/Helpers/HostedUISignInHelper.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Errors/HostedUIError.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/ErrorMapping/SignInError+Helper.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/RefreshSession/RefreshSessionState+Resolver.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Constants/AuthPluginErrorConstants.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/HostedUI/HostedUIRequestHelper.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthWebUISignInTask.swift

chore(auth): Fix hostedUI to throw the right errors

---

Amplify/Categories/Storage/Operation/StorageUploadFileOperation.swift
Amplify/Categories/Storage/StorageCategory+ClientBehavior.swift
Amplify/Categories/Storage/StorageCategoryBehavior.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/AWSS3StoragePlugin+AsyncClientBehavior.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Operation/AWSS3StorageUploadFileOperation.swift
AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/AWSS3StoragePluginAsyncBehaviorTests.swift
AmplifyTestCommon/Mocks/MockStorageCategoryPlugin.swift
AmplifyTests/CategoryTests/Hub/AmplifyOperationHubTests.swift

adds async function for uploadFile in Storage Plugin

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthConfirmSignUpTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthSignUpTask.swift

fix(auth): Await signup task for configuration

---

Amplify/Categories/Storage/Operation/StorageDownloadDataOperation.swift
Amplify/Categories/Storage/Operation/StorageUploadFileOperation.swift
Amplify/Categories/Storage/StorageCategory+ClientBehavior+Combine.swift
Amplify/Categories/Storage/StorageCategory+ClientBehavior.swift
Amplify/Categories/Storage/StorageCategoryBehavior.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/AWSS3StoragePlugin+AsyncClientBehavior.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Operation/AWSS3StorageGetURLOperation.swift
AmplifyTestCommon/Mocks/MockStorageCategoryPlugin.swift
AmplifyTests/CategoryTests/Hub/AmplifyOperationHubTests.swift

refines Storage plugin for new async support code

---

Amplify/Categories/Storage/StorageCategoryBehavior.swift

deprecates listener API in storage

---

AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/AWSS3StoragePlugin+AsyncClientBehavior.swift

whitespace formatting for Storage

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/AWSCognitoAuthPlugin.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/ClientBehavior/AWSCognitoAuthPlugin+UserBehavior.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/CredentialStorage/CredentialStoreOperationClient.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/AuthConfigureOperation.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/Helpers/AmplifyOperationHelper.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/Helpers/FetchAuthSessionOperationHelper.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/Helpers/HostedUISignInHelper.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/StateMachineSupport/AWSCognitoAuthPlugin+StateMachine.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthChangePasswordTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthClearFederationToIdentityPoolTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthConfirmSignInTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthDeleteUserTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthFederateToIdentityPoolTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthFetchSessionTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthSignInTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthSignOutTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthWebUISignInTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/DeviceTasks/AWSAuthFetchDevicesTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/DeviceTasks/AWSAuthForgetDeviceTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/DeviceTasks/AWSAuthRememberDeviceTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/Helpers/AWSAuthTaskHelper.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/UserTasks/AWSAuthAttributeResendConfirmationCodeTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/UserTasks/AWSAuthConfirmUserAttributeTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/UserTasks/AWSAuthFetchUserAttributeTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/UserTasks/AWSAuthUpdateUserAttributeTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/UserTasks/AWSAuthUpdateUserAttributesTask.swift

Royjit.amplifytaskasync

---

Amplify/Core/Support/AsyncSequence+forEach.swift
Amplify/Core/Support/Internal/InternalTask+AsyncSequence.swift
Amplify/Core/Support/Internal/InternalTask+Hub.swift
Amplify/Core/Support/Internal/InternalTask+Result.swift
Amplify/Core/Support/Internal/InternalTask.swift

adds doc comments

---

AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Configuration/AWSS3PluginPrefixResolver.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Operation/AWSS3StorageDownloadDataOperation.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Operation/AWSS3StorageDownloadFileOperation.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Operation/AWSS3StorageGetURLOperation.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Operation/AWSS3StorageListOperation.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Operation/AWSS3StorageRemoveOperation.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Operation/AWSS3StorageUploadDataOperation.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Operation/AWSS3StorageUploadFileOperation.swift
AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Configuration/AWSS3PluginPrefixResolverTests.swift
AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Configuration/AWSS3StoragePluginConfigurationTests.swift

revises PrefixResolver with single async function

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/DeviceSRPAuth/VerifyDevicePasswordSRP.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/HostedUI/ShowHostedUISignIn.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignOut/ShowHostedUISignOut.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/Helpers/ClearFederationOperationHelper.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/Helpers/FetchAuthSessionOperationHelper.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/Helpers/HostedUISignInHelper.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/hierarchical-state-machine-swift/StateAsyncSequence.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Helpers/UserPoolSignInHelper.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthClearFederationToIdentityPoolTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthConfirmSignInTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthFederateToIdentityPoolTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthSignInTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthSignOutTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/DeviceTasks/AWSAuthForgetDeviceTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/DeviceTasks/AWSAuthRememberDeviceTask.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/hierarchical-state-machine-swiftTests/CombinedStateTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/hierarchical-state-machine-swiftTests/StateMachineListenerTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/hierarchical-state-machine-swiftTests/StateMachineTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/hierarchical-state-machine-swiftTests/Support/Color.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/hierarchical-state-machine-swiftTests/Support/ColorCounter.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/hierarchical-state-machine-swiftTests/Support/Counter+Event.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/hierarchical-state-machine-swiftTests/Support/Counter+Resolver.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/hierarchical-state-machine-swiftTests/Support/Counter.swift

chore(auth): Adds structured code to rest of AmplifyTask

---

Package.swift

*Related:*
https://github.com/aws-amplify/amplify-ios/issues/1124
https://github.com/aws-amplify/amplify-ios/pull/1810
* Adds macOS 10.15 to supported platforms.

adds macOS to supported platforms

---

Amplify/Core/Support/AmplifyTask+OperationTaskAdapters.swift
AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Operation/AWSS3StorageListOperationTests.swift
AmplifyTestCommon/Mocks/MockStorageCategoryPlugin.swift

* adds bool parameter to use just during unit tests
* reformats code so that Xcode can parse it to work with the jump bar
* removes listener functions which were deprecated and removed

implements workaround to prevent deadlock with plugin tests

---

Amplify/Categories/Storage/StorageCategory+ClientBehavior.swift
Amplify/Categories/Storage/StorageCategoryBehavior.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/AWSS3StoragePlugin+AsyncClientBehavior.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/StorageBackgroundEventsRegistry.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/StorageServiceSessionDelegate.swift
AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Support/Internal/StorageBackgroundEventsRegistryTests.swift
AmplifyTestCommon/Mocks/MockStorageCategoryPlugin.swift
AmplifyTests/CategoryTests/Hub/AmplifyOperationHubTests.swift

implements background events handling for Storage

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignOut/InitiateGuestSignOut.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/Helpers/FetchAuthSessionOperationHelper.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Events/SignOutEvent.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/States/SignOutState.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/Authentication/AuthenticationState+Resolver.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/SignOut/SignOutState+Resolver.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Helpers/AuthCognitoSignedOutSessionHelper.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthSignOutTask.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/HubEventTests/AuthHubEventHandlerTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/OperationTests/HostedUITests/AWSAuthHostedUISignInTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ResolverTests/SignOutState/SignOutStateNotStartedTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ResolverTests/SignOutState/SignOutStateRevokingTokenTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ResolverTests/SignOutState/SignOutStateSigningOutGloballyTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ResolverTests/SignOutState/SignOutStateSigningOutLocallyTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/AWSAuthSignUpTaskTests.swift
Package.resolved

- Adds signOut flow for unAuth user
- Fix issue for unAuth fetchsession

fix(auth): FetchAuthsession get stuck on guest user

---

AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginAuthCognitoTests/AWSDataStoreAuthBaseTest.swift
AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginAuthCognitoTests/AWSDataStoreCategoryPluginAuthIntegrationTests+Support.swift
AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginAuthCognitoTests/AWSDataStoreCategoryPluginAuthIntegrationTests.swift
AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginAuthCognitoTests/AWSDataStoreCategoryPluginAuthOwnerIntegrationTests.swift

chore(auth): fix AWSDataStorePluginAuthCognitoTests to build 

---

Amplify/Core/Support/AmplifyTask+OperationTaskAdapters.swift
AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Operation/AWSS3StorageListOperationTests.swift
AmplifyTestCommon/Mocks/MockStorageCategoryPlugin.swift

fix(storage): revert workaround for deadlock (#2260) in favor of improved solution

fix(storage): revert workaround for deadlock (#2260) in favor of improved solution

---

AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/Mocks/MockData/GlobalSignOutOutputResponse+Mock.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/Mocks/MockData/RevokeTokenOutputResponse+Mock.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/AWSAuthSignOutTaskTests.swift

test(auth): Added test for the signout task

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Environment/SRPAuthEnvironment.swift

chore(auth): Remove TODO around SRP configuration

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/Helpers/FetchAuthSessionOperationHelper.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/States/RefreshSessionState.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/Authorization/AuthorizationState+Resolver.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/FetchAuthSession/FetchAuthSessionState+Resolver.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/hierarchical-state-machine-swift/StateMachine.swift

fix(auth): Handle fetch session errors

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/ClientBehavior/AWSCognitoAuthPlugin+DeviceBehavior.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/DeviceTasks/AWSAuthForgetDeviceTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/DeviceTasks/AWSAuthRememberDeviceTask.swift
AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/DeviceTests/AuthForgetDeviceTests.swift
AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/DeviceTests/AuthRememberDeviceTests.swift

chore(auth): Enable device features with device key

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/CredentialStorage/AWSCognitoAuthCredentialStore.swift

feat(Auth): Modify the service and default keys Auth

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/ErrorMapping/SignInError+Helper.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/AWSAuthSignInPluginTests.swift

fix(auth): Parse auth error correctly

---

Amplify/Core/Configuration/AmplifyConfiguration.swift

*Issue #, if available:* #2308 #1874
fix issue that causes SwiftUI previews to crash in certain scenarios

fix: fix issue that causes SwiftUI previews to crash in certain scenarios

---

Amplify/Core/Support/TimeInterval+Helper.swift
AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/InitialSync/InitialSyncOperation.swift

closes #398
Refactor to use TimeInterval extension method.

fix(datastore): refactor to use TimeInterval.milliseconds

---

AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Service/Storage/AWSS3StorageService.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/StorageMultipartUpload.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/StorageMultipartUploadClient.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/StorageMultipartUploadEvent.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/StorageMultipartUploadSession.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/StorageServiceSessionDelegate.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/StorageTransferTask.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/StorageUploadPart.swift
AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Support/Internal/MockMultipartUploadClient.swift
AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Support/Internal/StorageMultipartUploadSessionTests.swift

Storage: implements pausing and resuming with multipart upload

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/Configuration/InitializeAuthConfiguration.swift

fix(Auth): Catch expected KeychainStoreError.itemNotFound during Auth initialization

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/CredentialStore/MigrateLegacyCredentialStore.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Helpers/AuthProvider+Cognito.swift

fix(auth): Migrate federated signIn user

---

AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TestHarness/Mocks/MockedAuthCognitoPlugin.swift

fix(Auth): fixing macOS target for unit tests

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/CustomSignIn/InitiateCustomAuth.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/DeviceSRPAuth/VerifyDevicePasswordSRP.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/InitializeResolveChallenge.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/MigrateAuth/InitiateMigrateAuth.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/SRPAuth/VerifyPasswordSRP.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/VerifySignInChallenge.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Events/SignInChallengeEvent.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/States/DebugInfo/SignInChallengeState+Debug.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/States/DebugInfo/SignInState+Debug.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/States/SignInChallengeState.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/States/SignInState.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/SignIn/SignInChallengeState+Resolver.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/SignIn/SignInState+Resolver.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Helpers/UserPoolSignInHelper.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthConfirmSignInTask.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/HubEventTests/AuthHubEventHandlerTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/ClientBehaviorTests/AWSAuthConfirmSignInTaskTests.swift

chore(auth): Pass signInMethod to the right actions

---

AmplifyTests/CoreTests/AmplifyPublisherTests.swift

add test for Amplify.publisher.create with an AmplifyAsyncThrowingSequence

chore: add test for Amplify.publisher.create with an AmplifyAsyncThrowingSequence

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/CredentialStore/MigrateLegacyCredentialStore.swift

fix(auth): Add device details to migration logic

---

AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/Connection/DataStoreConnectionScenario4Tests.swift
AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/Connection/DataStoreConnectionScenario6Tests.swift
AmplifyPlugins/DataStore/Tests/DataStoreHostApp/DataStoreHostApp.xcodeproj/xcshareddata/xcschemes/AWSDataStorePluginIntegrationTests.xcscheme

chore(datstore-v2): fix integ test Scenario 4 and 6

---

AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/hierarchical-state-machine-swiftTests/StateMachineListenerTests.swift

test(auth): Fix the test that send out of order events

---

AmplifyPlugins/Auth/AWSCognitoAuthPlugin.xcodeproj/project.pbxproj
AmplifyPlugins/Auth/AWSCognitoAuthPlugin/AWSCognitoAuthPlugin+Configure.swift
AmplifyPlugins/Auth/AWSCognitoAuthPlugin/AWSCognitoAuthPlugin.swift
AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Models/AWSCognitoNetworkPreferences.swift
AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/ConfigurationTests/AWSCognitoAuthPluginConfigTests.swift

chore(auth): Fix the build failure in auth cocoapod

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/Helpers/ClearFederationOperationHelper.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthFederateToIdentityPoolTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthSignOutTask.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/AWSAuthSignOutTaskTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/UserBehaviourTests/BasePluginTest.swift

fix(Auth): removing clear credentials during federation and proper handling of sign out task

---

AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginIntegrationTests/Connection/DataStoreConnectionScenario6Tests.swift

https://github.com/aws-amplify/amplify-ios/issues/2336
Performing and testing Delete API with `.all` predicate performs a cascade delete on all the queried associated models. When deleting a Blog, it will query for all the blogs, then posts, and comments. Then delete the blogs with "cascade" enabled from the local SQLite DB. Then queue up the comment, post, then blog mutation events (in that order) for deletion from the local store. 
The test issue that I experienced running locally against my backend was that there was an orphaned comment. I can only guess why this happened, probably before the fix for cascade delete was applied here: (https://github.com/aws-amplify/amplify-ios/pull/1736), the cascade delete behavior was queueing up blog …

test(datastore): Fix DeleteAll test stability

---

AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/Connection/DataStoreConnectionScenario6Tests.swift
AmplifyPlugins/DataStore/Tests/DataStoreHostApp/DataStoreHostApp.xcodeproj/xcshareddata/xcschemes/AWSDataStorePluginIntegrationTests.xcscheme

https://github.com/aws-amplify/amplify-ios/issues/2340
v2 version of https://github.com/aws-amplify/amplify-ios/pull/2356

test(datastore-v2): Fix DeleteAll test stability

---

Amplify/Categories/Auth/Request/AuthWebUISignInRequest.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/CredentialStore/MigrateLegacyCredentialStore.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Models/Options/AWSAuthWebUISignInOptions.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/Helpers/HostedUISignInHelper.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Data/HostedUIProviderInfo.swift

chore(auth): Remove unused properties

---

AmplifyTests/CoreTests/AmplifyPublisherTests.swift

On iOS the behavior while running tests appears to operate with more limitations on concurrency, possibly a single thread while macOS is not restricted. It was causing the AsyncSequence to get no values after `finish()` was called on the Publisher side. The fix was to send values after the Publisher was created so they can be received before the sequence finishes.
I've confirmed that a single thread is used to run tests with the iOS Simulator. I printed out the current thread at multiple points and it showed thread 2 was used each time. With macOS it used threads numbers 2, 3 and 4 so it is able to run the tasks in the tests out of order. It effectively imposes serial behavior for iOS Simulator testing. The updated tests ensure the order is what the tests need. …

fix(Combine): fixes Publisher tests for macOS

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Models/AWSCognitoSignOutResult.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/AWSAuthSignOutTaskTests.swift

fix(auth): Add missing property in signout

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/AWSCognitoAuthPlugin+Configure.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/AWSCognitoAuthPlugin.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Environment/UserPoolEnvironment.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Service/UserPoolAnalytics/UserPoolAnalytics.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Service/UserPoolAnalytics/UserPoolAnalyticsBehavior.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Helpers/ConfigurationHelper.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Utils/ConfirmSignUpInput+Amplify.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Utils/InitiateAuthInput+Amplify.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Utils/RespondToAuthChallengeInput+Amplify.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Utils/SignUpInput+Amplify.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthConfirmResetPasswordTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthResendSignUpCodeTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthResetPasswordTask.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ActionTests/FetchAuthSession/FetchUserPoolTokens/RefreshUserPoolTokensTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ActionTests/SignOut/RevokeTokenTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ActionTests/SignOut/SignOutGloballyTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/HubEventTests/AuthHubEventHandlerTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/Mocks/MockAnalyticsHandler.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ResolverTests/SignUpState/SignUpInputTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/Support/DefaultConfig.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/AWSAuthMigrationSignInTaskTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/AuthorizationTests/BaseAuthorizationTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/ClientBehaviorTests/AWSAuthConfirmSignInTaskTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/ClientBehaviorTests/AWSCognitoAuthClientBehaviorTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/HostedUITests/AWSAuthHostedUISignInTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/UserBehaviourTests/BasePluginTest.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TestHarness/Mocks/MockedAuthCognitoPlugin.swift
AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/AuthUserAttributesTests/AuthUserAttributesTests.swift

feat(auth): Add pinpoint analytics to auth plugin

---

AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginAuthCognitoTests/AWSDataStoreAuthBaseTest.swift
AmplifyPlugins/DataStore/Tests/DataStoreHostApp/DataStoreHostApp/HubListenerTestUtilities.swift

final fix for the AWSDatastorePluginAuthCognitoTests to run succesfully:

test(datastore-v2): AWSDatastorePluginAuthCognitoTests 

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/Action+Logging.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/Configuration/InitializeAuthConfiguration.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Helpers/DeviceMetadataHelper.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TestHarness/CodableStates/CodableStates.swift
AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/AWSAuthBaseTest.swift
AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/CredentialStore/CredentialStoreConfigurationTests.swift
AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/SessionTests/GetCurrentUserTests.swift
AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/SignInTests/AuthCustomSignInTests.swift

fix(Auth): Minor fixes to fetching device metadata from keychain and fix integration tests

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/CredentialStore/MigrateLegacyCredentialStore.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/IntializeSignInFlow.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/SRPAuth/InitiateAuthSRP.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/SRPAuth/VerifyPasswordSRP.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/ClientBehavior/AWSCognitoAuthPlugin+ClientBehavior.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Models/AuthFlowType.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Models/Options/AWSAuthSignInOptions.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Data/SignInEventData.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Data/SignInMethod.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Data/UserPoolConfigurationData.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/States/DebugInfo/MigrateSignInState+Debug.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/States/DebugInfo/SignInState+Debug.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/SRP/SRPSignInState+Resolver.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Helpers/ConfigurationHelper.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthSignInTask.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/CredentialStore/CredentialStoreOperationClientTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ResolverTests/AuthTestData.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/Support/DefaultConfig.swift
AmplifyPlugins/Auth/Tests/AuthHostApp/AuthHostApp.xcodeproj/xcshareddata/xcschemes/AuthIntegrationTests.xcscheme

fix(auth): Custom auth to follow legacy v1 flow from configuration

---

README-combine-support.md
README.md

chore: update readmes

---

Amplify/Core/Support/TaskQueue.swift

make TaskQueue build with Xcode 13

fix: make TaskQueue build with Xcode 13

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/CredentialStorage/CredentialStoreOperationClient.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/CredentialStore/CredentialStoreOperationClientTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/Support/DefaultConfig.swift

fix(Auth): fixing race conditions in credential store client

---

AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/StorageServiceSessionDelegate.swift

adds task cancellation reason logging for URLSessionTaskDelegate

---

AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/StorageMultipartUpload.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/StorageMultipartUploadSession.swift

fixes for multipart upload computed properties with new paused state

---

Amplify/Categories/Geo/DeviceTracking/Geo+DeleteLocationOptions.swift
Amplify/Categories/Geo/DeviceTracking/Geo+Device.swift
Amplify/Categories/Geo/DeviceTracking/Geo+Location.swift
Amplify/Categories/Geo/DeviceTracking/Geo+UpdateLocationOptions.swift
Amplify/Categories/Geo/GeoCategory+ClientBehavior.swift
Amplify/Categories/Geo/GeoCategoryBehavior.swift
AmplifyPlugins/Geo/AWSLocationGeoPlugin/AWSLocationGeoPlugin+ClientBehavior.swift
AmplifyPlugins/Geo/AWSLocationGeoPlugin/Configuration/AWSLocationGeoPluginConfiguration+Keys.swift
AmplifyPlugins/Geo/AWSLocationGeoPlugin/Configuration/AWSLocationGeoPluginConfiguration.swift
AmplifyPlugins/Geo/AWSLocationGeoPlugin/Configuration/GeoPluginConfigError.swift
AmplifyPlugins/Geo/AWSLocationGeoPlugin/Dependency/AWSLocationAdapter.swift
AmplifyPlugins/Geo/AWSLocationGeoPlugin/Dependency/AWSLocationBehavior.swift
AmplifyPlugins/Geo/AWSLocationGeoPlugin/Support/Constants/GeoPluginErrorConstants.swift
AmplifyPlugins/Geo/AWSLocationGeoPlugin/Support/Utils/GeoErrorHelper.swift
AmplifyPlugins/Geo/AWSLocationGeoPluginTests/AWSLocationGeoPluginClientBehaviorTests.swift
AmplifyPlugins/Geo/AWSLocationGeoPluginTests/AWSLocationGeoPluginTestBase.swift
AmplifyPlugins/Geo/AWSLocationGeoPluginTests/Mocks/MockAWSLocation.swift
AmplifyPlugins/Geo/AWSLocationGeoPluginTests/Support/Constants/GeoPluginTestConfig.swift
AmplifyTestCommon/Mocks/MockGeoCategoryPlugin.swift

* add updateLocation and updateLocationHistory api to Geo category

feat(Geo): add updateLocation and deleteLocationHistory api

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/ASF/CognitoUserPoolASF+KeyChain.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/AWSCognitoAuthPlugin+Configure.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/Configuration/InitializeAuthConfiguration.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/Federation/ClearFederationToIdentityPool.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/FetchAuthorizationSession/PersistCredentials.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/RefreshAuthorizationSession/UserPool/RefreshUserPoolTokens.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/ConfirmDevice.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/CustomSignIn/InitiateCustomAuth.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/HostedUI/InitializeHostedUISignIn.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/MigrateAuth/InitiateMigrateAuth.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/SRPAuth/InitiateAuthSRP.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignOut/SignOutLocally.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/CredentialStorage/CredentialStoreOperationClient.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Environment/AuthEnvironment.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Helpers/DeviceMetadataHelper.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthConfirmResetPasswordTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthResendSignUpCodeTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthResetPasswordTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthSignUpTask.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/CredentialStore/CredentialStoreOperationClientTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/Support/DefaultConfig.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/ClientBehaviorTests/AWSAuthConfirmSignInTaskTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TestHarness/Mocks/MockedAuthCognitoPlugin.swift
AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/SignUpTests/AuthSignUpTests.swift

fix(auth): Use single client of CredentialsStore

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthSignOutTask.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ResolverTests/AuthorizationState/AuthorizationTestData.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/AWSAuthSignOutTaskTests.swift
AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/Helpers/AuthSessionHelper.swift
AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/SessionTests/SignedOutAuthSessionTests.swift

fix(auth): Add signOut during guest access

---

AmplifyPlugins/Analytics/Tests/AWSPinpointAnalyticsPluginUnitTests/Pinpoint/ActivityTrackerTests.swift

Since the `ActivityTracker` is observing `NotificationCenter` notifications and we are posting them in the tests, it's not safe to make the asserts in a synchronous way.
So I've refactored the `MockStateMachine` to store an array of processed events instead of the last one, and then validated that the expected value is included in there.
I've also increased the `timeout` for `testBackgroundTracking_afterTimeout_shouldReportBackgroundTimeout`, as it was exactly matching the amount of time the tracker waits to notify it, increasing the changes of failures.

chore(Analytics): Fixing flaky ActivityTracker unit tests.

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/AWSCognitoAuthPlugin+Configure.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/AWSCognitoAuthPlugin.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/ClientBehavior/AWSCognitoAuthPlugin+ClientBehavior.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/ClientBehavior/AWSCognitoAuthPlugin+DeviceBehavior.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/ClientBehavior/AWSCognitoAuthPlugin+UserBehavior.swift
AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/SignInTests/AuthSRPSignInTests.swift

fix(Auth): Making Auth API's sync

---

.github/workflows/integ_test.yml

test: Enable geo category integ test

---

AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Service/Storage/AWSS3StorageService.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/StorageMultipartUpload.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/StorageMultipartUploadClient.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/StorageMultipartUploadSession.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/StorageServiceProxy.swift
AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Support/Internal/MockMultipartUploadClient.swift

fixes pausing multipart uploads due to concurrency issues

---

AmplifyPlugins/DataStore/Tests/DataStoreHostApp/DataStoreHostApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Package.resolved
Package.swift

*Description of changes:* update SQLite dependency to 0.13.2

chore: update SQLite dependency to 0.13.2

---

AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Service/Storage/AWSS3StorageService.swift

usess default URLSessionConfiguration for macOS

---

AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/AWSDataStoreLocalStoreTests.swift

N/A
Moves initial saves to after initial query for `testObserveQuery`.

fix(datastore): fix observe query unit test

---

.github/workflows/integ_test.yml

N/A
Updates project path in `integ_test.yml` for Geo integration tests.

chore(geo): update working dir for geo integration tests

---

AmplifyPlugins/Auth/Tests/AuthHostApp/AuthHostApp.xcodeproj/project.pbxproj
AmplifyPlugins/Auth/Tests/AuthHostApp/AuthHostApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/SessionTests/SignedInAuthSessionTests.swift

test(auth): Random fetch auth session test

---

AmplifyPlugins/Storage/Tests/StorageHostApp/AWSS3StoragePluginIntegrationTests/AWSS3StoragePluginAccessLevelTests.swift
AmplifyPlugins/Storage/Tests/StorageHostApp/AWSS3StoragePluginIntegrationTests/AWSS3StoragePluginOptionsUsabilityTests.swift
AmplifyPlugins/Storage/Tests/StorageHostApp/AWSS3StoragePluginIntegrationTests/AWSS3StoragePluginPrefixKeyResolverTests.swift
AmplifyPlugins/Storage/Tests/StorageHostApp/AWSS3StoragePluginIntegrationTests/AWSS3StoragePluginTestBase.swift
AmplifyPlugins/Storage/Tests/StorageHostApp/AWSS3StoragePluginIntegrationTests/ResumabilityTests/AWSS3StoragePluginGetDataResumabilityTests.swift
AmplifyPlugins/Storage/Tests/StorageHostApp/AWSS3StoragePluginIntegrationTests/ResumabilityTests/AWSS3StoragePluginPutDataResumabilityTests.swift

fixes for Storage integration tests

---

AmplifyPlugins/Storage/Tests/StorageHostApp/AWSS3StoragePluginIntegrationTests/AWSS3StoragePluginAccessLevelTests.swift
AmplifyPlugins/Storage/Tests/StorageHostApp/StorageHostApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

fixes integration test for Storage access levels

---

Package.swift

chore: Remove unused flag from package.swift

---

AmplifyPlugins/Storage/Tests/StorageHostApp/StorageHostApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

updates Package.resolved for Storage Host App

---

.github/workflows/integ_test_datastore.yml

chore(datastore): set integration test timeout to 15 min

---

AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/StorageTransferTask.swift

makes StorageTransferTask thread-safe

---

AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/StorageMultipartUploadSession.swift
AmplifyPlugins/Storage/Tests/StorageHostApp/AWSS3StoragePluginIntegrationTests/AWSS3StoragePluginBasicIntegrationTests.swift

improves thread-safety for Storage

---

AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/StorageMultipartUploadSession.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/StorageTransferTask.swift
AmplifyPlugins/Storage/Tests/StorageHostApp/AWSS3StoragePluginIntegrationTests/ResumabilityTests/AWSS3StoragePluginPutDataResumabilityTests.swift

fixes integration tests for Storage

---

Amplify/Categories/Hub/HubCategory.swift
Amplify/Categories/Hub/Internal/HubCategory+CategoryConfigurable.swift
Amplify/Categories/Hub/Internal/HubCategory+Resettable.swift

fix: fix possible data race in hub

---

AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/DefaultStorageTransferDatabase.swift

fix data race in DefaultStorageTransferDatabase

fix(storage): fix data race in DefaultStorageTransferDatabase

---

AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Operation/AWSS3StorageDownloadFileOperationTests.swift
AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Operation/AWSS3StorageGetDataOperationTests.swift
AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Operation/AWSS3StorageGetURLOperationTests.swift
AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Operation/AWSS3StorageListOperationTests.swift
AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Operation/AWSS3StorageOperationTestBase.swift
AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Operation/AWSS3StoragePutDataOperationTests.swift
AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Operation/AWSS3StorageRemoveOperationTests.swift
AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Operation/AWSS3StorageUploadFileOperationTests.swift

fix bug in storage operation tests

fix(storage): fix bug in storage operation tests

---

AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Operation/AWSS3StorageDownloadDataOperation.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Operation/AWSS3StorageDownloadFileOperation.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Operation/AWSS3StorageGetURLOperation.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Operation/AWSS3StorageListOperation.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Operation/AWSS3StorageRemoveOperation.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Operation/AWSS3StorageUploadDataOperation.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Operation/AWSS3StorageUploadFileOperation.swift

fix data race in DefaultStorageTransferDatabase

fix(storage): make storage operations internal

---

AmplifyAsyncTesting/Sources/AsyncTesting/XCTestCase+AsyncTesting.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Service/Storage/AWSS3StorageService.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/StorageMultipartUpload.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/StorageMultipartUploadSession.swift
AmplifyPlugins/Storage/Tests/StorageHostApp/AWSS3StoragePluginIntegrationTests/AWSS3StoragePluginAccessLevelTests.swift
AmplifyPlugins/Storage/Tests/StorageHostApp/AWSS3StoragePluginIntegrationTests/AWSS3StoragePluginTestBase.swift
AmplifyPlugins/Storage/Tests/StorageHostApp/AWSS3StoragePluginIntegrationTests/Helpers/TestConfigHelper.swift
AmplifyPlugins/Storage/Tests/StorageHostApp/AWSS3StoragePluginIntegrationTests/ResumabilityTests/AWSS3StoragePluginGetDataResumabilityTests.swift
AmplifyPlugins/Storage/Tests/StorageHostApp/AWSS3StoragePluginIntegrationTests/ResumabilityTests/AWSS3StoragePluginPutDataResumabilityTests.swift

improvements for storage integration tests

---

AmplifyPlugins/Storage/Tests/StorageHostApp/AWSS3StoragePluginIntegrationTests/Helpers/TestConfigHelper.swift

increase integration test network timeout

fix(storage): increase integration test network timeout

---

AmplifyAsyncTesting/Sources/AsyncTesting/XCTestCase+AsyncTesting.swift
AmplifyPlugins/Storage/Tests/StorageHostApp/AWSS3StoragePluginIntegrationTests/Helpers/TestConfigHelper.swift
AmplifyPlugins/Storage/Tests/StorageHostApp/AWSS3StoragePluginIntegrationTests/ResumabilityTests/AWSS3StoragePluginGetDataResumabilityTests.swift
AmplifyPlugins/Storage/Tests/StorageHostApp/AWSS3StoragePluginIntegrationTests/ResumabilityTests/AWSS3StoragePluginPutDataResumabilityTests.swift

*Description of changes:* Increase `networkTimeout` for Storage Integration tests and `testTask` 

fix(Storage): increase testTask timeout and network timeout

---

AmplifyTests/CoreTests/AmplifyPublisherTests.swift

fix: amplify publisher tests

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/Helpers/HostedUISignInHelper.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/Support/DefaultConfig.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/HostedUITests/AWSAuthHostedUISignInTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/hierarchical-state-machine-swiftTests/StateMachineListenerTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/hierarchical-state-machine-swiftTests/StateMachineTests.swift

test(auth): Fixes HostedUI signIn flow and flaky test

---

AmplifyPlugins/Storage/Tests/StorageHostApp/AWSS3StoragePluginIntegrationTests/ResumabilityTests/AWSS3StoragePluginGetDataResumabilityTests.swift
AmplifyPlugins/Storage/Tests/StorageHostApp/AWSS3StoragePluginIntegrationTests/ResumabilityTests/AWSS3StoragePluginPutDataResumabilityTests.swift

fix storage upload/download pause integration tests

fix(storage): fix upload/download pause integration tests

---

.github/workflows/codeql.yml
.github/workflows/integ_test.yml
.github/workflows/integ_test_api.yml
.github/workflows/integ_test_datastore.yml
AmplifyPlugins/Core/AWSPluginsCore/ServiceConfiguration/AmplifyAWSServiceConfiguration.swift
CHANGELOG.md
README.md

chore: Updated changelog for v2 and removed dev-preview references

---

README.md

N/A
Fix broken link to API docs after renaming of repo.

chore(docs): api docs link after renaming

---

.circleci/config.yml
.github/workflows/codeql.yml
.github/workflows/integ_test.yml
.github/workflows/release_block_manual_pr.yml
.github/workflows/release_kickoff.yml
.github/workflows/release_merge_pr.yml
.jazzy.yaml
Amplify.podspec
fastlane/Fastfile

chore: Update the configuration to point to v1 and release

---

.jazzy.yaml
CircleciScripts/jazzy_doc_gen.sh

chore: Update jazzy cli command [skip ci]

---

UpgradeGuide.md

chore: Add upgrade guide [skip ci]

---

.circleci/config.yml

chore: Update v1 branch to start release on v1 branch

---

.circleci/config.yml
fastlane/Fastfile

chore: Add steps to do unstable release in main

---

.github/workflows/integ_test.yml
AmplifyPlugins/Auth/Tests/AuthHostApp/AuthHostApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/DeviceTests/AuthFetchDeviceTests.swift
AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/DeviceTests/AuthForgetDeviceTests.swift
AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/DeviceTests/AuthRememberDeviceTests.swift
AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/README.md

test(auth): Change the folder path for v2 auth tests

---

AmplifyPlugins/Analytics/Sources/AWSPinpointAnalyticsPlugin/Dependency/Pinpoint/Analytics/PinpointEvent.swift

fix(analytics): revert previous analytics limit commit

---

.circleci/config.yml

chore: Added stable release workflow to the CI pipeline

---

AmplifyAsyncTesting/Sources/AsyncTesting/XCTestCase+AsyncTesting.swift
AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/AWSDataStorePlugin+DataStoreBaseBehavior.swift

fix: Build failure in xcode 13.4

---

fastlane/Fastfile

chore: Change the CI fastlane script for v1 release

---

.circleci/config.yml
Gemfile.lock
fastlane/Fastfile
fastlane/README.md

chore: Update gemfilelock to point to the right ci script

---

AmplifyPlugins/Core/AWSPluginsCore/ServiceConfiguration/AmplifyAWSServiceConfiguration.swift

fix: Release automation changed the configuration source

---

AmplifyPlugins/Core/AWSPluginsCore/ServiceConfiguration/AmplifyAWSServiceConfiguration.swift
fastlane/Fastfile

chore: Change the version key for release CI [skip ci]

---

CircleciScripts/jazzy_doc_gen.sh

chore: updating doc gen script

---

fastlane/Fastfile

chore: updating fastlane script to forcefully fetch tags from remote

---

AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/AWSDataStorePlugin+DataStoreBaseBehavior.swift
AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/AWSDataStorePlugin.swift
AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Core/AWSDataStorePluginTests.swift
AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/DataStoreEndToEndTests.swift

https://github.com/aws-amplify/amplify-swift/issues/2167
This PR adds Unit & Integration Tests to align the code changes originally from https://github.com/aws-amplify/amplify-swift/pull/2517 on `v1` branch & make sure it works here on the `main` branch.
`v1` PR https://github.com/aws-amplify/amplify-swift/pull/2517

fix(datastore): fix stop then start API call pattern

---

.github/workflows/integ_test.yml
.github/workflows/integ_test_api.yml
.github/workflows/integ_test_datastore.yml
.github/workflows/integ_test_datastore_v2.yml

- ~~[ ] Ran AWSDataStorePluginIntegrationTests~~
- ~~[ ] Ran AWSDataStorePluginV2Tests~~
- ~~[ ] Ran AWSDataStorePluginMultiAuthTests~~
- ~~[ ] Ran AWSDataStorePluginCPKTests~~
- ~~[ ] Ran AWSDataStorePluginAuthCognitoTests~~
- ~~[ ] Ran AWSDataStorePluginAuthIAMTests~~

chore: add ability to manually run integration tests

---

AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/UserBehaviourTests/AWSCognitoAuthUserBehaviorTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/UserBehaviourTests/UserBehaviorFetchAttributeTests.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Dependency/AWSS3Adapter.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Dependency/AWSS3PreSignedURLBuilderAdapter.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Dependency/S3Client+SigV4Config.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Dependency/S3ClientConfigurationProtocol+Endpoint.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Dependency/UploadPartInput+presignURL.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Service/Storage/AWSS3StorageService.swift
Package.resolved
Package.swift

chore: Updating aws-swift-sdk to 0.5.0 and fixing s3 configuration issues

---

AmplifyPlugins/Analytics/Sources/AWSPinpointAnalyticsPlugin/Support/Extensions/Date+Formatting.swift
AmplifyPlugins/Analytics/Sources/AWSPinpointAnalyticsPlugin/Support/Extensions/PinpointClient+CredentialsProvider.swift
AmplifyPlugins/Geo/Sources/AWSLocationGeoPlugin/AWSLocationGeoPlugin+Configure.swift
AmplifyPlugins/Geo/Tests/AWSLocationGeoPluginTests/Mocks/MockAWSClientConfiguration.swift
AmplifyPlugins/Geo/Tests/AWSLocationGeoPluginTests/Mocks/MockAWSLocation.swift

chore: Fixing build errors in Geo and Analytics

---

Amplify/Categories/Geo/DeviceTracking/Geo+Device.swift
Amplify/Categories/Geo/DeviceTracking/Geo+DeviceTrackingOptions.swift
Amplify/Categories/Geo/GeoCategory+ClientBehavior.swift
Amplify/Categories/Geo/GeoCategoryBehavior.swift
AmplifyPlugins/Geo/Sources/AWSLocationGeoPlugin/AWSLocationGeoPlugin+ClientBehavior.swift
AmplifyPlugins/Geo/Sources/AWSLocationGeoPlugin/Dependency/AWSDeviceTracker.swift
AmplifyPlugins/Geo/Sources/AWSLocationGeoPlugin/Dependency/AWSDeviceTrackingBehavior.swift
AmplifyPlugins/Geo/Tests/AWSLocationGeoPluginTests/Mocks/MockDeviceTracker.swift
AmplifyTestCommon/Mocks/MockGeoCategoryPlugin.swift

* Refactor device id generation to use AWSAuthService to get cognito identity id.
* 

chore(geo): refactor device id generation

---

Amplify/Categories/Auth/AuthCategory+ClientBehavior.swift
Amplify/Categories/Auth/AuthCategoryBehavior.swift
Amplify/Categories/Auth/Request/AuthWebUISignInRequest.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/HostedUI/InitializeHostedUISignIn.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/ClientBehavior/AWSCognitoAuthPlugin+ClientBehavior.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/States/HostedUISignInState.swift
AmplifyPlugins/Auth/Tests/AuthHostedUIApp/AuthHostedUIApp.xcodeproj/project.pbxproj
AmplifyPlugins/Auth/Tests/AuthHostedUIApp/AuthHostedUIApp/Assets.xcassets/AccentColor.colorset/Contents.json
AmplifyPlugins/Auth/Tests/AuthHostedUIApp/AuthHostedUIApp/Assets.xcassets/AppIcon.appiconset/Contents.json
AmplifyPlugins/Auth/Tests/AuthHostedUIApp/AuthHostedUIApp/Assets.xcassets/Contents.json
AmplifyPlugins/Auth/Tests/AuthHostedUIApp/AuthHostedUIApp/AuthHostedUIAppApp.swift
AmplifyPlugins/Auth/Tests/AuthHostedUIApp/AuthHostedUIApp/ContentView.swift
AmplifyPlugins/Auth/Tests/AuthHostedUIApp/AuthHostedUIApp/Info.plist
AmplifyPlugins/Auth/Tests/AuthHostedUIApp/AuthHostedUIApp/Preview Content/Preview Assets.xcassets/Contents.json
AmplifyPlugins/Auth/Tests/AuthHostedUIApp/AuthHostedUIApp/Utils/AuthError+Info.swift
AmplifyPlugins/Auth/Tests/AuthHostedUIApp/AuthHostedUIApp/Utils/ConfigurationHelper.swift
AmplifyPlugins/Auth/Tests/AuthHostedUIApp/AuthHostedUIApp/Views/SignUpView.swift
AmplifyPlugins/Auth/Tests/AuthHostedUIApp/AuthHostedUIApp/Views/SignedInView.swift
AmplifyPlugins/Auth/Tests/AuthHostedUIApp/AuthHostedUIApp/Views/SignedOutView.swift
AmplifyPlugins/Auth/Tests/AuthHostedUIApp/AuthHostedUIAppUITests/AuthHostedUIAppUITests.swift
AmplifyPlugins/Auth/Tests/AuthHostedUIApp/AuthHostedUIAppUITests/AuthHostedUIAppUITestsLaunchTests.swift
AmplifyPlugins/Auth/Tests/AuthHostedUIApp/AuthHostedUIAppUITests/AuthenticationTest/HostedUISignInTests.swift
AmplifyPlugins/Auth/Tests/AuthHostedUIApp/AuthHostedUIAppUITests/Screen/AuthenticatedScreen.swift
AmplifyPlugins/Auth/Tests/AuthHostedUIApp/AuthHostedUIAppUITests/Screen/SignInScreen.swift
AmplifyPlugins/Auth/Tests/AuthHostedUIApp/AuthHostedUIAppUITests/Screen/SignUpScreen.swift
AmplifyPlugins/Auth/Tests/AuthHostedUIApp/AuthHostedUIAppUITests/UITestCase.swift
AmplifyTestCommon/Mocks/MockAuthCategoryPlugin.swift

feat(auth): Make the presentation anchor optional

---

AmplifyPlugins/Geo/Sources/AWSLocationGeoPlugin/Dependency/AWSDeviceTracker.swift
AmplifyPlugins/Geo/Sources/AWSLocationGeoPlugin/Dependency/AWSDeviceTrackingBehavior.swift
AmplifyPlugins/Geo/Sources/AWSLocationGeoPlugin/Persistence/PositionInternal.swift
AmplifyPlugins/Geo/Sources/AWSLocationGeoPlugin/Persistence/SQLiteLocationPersistenceAdapter.swift
AmplifyPlugins/Geo/Sources/AWSLocationGeoPlugin/Support/Constants/GeoPluginErrorConstants.swift
AmplifyPlugins/Geo/Tests/AWSLocationGeoPluginTests/AWSDeviceTrackerTests.swift
AmplifyPlugins/Geo/Tests/AWSLocationGeoPluginTests/AWSLocationGeoPluginTestBase.swift
AmplifyPlugins/Geo/Tests/AWSLocationGeoPluginTests/Mocks/MockDeviceTracker.swift
AmplifyPlugins/Geo/Tests/AWSLocationGeoPluginTests/Mocks/MockGeoKeychainStore.swift
AmplifyPlugins/Geo/Tests/AWSLocationGeoPluginTests/SQLiteLocationPersistenceAdapterTests.swift

*Description of changes:* Store `deviceID` in Keychain instead of `UserDefaults`

chore(geo): Store device id in Keychain

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/DeviceSRPAuth/InitiateAuthDeviceSRP.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/DeviceSRPAuth/StartDeviceSRPFlow.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Events/SignInEvent.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/States/DebugInfo/DeviceSRPState+Debug.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/States/DeviceSRPState.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/SRP/DeviceSRPState+Resolver.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/SignIn/SignInState+Resolver.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Helpers/UserPoolSignInHelper.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthSignInTask.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/AWSAuthSignInPluginTests.swift
AmplifyPlugins/Auth/Tests/AuthHostApp/AuthHostApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

fix(Auth): Fixing deviceSRP auth flow during MigrateAuth

---

AmplifyPlugins/Analytics/Tests/AnalyticsHostApp/AWSPinpointAnalyticsPluginIntegrationTests/AWSPinpointAnalyticsPluginIntegrationTests.swift
AmplifyPlugins/Analytics/Tests/AnalyticsHostApp/AnalyticsHostApp.xcodeproj/project.pbxproj
AmplifyPlugins/Analytics/Tests/AnalyticsHostApp/AnalyticsHostApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

*Description of changes:* Add stress tests for Analytics category

chore(analytics): Add stress tests for Analytics category

---

.github/workflows/integ_test.yml

update integration tests workflow to cause overall job to fail on failed storage test
- ~~[ ] Ran AWSDataStorePluginIntegrationTests~~
- ~~[ ] Ran AWSDataStorePluginV2Tests~~
- ~~[ ] Ran AWSDataStorePluginMultiAuthTests~~
- ~~[ ] Ran AWSDataStorePluginCPKTests~~
- ~~[ ] Ran AWSDataStorePluginAuthCognitoTests~~
- ~~[ ] Ran AWSDataStorePluginAuthIAMTests~~

chore: update integration tests workflow to cause overall job to fail on failed storage test

---

AmplifyPlugins/Predictions/AWSPredictionsPlugin/Support/Internal/NativeWebSocketProvider.swift

chore(predictions): Remove URL cache from TranscribeStreaming

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/AWSCognitoAuthPlugin+Configure.swift

chore(auth): Remove url cache from hostedUI token fetch

---

AmplifyPlugins/Analytics/Tests/AnalyticsHostApp/AWSPinpointAnalyticsPluginIntegrationTests/AWSPinpointAnalyticsPluginIntegrationTests.swift
AmplifyPlugins/Analytics/Tests/AnalyticsHostApp/AnalyticsHostApp.xcodeproj/project.pbxproj
AmplifyPlugins/Analytics/Tests/AnalyticsHostApp/AnalyticsHostApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
AmplifyPlugins/Analytics/Tests/AnalyticsHostApp/AnalyticsHostApp.xcodeproj/xcshareddata/xcschemes/AnalyticsHostApp.xcscheme
AmplifyPlugins/Analytics/Tests/AnalyticsHostApp/AnalyticsHostApp.xcodeproj/xcshareddata/xcschemes/AnalyticsStressTests.xcscheme
AmplifyPlugins/Analytics/Tests/AnalyticsHostApp/AnalyticsStressTests/AnalyticsStressTests.swift
AmplifyPlugins/Analytics/Tests/AnalyticsHostApp/AnalyticsStressTests/README.md

*Description of changes:* Create a new test target for Analytics stress tests

chore(analytics): Create a new test target for Analytics stress tests

---

AmplifyPlugins/Core/AWSPluginsCore/Auth/Provider/AmplifyAWSCredentialsProvider.swift
AmplifyPlugins/Core/AWSPluginsCoreTests/Auth/AWSAuthServiceTests.swift

fix(core): Add proper handling of expired credentials

---

AmplifyPlugins/API/AWSAPICategoryPluginFunctionalTests/GraphQLModelBased/GraphQLConnectionScenario3Tests+List.swift
AmplifyPlugins/API/AWSAPICategoryPluginFunctionalTests/GraphQLModelBased/GraphQLModelBasedTests.swift

This is the `v1` version of https://github.com/aws-amplify/amplify-swift/pull/2665

chore(api-v1): functional integ tests - paginate on list requests

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/RefreshAuthorizationSession/InitializeRefreshSession.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/CredentialStorage/AmplifyCredentials+CognitoSession.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/Helpers/FetchAuthSessionOperationHelper.swift

chore(auth): Cleanup on FetchAuthSessionOperationhelper

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/SRPAuth/VerifyPasswordSRP.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/VerifySignInChallenge.swift

fix(auth): Build failure due to typo in device binding

---

Amplify/Categories/DataStore/Model/Internal/Schema/ModelSchema.swift
AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Dependency/AuthorizationProviderAdapter.swift
AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Support/Utils/AuthErrorHelper.swift
AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Support/Utils/UserCodeDeliveryDetails+Extension.swift
AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/MutationEvent/MutationEventClearState.swift

chore: Fixing Xcode warnings.

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/RefreshAuthorizationSession/UserPool/RefreshUserPoolTokens.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/DeviceSRPAuth/InitiateAuthDeviceSRP.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/DeviceSRPAuth/VerifyDevicePasswordSRP.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/IntializeSignInFlow.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/SRPAuth/InitiateAuthSRP.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/SRPAuth/VerifyPasswordSRP.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/VerifySignInChallenge.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Data/SRPStateData.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Events/SignInChallengeEvent.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Events/SignInEvent.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/SRP/SRPSignInState+Resolver.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/SignIn/SignInChallengeState+Resolver.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Helpers/DeviceMetadataHelper.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Helpers/UserPoolSignInHelper.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Utils/RespondToAuthChallengeInput+Amplify.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/DeviceTasks/AWSAuthForgetDeviceTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/DeviceTasks/AWSAuthRememberDeviceTask.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ActionTests/InitiateAuthSRP/VerifyPasswordSRPTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ActionTests/VerifySignInChallenge/VerifySignInChallengeTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ResolverTests/SRPSignInState/SRPTestData.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/ClientBehaviorTests/AWSAuthConfirmSignInTaskTests.swift

This is a feature branch, review the sub PRs in each commit.
- #2719
- #2699
- #2697
- #2694
- #2691

fix(auth): Device tracking fixes feature branch

---

.circleci/config.yml

enable fortify scan in CircleCI

chore: enable fortify in v1 branch

---

Package.resolved
Package.swift

upgrade to aws-sdk-swift v0.6.1
- ~~[ ] New or updated tests include `Given When Then` inline code documentation and are named accordingly `testThing_condition_expectation()`~~

fix: upgrade to aws-sdk-swift v0.6.1

---

AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/DataStoreConsecutiveUpdatesTests.swift

For integration test cases of `DataStoreConsecutiveUpdatesTests`, there is chance that some MutationEvents are not processed or put into inProcess state when we've received previous operation response from server side. According to the [current reconciliation algorithm](https://github.com/aws-amplify/amplify-swift/blob/main/AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/MutationSync/AWSMutationDatabaseAdapter/AWSMutationDatabaseAdapter%2BMutationEventIngester.swift#L198-L214), these incoming event will be ignored and will not be published as hub event. 
Therefore, this fix patch is updating the assert logic focus on confirming the data is eventually consistent.

test(datastore): fix flaky integration test cases

---

AmplifyPlugins/Notifications/Push/Tests/PushNotificationHostApp/PushNotificationHostAppUITests/PushNotificationHostAppUITests.swift

fix verifyRequestNotificationsPermissions integration test

fix(notifications): fix verifyRequestNotificationsPermissions integration test

---

.circleci/config.yml

chore(notifications): add push notifications unit tests to circle CI config

---

CHANGELOG.md

- ~~[ ] Build succeeds with all target using Swift Package Manager~~
- ~~[ ] New or updated tests include `Given When Then` inline code documentation and are named accordingly `testThing_condition_expectation()`~~

chore(notifications): update changelog [skip ci]

---

Amplify/Categories/Storage/Operation/Request/StorageDownloadDataRequest.swift
Amplify/Categories/Storage/Operation/Request/StorageDownloadFileRequest.swift
Amplify/Categories/Storage/Operation/Request/StorageGetURLRequest.swift
Amplify/Categories/Storage/Operation/Request/StorageListRequest.swift
Amplify/Categories/Storage/Operation/Request/StorageRemoveRequest.swift
Amplify/Categories/Storage/Operation/Request/StorageUploadDataRequest.swift
Amplify/Categories/Storage/Operation/Request/StorageUploadFileRequest.swift
Amplify/Categories/Storage/StorageAccessLevel.swift

Adds missing tags that allow linking between plugin documentation and general category specification types.

chore(storage): Added request swiftdoc tags

---

.github/workflows/notify_release.yml

chore: Update notify_release.yml

---

.github/workflows/notify_issue_comment.yml
.github/workflows/notify_new_issue.yml

chore: Updating notify actions to use env vars

---

.github/workflows/notify_issue_comment.yml
.github/workflows/notify_new_issue.yml
.github/workflows/notify_release.yml

chore: using string interpolation correctly for workflows [skip ci]

---

AmplifyPlugins/Predictions/AWSPredictionsPlugin/AWSPredictionsPlugin+ClientBehavior.swift

- updates function signatures of top-level APIs in AWSPredictionsPlugin
- 

feat(predictions): update top level awspredictionsplugin APIs

---

Amplify/Categories/Predictions/Request/Interpret/Interpret+Result.swift

- fixes non-namespaced types in one model type.

fix(predictions): tiny model type update

---

AmplifyPlugins/Predictions/AWSPredictionsPlugin/Service/Predictions/AWSComprehendServiceBehavior.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Service/Predictions/AWSPollyServiceBehavior.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Service/Predictions/AWSPredictionsService+Comprehend.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Service/Predictions/AWSPredictionsService+Polly.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Service/Predictions/AWSPredictionsService+Rekognition.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Service/Predictions/AWSPredictionsService+Textract.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Service/Predictions/AWSPredictionsService+Transcribe.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Service/Predictions/AWSPredictionsService+Translate.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Service/Predictions/AWSRekognitionServiceBehavior.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Service/Predictions/AWSTextractServiceBehavior.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Service/Predictions/AWSTranscribeStreamingServiceBehavior.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Service/Predictions/AWSTranslateServiceBehavior.swift

- adds specific AWS service behaviors back in.
*Note: functionally, this is very close to a 1:1 mapping of v1. Subsequent PR will take care of some cleanup / error handling.

feat(predictions): add service behaviors

---

Amplify/Categories/API/AuthProvider/APIAuthProviderFactory.swift
Amplify/Categories/API/Interceptor/URLRequestInterceptor.swift
AmplifyPlugins.podspec
AmplifyPlugins/API/APICategoryPlugin.xcodeproj/project.pbxproj
AmplifyPlugins/API/AWSAPICategoryPlugin/Interceptor/RequestInterceptor/AuthTokenProviderWrapper.swift
AmplifyPlugins/API/AWSAPICategoryPlugin/Interceptor/RequestInterceptor/AuthTokenURLRequestInterceptor.swift
AmplifyPlugins/API/AWSAPICategoryPlugin/Interceptor/RequestInterceptor/IAMURLRequestInterceptor.swift
AmplifyPlugins/API/AWSAPICategoryPlugin/Interceptor/SubscriptionInterceptor/AuthenticationTokenAuthInterceptor.swift
AmplifyPlugins/API/AWSAPICategoryPlugin/Interceptor/SubscriptionInterceptor/HeaderIAMSigningHelper.swift
AmplifyPlugins/API/AWSAPICategoryPlugin/Interceptor/SubscriptionInterceptor/IAMAuthInterceptor.swift
AmplifyPlugins/API/AWSAPICategoryPlugin/Interceptor/SubscriptionInterceptor/OIDCAuthProviderWrapper.swift
AmplifyPlugins/API/AWSAPICategoryPlugin/Operation/AWSGraphQLOperation.swift
AmplifyPlugins/API/AWSAPICategoryPlugin/Operation/AWSRESTOperation.swift
AmplifyPlugins/API/AWSAPICategoryPluginTests/Configuration/AWSAPICategoryPluginConfigurationTests.swift
AmplifyPlugins/API/AWSAPICategoryPluginTests/Interceptor/AuthTokenURLRequestInterceptorTests.swift
AmplifyPlugins/API/AWSAPICategoryPluginTests/Interceptor/SubscriptionInterceptor/IAMAuthInterceptorTests.swift
AmplifyPlugins/API/Podfile
AmplifyPlugins/API/Podfile.lock
AmplifyPlugins/Core/AWSPluginsCore/Auth/Provider/AuthTokenProvider.swift
AmplifyPlugins/DataStore/Podfile.lock
Package.swift

This is a feature branch PR. All the commits in this PR are already reviewed and approved.
https://github.com/aws-amplify/amplify-swift/pull/2870 feat(api): Add async protocol implementation for token request interceptors
https://github.com/aws-amplify/amplify-swift/pull/2871 feat(api): Async IAM signing
https://github.com/aws-amplify/amplify-swift/pull/2876 feat(api): Update URL interceptor to be async

feat(api): Add async flavor for request interceptors

---

AmplifyPlugins/API/APICategoryPlugin.xcodeproj/project.pbxproj
AmplifyPlugins/API/AWSAPICategoryPlugin/Interceptor/SubscriptionInterceptor/IAMAuthInterceptor.swift
AmplifyPlugins/API/AWSAPICategoryPlugin/Interceptor/SubscriptionInterceptor/IAMHeaderSigningHelper.swift
AmplifyPlugins/API/AWSAPICategoryPluginTests/Interceptor/SubscriptionInterceptor/IAMAuthInterceptorTests.swift

Follow up from previous PR to change function naming - https://github.com/aws-amplify/amplify-swift/pull/2889#discussion_r1175898653

chore(api): Update the function name and add comments

---

AmplifyPlugins/Predictions/AWSPredictionsPlugin/Support/Utils/IdentifyCelebritiesResultTransformers.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Support/Utils/IdentifyEntitiesResultTransformers.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Support/Utils/IdentifyLabelsResultTransformers.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Support/Utils/IdentifyResultTransformers.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Support/Utils/IdentifyTextResultTransformers+KeyValueSet.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Support/Utils/IdentifyTextResultTransformers+Tables.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Support/Utils/IdentifyTextResultTransformers.swift

chore(predictions): re-add model transformers

---

AmplifyPlugins/Predictions/AWSPredictionsPlugin/Service/MultiService/IdentifyMultiService.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Service/MultiService/InterpretTextMultiService.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Service/MultiService/MultiServiceBehavior.swift

- re-adds multiservices (offline / online). 
*likely to be refactored out into something thinner in a subsequent staging PR.

chore(predictions): re-add multiservices

---

.circleci/config.yml
.github/workflows/integ_test.yml

test(predictions): ci - add unit and integration test jobs

---

README.md

Updates snippets in `README.md` to be compatible with v2 APIs.

chore(docs): update readme with v2 snippets

---

.github/workflows/new_issue_maintainer.yml
.github/workflows/notify_issue_comment.yml

chore: updating users on notify actions

---

Amplify/Categories/Storage/Error/StorageError.swift
Amplify/Categories/Storage/Operation/StorageDownloadDataOperation.swift
Amplify/Categories/Storage/Operation/StorageDownloadFileOperation.swift
Amplify/Categories/Storage/Operation/StorageGetURLOperation.swift
Amplify/Categories/Storage/Operation/StorageListOperation.swift
Amplify/Categories/Storage/Operation/StorageRemoveOperation.swift
Amplify/Categories/Storage/Operation/StorageUploadDataOperation.swift
Amplify/Categories/Storage/Operation/StorageUploadFileOperation.swift
Amplify/Categories/Storage/Result/ProgressListener.swift
Amplify/Categories/Storage/StorageCategory.swift
Amplify/Categories/Storage/StorageCategoryConfiguration.swift

chore(storage): Added missing doc tags

---

AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/AWSS3StoragePlugin+ClientBehavior.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/AWSS3StoragePlugin+Configure.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/AWSS3StoragePlugin+Reset.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/AWSS3StoragePlugin.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Configuration/AWSS3PluginPrefixResolver.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Configuration/AWSS3StoragePluginConfiguration.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Dependency/SdkTypealiases.swift

chore(storage): Added plugin doc tags

---

Amplify/Core/Support/AmplifyError.swift
Amplify/Core/Support/AmplifyErrorMessages.swift
Amplify/Core/Support/AmplifyTask.swift
Amplify/Core/Support/DeviceInfo.swift

In the spirit of aiming to fully document all our types, this PR enhances documentation for AmplifyError, AmplifyErrorMessages, AmplifyTask, and DeviceInfo.

chore(core): Added documentation to AmplifyError, AmplifyErrorMessages, AmplifyTask, and DeviceInfo.

---

README.md

https://github.com/aws-amplify/amplify-swift/issues/2960
Removing outdated Developer Preview mention in the README file.

chore: Updating README to remove outdated dev-preview reference

---

Amplify/Amplify.swift
Amplify/Core/Category/Category+Logging.swift
Amplify/Core/Category/Category.swift
Amplify/Core/Category/CategoryType.swift
Amplify/Core/Configuration/AmplifyConfiguration.swift
Amplify/Core/Configuration/CategoryConfiguration.swift
Amplify/Core/Configuration/ConfigurationError.swift
Amplify/Core/Error/CoreError.swift

chore(core): Enhanced swift documentation

---

.circleci/config.yml
fastlane/Fastfile

ci: read CocoaPods trunk token from AWS secret

---

.github/workflows/integ_test_datastore.yml

- enable datastore transformer v2 test

test(datastore): enable datastore transformer v2 test

---

README.md

This PR updates the README file to mention tvOS and watchOS support.
It also adds the missing **Push Notifications** and **Predictions** categories.

chore: Updating README

---

.github/ISSUE_TEMPLATE/bug_report.yaml
README.md

- Updates README.md to include information about preview visionOS support.
- Updates issue template to include visionOS as platform + some other misc. updates.

chore: update readme and issue template for visionOS support

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/AWSCognitoAuthPlugin+EscapeHatch.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/AWSCognitoAuthPlugin+PluginSpecificAPI.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/AWSCognitoAuthPluginBehavior.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/ClientBehavior/AWSCognitoAuthPlugin+ClientBehavior.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/ClientBehavior/AWSCognitoAuthPlugin+UserBehavior.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Request/FetchMFAPreferenceRequest.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Request/UpdateMFAPreferenceRequest.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthConfirmSignInTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/FetchMFAPreferenceTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/Helpers/AWSAuthTaskHelper.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/Protocols/AuthSetUpTOTPTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/Protocols/AuthVerifyTOTPSetupTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/SetUpTOTPTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/UpdateMFAPreferenceTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/VerifyTOTPSetupTask.swift

Depends on: 
* #3040 
* #3041 
* #3042
Changes
* Adds and restructures plugin API's
* Adds request implementations needed for tasks.
* Adds implementations of the tasks for the public API's
_NOTE: The unit and integration tests will fail until all changes make it to the feature branch_
(The PR is directed towards a feature branch)

feat(Auth): Adding TOTP tasks and requests to AWSAuthCognitoPlugin

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Models/MFATypeExtension.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Helpers/UserPoolSignInHelper.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/Helpers/AWSAuthTaskHelper.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/SetUpTOTPTask.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/ClientBehaviorTests/ClientBehaviorConfirmResetPasswordTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/ClientBehaviorTests/ClientBehaviorResetPasswordTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/ClientBehaviorTests/MFA/FetchMFAPreferenceTaskTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/ClientBehaviorTests/MFA/SetUpTOTPTaskTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/ClientBehaviorTests/MFA/VerifyTOTPSetupTaskTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/ClientBehaviorTests/SignIn/AWSAuthConfirmSignInTaskTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/ClientBehaviorTests/SignIn/ConfirmSignInTOTPTaskTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/ClientBehaviorTests/SignIn/ConfirmSignInWithMFASelectionTaskTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/ClientBehaviorTests/SignIn/ConfirmSignInWithSetUpMFATaskTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/ClientBehaviorTests/SignUp/AWSAuthResendSignUpCodeAPITests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/DeviceBehaviorTests/DeviceBehaviorFetchDevicesTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/DeviceBehaviorTests/DeviceBehaviorForgetDeviceTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/DeviceBehaviorTests/DeviceBehaviorRememberDeviceTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/UserBehaviourTests/UserBehaviorChangePasswordTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/UserBehaviourTests/UserBehaviorConfirmAttributeTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/UserBehaviourTests/UserBehaviorFetchAttributeTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/UserBehaviourTests/UserBehaviorResendCodeTests.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/UserBehaviourTests/UserBehaviorUpdateAttributeTests.swift
AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/SignOutTests/AuthSignOutTests.swift

Worked on review comments from 
- https://github.com/aws-amplify/amplify-swift/pull/3047
- https://github.com/aws-amplify/amplify-swift/pull/3046

feat(Auth): Worked on review comments and cleaning up unit tests

---

.swiftpm/xcode/xcshareddata/xcschemes/AWSCloudWatchLoggingPlugin.xcscheme
.swiftpm/xcode/xcshareddata/xcschemes/Amplify-Package.xcscheme
Amplify/Categories/Logging/LogLevel.swift
Amplify/DefaultPlugins/AWSUnifiedLoggingPlugin/Internal/OSLogWrapper.swift
Amplify/DevMenu/Data/LogEntryItem.swift
AmplifyPlugins/Logging/Sources/AWSCloudWatchLoggingPlugin/AWSCloudWatchLoggingError.swift
AmplifyPlugins/Logging/Sources/AWSCloudWatchLoggingPlugin/Consumer/CloudWatchLoggingConsumer.swift
AmplifyPlugins/Logging/Sources/AWSCloudWatchLoggingPlugin/Consumer/CloudWatchLoggingEntryFormatter.swift
AmplifyPlugins/Logging/Sources/AWSCloudWatchLoggingPlugin/Consumer/CloudWatchLoggingStreamNameFormatter.swift
AmplifyPlugins/Logging/Sources/AWSCloudWatchLoggingPlugin/Domain/LogBatch.swift
AmplifyPlugins/Logging/Sources/AWSCloudWatchLoggingPlugin/Domain/LogBatchConsumer.swift
AmplifyPlugins/Logging/Sources/AWSCloudWatchLoggingPlugin/Domain/LogBatchProducer.swift
AmplifyPlugins/Logging/Sources/AWSCloudWatchLoggingPlugin/Domain/LoggerKey.swift
AmplifyPlugins/Logging/Sources/AWSCloudWatchLoggingPlugin/Persistence/LogEntry.swift
AmplifyPlugins/Logging/Sources/AWSCloudWatchLoggingPlugin/Persistence/LogEntryCodec.swift
AmplifyPlugins/Logging/Sources/AWSCloudWatchLoggingPlugin/Producer/RotatingLogBatch.swift
AmplifyPlugins/Logging/Tests/AWSCloudWatchLoggingPluginTests/CloudWatchLogConsumerTests.swift
AmplifyPlugins/Logging/Tests/AWSCloudWatchLoggingPluginTests/LogEntryTestExtensions.swift
AmplifyPlugins/Logging/Tests/AWSCloudWatchLoggingPluginTests/LogEntryTests.swift
AmplifyPlugins/Logging/Tests/AWSCloudWatchLoggingPluginTests/MockCloudWatchLogsClient.swift
AmplifyPlugins/Logging/Tests/AWSCloudWatchLoggingPluginTests/MockLogger.swift
AmplifyPlugins/Logging/Tests/AWSCloudWatchLoggingPluginTests/TestResources/amplifyconfiguration_logging.json
AmplifyPlugins/Logging/Tests/AWSCloudWatchLoggingPluginTests/TestResources/remoteloggingconstraints.json
Package.swift

feat(logging): add initial supporting structures for new logger plugin

---

AmplifyPlugins/Logging/Sources/AWSCloudWatchLoggingPlugin/Support/AWSCloudWatchLoggingConstraintsResolver.swift
AmplifyPlugins/Logging/Sources/AWSCloudWatchLoggingPlugin/Support/AWSCloudWatchLoggingFilter.swift
AmplifyPlugins/Logging/Sources/AWSCloudWatchLoggingPlugin/Support/AWSCloudWatchLoggingFilterBehavior.swift
AmplifyPlugins/Logging/Sources/AWSCloudWatchLoggingPlugin/Support/AWSCloudWatchLoggingMonitor.swift
AmplifyPlugins/Logging/Sources/AWSCloudWatchLoggingPlugin/Support/Constants/PluginErrorConstants.swift
AmplifyPlugins/Logging/Sources/AWSCloudWatchLoggingPlugin/Support/LoggingConstraintsLocalStore.swift
AmplifyPlugins/Logging/Sources/AWSCloudWatchLoggingPlugin/Support/LoggingNetworkMonitor.swift
AmplifyPlugins/Logging/Tests/AWSCloudWatchLoggingPluginTests/AWSCloudWatchLoggingMonitorTests.swift
AmplifyPlugins/Logging/Tests/AWSCloudWatchLoggingPluginTests/AWSCloudWatchingLoggingFilterTests.swift
AmplifyPlugins/Logging/Tests/AWSCloudWatchLoggingPluginTests/LoggingNetworkMonitorTests.swift

Add supporting components for the logging plugin

feat(logging): add supporting structure to for logging plugin

---

README.md

chore: Update README.md to update minimum supported Xcode version to 14.1 [skip ci]

---

.gitignore
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Service/ErrorMapping/RespondToAuthChallengeOutputError+AuthError.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Service/ErrorMapping/VerifySoftwareTokenOutputError+AuthError.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/SignIn/SignInState+Resolver.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/FetchMFAPreferenceTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/Protocols/AuthDeleteUserTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/Protocols/AuthSetUpTOTPTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/UpdateMFAPreferenceTask.swift

feat(Auth): Updating the Sign In resolver to add new cases 

---

CONTRIBUTING.md
README.md

Updating README.md and CONTRIBUTING.md to include details about Amplify's guidelines on semantic versioning.

chore: Updating README.md and CONTRIBUTING.md to include details about semantic versioning

---

.github/workflows/deploy_package.yml

This PR adds the `secrets: inherit` attribute when calling children workflows from the deploy workflow.

chore(workflows): inheriting secrets when calling workflows

---

.github/workflows/deploy_package.yml

Unquoting the retrieved token on the release workflow, as it caused the checkout to fail.

chore: [v1] Fixing wrong parsing in release workflow [skip ci]

---

Amplify/Categories/Storage/Operation/Request/StorageDownloadDataRequest.swift

chore: Add transfer acceleration documentation for plugin options

---

Package.swift

chore: remove invalid exclude warning

---

.github/workflows/deploy_package.yml
.github/workflows/deploy_release.yml
.github/workflows/release_doc.yml
CircleciScripts/jazzy_doc_gen.sh

-  add documentation release workflow after stable release

ci: add release doc workflow

---

.github/workflows/canary.yml

ci: add canary workflow

---

AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/Model/DTOMapping.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/Model/FaceLivenessSession+OvalMatchChallenge.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/ServiceModel/ChallengeConfig.swift

* Add new field for oval fit timeout in the liveness service model
* Amplify Liveness UI component will need to update to new version of Amplify once this is released

chore: update liveness service model with oval  fit timeout

---

Package.resolved
Package.swift

update swift sdk dependency version to 0.22.0

---

.github/workflows/build_amplify_swift.yml
.github/workflows/codeql.yml
.github/workflows/fortify_scan.yml
.github/workflows/unit_test.yml

Adds pass confirmation jobs to workflows that should be required status checks.
This lets us add / remove required status checks (`<dependent-jobs>`) directly within the applicable workflow files rather than in branch protection settings.
Without the `if: {{ !cancelled() }}`, a dependent job failure would cause the `confirm-pass` job to be skipped. A required status check job that is skipped satisfies the status check (i.e. allows the PR to be merged).
```bash
confirm-pass:
runs-on: ubuntu-latest
name: Confirm Pass
if: ${{ !cancelled() }}
needs: [
<dependent-jobs>
]
env:
EXIT_CODE: ${{ contains(needs.*.result, 'failure') && 1 || 0 }}
steps:
- run: exit $EXIT_CODE
```
- Example of failing as expected: https://github.com/aws-amplify/amplify-swift/actions/runs/5881151050
- Example of passing …

chore: add pass confirmation jobs in actions

---

CHANGELOG.md

Add back a missing changelog item from v2.18.0 release. The commit was missing the "feat" prefix so CI didn't pick it up

chore: Update CHANGELOG.md for 2.18.0 [skip ci]

---

AmplifyPlugins/API/Sources/AWSAPIPlugin/Interceptor/RequestInterceptor/IAMURLRequestInterceptor.swift
AmplifyPlugins/API/Sources/AWSAPIPlugin/Interceptor/SubscriptionInterceptor/IAMAuthInterceptor.swift

Makes necessary changes to get AWSAPIPlugin to compile.
none

fix: misc. changes to AWSAPIPlugin

---

AmplifyPlugins/Notifications/Push/Sources/AWSPinpointPushNotificationsPlugin/Error/CommonRunTimeError+PushNotificationsErrorConvertible.swift
AmplifyPlugins/Notifications/Push/Sources/AWSPinpointPushNotificationsPlugin/Error/Pinpoint+PushNotificationsErrorConvertible.swift
AmplifyPlugins/Notifications/Push/Sources/AWSPinpointPushNotificationsPlugin/Error/PushNotificationsErrorConvertible.swift
AmplifyPlugins/Notifications/Push/Sources/AWSPinpointPushNotificationsPlugin/Extensions/Error+PushNotifications.swift

Updates error handling in AWSPinpointPushNotificationsPlugin.
none

fix(push-notifications): error handling

---

AmplifyPlugins/Internal/Tests/InternalAWSPinpointUnitTests/PinpointRequestsRegistryTests.swift

Target executed requests when asserting user-agent correctness in `PinpointRequestsRegistryTests` 

fix(pinpoint-requests-registry-tests): target executed request in tests

---

Package.resolved

Update Package.resolved to fix release build issues.

chore: update package.resolved with latest references

---

AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TestHarness/AuthTestHarnessInput.swift
AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TestHarness/CognitoAPIDecoding/CognitoAPIDecodingHelper.swift

Changes error generation in auth test harness to work around Swift SDK changes to access control.
See base branch staging PR for more information:
- https://github.com/aws-amplify/amplify-swift/pull/3346

test: update auth test harness for sdk access control changes [skip ci]

---

AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Dependency/UploadPartInput+presignURL.swift

Moves `UploadPartOutputError` into Amplify to allow `UploadPartInput().customPresignURL(config:expiration:)` to continue working. This is necessary because the Swift SDK recently made that type internal. 
See base branch staging PR for more information:
- https://github.com/aws-amplify/amplify-swift/pull/3346

fix: move UploadPartOutputError into Amplify for UploadPart signing [skip ci]

---

.github/workflows/release_kickoff.yml

Revert "chore: Adding checkbox validations to the release workflow trigger (#3376)

---

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthChangePasswordTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthClearFederationToIdentityPoolTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthConfirmResetPasswordTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthConfirmSignInTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthConfirmSignUpTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthDeleteUserTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthFederateToIdentityPoolTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthFetchSessionTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthResendSignUpCodeTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthResetPasswordTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthSignInTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthSignOutTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthSignUpTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthWebUISignInTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/DeviceTasks/AWSAuthFetchDevicesTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/DeviceTasks/AWSAuthForgetDeviceTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/DeviceTasks/AWSAuthRememberDeviceTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/Protocols/AmplifyAuthTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/UserTasks/AWSAuthAttributeResendConfirmationCodeTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/UserTasks/AWSAuthConfirmUserAttributeTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/UserTasks/AWSAuthFetchUserAttributeTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/UserTasks/AWSAuthUpdateUserAttributeTask.swift
AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/UserTasks/AWSAuthUpdateUserAttributesTask.swift

N/A
Adding info and error logs around Amplify Auth tasks.

fix(Auth): Add logging to Amplify Auth tasks

---

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/OutgoingMutationQueue/ProcessMutationErrorFromCloudOperation.swift
AmplifyPlugins/DataStore/Podfile.lock
Podfile.lock

chore: upgrade pod dependencies

---

AmplifyPlugins/Auth/Tests/AuthHostApp/AuthHostApp.xcodeproj/project.pbxproj
AmplifyPlugins/Auth/Tests/AuthHostApp/AuthHostApp.xcodeproj/xcshareddata/xcschemes/AuthIntegrationTests.xcscheme
AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/AWSAuthBaseTest.swift
AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/PasswordlessTests/SignInWithMagicLinkTests.swift
AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/PasswordlessTests/SignInWithOTPTests.swift

feat(auth): add integration tests

---

AmplifyPlugins/Predictions/AWSPredictionsPluginIntegrationTests/IdentifyBasicIntegrationTests.swift

See same fix on main https://github.com/aws-amplify/amplify-swift/pull/3408

test(predictions): Fix prediction integration test

---

.github/composite_actions/download_test_configuration/action.yml
.github/workflows/build_amplify_swift.yml
.github/workflows/canary.yml
.github/workflows/codeql.yml
.github/workflows/dependency-review.yml
.github/workflows/deploy_package.yml
.github/workflows/deploy_release.yml
.github/workflows/deploy_unstable.yml
.github/workflows/fortify_scan.yml
.github/workflows/integ_test_push_notifications.yml
.github/workflows/release_block_manual_pr.yml
.github/workflows/release_doc.yml
.github/workflows/release_kickoff.yml
.github/workflows/run_integration_tests.yml
.github/workflows/run_unit_tests.yml
.github/workflows/stress_test.yml
.github/workflows/upload_coverage_report.yml

- Updates versions of dependency actions.

chore: update github action dependency versions

---

README.md

Fixes a typo in the Cognito framework name and updates `.add(_:)` to `.add(plugin:)`
Fixes two issues I encountered while following the README.

chore: Minor fix for README

---

README.md

None
Update minimum supported xcode version for installation on supported platforms

chore: update minimum supported xcode version

---

AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Storage/CascadeDeleteOperation.swift
AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/Attempt.swift
AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Support/Internal/AttemptTests.swift

https://github.com/aws-amplify/amplify-swift/issues/3528
This PR includes changes to code to build for xcode 15.3 beta 2.

fix(build): update code to build for xcode 15.3 beta 2

---

.github/workflows/issue_closed.yml

None
In the AWS SDKs, we received some customer feedback that our closed issue message is too loud and too full of emoji. This message is slightly more polite. Please feel free to discard this PR if you disagree.

chore: a more polite closed issue message

---

Amplify/Core/Support/TaskQueue.swift
AmplifyTests/CoreTests/AmplifyTaskQueueTests.swift

fix(Core): TaskQueue<Success> async execution is not serial #3556

---

AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/Events/LivenessEvent.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/Events/LivenessFinalClientEvent.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/Events/LivenessFreshnessEvent.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/Events/LivenessInitialClientEvent.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/Model/DTOMapping.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/Model/FaceLivenessSession+Challenge.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/Model/FaceLivenessSession+SessionConfiguration.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/SPI/AWSPredictionsPlugin+Liveness.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/Service/Challenge.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/Service/FaceLivenessSession.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/Service/FaceLivenessSessionRepresentable.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/ServiceModel/ChallengeEvent.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/ServiceModel/ClientChallenge.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/ServiceModel/FaceMovementClientChallenge.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/ServiceModel/FaceMovementServerChallenge.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/ServiceModel/ServerChallenge.swift

None
Add public definitions for no light challenge support

feat(predictions): add public definitions for no light challenge support

---

AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/Events/LivenessEvent.swift
AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/SPI/AWSPredictionsPlugin+Liveness.swift

Adding support to handle invalid signature exception from a Liveness event

chore(predictions): add support for invalid signature exception

---

.github/workflows/unit_test.yml

Skip code coverage to avoid codecov upload. Upload is failing for the release: 

chore: skip report coverage

---

Package.resolved
Package.swift

This PR upgrades our dependency of **SQLite.swift** to version [0.15.0](https://github.com/stephencelis/SQLite.swift/releases/tag/0.15.0), which includes its Privacy Manifest file.
- [DataStore](https://github.com/aws-amplify/amplify-swift/actions/runs/8901695473)
- [API](https://github.com/aws-amplify/amplify-swift/actions/runs/8901694589)  
- [![](https://64.media.tumblr.com/tumblr_ltdghqdz981qh59n0o4_250.gif)](https://github.com/aws-amplify/amplify-swift/actions/runs/8901692790)

feat: Upgrading to SQLite.swift 0.15.0

---

AmplifyPlugins/Analytics/Tests/AnalyticsHostApp/AWSPinpointAnalyticsPluginIntegrationTests/README.md

Removed some unnecessary CDK steps such as the pre-sign-up lambda, and update to latest commands

chore(analytics): integ readme clean up

---

.codecov.yml

This PR disables the patch status check from Codecov

chore: Disabling patch status check [skip ci]

---

Amplify/DevMenu/AmplifyDevMenu.swift
AmplifyTests/DevMenuTests/GestureRecognizerTests.swift

Fixing compilation error with Swift 6 for dev menu 

chore(core): resolve swift 6 errors in dev menu

---

.github/composite_actions/get_platform_parameters/action.yml
canaries/example/Gemfile.lock

Update gem.lock file to include required platform to run canary test

chore: fix failed canary test

---

AmplifyPlugins/Logging/Sources/AWSCloudWatchLoggingPlugin/AWSCloudWatchLoggingSessionController.swift
AmplifyPlugins/Logging/Sources/AWSCloudWatchLoggingPlugin/Consumer/CloudWatchLoggingConsumer.swift
AmplifyPlugins/Logging/Sources/AWSCloudWatchLoggingPlugin/Consumer/CloudWatchLoggingStreamNameFormatter.swift
AmplifyPlugins/Logging/Tests/AWSCloudWatchLoggingPluginTests/CloudWatchLogConsumerTests.swift

Update Logging plugin to compile with Swift 6 tooling enabled

fix(logging): fix Swift 6 compiler error

---

.github/workflows/apiBreakTest.yml
Amplify/Amplify.swift
api-dump-test/A.json
api-dump-test/B.json
api-dump-test/expected-result.txt
check_api_breakage.sh

chore: Add API Breakage Checking GH Action
