AmplifyPlugins/API/AWSAPICategoryPlugin/Interceptor/SubscriptionInterceptor/APIKeyAuthInterceptor.swift, AmplifyPlugins/API/AWSAPICategoryPlugin/Interceptor/SubscriptionInterceptor/AppSyncSubscriptionInterceptor.swift, AmplifyPlugins/API/AWSAPICategoryPlugin/Interceptor/SubscriptionInterceptor/CognitoUserPoolsAuthInterceptor.swift, AmplifyPlugins/API/AWSAPICategoryPlugin/Interceptor/SubscriptionInterceptor/IAMAuthInterceptor.swift, AmplifyPlugins/API/AWSAPICategoryPlugin/Subscription/ConnectionProvider/AppSyncConnectionProvider+EventHandler.swift, AmplifyPlugins/API/AWSAPICategoryPlugin/Subscription/ConnectionProvider/AppSyncConnectionProvider.swift, AmplifyPlugins/API/AWSAPICategoryPlugin/Subscription/SubscriptionConnection/AppSyncSubscriptionConnection+EventHandler.swift, AmplifyPlugins/API/AWSAPICategoryPlugin/Subscription/SubscriptionConnection/AppSyncSubscriptionConnection.swift, AmplifyPlugins/API/AWSAPICategoryPlugin/Subscription/Websocket/StarscreamWebsocketProvider+WebsocketDelegate.swift, AmplifyPlugins/API/AWSAPICategoryPlugin/Subscription/Websocket/StarscreamWebsocketProvider.swift, AmplifyPlugins/API/AWSAPICategoryPlugin/Support/Utils/AppSyncJSONHelper.swift
replaces print's with verbose/warn/error
=> Update logging to use Amplify.API.log

Amplify/Categories/DataStore/DataStoreCategory+Behavior.swift
Allows for invocations like `Amplify.DataStore.query(Post.self) { _ in }`
=> Make predicate optional for query

Amplify.xcodeproj/project.pbxproj, AmplifyPlugins/API/AWSAPICategoryPluginFunctionalTests/GraphQLSyncBased/GraphQLSyncBasedTests.swift, AmplifyPlugins/Core/AWSPluginsCore/Model/GraphQLDocument/GraphQLDocument+DeleteSyncMutation.swift, AmplifyPlugins/Core/AWSPluginsCore/Model/GraphQLDocument/GraphQLDocument+GetQuery.swift, AmplifyPlugins/Core/AWSPluginsCore/Model/GraphQLDocument/GraphQLDocument+ListQuery.swift, AmplifyPlugins/Core/AWSPluginsCore/Model/GraphQLDocument/GraphQLDocument+Mutation.swift, AmplifyPlugins/Core/AWSPluginsCore/Model/GraphQLDocument/GraphQLDocument+Subscription.swift, AmplifyPlugins/Core/AWSPluginsCore/Model/GraphQLDocument/GraphQLDocument+SyncMutation.swift, AmplifyPlugins/Core/AWSPluginsCore/Model/GraphQLDocument/GraphQLDocument+SyncQuery.swift, AmplifyPlugins/Core/AWSPluginsCore/Model/GraphQLDocument/GraphQLDocument.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLDocument/GraphQLDocumentTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLDocument/GraphQLGetQueryTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLDocument/GraphQLListQueryTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLDocument/GraphQLMutationTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLDocument/GraphQLSubscriptionTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/OutgoingMutationQueue/SyncMutationToCloudOperation.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/IncomingAsyncSubscriptionEventPublisher.swift, AmplifyPlugins/DataStore/DataStoreCategoryPlugin.xcodeproj/project.pbxproj
This introduces a flag for whether a GraphQLDocument helper method should contain the sync-able fields. Methods like GraphQLSyncQuery by default will be true, and methods like GraphQLGetQuery can be used with syncEnabled parameter.
- Moved MinimalGraphQLDeleteMutation over to PluginsCore as GraphQLDeleteSyncMutation
- Updated GraphQLListQuery to include limit and nextToken, in anticipation for ModelBased List query to allow limit/nextToken.
- Ensured the Sync provisioned backend in API integration tests is working as expected, and so went to datastore plugin and updated the calls where necessary, like
```
let document = GraphQLSubscription(of: modelType,
type: subscriptionType,
syncEnabled: true)
// adding syncEnabled true parameter
```
- Ensure Model based APIs are working. by default …
=> Remove dependency on ModelRegistry for syncability of models

Amplify.xcodeproj/project.pbxproj, Amplify/Core/Support/DispatchSource+MakeOneOff.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/OutgoingMutationQueue/MutationRetryNotifier.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/OutgoingMutationQueue/OutgoingMutationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/OutgoingMutationQueue/SyncMutationToCloudOperation.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/NetworkReachabilityNotifier.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RequestRetryable.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RequestRetryablePolicy.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/MutationQueue/SyncMutationToCloudOperationTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/NetworkReachabilityNotifierTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/RequestRetryablePolicyTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/Support/MockSQLiteStorageEngineAdapter.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/TestSupport/Mocks/MockRequestRetryablePolicy.swift, AmplifyPlugins/DataStore/DataStoreCategoryPlugin.xcodeproj/project.pbxproj, AmplifyTestCommon/Mocks/MockAPICategoryPlugin.swift, AmplifyTestCommon/Mocks/MockAPIResponders.swift, Podfile.lock, Pods/Manifest.lock, Pods/Pods.xcodeproj/project.pbxproj
Work-in-progress.  need to find a way to plumb through the hostname from the client config
=> Integrate retryability for outgoing mutation queue

Amplify.xcodeproj/project.pbxproj, AmplifyPlugins/API/AWSAPICategoryPlugin/Interceptor/RequestInterceptor/APIKeyURLRequestInterceptor.swift, AmplifyPlugins/API/AWSAPICategoryPlugin/Interceptor/RequestInterceptor/IAMURLRequestInterceptor.swift, AmplifyPlugins/API/AWSAPICategoryPlugin/Interceptor/RequestInterceptor/UserPoolRequestInterceptor.swift, AmplifyPlugins/API/AWSAPICategoryPlugin/Support/Constants/URLRequestConstants.swift, AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/Dependency/AWSPinpointAdapter.swift, AmplifyPlugins/Core/AWSPluginsCore/ServiceConfiguration/AmplifyAWSServiceConfiguration.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/ServiceConfiguration/AmplifyAWSServiceConfigurationTests.swift, AmplifyPlugins/Predictions/AWSPredictionsPlugin/AWSPredictionsPlugin+Configure.swift, AmplifyPlugins/Predictions/AWSPredictionsPlugin/Service/CoreML/CoreMLPredictionService.swift, AmplifyPlugins/Predictions/AWSPredictionsPlugin/Service/Predictions/AWSPredictionsService.swift, AmplifyPlugins/Predictions/AWSPredictionsPluginTests/Service/PredictionsTest/PredictionsServiceComprehendTests.swift, AmplifyPlugins/Predictions/AWSPredictionsPluginTests/Service/PredictionsTest/PredictionsServiceRekognitionTests.swift, AmplifyPlugins/Predictions/AWSPredictionsPluginTests/Service/PredictionsTest/PredictionsServiceTextractTests.swift, AmplifyPlugins/Predictions/AWSPredictionsPluginTests/Service/PredictionsTest/PredictionsServiceTranslateTests.swift, AmplifyPlugins/Storage/AWSS3StoragePlugin/Service/Storage/AWSS3StorageService.swift, Podfile.lock, Pods/Manifest.lock, Pods/Pods.xcodeproj/project.pbxproj
This pr is a continuation of the royjit@'s work here:
https://github.com/aws-amplify/amplify-ios/pull/166
* Created (mostly copy and pasted) ServiceConfiguration -> AmplifyAWSServiceConfiguration
* Updated (mostly copy and pasted) Predictions category to use this new class (which should be used when using aws-sdk-ios)
* Updated Amplify API to leverage AmplifyAWSServiceConfiguration
* URLRequestContants.swift -> URLRequestConstants
* removed placeholder useragent
* Update for Analytics to use AmplifyAWSServiceConfiguration
* Update for Storage to use AmplifyAWSServiceConfiguration
=> Adding amplify specific user agent, revival of PR#166 (271)

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/AWSDataStorePlugin.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/StorageEngine.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/StorageEngineBehavior.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Subscribe/DataStorePublisher.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngine.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngineBehavior.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/AWSIncomingEventReconciliationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/IncomingEventReconciliationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/ReconcileAndLocalSave/AWSModelReconciliationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/ReconcileAndLocalSave/ModelReconciliationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/ReconcileAndLocalSave/ReconcileAndLocalSaveOperation.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/LocalSubscriptionTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/RemoteEngineSyncTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/Support/MockSQLiteStorageEngineAdapter.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/TestSupport/Mocks/MockAWSIncomingEventReconciliationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/TestSupport/Mocks/MockAWSInitialSyncOrchestrator.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/TestSupport/Mocks/MockOutgoingMutationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/TestSupport/Mocks/MockReconciliationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/TestSupport/SyncEngineTestBase.swift, AmplifyPlugins/DataStore/DataStoreCategoryPlugin.xcodeproj/project.pbxproj, Podfile.lock, Pods/Manifest.lock, Pods/Target Support Files/Pods-Amplify/Pods-Amplify-acknowledgements.markdown, Pods/Target Support Files/Pods-Amplify/Pods-Amplify-acknowledgements.plist
* Compiled hello world app against this code to see mutation events being printed out w/:
```
noteSubscription = Amplify.DataStore.publisher(for: Note.self)
.sink(receiveCompletion: {completion in
if case .failure(let err) =  completion { 
print("issue with subscription: \(err)")
}
}, receiveValue: { value in
print("Subscription got this value: \(value)")
})
```
* Ran unit tests
=> Add mutation events to publisher() interfaces in sync engine components to bubble up status and mutation events

Amplify.xcodeproj/project.pbxproj, Amplify/Categories/Storage/Error/AuthError.swift, AmplifyPlugins/API/APICategoryPlugin.xcodeproj/project.pbxproj, AmplifyPlugins/API/APICategoryPlugin.xcodeproj/xcshareddata/xcschemes/RESTWithUserPoolIntegrationTests.xcscheme, AmplifyPlugins/API/AWSAPICategoryPlugin/Interceptor/RequestInterceptor/IAMURLRequestInterceptor.swift, AmplifyPlugins/API/AWSAPICategoryPlugin/Interceptor/RequestInterceptor/UserPoolRequestInterceptor.swift, AmplifyPlugins/API/AWSAPICategoryPlugin/Operation/AWSGraphQLOperation.swift, AmplifyPlugins/API/AWSAPICategoryPlugin/Operation/AWSRESTOperation.swift, AmplifyPlugins/API/AWSAPICategoryPluginIntegrationTests/REST/RESTWithUserPoolIntegrationTests/Info.plist, AmplifyPlugins/API/AWSAPICategoryPluginIntegrationTests/REST/RESTWithUserPoolIntegrationTests/README.md, AmplifyPlugins/API/AWSAPICategoryPluginIntegrationTests/REST/RESTWithUserPoolIntegrationTests/RESTWithUserPoolIntegrationTests.swift, AmplifyPlugins/API/Podfile, AmplifyPlugins/Core/AWSPluginsCore/Auth/AWSAuthService.swift, AmplifyPlugins/Core/AWSPluginsCore/Auth/AWSMobileClientError+Extension.swift
This adds integration tests around using APIGateway with Cognito User Pool token authentication. Updated some error handling logic to accurately bubble up the error for "User is not authenticated and tries to make a call against the API", so is reflected in the test.
Currently Amplify-CLI experience does not support creating REST API with cognito use pool authorizier, experience and feature request documented here: https://github.com/aws-amplify/amplify-cli/issues/3390
=> Add Rest API with UserPool Integration tests

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngine+Action.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngine+IncomingEventReconciliationQueueEvent.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngine+Resolver.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngine+State.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngine.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/LocalSubscriptionTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/RemoteEngineSyncTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/TestSupport/SyncEngineTestBase.swift, AmplifyPlugins/DataStore/DataStoreCategoryPlugin.xcodeproj/project.pbxproj
=> Update RemoteSyncEngine to adopt a StateMachine to allow for easier control of start/stop/retry

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngine+Action.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngine+IncomingEventReconciliationQueueEvent.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngine+Resolver.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngine+Retryable.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngine+State.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngine.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngineBehavior.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/LocalSubscriptionTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/RemoteSyncEngineTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/TestSupport/SyncEngineTestBase.swift, AmplifyPlugins/DataStore/DataStoreCategoryPlugin.xcodeproj/project.pbxproj
This handles logic to restart the remote sync engine, without actually canceling downstream components.
=> Added retry/restart logic to RemoteSyncEngine without cancel downstream components

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngine+Action.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngine+IncomingEventReconciliationQueueEvent.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngine+Resolver.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngine+Retryable.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngine.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/AWSIncomingEventReconciliationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/AWSIncomingSubscriptionEventPublisher.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/IncomingAsyncSubscriptionEventPublisher.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/IncomingEventReconciliationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/IncomingSubscriptionEventPublisher.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/ReconcileAndLocalSave/AWSModelReconciliationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/Support/Cancellable.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/RemoteSyncEngineTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/ModelReconciliationQueueBehaviorTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/Support/ReconciliationQueueTestBase.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/TestSupport/Mocks/MockAWSIncomingEventReconciliationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/TestSupport/Mocks/MockReconciliationQueue.swift, AmplifyPlugins/DataStore/DataStoreCategoryPlugin.xcodeproj/project.pbxproj
In this PR, we are adding a cancellable interface, but still not calling cancel -- that will be done in the next PR
=> Adding cancellable interface to RemoteSyncEngine components

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngine+IncomingEventReconciliationQueueEvent.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngine+Resolver.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngine.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/AWSIncomingEventReconciliationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/AWSIncomingSubscriptionEventPublisher.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/IncomingAsyncSubscriptionEventPublisher.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/IncomingAsyncSubscriptionEventToAnyModelMapper.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/IncomingEventReconciliationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/IncomingSubscriptionEventPublisher.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/ReconcileAndLocalSave/AWSModelReconciliationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/ReconcileAndLocalSave/ModelReconciliationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/RemoteSyncEngineTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/ModelReconciliationDeleteTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/TestSupport/Mocks/MockAWSIncomingEventReconciliationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/TestSupport/SyncEngineTestBase.swift
In this case we are waiting for the subscriptions to properly initialize the subscriptions, which means, we have the need to make sure that the sockets are connected, prior to doing our initial sync.
I'm not particularly proud how we are handling connected sockets & propagating that status up -- I will be refactoring this shortly -- but the good news is that if i explicitly kill sockets in API, this code seems to allow us to bring and remote sync engine up and down! :)
Known issues
. API is not passing back errors (working with lawmicha@ on this.)
. API is storing connections and not killing them (have some code which cleans the connections on a cancel() of an Amplify API operation) (working with lawmicha@ on this)
. OutgoingMutationQueue occasionally receives and invalid state transition …
=> Propagate connection status up, wait on subscription init, fix unit tests

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/AWSIncomingSubscriptionEventPublisher.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/IncomingAsyncSubscriptionEventPublisher.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/IncomingAsyncSubscriptionEventToAnyModelMapper.swift
Found two memory leaks using the memory graph debugger/visualizer.
Repro:
setup a data store app, go into airplane mode to force subscription connections to fail, then go back online to restart subscription connections
Observed behavior:
Instances of AWSIncomingSubscriptionEventPublisher were referencing itself
IncomingAsyncSubscriptionEventToAnyModelMapper references dangling due to subscriptions and.
=> Fix two memory leaks when restarting remote sync engine

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RequestRetryablePolicy.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/RequestRetryablePolicyTests.swift
Issue was reported here for app sync:
https://github.com/awslabs/aws-mobile-appsync-sdk-ios/issues/339
Since we are using very similar logic, this needs to get updated for datastore as well.
=> Fix crash when retry handler attemptNumber is >= 57

AmplifyPlugins.podspec, AmplifyPlugins/API/Podfile
Looks like 1.0.2 removed interceptors while current version takes ~1.0.0 which will pulls in 1.0.2 and has some classes missing like RealtimeGatewayURLInterceptor. I published 1.1.0 and need to bump the version of the consumers.
=> Use AppSyncRealTimeClient 1.1.0

Amplify/Categories/DataStore/DataStoreCategory+Behavior.swift, Amplify/Categories/DataStore/DataStoreCategoryBehavior.swift, Amplify/Categories/DataStore/Query/QueryPredicate.swift, Amplify/Core/Support/BasicClosure.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/AWSDataStorePlugin+DataStoreBaseBehavior.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/ModelStorageBehavior.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/SQLStatement+Condition.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/StorageEngineAdapter+SQLite.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/StorageEngine.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/StorageEngineAdapter.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Core/SQLiteStorageEngineAdapterTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/Support/MockSQLiteStorageEngineAdapter.swift, AmplifyTestCommon/Mocks/MockDataStoreCategoryPlugin.swift
This code adds the following concepts:
- sql `transaction` interface to the storageAdapter
- `QueryPredicateConstant.all` to query for all items
- New `delete(type, predicate)` interface for storageEngine/ModelStroageBehavior
- Implementation of transaction-based delete Model.Type w/ predicate
- Submission of individual deleted modelIds to be submitted to the sync engine, but without the predicate.  Deferring submitting the predicate until we can refactor the MutationEvent to two separate classes -- one to notify customers, and one to submit into the SyncEngine
=> Datastore delete model type with local predciate API w/out predicate on sync

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/OutgoingMutationQueue/SyncMutationToCloudOperation.swift
Fix DataStore delete mutation - pass in model.id. Previously it was passing in mutationEvent.Id which is just a unique identifier for the mutationEvent, not the model instance's identifier
=> Fix DataStore delete mutation 

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngine.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/IncomingAsyncSubscriptionEventPublisher.swift
- Minor refactor to avoid using mutex/DispatchSemaphore
- Removed serial operation queue that was no longer being used in RemoteSyncEngine
=> Switch mutex to serial work queue & remove unused serial queue

Amplify/Categories/DataStore/DataStoreCategory+Behavior.swift, Amplify/Categories/DataStore/DataStoreCategoryBehavior.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/AWSDataStorePlugin+DataStoreBaseBehavior.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/AWSDataStorePlugin+DataStoreSubscribeBehavior.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/AWSDataStorePlugin.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/StorageEngineAdapter+SQLite.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/StorageEngine.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/StorageEngineAdapter.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/StorageEngineBehavior.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/MutationEvent/AWSMutationEventPublisher.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/MutationEvent/MutationEventPublisher.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/OutgoingMutationQueue/OutgoingMutationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngine+Action.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngine+Resolver.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngine+Retryable.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngine+State.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngine.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngineBehavior.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/RemoteSyncEngineTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/Support/MockSQLiteStorageEngineAdapter.swift, AmplifyTestCommon/Mocks/MockDataStoreCategoryPlugin.swift
. clear() is an async interface
. After calling clear() on DataStore, the datastore is in an idle state -- that is, the remote sync engine has stopped, all subscriptions have been severed and any publishers the customer may have been listening were called with receiveCompletion() (meaning, they will need to re-subscribe)
. Any subsequent call to query, save, delete, publisher() will restart the sync engine and publishers, mirroring JS's behavior
=> Datastore clear() sync implementation

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/OutgoingMutationQueue/OutgoingMutationQueue+Action.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/OutgoingMutationQueue/OutgoingMutationQueue+Resolver.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/OutgoingMutationQueue/OutgoingMutationQueue+State.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/OutgoingMutationQueue/OutgoingMutationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/MutationQueue/OutgoingMutationQueueTestsWithMockStateMachine.swift
I was thinking to destroying the operation that is responsible for sending the mutation event to the backend, and on resume re-reading it out of the local data store, but... I decided against that in the short term, as the changes seem to balloon pretty quickly.
I decided that it would be better just to fix the immediate bug first (e.g. ensure that the outgoing mutation queue gets resumed), and then take a step back to figure out if there's a better way to accomplish this (if needed)
Tested making a bunch of create mutations,
then going offline,
then made create mutations while offline
then go online (and check to make sure that the mutations are automatically sync'ed to the backend)
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
=> Fix resuming outgoing mutation queue

AmplifyPlugins/Core/AWSPluginsCore/Model/Support/SelectionSet.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLDocument/GraphQLSyncQueryTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/OutgoingMutationQueue/SyncMutationToCloudOperation.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginIntegrationTests/README.md, AmplifyPlugins/DataStore/DataStoreCategoryPlugin.xcodeproj/project.pbxproj
`DataStoreEndToEndTests.testCreateMutateDelete` was broken for two reasons:
- SelectionSet string generation logic was incorrect, fixed with added unit test
- MutationEvent does not contain model for delete mutationTypes, and the id of the model should be retrieved from mutationEvent.modelId
This also adds a README for setting up the DataStore tests and made sure the tests are passing.
=> Fix DataStore E2E test - testCreateMutateDelete

AWSPluginsCore.podspec, AWSPredictionsPlugin.podspec, AmplifyPlugins.podspec, AmplifyPlugins/API/AWSAPICategoryPlugin/Interceptor/SubscriptionInterceptor/IAMAuthInterceptor.swift, AmplifyPlugins/API/Podfile, AmplifyPlugins/Analytics/Podfile, AmplifyPlugins/DataStore/Podfile, AmplifyPlugins/Predictions/Podfile, AmplifyPlugins/Storage/Podfile, Podfile, Podfile.lock, Pods/Manifest.lock, Pods/Pods.xcodeproj/project.pbxproj
https://github.com/aws-amplify/amplify-ios/issues/356
Ran `pod cache clean --all && pod install --repo-update` across all plugins after dependency update
=> Upgrade SDK dependency to 2.13.0

Amplify.xcodeproj/project.pbxproj, Amplify/Categories/DataStore/Query/AnyQueryPredicate.swift, Amplify/Categories/DataStore/Query/QueryOperator+Codable.swift, Amplify/Categories/DataStore/Query/QueryPredicate.swift, Amplify/Categories/DataStore/Subscribe/MutationEvent+Schema.swift, Amplify/Categories/DataStore/Subscribe/MutationEvent.swift, AmplifyPlugins/Core/AWSPluginsCore/Model/GraphQLRequest/GraphQLRequest+AnyModelWithSync.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLDocument/GraphQLSyncQueryTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/StorageEngine.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/AWSMutationDatabaseAdapter/AWSMutationDatabaseAdapter+MutationEventIngester.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/OutgoingMutationQueue/SyncMutationToCloudOperation.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginIntegrationTests/DataStoreEndToEndTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginIntegrationTests/TestSupport/SyncEngineIntegrationTestBase.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/MutationQueue/AWSMutationDatabaseAdapterTests.swift, AmplifyPlugins/DataStore/DataStoreCategoryPlugin.xcodeproj/project.pbxproj
**Description of changes**
- Add Codable conformance to QueryPredicate to allow encodinig/decoding to JSON, stored in MutationEvent. This is accomplished with `AnyQueryPredicate` for encoding array of predicates, and custom Codable for `QueryOperator`.
- Storing `queryPredicateJson` in MutationEvent to allow decoding to `QueryPredicate` for 1. sending API requests with condition input on create/update mutations, and 2. handle conditional mutations in the `AWSMutationDatabaseAdapter: MutationEventIngester`.
-  `AWSMutationDatabaseAdapter` resolves conflicts for incoming candidate mutation events with conditions by saving the candidate. (does not drop/replace local with candidate, etc)
**DRAFT**
- This is written on top of existing PR for DataStore.save() with conditiion for local store …
=> DataStore.save() with condition for remote storage

Amplify.xcodeproj/project.pbxproj, Amplify/Categories/DataStore/DataStoreCategory+Behavior.swift, Amplify/Categories/DataStore/DataStoreCategoryBehavior.swift, Amplify/Categories/DataStore/Query/QueryPaginationInput.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/AWSDataStorePlugin+DataStoreBaseBehavior.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/ModelStorageBehavior.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/QueryPaginationInput+SQLite.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/SQLStatement+Select.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/StorageEngineAdapter+SQLite.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/StorageEngine.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/StorageEngineAdapter.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/AWSMutationDatabaseAdapter/AWSMutationDatabaseAdapter+MutationEventSource.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/Support/MutationEvent+Query.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Core/QueryPaginationInputTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Core/SQLStatementTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/Support/MockSQLiteStorageEngineAdapter.swift, AmplifyPlugins/DataStore/DataStoreCategoryPlugin.xcodeproj/project.pbxproj, AmplifyTestCommon/Mocks/MockDataStoreCategoryPlugin.swift, Pods/Pods.xcodeproj/project.pbxproj
**Notes:**
Introduce pagination support to the `DataStore.query` API.
- `QueryPaginationInput` holds the pagination values
- the `DataStore` plugin translates that struct to SQLite limit/offset
- add tests to make sure the new API behaves correctly under different scenarios
=> add pagination support to DataStore

Amplify.podspec, AmplifyTools/amplify-tools.sh
Updates based on @drochetti 's PR with regards to making amplify tools work in the amplify-ios package.
If end-user apps want to use amplify tools they need to.
1.  pod init
2.  add the following to their pod file:
```
pod 'Amplify'
pod 'Amplify/Tools'
```
3.  run
```
pod install --repo-update
```
4. open the project
```
xed .
```
5.  Add the following as a build step to their project.  For example
6. Build the project via xcode (cmd +b)
=> Rest of changes to make amplify-tools work

Amplify/Categories/DataStore/Query/QueryPaginationInput.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/StorageEngine.swift, Pods/Pods.xcodeproj/project.pbxproj
This passes the predicate passed in from `delete(modelType, predicate)` to the MutationEvent which will get used when syncing to the cloud
=> Add predicate to sync deletions

.circleci/config.yml, .jazzy.yaml, AWSPluginsCore.podspec, AWSPredictionsPlugin.podspec, Amplify.podspec, Amplify/Info.plist, AmplifyFunctionalTests/Info.plist, AmplifyPlugins.podspec, AmplifyPlugins/API/AWSAPICategoryPlugin/Info.plist, AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/Resources/Info.plist, AmplifyPlugins/Core/AWSPluginsCore/Info.plist, AmplifyPlugins/Core/AWSPluginsCore/ServiceConfiguration/AmplifyAWSServiceConfiguration.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Info.plist, AmplifyPlugins/Core/AWSPluginsTestCommon/Info.plist, AmplifyPlugins/Predictions/AWSPredictionsPlugin/Resources/Info.plist, AmplifyPlugins/Predictions/CoreMLPredictionsPlugin/Resources/Info.plist, AmplifyPlugins/Storage/AWSS3StoragePlugin/Resources/Info.plist, AmplifyTestApp/Info.plist, AmplifyTestCommon.podspec, AmplifyTestCommon/Info.plist, AmplifyTests/Info.plist, CoreMLPredictionsPlugin.podspec, fastlane/Fastfile
* Adding `sleep` for 10 mins in between dependent pods. This is a temporary measure, as the CocoaPods team now have a [PR](https://github.com/CocoaPods/cocoapods-trunk/pull/147) for allowing pushing pods straight to the git repo (circumventing the CDN, which will obviate the need for the delay between pushes)
* Bump versions to 0.11.0
=> 0.11.0 Release

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/AWSDataStorePlugin.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/StorageEngine.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/InitialSync/InitialSyncOperation.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/InitialSync/InitialSyncOrchestrator.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngine.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/APICategoryDependencyTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/InitialSync/InitialSyncOperationTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/InitialSync/InitialSyncOrchestratorTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/LocalSubscriptionTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/MutationQueue/AWSMutationEventIngesterTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/RemoteSync/RemoteSyncAPIInvocationTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/RemoteSyncEngineTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/TestSupport/BaseDataStoreTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/TestSupport/Mocks/MockAWSInitialSyncOrchestrator.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/TestSupport/Mocks/NoOpInitialSyncOrchestrator.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/TestSupport/SyncEngineTestBase.swift
Sending out draft PR since branch feature/datastore-config has not been pushed yet.
- Basic infrastructure changes to pass datastoreconfiguration through datastore 
- added default conflict handler to datastore configuration 
=> Pass instance of DataStoreConfiguration through Datastore

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/MutationEvent/MutationEventClearState.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngine+Action.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngine+Resolver.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngine+State.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngine.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngineBehavior.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/MutationQueue/MutationEventClearStateTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/MutationQueue/MutationIngesterConflictResolutionTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/RemoteSyncEngineTests.swift, AmplifyPlugins/DataStore/DataStoreCategoryPlugin.xcodeproj/project.pbxproj
=> Clear inProcess state on startup of outgoing mutation queue

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/AWSMutationDatabaseAdapter/AWSMutationDatabaseAdapter+MutationEventIngester.swift
=> Mark outgoing mutation as inProcess if nextEventPromise exists

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngine.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/AWSIncomingEventReconciliationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/ReconcileAndLocalSave/AWSModelReconciliationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/AWSIncomingEventReconciliationQueueTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/Support/MockModelReconciliatinQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/TestSupport/Mocks/MockAWSIncomingEventReconciliationQueue.swift, AmplifyPlugins/DataStore/DataStoreCategoryPlugin.xcodeproj/project.pbxproj
Prior to this fix, the crash looked something like this:
Seems like a race condition, where both subscription connections are coming in very quick succession, and somehow we are getting into a read/write race condition with `reconciliationQueueConnectionStatus` inside of `AWSIncomingEventReconciliationQueue`.
To reproduce this issue, you can remove the `connectionStatusOperationQueue.async` and run the unit test in `AWSIncomingEventReconciliationQueueTests` to see a very similar segfault:
```
2020-04-09 17:42:10.082784-0700 SampleDataStore[92033:19843535] [IncomingAsyncSubscriptionEventToAnyModelMapper] connectionState now connected
2020-04-09 17:42:10.082807-0700 SampleDataStore[92033:19843493] [IncomingAsyncSubscriptionEventToAnyModelMapper] connectionState now connected
2020-04-09 …
```
=> fix: Bug where subscription connections happen at the same time

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/DataStoreConfiguration.swift
=> fix: typo DataStoreConclictData to DataStoreConflictData

Amplify/Categories/Analytics/AnalyticsCategory+ClientBehavior.swift, Amplify/Categories/Analytics/AnalyticsCategoryBehavior.swift, Amplify/Categories/Analytics/AnalyticsProfile.swift, Amplify/Categories/Analytics/Event/AnalyticsEvent.swift, Amplify/Categories/Analytics/Event/BasicAnalyticsEvent.swift, AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/AWSPinpointAnalyticsPlugin+ClientBehavior.swift, AmplifyPlugins/Analytics/AWSPinpointAnalyticsPluginIntegrationTests/AWSPinpointAnalyticsPluginIntergrationTests.swift, AmplifyPlugins/Analytics/AWSPinpointAnalyticsPluginTests/AWSPinpointAnalyticsPluginClientBehaviorTests.swift, AmplifyTestCommon/Mocks/MockAnalyticsCategoryPlugin.swift, AmplifyTests/CategoryTests/Analytics/AnalyticsCategoryClientAPITests.swift, AmplifyTests/CoreTests/NotificationListeningAnalyticsPlugin.swift
- Added `unregisterGlobalProperties(_ keys: String...)` at the Category level. Because Amplify.Analytics.methods will call into the plugin. A variadic parameter turns into an array so there isn't an easy way to pass it in to call the plugin's method with variadic parameter. This way, the Analytics Category provides a helper method which calls into the `unregisterGlobalProperties(Set of strings)`, and plugin only needs to implement the single unregister method.
- Using typealias for map of property values, `AnalyticsPropertyValues`
=> feat: analytics updates API improvements (unregisterGlobalProperties)

Amplify.xcodeproj/project.pbxproj, Amplify/Categories/API/Response/GraphQLError.swift, AmplifyPlugins/API/APICategoryPlugin.xcodeproj/project.pbxproj, AmplifyPlugins/API/AWSAPICategoryPlugin/Support/Utils/GraphQLResponseDecoder+DecodeError.swift, AmplifyPlugins/API/AWSAPICategoryPlugin/Support/Utils/GraphQLResponseDecoder.swift, AmplifyPlugins/API/AWSAPICategoryPluginFunctionalTests/GraphQLSyncBased/GraphQLSyncBasedTests.swift, AmplifyPlugins/API/AWSAPICategoryPluginFunctionalTests/GraphQLSyncBased/README.md, AmplifyPlugins/API/AWSAPICategoryPluginTests/Support/Utils/GraphQLResponseDecoderDecodeErrorTests.swift, AmplifyPlugins/API/AWSAPICategoryPluginTests/Support/Utils/GraphQLResponseDecoderTests.swift, AmplifyPlugins/Core/AWSPluginsCore/API/AppSyncErrorType.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/OutgoingMutationQueue/ProcessMutationErrorFromCloudOperation.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/MutationQueue/ProcessMutationErrorFromCloudOperationTests.swift
This change merges the graphQL error values with keys which do not match the GraphQL spec into the extensions JSON.
Android PR for reference https://github.com/aws-amplify/amplify-android/pull/392
=> feat: [API] Merge non-GraphQL spec error fields into GraphQLError.extensions

Amplify.xcodeproj/project.pbxproj, Amplify/Categories/DataStore/Model/Schema/AuthRule.swift, Amplify/Categories/DataStore/Model/Schema/Model+Schema.swift, Amplify/Categories/DataStore/Model/Schema/ModelSchema+Definition.swift, Amplify/Categories/DataStore/Model/Schema/ModelSchema.swift, AmplifyTestCommon/Models/Blog+Schema.swift, AmplifyTestCommon/Models/Blog.swift, AmplifyTestCommon/Models/schema.graphql
This adds the class to contain the metadata about auth directive information on a model. This is information required to align the GraphQL Transform provisioned backend APIs and the generated client library call with the backend.
```
model.authRules = [
rule(allow: .owner, ownerField: blog.owner, operations: [.create, .update, .delete]),
rule(allow: .groups, groups: ["Admin"]),
]
```
=> feat: [DataStore] Add AuthRule support in Model schema

Amplify/Categories/DataStore/Model/Schema/ModelSchema+Definition.swift, Amplify/Categories/DataStore/Model/Schema/ModelSchema.swift, AmplifyTestCommon/Models/Blog+Schema.swift, AmplifyTestCommon/Models/Blog.swift, AmplifyTestCommon/Models/schema.graphql
Add support for field level auth directive
```
type Blog
@model
@auth(rules: [
{ allow: owner, ownerField: "owner", "operations: [create, update, delete] },
{ allow: owner, ownerField: "owner", "operations: [create, read] },
{ allow: groups, groups: ["Admin"] }
]) {
id: ID!
content: String!
createdAt: AWSDateTime!
owner: String
authorsNotes: String @auth( rules: [
{ allow: owner, ownerField: "owner", operations: [update] }
])
}
```
schema
```
public static let schema = defineSchema { model in
let blog = Blog.keys
model.pluralName = "Blogs"
model.authRules = [
rule(allow: .owner, ownerField: blog.owner, operations: [.create, .read]),
rule(allow: .groups, groups: ["Admin"]),
]
model.fields(
.id(),
.field(blog.content, is: .required, ofType: …
```
=> feat: [DataStore] Add AuthRule to field level

AmplifyPlugins/Auth/AWSAuthPlugin/Dependency/AuthenticationProviderAdapter+SignOut.swift
If the user is signed in through the webUI calling SignOut require the api to be called in main thread.
This change make sure that signOut happens in main thread.
=> fix(Auth): Crash in WebUI signout

Amplify/Categories/Auth/Models/AuthCodeDeliveryDetails.swift, Amplify/Categories/Auth/Models/AuthUserAttribute.swift, AmplifyPlugins/Auth/AWSAuthPlugin.xcodeproj/project.pbxproj, AmplifyPlugins/Auth/AWSAuthPlugin/AWSAuthPlugin+Configure.swift, AmplifyPlugins/Auth/AWSAuthPlugin/Dependency/AuthUserServiceAdapter.swift, AmplifyPlugins/Auth/AWSAuthPlugin/Dependency/AuthenticationProviderAdapter+SignIn.swift, AmplifyPlugins/Auth/AWSAuthPlugin/Dependency/AuthenticationProviderAdapter+SignUp.swift, AmplifyPlugins/Auth/AWSAuthPlugin/Support/Utils/AuthUserAttributeKey+Extension.swift, AmplifyPlugins/Auth/AWSAuthPlugin/Support/Utils/UserCodeDeliveryDetails+Extension.swift, AmplifyPlugins/Auth/AWSAuthPluginTests/Utils/AuthUserAttributeKeyTests.swift
- AuthUserAttributeKey to [RawRepresentable](https://developer.apple.com/documentation/swift/rawrepresentable), handles #419 
- Changed String attributeName in CodeDelivery to AuthUserAttributeKey
Update 1
- Added a new case `unknown` to the enum list to track an attribute unknown to the system and not a custom attribute.
- Raw value given in init will always be returned when we call `Enum.rawValue`
- Added missing userService and deviceService to the configuration
=> refactor(Auth): Refactored AuthUserAttributeKey to be RawRepresentable

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/AWSDataStorePlugin.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/APICategoryDependencyTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/LocalSubscriptionTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/MutationQueue/AWSMutationEventIngesterTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/MutationQueue/OutgoingMutationQueueTestsWithMockStateMachine.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/MutationQueue/ProcessMutationErrorFromCloudOperationTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/MutationQueue/SyncMutationToCloudOperationTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/RemoteSync/RemoteSyncAPIInvocationTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/ReconcileAndLocalSaveOperationTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/TestSupport/BaseDataStoreTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/TestSupport/SyncEngineTestBase.swift
=> fix(datastore): only start the remote sync engine if we have awsapiplugin

AmplifyPlugins/Auth/AWSAuthPlugin/AWSAuthPlugin.swift, AmplifyPlugins/Auth/AWSAuthPlugin/Models/AWSAuthService.swift
The escape hatch enum type was conflicting with the AWSPluginsCore class type. This was causing build failures in packages that are using both AWSAuthPlugin and AWSPluginsCore.
Conflicting class - [link](https://github.com/aws-amplify/amplify-ios/blob/master/AmplifyPlugins/Core/AWSPluginsCore/Auth/AWSAuthService.swift)
=> refactor(Auth): Rename the escape hatch enums type

AmplifyPlugins/API/APICategoryPlugin.xcodeproj/project.pbxproj, AmplifyPlugins/API/APICategoryPlugin.xcodeproj/xcshareddata/xcschemes/GraphQLWithUserPoolIntegrationTests.xcscheme, AmplifyPlugins/API/AWSAPICategoryPluginFunctionalTests/BlogPostCommentGraphQLWithAPIKey/BlogPostCommentGraphQLWithAPIKeyTests.swift, AmplifyPlugins/API/AWSAPICategoryPluginIntegrationTests/GraphQL/GraphQLWithUserPoolIntegrationTests/AuthDirective/GraphQLAuthDirectiveIntegrationTests+Support.swift, AmplifyPlugins/API/AWSAPICategoryPluginIntegrationTests/GraphQL/GraphQLWithUserPoolIntegrationTests/AuthDirective/GraphQLAuthDirectiveIntegrationTests.swift, AmplifyPlugins/API/AWSAPICategoryPluginIntegrationTests/GraphQL/GraphQLWithUserPoolIntegrationTests/AuthDirective/README.md, AmplifyPlugins/API/AWSAPICategoryPluginIntegrationTests/GraphQL/GraphQLWithUserPoolIntegrationTests/AuthDirective/SocialNote.swift, AmplifyTestCommon/Helpers/AuthHelper.swift, AmplifyTestCommon/Models/schema.graphql
This builds on top of https://github.com/aws-amplify/amplify-ios/pull/423 which provides the graphQL document builders to make the requests.
The integration tests run against a backend provisioined
- with a schema containing a model with auth directive
- cognito user pool as the auth mode.
- conflict resolution enabled
The schema is a read-only model by others other than owner.
```
type SocialNote
@model
@auth(rules: [
{ allow: owner, ownerField: "owner", operations: [create, update, delete] },
]) {
id: ID!
content: String!
owner: String
}
```
This test mainly executes methods relating to DataStore usage, ensuring expected service behavior and validating how the caller handles the API response, especially when the caller is unauthorized: …
=> feat: [API] auth directive integration tests

AmplifyTools/amplify-tools.sh, Podfile.lock, Pods/Manifest.lock
See https://github.com/aws-amplify/amplify-cli/pull/4268 for details
=> fix(tools): change the tools script to comply with amplify-app changes

Amplify/Categories/DataStore/DataStoreError.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/OutgoingMutationQueue/OutgoingMutationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/OutgoingMutationQueue/ProcessMutationErrorFromCloudOperation.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/MutationQueue/ProcessMutationErrorFromCloudOperationTests.swift
Scenario: 'Owner' is not signed in, persists to local store via DataStore.save()/DataStore.delete(), the mutationEvent is then attempted to call API.mutate. the mutate fails with `notAuthenticated` error.
This change checks for unauthenticated calls to API and propagates the error and corresponding MutationEvent to the developer using `DataStoreConfiguration.errorHandler`.
The error provided to the developer is
```
public enum DataStoreError: Error {
case api(AmplifyError, MutationEvent? = nil)
```
With the mutation event, the developer can see that the API call failed for some particular DataStore call. The developer can decide what to do. For example, 
- delete the data using the mutation event's model identifier, if it were a `.create` …
=> feat: [DataStore][AuthDirective] SyncToCloud not authenticated error handling

Amplify.xcodeproj/project.pbxproj, Amplify/Categories/Auth/Models/AuthEventName.swift, AmplifyPlugins/Auth/AWSAuthPlugin.xcodeproj/project.pbxproj, AmplifyPlugins/Auth/AWSAuthPlugin/AWSAuthPlugin+Configure.swift, AmplifyPlugins/Auth/AWSAuthPlugin/AWSAuthPlugin+Reset.swift, AmplifyPlugins/Auth/AWSAuthPlugin/AWSAuthPlugin.swift, AmplifyPlugins/Auth/AWSAuthPlugin/HubEvents/AuthHubEventBehavior.swift, AmplifyPlugins/Auth/AWSAuthPlugin/HubEvents/AuthHubEventHandler.swift
Implement logic to send out hub events when the following event happens: User signedIn, user signedOut or when signedIn session expired. Developers can listen to these events through hub = 
```swift
Amplify.Hub.listen(to: .auth) { (payload) in
switch payload.eventName {
case HubPayload.EventName.Auth.signedIn:
print("User signed In, update UI")
case HubPayload.EventName.Auth.signedOut:
print("User signed Out, update UI")
case HubPayload.EventName.Auth.sessionExpired:
print("Session expired, show sign in aui")
default:
break
}
}
```
=> feat(Auth): Hub events for signedIn signedOut and sessionExpire

Amplify.xcodeproj/project.pbxproj, Amplify/Categories/DataStore/Query/ModelKey.swift, Amplify/Categories/DataStore/Query/QueryField.swift, AmplifyPlugins/Core/AWSPluginsCore/Model/Support/Model+GraphQL.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLDocument/GraphQLCreateMutationTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLDocument/GraphQLDeleteMutationTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLDocument/GraphQLGetQueryTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLDocument/GraphQLListQueryTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLDocument/GraphQLSubscriptionTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLDocument/GraphQLSyncQueryTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLDocument/GraphQLUpdateMutationTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLRequest/GraphQLRequestAnyModelWithSyncTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Core/SQLStatementTests.swift, AmplifyTestCommon/Models/Post+Schema.swift, AmplifyTestCommon/Models/Post.swift, AmplifyTestCommon/Models/PostStatus.swift, AmplifyTestCommon/Models/schema.graphql
**Notes:**
- add support for `EnumPersistable` on `QueryPredicate`
- fix enum conversion on `GraphQLInput`
- add more tests around enum values
=> fix: enum fixes for query predicates and graphql input

Amplify/Categories/Auth/AuthCategory+ClientBehavior.swift, Amplify/Categories/Auth/AuthCategory+DeviceBehavior.swift, Amplify/Categories/Auth/AuthCategoryBehavior.swift, Amplify/Categories/Auth/AuthCategoryDeviceBehavior.swift, Amplify/Categories/Auth/Request/AuthForgetDeviceRequest.swift, Amplify/Categories/Predictions/Models/LanguageType.swift, AmplifyPlugins/Auth/AWSAuthPlugin.xcodeproj/project.pbxproj, AmplifyPlugins/Auth/AWSAuthPlugin/ClientBehavior/AWSAuthPlugin+ClientBehavior.swift, AmplifyPlugins/Auth/AWSAuthPlugin/ClientBehavior/AWSAuthPlugin+DeviceBehavior.swift, AmplifyPlugins/Auth/AWSAuthPluginIntegrationTests/AuthDeviceTests/AuthDeviceOperationTests.swift, AmplifyPlugins/Auth/AWSAuthPluginIntegrationTests/AuthSignUpTests/AuthSignUpTests.swift, AmplifyTestCommon/Mocks/MockAuthCategoryPlugin.swift
Issue - https://github.com/aws-amplify/amplify-ios/issues/424
- Renamed confirmSignUp, resendSignUpCode and forgetDevice apis
- Added basic integration test
- Removed build warnings
=> refactor(Auth): Renamed confirmSignUp, resendSignUpCode and forgetDevice apis

Amplify/Categories/DataStore/Model/Schema/AuthRule.swift, Amplify/Categories/DataStore/Model/Schema/Model+Schema.swift, AmplifyPlugins/Core/AWSPluginsCore/Model/Support/AuthRule+Extension.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/Decorator/AuthRuleDecorator/ModelMultipleOwnerAuthRuleTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/Decorator/AuthRuleDecorator/ModelWithOwnerFieldAuthRuleTests.swift, AmplifyTestCommon/Models/Blog+Schema.swift
- this removes `provider` as that is not needed in the schema, only the API needs to configured with the correct provider at provisioning time.
- moves CodingKey to a String, for the case where developer does not provide an owner field in the model, we need to pass the default values over to the schema (less logic stored in the library), allows CLI to be source of truth for default values.
=> feat: AuthRule alignment with codegen

Amplify/Categories/Auth/Request/AuthSignOutRequest.swift, AmplifyPlugins/Auth/AWSAuthPlugin/Dependency/AuthenticationProviderAdapter+SignOut.swift, AmplifyPlugins/Auth/AWSAuthPlugin/Service/AWSMobileClient/AWSMobileClientAdapter.swift, AmplifyPlugins/Auth/AWSAuthPlugin/Service/AWSMobileClient/AWSMobileClientBehavior.swift
Description:
- Made local signOut as the default behavior
- Added an option to signOutRequest for globalSignOut
- If global signOut fails with notAuthorized error, we do a localSignOut, since it is not a recoverable error.
```swift
// Global signout
let options = AuthSignOutRequest.Options(globalSignOut: true)
Amplify.Auth.signOut(options: options) { (event) in
switch event {
case .failure(let error):
print(error)
case .success:
print("success")
}
}
// Local signOut
Amplify.Auth.signOut { (event) in
switch event {
case .failure(let error):
print(error)
case .success:
print("success")
}
}
```
*Issue #456 
=> fix(Auth): Locally signOut the user if globaly signout fail with notAuthorized

Amplify/Categories/Auth/Operation/AuthSocialWebUISignInOperation.swift, AmplifyPlugins/Auth/AWSAuthPlugin.xcodeproj/project.pbxproj, AmplifyPlugins/Auth/AWSAuthPlugin/Dependency/AuthenticationProviderAdapter+SignOut.swift, AmplifyPlugins/Auth/AWSAuthPlugin/HubEvents/AuthHubEventHandler.swift, AmplifyPlugins/Auth/AWSAuthPlugin/Operations/AWSAuthSocialWebUISignInOperation.swift, AmplifyPlugins/Auth/AWSAuthPluginTests/HubEventTests/AuthHubEventHandlerTests.swift
- Fix for hub event not being fired for successful signIn in webUi and social provider signIn
- Fixed typo for webUI event
- Added Unit tests
=> fix(Auth): Hub event for successful signIn for webUI signIn

AmplifyPlugins/API/AWSAPICategoryPluginIntegrationTests/GraphQL/GraphQLWithUserPoolIntegrationTests/AuthDirective/GraphQLAuthDirectiveIntegrationTests+Support.swift, AmplifyPlugins/API/AWSAPICategoryPluginIntegrationTests/GraphQL/GraphQLWithUserPoolIntegrationTests/AuthDirective/SocialNote.swift
This uses the code generated SoocialNote from `amplify codegen models` on @yuth dev branch
- Reordered the ownerField with identityClaim due to contrsuctor for rule has a different ordering of parameters
=> feat(api): (Integ) SocialNote from codegen

.circleci/config.yml, .gitignore, AWSPluginsCore.podspec, AWSPredictionsPlugin.podspec, Amplify.podspec, Amplify/Info.plist, AmplifyFunctionalTests/Info.plist, AmplifyPlugins.podspec, AmplifyPlugins/API/AWSAPICategoryPlugin/Info.plist, AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/Resources/Info.plist, AmplifyPlugins/Analytics/Podfile, AmplifyPlugins/Auth/Podfile, AmplifyPlugins/Core/AWSPluginsCore/Info.plist, AmplifyPlugins/Core/AWSPluginsCore/ServiceConfiguration/AmplifyAWSServiceConfiguration.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Info.plist, AmplifyPlugins/Core/AWSPluginsTestCommon/Info.plist, AmplifyPlugins/Predictions/AWSPredictionsPlugin/Resources/Info.plist, AmplifyPlugins/Predictions/CoreMLPredictionsPlugin/Resources/Info.plist, AmplifyPlugins/Storage/AWSS3StoragePlugin/Resources/Info.plist, AmplifyPlugins/Storage/Podfile, AmplifyTestApp/Info.plist, AmplifyTestCommon.podspec, AmplifyTestCommon/Info.plist, AmplifyTests/Info.plist, CHANGELOG.md, CircleciScripts/setup_private_specs.sh, CoreMLPredictionsPlugin.podspec, Podfile
- ci: Enable local lib linting of monorepo
- chore: Bump release to 1.0.0-rc.1
- chore: Update minimum SDK Dependency to 2.13.4
- chore: Podfile cleanup
- chore: Remove unnecessary requires_arc build setting
The newly-added `CircleciScripts/setup_private_specs.sh` script also makes it easier to do app development against unreleased code. We'll add something to the README later. Someday we'll do nightly builds and it won't really be necessary to jump through these hoops for app development with bleeding-edge versions.
The `setup_private_specs.sh` script also makes it possible to lint the pods before the release. It modifies the specs in the private repo so dependencies resolve correctly, but the base file itself is linted directly from the local git working …
=> chore: 1.0.0-rc.1 release prep

AmplifyPlugins/Auth/AWSCognitoAuthPlugin.xcodeproj/project.pbxproj, AmplifyPlugins/Auth/AWSCognitoAuthPlugin.xcodeproj/xcshareddata/xcschemes/AWSCognitoAuthPluginIntegrationTests.xcscheme, AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Operations/AWSAuthConfirmSignUpOperation.swift, AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Operations/AWSAuthResendSignUpCodeOperation.swift, AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Operations/AWSAuthSignInOperation.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/AWSAuthBaseTest.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/AuthSignInTests/AuthUsernamePasswordSignInTests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/AuthSignUpTests/AuthConfirmSignUpTests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/AuthSignUpTests/AuthResendSignUpCodeTests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/AuthSignUpTests/AuthSignUpTests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/AuthUserTests/AuthUserTests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/README.md, AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/Resources/Info.plist, AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/Support/AuthSignInHelper.swift, AmplifyPlugins/Auth/HostApp/Resources/Info.plist
- Added basic integration test for signIn, signUp and session apis
- Fixed operation that does not cancel when cancel is called
- Changed the integration test target from UITest to UnitTest so that keychain access works correctly.
=> test: Auth integration test for signUp, signIn

fastlane/Fastfile
The Fastfile specified a hardcoded Swift version that a) didn't correspond to any swift versions recognized as options by the Swift compiler, and b) conflicted with the swift version specified in our podspec files. Removing that Fastfile version lets podspec linting use the value from the Podspec file instead of the overridden value from the Fastfile
=> ci: Remove swift_version from Fastfile

Amplify/Categories/DataStore/DataStoreCategory+Behavior.swift, Amplify/Categories/DataStore/DataStoreCategoryBehavior.swift, Amplify/Categories/DataStore/Model/Collection/List+LazyLoad.swift, Amplify/Core/Category/CategoryType.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLDocument/GraphQLCreateMutationTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLDocument/GraphQLDeleteMutationTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLDocument/GraphQLUpdateMutationTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLRequest/GraphQLRequestAnyModelWithSyncTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLRequest/GraphQLRequestAuthRuleTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLRequest/GraphQLRequestModelTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/Support/QueryPredicateGraphQLTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/AWSDataStorePlugin+DataStoreBaseBehavior.swift, AmplifyTestCommon/Mocks/MockDataStoreCategoryPlugin.swift, AmplifyTestCommon/Models/Blog.swift, Podfile.lock, Pods/Manifest.lock
*Issue #, if available:* #487 
Change the QueryPredicate from a `() -> QueryPredicate` to `QueryPredicate?`:
```swift
// before
Amplify.DataStore.query(Todo.self, where: { Todo.keys.title.beingsWith("Amplify") })
// after
Amplify.DataStore.query(Todo.self, where: Todo.keys.title.beingsWith("Amplify"))
```
=> fix(datastore): query predicate API and integration tests fixes #487

AWSPluginsCore.podspec, AWSPredictionsPlugin.podspec, Amplify.podspec, Amplify/Info.plist, AmplifyFunctionalTests/Info.plist, AmplifyPlugins.podspec, AmplifyPlugins/API/AWSAPICategoryPlugin/Info.plist, AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/Resources/Info.plist, AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Resources/Info.plist, AmplifyPlugins/Core/AWSPluginsCore/Info.plist, AmplifyPlugins/Core/AWSPluginsCore/ServiceConfiguration/AmplifyAWSServiceConfiguration.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Info.plist, AmplifyPlugins/Core/AWSPluginsTestCommon/Info.plist, AmplifyPlugins/Predictions/AWSPredictionsPlugin/Resources/Info.plist, AmplifyPlugins/Predictions/CoreMLPredictionsPlugin/Resources/Info.plist, AmplifyPlugins/Storage/AWSS3StoragePlugin/Resources/Info.plist, AmplifyTestApp/Info.plist, AmplifyTestCommon.podspec, AmplifyTestCommon/Info.plist, AmplifyTests/Info.plist, CHANGELOG.md, CoreMLPredictionsPlugin.podspec
=> chore(release): Prep for 1.0.0 release

AmplifyPlugins/Auth/AWSCognitoAuthPlugin.xcodeproj/project.pbxproj, AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Support/Utils/AuthErrorHelper.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/AuthSessionTests/SignedInAuthSessionTests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/AuthSignOutTests/AuthSignOutTests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/AuthSignUpTests/AuthConfirmSignUpTests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/README.md, AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/Support/AuthSessionHelper.swift
=> test(Auth): Integration test related to apis for session, signOut

Amplify.podspec, CHANGELOG.md
Addressing issue filed here:
https://github.com/aws-amplify/amplify-ios/issues/492
=> fix(tools): run amplify tools with space in project folder

AmplifyPlugins/Core/AWSPluginsCore/Model/Support/QueryPredicate+GraphQL.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/Support/QueryPredicateGraphQLTests.swift
Amplify GraphQL Predicates should support all Temporal types, but only Date was previously supported. This change also reformats the `graphQLValue` to use a more Swifty `switch` statement instead of multiple if/thens.
Note: The assertions in the new unit tests aren't terribly meaningful, but by exercising the code, we can ensure we won't hit a precondition failure due to an unsupported type.
=> fix(DataStore): Support all Temporal types in predicates

AmplifyTools/amplify-tools.sh
In attempts of addressing:
https://github.com/aws-amplify/amplify-ios/issues/502
If customers have an older version of amplify-app installed on their machines, we will exec the command:
```
npx amplify-app@latest
```
Otherwise, we will execute:
```
npx amplify-app
```
Forcing latest did not seem like the right thing to do.  Also, when running npx, there isn't a good way of status-ing where the command (amplify-app) is being pulled from ( a local repo, or... online. etc..)
In addition to checking the version of `amplify-app`, I extended this to check the version of amplify-cli per the request of @drochetti.  We will fail a build if customers do not have a minimum version required for `amplify-cli`.  Upon failing a build, they will be greeted with this message in Xcode:
Fully open to …
=> fix(tools): require min version or use @latest

AWSPluginsCore.podspec, AWSPredictionsPlugin.podspec, Amplify.podspec, Amplify.xcodeproj/project.pbxproj, AmplifyPlugins.podspec, AmplifyPlugins/Auth/AWSCognitoAuthPlugin.xcodeproj/project.pbxproj, AmplifyPlugins/DataStore/DataStoreCategoryPlugin.xcodeproj/project.pbxproj, AmplifyTestCommon.podspec, CHANGELOG.md, CircleciScripts/setup_private_specs.sh, CoreMLPredictionsPlugin.podspec, Podfile, Podfile.lock, Pods/Manifest.lock
Although the AWSCore dependency is transitively included by many of the plugin
pods, the Xcode initial index doesn't appear to pick it up on a fresh
installation. This causes the build to fail until the user issues a "Clean
Build Folder", then rebuilds. This change adds explicit dependencies on AWSCore
throughout, and AWSAuthCore as needed, to ensure that consuming projects can
continue to specify only the "Amplify" and "AmplifyPlugin/<plugin name>" pods
in their own projects.
In addition, this change includes some cleanup items:
- chore: Normalize version declarations across podspecs
- chore: Update bundled pod dependencies
- chore: Reorder Header build phases to come before Compile Sources
- chore: Update packaged pod dependencies to latest versions
- chore: Remove redundant pod from …
=> fix(core): Add explicit AWSCore dependency to fix errors during initial build

Amplify.xcodeproj/project.pbxproj, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLRequest/GraphQLRequestAuthRuleTests.swift, AmplifyTestCommon/Models/Article+Schema.swift, AmplifyTestCommon/Models/Article.swift, AmplifyTestCommon/Models/schema.graphql
This removes Blog with auth rules and changes the name of the model to Article
=> Replace Blog with Article

Amplify.xcodeproj/project.pbxproj, AmplifyPlugins/Core/AWSPluginsCore/Model/Support/SelectionSet.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLRequest/GraphQLRequestOptionalAssociationTests.swift, AmplifyTestCommon/Models/AmplifyModels.swift, AmplifyTestCommon/Models/User+Schema.swift, AmplifyTestCommon/Models/User.swift, AmplifyTestCommon/Models/UserFollowers+Schema.swift, AmplifyTestCommon/Models/UserFollowers.swift, AmplifyTestCommon/Models/UserFollowing+Schema.swift, AmplifyTestCommon/Models/UserFollowing.swift, AmplifyTestCommon/Models/schema.graphql
https://github.com/aws-amplify/amplify-ios/issues/483
This PR fixes a problem with the selection set that is generated for a Model containing a connection to another Model. Take this for example
```
type Post @model {
user: User @connection
}
```
translates to "A Post has an optional association to the User"
`.belongsTo(post.user, is: .optional, ofType: User.self, targetName: "postUserId"),`
The original code checked for required associations
```
let isRequiredAssociation = field.isRequired && field.isAssociationOwner
if isRequiredAssociation, let associatedModel = field.associatedModel {
```
Consider a case where we retrieve the Post and the User does not exist on the Post. The selection set's intent is to retrieve that data in the …
=> fix(api): incorrect selection set for optional associated field

.jazzy.yaml
Invoking Jazzy with `jazzy --config .jazzy.yaml --module Amplify --podspec Amplify.podspec --output docs` will cause Jazzy to pick up the module version from the podspec file, so there is no need to specify it in the config.
=> chore: Remove hardcoded version from .jazzy.yml

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/Statement+Model.swift, CHANGELOG.md
Fixed a *caca* that slipped through the cracks in the 1.0.1 release.
This will fix initialization of `List<M>` in 3+ level deep relationships.
---
=> fix(datastore): wrong keyPath in lazy list initialization

Amplify.xcodeproj/project.pbxproj, Amplify/Categories/DataStore/Model/Embedded.swift, Amplify/Categories/DataStore/Model/Schema/ModelField+Association.swift, Amplify/Categories/DataStore/Model/Schema/ModelSchema+Definition.swift, AmplifyPlugins/Core/AWSPluginsCore/Model/Decorator/ConflictResolutionDecorator.swift, AmplifyPlugins/Core/AWSPluginsCore/Model/Support/Model+GraphQL.swift, AmplifyPlugins/Core/AWSPluginsCore/Model/Support/SelectionSet.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/Decorator/AuthRuleDecorator/ModelMultipleOwnerAuthRuleTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLRequest/GraphQLRequestNonModelTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/Support/ModelGraphQLTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/ModelValueConverter+SQLite.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Models/ExampleWithEveryType+Schema.swift, AmplifyTestCommon/Models/NonModel/Category.swift, AmplifyTestCommon/Models/NonModel/Color.swift, AmplifyTestCommon/Models/NonModel/Section.swift, AmplifyTestCommon/Models/NonModel/Todo+Schema.swift, AmplifyTestCommon/Models/NonModel/Todo.swift
- This adds `Embbeded` protocol to return the schema information for embedded types. This means the code generated schema for an embedded type should look something like this:
```
class Category: Embedded {
...
}
extension Category {
public enum CodingKeys: CodingKey {
case name
case color
}
public static let keys = CodingKeys.self
// store info about the field's name, nullability, and their types.
public static let schema = defineSchema { embedded in
let category = Category.keys
embedded.fields(.field(category.name, is: .required, ofType: .string),
.field(category.color, is: .required, ofType: .embedded(type: Color.self)))
}
}
```
- Also introduced a `.embeddedCollection` case to hold embbeded types which are arrays. This was required …
=> Add Embedded type to store schema info for custom types

AmplifyTools/amplify-tools.sh, CHANGELOG.md
*Issue #* #488 
*Description of changes:* When NVM is installed it needs to be manually initialized inside the Xcode script runtime, otherwise a different NodeJS will be used.
ps: also did some formatting on the file (actually VSCode did).
Diff excluding the formatting changes: https://github.com/aws-amplify/amplify-ios/pull/535/commits/0b4f9bc20fd06318334e2c0884b6493ee114145b
---
=> fix(tools): nvm support added so node is correctly resolved

CoreMLPredictionsPlugin.podspec
Add `$` in front of `AMPLIFY_VERSION` for CoreMLPredictionsPlugin.podspec
=> fix:Update CoreML podspec with amplify version

AWSPluginsCore.podspec, AWSPredictionsPlugin.podspec, Amplify.podspec, AmplifyPlugins.podspec, AmplifyPlugins/API/Podfile, AmplifyPlugins/Analytics/Podfile, AmplifyPlugins/Auth/Podfile, AmplifyPlugins/DataStore/Podfile, AmplifyPlugins/Predictions/Podfile, AmplifyPlugins/Storage/Podfile, AmplifyTestCommon.podspec, CoreMLPredictionsPlugin.podspec, Podfile, build-support/dependencies.rb
- Removed loading of the ruby script from PodSpec files. There were some unknown DSL errors when running `pod lib lint` as dependnecies aren't referencable by just including the file.
=> Fix pod lib lint error with Podspecs with local variables

fastlane/Fastfile
use `cocoapods` version defined in Gemfile, instead of the default in CCI's macOS executor
=> ci(fastlane): use bundle pod push

Gemfile.lock
issue with getting last tag correctly has been fixed in release_actions. Updating the version here
=> ci: update to latest release_actions

AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Dependency/AuthorizationProviderAdapter+SignedInSession.swift, AmplifyPlugins/Auth/Podfile.lock
Amplify can be used with only Cognito User Pool configured. With the configuration structure shown below. In this case while calling the api `fetchAuthSession` the returned result doesnot provide the right values for usersub and cognito tokens. This PR fixes this behavior.
```
{
"UserAgent": "aws-amplify-cli/2.0",
"Version": "1.0",
"auth": {
"plugins": {
"awsCognitoAuthPlugin": {
"UserAgent": "aws-amplify/cli",
"Version": "0.1.0",
"IdentityManager": {
"Default": {}
},
"CognitoUserPool": {
"Default": {
"PoolId": "xx",
"AppClientId": "xx",
"AppClientSecret": "xx",
"Region": "xx"
}
},
"Auth": {
"Default": {
"OAuth": {
...
},
"authenticationFlowType": "USER_SRP_AUTH"
}
}
}
}
}
}
```
By submitting this pull request, I confirm that my contribution is made under the …
=> fix(auth): User pool token, user sub should be returned for signedIn user with no identityPool config

AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Dependency/AuthenticationProviderAdapter+SignIn.swift
*Issue :*  https://github.com/aws-amplify/amplify-ios/issues/569, https://github.com/aws-amplify/amplify-ios/issues/623
Amplify.Auth.signInWithWebUI was not presenting properly if there is already a view controller presented. This change will try to figure out the top presenting view controller and then present the sign in UI over it.
=> fix(auth): Fix an issue that prevents signInWithWebUI to present over a presenting vc

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/StorageEngineAdapter+SQLite.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginIntegrationTests/DataStoreLocalStoreTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginIntegrationTests/TestSupport/LocalStoreIntegrationTestBase.swift, AmplifyPlugins/DataStore/DataStoreCategoryPlugin.xcodeproj/project.pbxproj
- Added missing parameter `paginationInput` so that can be called
- Added an integration test to verify if the `paginationInput ` is actually being called.
Issue: https://github.com/aws-amplify/amplify-ios/issues/646
=> fix(Datastore): paginationInput not passed down in query

Amplify/Categories/API/Internal/APICategory+CategoryConfigurable.swift, Amplify/Categories/Analytics/Internal/AnalyticsCategory+CategoryConfigurable.swift, Amplify/Categories/Auth/Internal/AuthCategory+CategoryConfigurable.swift, Amplify/Categories/DataStore/Internal/DataStoreCategory+Configurable.swift, Amplify/Categories/Hub/Internal/HubCategory+CategoryConfigurable.swift, Amplify/Categories/Logging/Internal/LoggingCategory+CategoryConfigurable.swift, Amplify/Categories/Predictions/Internal/PredictionsCategory+CategoryConfigurable.swift, Amplify/Categories/Storage/Internal/StorageCategory+CategoryConfigurable.swift, Amplify/Core/Configuration/AmplifyConfiguration.swift, Amplify/Core/Configuration/Internal/CategoryConfigurable.swift, AmplifyPlugins/API/AWSAPICategoryPlugin/AWSAPIPlugin+Configure.swift, AmplifyPlugins/API/AWSAPICategoryPluginTests/AWSAPICategoryPlugin+ConfigureTests.swift, AmplifyPlugins/API/Podfile.lock, AmplifyPlugins/Analytics/AWSPinpointAnalyticsPluginTests/AWSPinpointAnalyticsPluginConfigureTests.swift, AmplifyPlugins/Analytics/Podfile.lock, AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Dependency/AuthenticationProviderAdapter+SignIn.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AWSCognitoAuthPluginConfigTests.swift, AmplifyPlugins/Auth/Podfile.lock, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Core/ConfigurationTests.swift, AmplifyPlugins/DataStore/DataStoreCategoryPlugin.xcodeproj/project.pbxproj, AmplifyPlugins/DataStore/Podfile.lock, AmplifyPlugins/Predictions/AWSPredictionsPluginTests/ConfigurationTests/PredictionsPluginConfigurationTests.swift, AmplifyPlugins/Predictions/Podfile.lock, AmplifyPlugins/Storage/AWSS3StoragePluginTests/AWSS3StoragePluginBaseConfigTests.swift, AmplifyPlugins/Storage/AWSS3StoragePluginTests/AWSS3StoragePluginConfigureTests.swift, AmplifyPlugins/Storage/Podfile.lock
*Issue https://github.com/aws-amplify/amplify-ios/issues/480*
This change allows to call configure method of each plugin with a nil value. ie even if the corresponding configuration is not present in the configuration file, plugin's configure will be called.
*Issue we are solving:*
Suppose that I added two plugins to my project `AWSAPIPlugin` and `AWSDataStorePlugin`, but forgot to add any configuration for API in my `amplifyconfiguration.json`. Since there is no configuration the current logic does not invoke the `configure(:)` function of `AWSAPIPlugin`. So we end up using a not-configured plugin and end up in unintended error or crash like this - https://github.com/aws-amplify/amplify-ios/issues/480
*Thought process behind this change:*
All category in Amplify …
=> fix: Plugins that are not configured correctly will be error at initial step

AmplifyPlugins/API/APICategoryPlugin.xcodeproj/project.pbxproj, AmplifyPlugins/API/AWSAPICategoryPlugin/Operation/AWSGraphQLSubscriptionOperation.swift, AmplifyPlugins/API/AWSAPICategoryPluginTests/AWSGraphQLSubscriptionOperationCancelTests.swift
The current AWSGraphQLSubscriptionOperation implementation does not handle cancellations correctly:
- It does not set the `isCancelled` advisory flag in all code paths
- It does not emit a completion for all code paths
This fix causes all code paths through `cancel` to both set the advisory flag and emit a completion to the result listener. Active subscriptions will also receive a "disconnected subscription" event, as before.
=> fix: Fix cancellation logic for AWSGraphQLSubscriptionOperation

AmplifyPlugins/Storage/AWSS3StoragePlugin/Service/Storage/AWSS3StorageService+DownloadBehavior.swift, AmplifyPlugins/Storage/AWSS3StoragePluginFunctionalTests/AWSS3StoragePluginAccessLevelTests.swift, AmplifyPlugins/Storage/AWSS3StoragePluginFunctionalTests/AWSS3StoragePluginNegativeTests.swift
https://github.com/aws-amplify/amplify-ios/issues/285
When downloading to file using TransferUtility, and the key cannot be found in S3, the file is populated with the error message from the response. This ensures that the behavior is, when key is not found, the file is removed so there isn't incorrect data like the error message
=> fix(storage): delete file if key not found on download

AmplifyPlugins/Auth/AWSCognitoAuthPlugin.xcodeproj/project.pbxproj, AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Models/Options/AWSAuthConfirmResetPasswordOptions.swift, AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Models/Options/AWSAuthConfirmSignInOptions.swift, AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Models/Options/AWSAuthConfirmSignUpOptions.swift, AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Models/Options/AWSAuthResetPasswordOptions.swift, AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Models/Options/AWSAuthSignInOptions.swift, AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Models/Options/AWSAuthSignUpOptions.swift, AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Models/Options/AWSAuthWebUISignInOptions.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/AuthSignInTests/AuthUsernamePasswordSignInTests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/AuthSignUpTests/AuthConfirmSignUpTests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/AuthSignUpTests/AuthSignUpTests.swift
Bug fix according to issue: https://github.com/aws-amplify/amplify-ios/issues/654
- Added initializers for `AWSAuthConfirmResetPasswordOptions`, `AWSAuthConfirmSignInOptions`, `AWSAuthConfirmSignUpOptions`, `AWSAuthResetPasswordOptions`, `AWSAuthSignInOptions`, `AWSAuthSignUpOptions` and `AWSAuthWebUISignInOptions`
- Added integration tests for `AWSAuthSignInOptions ` and `AWSAuthSignUpOptions` 
=> fix(auth): missing initializers for AWSAuth*Options

AmplifyPlugins/API/Podfile.lock, AmplifyPlugins/Analytics/Podfile.lock, AmplifyPlugins/Auth/Podfile.lock, AmplifyPlugins/DataStore/Podfile.lock, AmplifyPlugins/Predictions/Podfile.lock, AmplifyPlugins/Storage/Podfile.lock, Podfile.lock
Update SDK dependencies including AppSyncRealTimeClient to address https://github.com/aws-amplify/amplify-ios/issues/677.
=> chore: Update SDK dependencies

AmplifyPlugins/API/Podfile.lock, AmplifyPlugins/Analytics/Podfile.lock, AmplifyPlugins/Auth/Podfile.lock, AmplifyPlugins/DataStore/Podfile.lock, AmplifyPlugins/Predictions/Podfile.lock, AmplifyPlugins/Storage/Podfile.lock, Podfile.lock, build-support/dependencies.rb
Pin to SwiftFormat 0.44.17 pending context-sensitive brace rules in SwiftLint
=> chore: Pin to SwiftFormat 0.44.17

AmplifyPlugins/API/Podfile.lock, AmplifyPlugins/Analytics/Podfile.lock, AmplifyPlugins/Auth/Podfile.lock, AmplifyPlugins/DataStore/Podfile.lock, AmplifyPlugins/Predictions/Podfile.lock, Podfile.lock
Most Podfile.lock's were updated to 2.15.1 from 2.15.0 except for Predictions from 2.13
=> chore: update SDK to 2.15.1

AmplifyPlugins/API/APICategoryPlugin.xcodeproj/project.pbxproj, AmplifyPlugins/API/AWSAPICategoryPluginIntegrationTests/GraphQL/GraphQLWithUserPoolIntegrationTests/AuthDirective/README.md, AmplifyPlugins/API/AWSAPICategoryPluginIntegrationTests/GraphQL/GraphQLWithUserPoolIntegrationTests/GraphQLWithUserPoolIntegrationTests.swift, AmplifyPlugins/API/AWSAPICategoryPluginIntegrationTests/REST/RESTWithUserPoolIntegrationTests/README.md, AmplifyPlugins/API/AWSAPICategoryPluginIntegrationTests/REST/RESTWithUserPoolIntegrationTests/RESTWithUserPoolIntegrationTests.swift, AmplifyPlugins/Core/AWSPluginsCore/Auth/AWSAuthService.swift
https://github.com/aws-amplify/amplify-ios/issues/618
This updates the Cognito User Pool interceptor to use the accessToken. Android and JS is using accessToken, while iOS was using idToken before. According to the [AWS docs](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-with-identity-providers.html), both can be passed to the service. 
=> fix(api): cognito user pool intercept with accessToken

Amplify/Categories/Predictions/Models/Table.swift, AmplifyPlugins/Predictions/AWSPredictionsPlugin/Support/Utils/IdentifyTextResultTransformers+Tables.swift, AmplifyPlugins/Predictions/AWSPredictionsPluginIntegrationTests/IdentifyBasicIntegrationTests.swift, CHANGELOG.md
Reference for this issue: https://github.com/aws-amplify/amplify-ios/issues/694
- Added `rowIndex` and `columnIndex` for `CELL` struct.
- Updated integration test `testIdentifyTextTables`
=> fix(Predictions): rowIndex and columnIndex for cell

fastlane/Fastfile
Get latest tags before inferring next version (to prevent race condition in simultaneously running pipelines)
=> ci(fastlane): fix retry logic and perform a git fetch before lane

AmplifyPlugins/Auth/AWSCognitoAuthPlugin.xcodeproj/project.pbxproj, AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Dependency/AuthUserServiceAdapter.swift, AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Dependency/AuthenticationProviderAdapter+SignIn.swift, AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Dependency/AuthenticationProviderAdapter+SignUp.swift, AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Models/Options/AWSAttributeResendConfirmationCodeOptions.swift, AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Models/Options/AWSAuthResendSignUpCodeOptions.swift, AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Models/Options/AWSResendAttributeConfirmationCodeOptions.swift, AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Models/Options/AWSUpdateUserAttributeOptions.swift, AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Models/Options/AWSUpdateUserAttributesOptions.swift, AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Service/AWSMobileClient/AWSMobileClientAdapter.swift, AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Service/AWSMobileClient/AWSMobileClientBehavior.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/AWSAuthBaseTest.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/AuthSignInTests/AuthUsernamePasswordSignInTests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/AuthSignUpTests/AuthSignUpTests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/AuthUserAttributesTests/AuthUserAttributesTests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/README.md, AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/Support/AuthConfigurationHelper.swift
This exposes a few new Options structs to pass metadata into certain API calls
APIs
- ResendSignUpCode (new) → requires another set up to integ test
- ResendAttributeConfirmationCode (new)
- test: testSuccessfulResendConfirmationCode
- flow: resendConfirmationCode → verifyUserAttribute -> AWSMobileClientUserDetails.verifyUserAttribute → getUserAttributeVerificationCode
- UpdateUserAttribute (new) / UpdateUserAttributes (new)
- test: testSuccessfulUpdateEmailAttribute
- flow:  update → updateUserAttributes -> AWSMobileClientUserDetails.updateUserAttributes → update(attributes)
- Sign up
- test: testRegisterUserWithSignUpOptions calls Cognito's Sign Up
- Sign In
- test: testSignInWithSignInOptions
- flow: Cognito …
=> feat(auth): Add metadata options for passing clientMetadata to APIs

Amplify/Categories/API/ClientBehavior/AmplifyAPICategory+GraphQLBehavior.swift, Amplify/Categories/API/ClientBehavior/AmplifyAPICategory+RESTBehavior.swift, Amplify/Categories/Auth/AuthCategory+ClientBehavior.swift, Amplify/Categories/Auth/AuthCategory+DeviceBehavior.swift, Amplify/Categories/Auth/AuthCategory+UserBehavior.swift, Amplify/Categories/Predictions/PredictionsCategory+ClientBehavior.swift, Amplify/Categories/Storage/StorageCategory+ClientBehavior.swift, AmplifyPlugins/API/AWSAPICategoryPluginTests/AWSAPICategoryPlugin+ConfigureTests.swift, AmplifyPlugins/Analytics/AWSPinpointAnalyticsPluginTests/AWSPinpointAnalyticsPluginConfigureTests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Dependency/AuthenticationProviderAdapter+SignOut.swift, AmplifyPlugins/Auth/AWSCognitoAuthPlugin/HubEvents/AuthHubEventHandler.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AWSCognitoAuthPluginConfigTests.swift, AmplifyPlugins/Storage/AWSS3StoragePluginTests/AWSS3StoragePluginConfigureTests.swift, AmplifyPlugins/Storage/AWSS3StoragePluginTests/Mocks/MockAWSS3StorageService.swift, Podfile.lock, README-combine-support.md
refs:#713
When this is released, merge https://github.com/aws-amplify/docs/pull/2246
=> fix: Propagate @discardableResult to implementations

AmplifyPlugins/Core/AWSPluginsCore/ServiceConfiguration/AmplifyAWSServiceConfiguration.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/ServiceConfiguration/AmplifyAWSServiceConfigurationTests.swift
Added ability to add platform information to the user agent. The user agent can now add in the following format:
```
<Platform-2-Name/Platform-2-Version> <Platform-1-Name/Platform-1-Version> amplify-iOS/xx.yy iOS/13.6 en_US
```
=> refactor(core): Add support for useragent to add platform info

CHANGELOG.md
Removed stray 'Unreleased' section from CHANGELOG, since CHANGELOG is automatically generated during our release CI/CD step.
=> chore: Remove stray 'Unreleased' section

.jazzy.yaml
By not specifying in the .jazzy.yaml file, Jazzy will pick up the version from
the module's Info.plist, which is updated as part of the version bump.
=> chore: Remove version from .jazzy config

Amplify/Categories/DataStore/Model/Collection/List+Model.swift, AmplifyPlugins/API/AWSAPICategoryPluginFunctionalTests/AnyModelIntegrationTests.swift, AmplifyPlugins/API/AWSAPICategoryPluginFunctionalTests/GraphQLModelBased/GraphQLModelBasedTests.swift, AmplifyPlugins/API/AWSAPICategoryPluginFunctionalTests/GraphQLSyncBased/GraphQLSyncBasedTests.swift
Models with 1-to-many connections contain a List, for example
```
public struct Post: Model {
public var comments: List<Comment>?
```
The post contains a list of comments. When constructing a Get Query for a Post, the Model-to-GraphQLRequest builders will only generate the first depth of a selection set since comments is not a required association. If the developer wants to retrieve the comments for that particular Post, The developer can create a custom selection set for the GetQuery containing nested selection set with the comments. 
```
query getPost($id: ID!) {
getPost(id: $id){
id
title
content
createdAt
updatedAt
draft
rating
status
comments {
items {
id
content
createdAt
updatedAt
post {
id
title
content
createdAt
updatedAt
draft …
```
=> feat(api): Adding custom 'items' deserialization for List

Amplify/Categories/DataStore/DataStoreStatement.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/SQLStatement+Condition.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/SQLStatement+CreateTable.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/SQLStatement+Delete.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/SQLStatement+Insert.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/SQLStatement+Select.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/SQLStatement+Update.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/SQLStatement.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/StorageEngineAdapter+SQLite.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/StorageEngineAdapter+UntypedModel.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Core/SQLStatementTests.swift, AmplifyPlugins/DataStore/DataStoreCategoryPlugin.xcodeproj/xcshareddata/xcschemes/AWSDataStoreCategoryPlugin.xcscheme
DatastoreStatement that communicate with the underlying storage doesnot need a dependency on Model.Type. This PR is part of the larger work on removing the dependency on the static properties of Model.Type from Datastore.
Instead of Model.Type DatastoreStatement will be using ModelSchema. The `Model.Type` property in `DatastoreStatement` is not used anywhere externally before this change. So make this change should not affect any public apis.
*Current usage of DatastoreStatement:*
`DatastoreStatement` protocol is currently only used as a parent protocol of [`SQLStatement`](https://github.com/aws-amplify/amplify-ios/blob/d88447789d26f042e26f70565a9283dc143a8b22/AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/SQLStatement.swift#L15). And …
=> refactor(datastore): Removed the dependency on Model.Type from DataStoreStatement

AmplifyPlugins/Core/AWSPluginsCore/Model/Support/Model+GraphQL.swift
https://github.com/aws-amplify/amplify-ios/issues/748
This is a minor refactoring of the code as a workaround discovered in https://github.com/aws-amplify/amplify-ios/issues/748 by moving the default operator usage outside the guard statement. This would enable developers to build apps that use the APIPlugin with the Model-to-GraphQLRequest builders on Swift 5.3 while we continue to investigate the issue
=> fix: move default operator outside of guard statement

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/ReconcileAndLocalSave/AWSModelReconciliationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/ReconcileAndLocalSave/ReconcileAndLocalSaveOperation.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/ModelReconciliationQueueBehaviorTests.swift
Pushing this out, prior to being ready to push into mainline ( need to update the rest of the unit tests), becuase there is a slight difference from the suggested approach listed here:
https://github.com/aws-amplify/amplify-ios/issues/755
=> fix(DataStore): model reconciliation queue publisher

Amplify/Categories/DataStore/Model/Internal/ModelRegistry.swift, Amplify/Categories/DataStore/Model/Internal/Schema/ModelSchema.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/AWSDataStorePlugin.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/ModelStorageBehavior.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/Model+SQLite.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/StorageEngineAdapter+SQLite.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/StorageEngine.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/APICategoryDependencyTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/InitialSync/InitialSyncOperationTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/LocalSubscriptionTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/MutationQueue/AWSMutationEventIngesterTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/RemoteSync/RemoteSyncAPIInvocationTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/Support/MockSQLiteStorageEngineAdapter.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/TestSupport/BaseDataStoreTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/TestSupport/SyncEngineTestBase.swift, AmplifyPlugins/DataStore/Podfile.lock
During configuration of datastore storage we pass a list of Model.Type to setup the storage. This is not required and can be replaced with a list of ModelSchema. This PR is part of the larger work on removing the dependency on the static properties of Model.Type from Datastore.
*Previous PRs:*
Removed the dependency on Model.Type from DataStoreStatement - https://github.com/aws-amplify/amplify-ios/pull/718
=> refactor(datastore): Removed dependency of Model.Type in setup

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/AWSDataStorePlugin+DataStoreBaseBehavior.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/StorageEngineAdapter+SQLite.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/StorageEngineAdapter+UntypedModel.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/StorageEngine.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/StorageEngineAdapter.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Core/SQLiteStorageEngineAdapterTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/Support/MockSQLiteStorageEngineAdapter.swift
Changed `StorageEngineAdapter.exists` api to accept ModelSchema instead of Model.Type. This PR is part of the larger work on removing the dependency on the static properties of Model.Type from Datastore.
Previous PRs:
Removed dependency of Model.Type in setup (#734)
Removed the dependency on Model.Type from DataStoreStatement - #718
=> refactor(datastore): Changed StorageEngineAdapter.exists api to accept ModelSchema instead of Model.Type

Amplify/Categories/DataStore/DataStoreCategory+HubPayloadEventName.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/Events/OutboxMutationEvent.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/OutgoingMutationQueue/OutgoingMutationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginIntegrationTests/DataStoreHubEventsTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginIntegrationTests/README.md, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/MutationQueue/OutgoingMutationQueueTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/MutationQueue/OutgoingMutationQueueTestsWithMockStateMachine.swift, AmplifyPlugins/DataStore/DataStoreCategoryPlugin.xcodeproj/project.pbxproj, AmplifyTestCommon/Mocks/MockAPICategoryPlugin.swift
In this PR, I will implement:
- outboxMutationEnqueued
- outboxMutationProcessed
```swift
{
"model": "Note",
"element": {
"id": "d98f54ff-53dd-44d0-b99f-562e8f58ae3c",
"content": "I am some content",
"_version": 1,
"_lastChangedAt": 1594938571692,
"_deleted": null
}
}
// iOS equivalent
struct OutboxMutationEvent {
let modelName: String
let element: OutboxMutationEventElement
}
struct OutboxMutationEventElement {
let model: Model
let version: Int?
let lastChangedAt: Int?
let deleted: Bool?
}
```
=> feat(datastore): Dispatch outboxMutationEnqueued, outboxMutationProcessed events

Amplify/Categories/DataStore/DataStoreStatement.swift, Amplify/Categories/DataStore/Model/Internal/ModelRegistry.swift, Amplify/Categories/DataStore/Model/Internal/Schema/ModelField+Association.swift, Amplify/Categories/DataStore/Model/Internal/Schema/ModelSchema+Definition.swift, AmplifyPlugins/Core/AWSPluginsCore/Model/Support/SelectionSet.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/Model+SQLite.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/SQLStatement+CreateTable.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/SQLStatement+Select.swift
Removes dependency on Model.Type in registration of models. This PR is part of the larger work on removing the dependency on the static properties of Model.Type from Datastore.
Previous PRs:
Changed StorageEngineAdapter.exists api to accept ModelSchema instead of Model.Type (#736)
Removed dependency of Model.Type in setup (#734)
Removed the dependency on Model.Type from DataStoreStatement - #718
=> refactor(datastore): Remove dependency on Model.Type from registration

Amplify/Categories/API/Operation/AmplifyOperation+APIPublishers.swift, Amplify/Categories/Auth/Operation/AmplifyOperation+AuthPublishers.swift, Amplify/Categories/Predictions/Operation/AmplifyOperation+PredictionsPublishers.swift, Amplify/Categories/Storage/Operation/Operation+StoragePublishers.swift
Prevents errors for customers compiling with Swift toolchains < 5.2
refs:
- #717
- #740
- #744
This fixes compilation errors on my local installation of Xcode 11.3.1.
=> fix: Add #if swift check for Combine publishers

Amplify.xcodeproj/project.pbxproj, Amplify/Categories/DataStore/DataStoreStatement.swift, Amplify/Categories/DataStore/Model/Internal/Model+Subscript.swift, Amplify/Categories/DataStore/Model/Internal/ModelRegistry.swift, Amplify/Categories/DataStore/Model/Internal/Schema/ModelSchema.swift, Amplify/Categories/DataStore/Model/JSONHelper/JSONValueHolder.swift, Amplify/Categories/DataStore/Model/Model.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/ModelStorageBehavior.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/Model+SQLite.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/SQLStatement+Insert.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/SQLStatement+Update.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/StorageEngineAdapter+SQLite.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/StorageEngineAdapter+UntypedModel.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/StorageEngine.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/StorageEngineAdapter.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Core/SQLiteStorageEngineAdapterJsonTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Core/SQLiteStorageEngineAdapterTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Core/SortByDependencyOrderTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Models/DynamicModel.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Models/SQLModelValueConverterTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/Support/MockSQLiteStorageEngineAdapter.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/TestSupport/Mocks/TestModelRegistration.swift, AmplifyPlugins/DataStore/DataStoreCategoryPlugin.xcodeproj/project.pbxproj, AmplifyPlugins/DataStore/Podfile.lock, AmplifyTestCommon/Mocks/MockAPICategoryPlugin.swift, AmplifyTests/CategoryTests/DataStore/JSONValueHolderTest.swift, Podfile.lock
Removes the dependency on model type in the StorageEngine apis `save` and `query`. Added a new protocol called `JSONValueHolder`, the concrete implementation of this protocol will holds the internal data in a json format. `JSONValueHolder.jsonValue(for:)` can be used to get the value for a particular key inside the json map. 
For example developer can create the following struct using the `JSONValueHolder`.
```swift
struct DynamicModel: JSONValueHolder {
let values: [String: JSONValue]
func jsonValue(for key: String) -> Any?? {
switch values[key] {
case .some(.array(let deserializedValue)):
return deserializedValue
case .some(.boolean(let deserializedValue)):
return deserializedValue
case .some(.number(let deserializedValue)):
return deserializedValue
case …
```
=> refactor(datastore): Remove the dependency of model type save and query in StorageEngine

.circleci/config.yml
https://github.com/aws-amplify/amplify-ios/issues/782
=> fix: Remove enableThreadSanitizer flag from test invocation

Amplify.xcodeproj/project.pbxproj, Amplify/Categories/DataStore/Model/Internal/ModelRegistry+Syncable.swift, Amplify/Categories/DataStore/Model/Internal/ModelRegistry.swift, Amplify/Categories/DataStore/Model/JSONHelper/JSONValueHolder.swift, AmplifyPlugins/Core/AWSPluginsCore/Model/Decorator/AuthRuleDecorator.swift, AmplifyPlugins/Core/AWSPluginsCore/Model/Decorator/ConflictResolutionDecorator.swift, AmplifyPlugins/Core/AWSPluginsCore/Model/Decorator/DirectiveNameDecorator.swift, AmplifyPlugins/Core/AWSPluginsCore/Model/Decorator/FilterDecorator.swift, AmplifyPlugins/Core/AWSPluginsCore/Model/Decorator/ModelBasedGraphQLDocumentDecorator.swift, AmplifyPlugins/Core/AWSPluginsCore/Model/Decorator/ModelDecorator.swift, AmplifyPlugins/Core/AWSPluginsCore/Model/Decorator/ModelIdDecorator.swift, AmplifyPlugins/Core/AWSPluginsCore/Model/Decorator/PaginationDecorator.swift, AmplifyPlugins/Core/AWSPluginsCore/Model/GraphQLDocument/ModelBasedGraphQLDocumentBuilder.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/AWSDataStorePlugin+DataStoreBaseBehavior.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/ModelStorageBehavior.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/StorageEngineAdapter+SQLite.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/StorageEngine.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/StorageEngineAdapter.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/AWSMutationDatabaseAdapter/AWSMutationDatabaseAdapter+MutationEventIngester.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/OutgoingMutationQueue/ProcessMutationErrorFromCloudOperation.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/ReconcileAndLocalSave/ReconcileAndLocalSaveOperation.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Core/SQLiteStorageEngineAdapterJsonTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Core/SQLiteStorageEngineAdapterTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/Support/MockSQLiteStorageEngineAdapter.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/TestSupport/Mocks/TestModelRegistration.swift
*Description of changes:* Removes the modelType from model decorator. This is part of the larger work on removing dependency on Model.Type in Datastore.
=> refactor(datastore): Remove dependency on ModelType from ModelDecorator

Amplify.xcodeproj/xcshareddata/xcschemes/AWSPluginsCore.xcscheme, AmplifyPlugins/API/APICategoryPlugin.xcodeproj/xcshareddata/xcschemes/AWSAPICategoryPlugin.xcscheme, AmplifyPlugins/API/APICategoryPlugin.xcodeproj/xcshareddata/xcschemes/GraphQLWithIAMIntegrationTests.xcscheme, AmplifyPlugins/API/APICategoryPlugin.xcodeproj/xcshareddata/xcschemes/GraphQLWithUserPoolIntegrationTests.xcscheme, AmplifyPlugins/API/APICategoryPlugin.xcodeproj/xcshareddata/xcschemes/RESTWithIAMIntegrationTests.xcscheme, AmplifyPlugins/API/APICategoryPlugin.xcodeproj/xcshareddata/xcschemes/RESTWithUserPoolIntegrationTests.xcscheme, AmplifyPlugins/Auth/AWSCognitoAuthPlugin.xcodeproj/xcshareddata/xcschemes/AWSCognitoAuthPlugin.xcscheme, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/ReconcileAndLocalSave/AWSModelReconciliationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/TestSupport/Mocks/MockAWSIncomingEventReconciliationQueue.swift, AmplifyPlugins/DataStore/DataStoreCategoryPlugin.xcodeproj/xcshareddata/xcschemes/AWSDataStoreCategoryPlugin.xcscheme, AmplifyPlugins/Predictions/PredictionsCategoryPlugin.xcodeproj/xcshareddata/xcschemes/AWSPredictionsPlugin.xcscheme, AmplifyPlugins/Predictions/PredictionsCategoryPlugin.xcodeproj/xcshareddata/xcschemes/CoreMLPredictionsPlugin.xcscheme, AmplifyPlugins/Storage/StoragePlugin.xcodeproj/xcshareddata/xcschemes/AWSS3StoragePlugin.xcscheme, AmplifyTestCommon/Mocks/MessageReporter.swift, AmplifyTestCommon/Mocks/MockAPICategoryPlugin.swift
https://github.com/aws-amplify/amplify-ios/issues/773
- Wraps `reconcileAndLocalSaveOperationSinks` in an AtomicValue to protect from data races
- Fixes data races in test mocks
- Enable Thread Sanitizer throughout all tests
- Add code coverage for Storage plugin test
=> fix: Data race in AWSModelReconciliationQueue

AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/TestSupport/Mocks/MockStateMachine.swift
Fixes sporadic data races in MockStateMachine that [we are seeing](https://app.circleci.com/pipelines/github/aws-amplify/amplify-ios/1963/workflows/75662a04-24c0-4c24-a1c5-7d50e0dd862a/jobs/16663) now that we have enabled Thread Sanitizer:
```
==================
WARNING: ThreadSanitizer: Swift access race (pid=4622)
Modifying access of Swift variable at 0x7b18000459b8 by main thread:
#0 MockStateMachine.expectActionCriteriaQueue.modify <compiler-generated> (AWSDataStoreCategoryPluginTests:x86_64+0x1ec7bd)
#1 MockStateMachine.pushExpectActionCriteria(expectActionCriteria:) MockStateMachine.swift:26 (AWSDataStoreCategoryPluginTests:x86_64+0x1ed445)
#2 OutgoingMutationQueueMockStateTest.testRequestingEvent_subscriptionSetup() …
```
=> chore: Fix data race in MockStateMachine

Amplify/Categories/DataStore/Model/Internal/Schema/ModelSchema.swift, AmplifyPlugins/Core/AWSPluginsCore/Model/Decorator/ModelBasedGraphQLDocumentDecorator.swift, AmplifyPlugins/Core/AWSPluginsCore/Model/GraphQLDocument/GraphQLMutation.swift, AmplifyPlugins/Core/AWSPluginsCore/Model/GraphQLDocument/GraphQLQuery.swift, AmplifyPlugins/Core/AWSPluginsCore/Model/GraphQLDocument/GraphQLSubscription.swift, AmplifyPlugins/Core/AWSPluginsCore/Model/GraphQLDocument/ModelBasedGraphQLDocumentBuilder.swift, AmplifyPlugins/Core/AWSPluginsCore/Model/GraphQLRequest/GraphQLRequest+AnyModelWithSync.swift, AmplifyPlugins/Core/AWSPluginsCore/Model/GraphQLRequest/GraphQLRequest+Model.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/Decorator/AuthRuleDecorator/ModelMultipleOwnerAuthRuleTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/Decorator/AuthRuleDecorator/ModelReadUpdateAuthRuleTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/Decorator/AuthRuleDecorator/ModelWithOwnerFieldAuthRuleTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLDocument/GraphQLCreateMutationTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLDocument/GraphQLDeleteMutationTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLDocument/GraphQLGetQueryTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLDocument/GraphQLListQueryTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLDocument/GraphQLSubscriptionTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLDocument/GraphQLSyncQueryTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLDocument/GraphQLUpdateMutationTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLRequest/GraphQLRequestAnyModelWithSyncTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLRequest/GraphQLRequestAuthRuleTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLRequest/GraphQLRequestModelTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/InitialSync/InitialSyncOperation.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/IncomingAsyncSubscriptionEventPublisher.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/ModelReconciliationDeleteTests.swift
Removes the dependency of Model.Type in the graphql request builders. This is the continuation of the previous PR - #781
=> refactor(datastore): Removes Model.Type dependency from GraphlQLRequest

.circleci/config.yml
Adds steps to save build & test output to raw log files, and store them as CircleCI artifacts. Draft PR until I'm able to test the output on an actual run.
See artifacts uploaded for runs at https://app.circleci.com/pipelines/github/aws-amplify/amplify-ios/1979/workflows/6cdb8e1a-b441-488e-a149-0a306706126d
=> chore: Save build & test artifacts

Amplify/Categories/DataStore/Model/Internal/ModelRegistry.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/Model+SQLite.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/StorageEngineAdapter+SQLite.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/StorageEngineAdapter.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/InitialSync/InitialSyncOperation.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/InitialSync/InitialSyncOrchestrator.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngine.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/AWSIncomingEventReconciliationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/AWSIncomingSubscriptionEventPublisher.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/IncomingAsyncSubscriptionEventPublisher.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/ReconcileAndLocalSave/AWSModelReconciliationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/InitialSync/InitialSyncOperationTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/AWSIncomingEventReconciliationQueueTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/ModelReconciliationQueueBehaviorTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/Support/MockModelReconciliatinQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/Support/MockSQLiteStorageEngineAdapter.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/TestSupport/Mocks/MockAWSIncomingEventReconciliationQueue.swift
- Removed ModelType from the initial configuration of RemoteSyncEngine
- Removed unused sort function on modelType
- Updated test to reflect the changes
=> Removed ModelType from the initial configuration of RemoteSyncEngine

AmplifyPlugins/Core/AWSPluginsCore/Model/Decorator/AuthRuleDecorator.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/Decorator/AuthRuleDecorator/ModelMultipleOwnerAuthRuleTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/Decorator/AuthRuleDecorator/ModelReadUpdateAuthRuleTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLRequest/GraphQLRequestAuthRuleTests.swift
In attempts to fix:
https://github.com/aws-amplify/amplify-ios/issues/691
Corresponding android change:
https://github.com/aws-amplify/amplify-android/pull/807/files#diff-5a6612b4d7b74db7c28a89d55c63cd09
=> fix(DataStore): owner based auth, read operations

Amplify.xcodeproj/project.pbxproj, AmplifyPlugins/Core/AWSPluginsCore/Model/Decorator/AuthRuleDecorator.swift, AmplifyPlugins/Core/AWSPluginsCore/Model/GraphQLRequest/GraphQLRequest+AnyModelWithSync.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/Decorator/AuthRuleDecorator/ModelMultipleOwnerAuthRuleTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/Decorator/AuthRuleDecorator/ModelReadUpdateAuthRuleTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/Decorator/AuthRuleDecorator/ModelWithOwnerFieldAuthRuleTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLRequest/GraphQLRequestAuthIdentityClaimTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLRequest/GraphQLRequestAuthRuleTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLRequest/MockAWSAuthUser.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/IncomingAsyncSubscriptionEventPublisher.swift, AmplifyTestCommon/Models/ScenarioATest6Post+Schema.swift, AmplifyTestCommon/Models/ScenarioATest6Post.swift
In attempts to resolve:
https://github.com/aws-amplify/amplify-ios/issues/485
=> fix(Core): support identityClaim "sub"

Amplify/Categories/DataStore/Subscribe/MutationEvent.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/AWSDataStorePlugin+DataStoreBaseBehavior.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/StorageEngineAdapter+SQLite.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/StorageEngineAdapter+UntypedModel.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/StorageEngine.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/InitialSync/InitialSyncOperation.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/AWSIncomingEventReconciliationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/IncomingEventReconciliationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/MutationQueue/AWSMutationDatabaseAdapterTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/MutationQueue/OutgoingMutationQueueTestsWithMockStateMachine.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/MutationQueue/ProcessMutationErrorFromCloudOperationTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/MutationQueue/SyncMutationToCloudOperationTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/TestSupport/Mocks/MockAWSIncomingEventReconciliationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/TestSupport/Mocks/MockReconciliationQueue.swift
- Removed dependency of Model.Type in Initial sync. Uses `__typename` to figure out the model name for the untyped model in save
- Mutation event takes a modelSchema now to identity the modelName.
=> refactor(datastore): Removed dependency of Model.Type in Initial sync

fastlane/Pluginfile
Default branch of https://github.com/aws-amplify/amplify-ci-support is now `main`.
=> chore: Update source branch of ci-support repo

AmplifyPlugins/API/APICategoryPlugin.xcodeproj/project.pbxproj, AmplifyPlugins/API/AWSAPICategoryPlugin/Operation/AWSGraphQLSubscriptionOperation.swift, AmplifyPlugins/API/AWSAPICategoryPlugin/Support/Utils/AppSyncJSONValue+toJSONValue.swift, AmplifyPlugins/API/AWSAPICategoryPlugin/Support/Utils/GraphQLResponseDecoder+DecodeError.swift, AmplifyPlugins/Core/AWSPluginsCore/API/AppSyncErrorType.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/OutgoingMutationQueue/ProcessMutationErrorFromCloudOperation.swift
When a subscription fails due to an authorization issue, parse and surface AppSyncJSONValue errors
in order to let DataStore recover
=> fix(auth): parse and surface returned subscription @auth errors

.github/workflows/stale.yml
*Description of changes:* this PR adds a GitHub Action workflow to automatically handle stale issues. It leverages the official https://github.com/actions/stale 
=> add github workflow action to handle stale issues

AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Dependency/AuthenticationProviderAdapter+SignIn.swift
*Issue:* #809 
*Description of changes:* Fix an issue where the UI was dismissed after the callback was completed.
=> fix(auth): Dismiss UI first before sending callback for HostedUI

AmplifyPlugins/Core/AWSPluginsCore/Model/GraphQLRequest/GraphQLRequest+AnyModelWithSync.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/Model+SQLite.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/StorageEngineAdapter+SQLite.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/OutgoingMutationQueue/ProcessMutationErrorFromCloudOperation.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/OutgoingMutationQueue/SyncMutationToCloudOperation.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/ReconcileAndLocalSave/AWSModelReconciliationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/ReconcileAndLocalSave/ReconcileAndLocalSaveOperation.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Core/SQLiteStorageEngineAdapterJsonTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/ReconcileAndLocalSaveOperationTests.swift
- Updated sync operations to make use of model schema
- Fixed local save to use id from the associated model for json type.
=> refactor(datastore): Fix sync and local save to use non modeltype

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/AWSIncomingEventReconciliationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/AWSIncomingSubscriptionEventPublisher.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/IncomingSubscriptionEventPublisher.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/ReconcileAndLocalSave/AWSModelReconciliationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/ReconcileAndLocalSave/ModelReconciliationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/AWSIncomingEventReconciliationQueueTests.swift
Keep DataStore sync engine running even if model subscriptions fail
=> fix(datastore): keep DataStore sync engine running even if model subscriptions fail

Amplify.xcodeproj/project.pbxproj, AmplifyPlugins/Core/AWSPluginsCore/Model/Decorator/AuthRuleDecorator.swift, AmplifyPlugins/Core/AWSPluginsCore/Model/Support/AuthRule+Extension.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/Decorator/AuthRuleDecorator/ModelMultipleOwnerAuthRuleTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/Decorator/AuthRuleDecorator/ModelReadUpdateAuthRuleTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/Decorator/AuthRuleDecorator/ModelWithOwnerFieldAuthRuleTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLRequest/GraphQLRequestAuthIdentityClaimTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLRequest/GraphQLRequestAuthRuleTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLRequest/GraphQLRequestOwnerAndGroupTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/IncomingAsyncSubscriptionEventPublisher.swift, AmplifyTestCommon/Models/OGCScenarioBMGroupPost+Schema.swift, AmplifyTestCommon/Models/OGCScenarioBMGroupPost.swift, AmplifyTestCommon/Models/OGCScenarioBPost+Schema.swift, AmplifyTestCommon/Models/OGCScenarioBPost.swift
=> fix(DataStore): Owner and Group Combined @auth

Amplify/Categories/Auth/AuthCategory.swift, AmplifyTestCommon/Mocks/MockAuthCategoryPlugin.swift, AmplifyTests/CategoryTests/Auth/AuthCategoryConfigurationTests.swift
Fixes https://github.com/aws-amplify/amplify-ios/issues/829
When adding an Auth plugin using `Amplify.add(plugin:)`, if the plugin does not have a key a `PredictionsError` will be thrown. Since this is the `AuthCategory` I would expect an `AuthError` to be thrown. This code changes the error to an `AuthError` and adds a new unit test to verify (1) that an error is thrown and (2) that the error is an `AuthError`.
=> fix: auth category should throw AuthError instead of PredictionsError

Amplify.xcodeproj/project.pbxproj, AmplifyPlugins/Core/AWSPluginsCore/ServiceConfiguration/AmplifyAWSServiceConfiguration+Platform.swift, AmplifyPlugins/Core/AWSPluginsCore/ServiceConfiguration/AmplifyAWSServiceConfiguration.swift
In the fast lane script, there are one-off's that bump the version
```
set_key_value(file: "AmplifyPlugins/Core/AWSPluginsCore/ServiceConfiguration/AmplifyAWSServiceConfiguration.swift", key: "version", value: version)
```
the problem was the version parameter was being picked up and replaced the type with the version number:
https://github.com/aws-amplify/amplify-ios/commit/3b431c8eec094d1f29a4bacdd15a42001183a316#r43315436
And so, this code change is to move that extension over to it's own file
=> fix: move AWSServiceConfiguration Platform extension

fastlane/Fastfile
The error is
```
[22:27:44]: Unknown method 'warn', supported [:crash!, :not_implemented, :important, :shell_error!, :success, :build_failure!, :confirm, :command, :verbose, :abort_with_message!, :test_failure!, :deprecated, :error, :interactive?, :password, :input, :select, :header, :user_error!, :message, :command_output, :content_error]
```
ref https://docs.fastlane.tools/advanced/actions/#interacting-with-the-user
=> fix: replace fastlane warn method

AmplifyPlugins/Core/AWSPluginsCore/Model/Support/Model+GraphQL.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLDocument/GraphQLUpdateMutationTests.swift
*Issue #, if available:* #828 
**Notes:**
In some scenarios the fields of type `.collection` were not being
correctly excluded from the `input` of the `GraphQLRequest`.
This change makes sure the fields of type `.collection` are not added to
the input variable.
=> fix(api): make sure collections are not in the gql input - fixes #828

Amplify.xcodeproj/project.pbxproj, AmplifyPlugins/Core/AWSPluginsCore/Model/Decorator/AuthRuleDecorator.swift, AmplifyPlugins/Core/AWSPluginsCore/Model/Support/AuthRule+Extension.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/Decorator/AuthRuleDecorator/ModelWithOwnerAuthAndGroupWithGroupClaim.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/Decorator/AuthRuleDecorator/ModelWithOwnerAuthAndMultiGroup.swift
Updated the algorithm to support multiple read restricted group based rules.  For example, if given the following schema:
```
type OIDCMultiGroupPost
@model
@auth(
rules: [
{ allow: owner, provider: oidc, identityClaim: "sub"},
{ allow: groups, provider: oidc, groups: ["Admins"],
groupClaim: "https://myapp.com/claims/groups"},
{ allow: groups, provider: oidc, groups: ["Moderators", "Editors"],
groupClaim: "https://differentapp.com/claims/groups"}
]
) {
id: ID!
title: String!
owner: String
}
```
The following examples of OIDC tokens with the following claims, will result in a subscription document that does not filter on the owner (since the user is part of at least one of the groups of a claim that was specified in the schema)
```
Example 1:
["username": "user1",
"sub": …
```
=> fix(Core): use groupClaim in @auth rule for oidc

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/AWSDataStorePlugin+DataStoreBaseBehavior.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/ModelStorageBehavior.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/QuerySort+SQLite.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/QuerySortDescriptor.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/SQLStatement+Select.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/StorageEngineAdapter+SQLite.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/StorageEngine.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/AWSMutationDatabaseAdapter/AWSMutationDatabaseAdapter+MutationEventSource.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/MutationEvent/MutationEventClearState.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/Support/MutationEvent+Query.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Core/SQLStatementTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/Support/MockSQLiteStorageEngineAdapter.swift, AmplifyPlugins/DataStore/DataStoreCategoryPlugin.xcodeproj/project.pbxproj
*Description of changes:* Give support for AWSDatastorePlugin to accept non Coding key based sort input. The public api can be accessed via escape hatch
```swift
public func query<M: Model>(_ modelType: M.Type,
modelSchema: ModelSchema,
where predicate: QueryPredicate? = nil,
sort sortInput: [QuerySortDescriptor]? = nil,
paginate paginationInput: QueryPaginationInput? = nil,
completion: DataStoreCallback<[M]>)
```
=> refactor(datastore): Support for non codingkey based sort

AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLRequest/GraphQLRequestOwnerAndGroupTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/StorageEngine+SyncRequirement.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/InitialSync/InitialSyncOperation.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/InitialSync/InitialSyncOperationEvent.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/InitialSync/ModelSyncedEventEmitter.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/InitialSync/SyncEventEmitter.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/ReconcileAndLocalSave/AWSModelReconciliationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/InitialSync/InitialSyncOperationTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/InitialSync/ReadyEventEmitterTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/InitialSync/SyncEventEmitterTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/AWSIncomingEventReconciliationQueueTests.swift
=> refactor(datastore): Replace usage of Model.Type from internal HubEvent

Amplify/Core/Configuration/Internal/Amplify+Reset.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/InitialSync/SyncEventEmitterTests.swift
The existing implementation of `Amplify.reset()` is to call `reset()` on every Categories and put them in global `DispatchGroup` which might cause a race condition. For example, during the `DataStore` reset process, it depends on `Hub` to dispatch some event, but at that point, `Hub` might already been reset and cause a precondition failure on https://github.com/aws-amplify/amplify-ios/blob/main/Amplify/Categories/Hub/HubCategory.swift#L44
The change I made is:
`reset()` on `logging` and `hub` categories should be called when other categories finish resetting.
=> fix(amplify): change reset method

.gitallowed, Amplify/Core/Support/AtomicDictionary.swift, Amplify/Core/Support/AtomicValue+Bool.swift, Amplify/Core/Support/AtomicValue+Numeric.swift, Amplify/Core/Support/AtomicValue+RangeReplaceableCollection.swift, Amplify/Core/Support/AtomicValue.swift, AmplifyTests/CoreTests/AtomicDictionaryTests.swift, AmplifyTests/CoreTests/AtomicValueTests.swift
My initial implementation of AtomicValue was naively based on a `DispatchQueue` to protect access to the internal value and protect against data races. However, that could result in thread explosions (since not specifying a `target` for the private queue defaults to the global "overcommit" queue), and will require needless context switches. This change refactors `AtomicValue` and `AtomicDictionary` to use an `NSLock` instead of a `DispatchQueue` to protect against data races. As evidenced by the new performance test, this increases performance by about 50% over the previous implementation. It's not likely to make much of a change in our customer apps, since we don't typically have super-high volume use cases for our Atomics, but reducing thread usage is a win …
=> chore: Use NSLock instead of DispatchQueue to protect Atomics

.circleci/config.yml, Amplify.xcodeproj/xcshareddata/xcschemes/AWSPluginsCore.xcscheme, Amplify.xcodeproj/xcshareddata/xcschemes/Amplify.xcscheme, AmplifyPlugins/API/APICategoryPlugin.xcodeproj/xcshareddata/xcschemes/AWSAPICategoryPlugin.xcscheme, AmplifyPlugins/Analytics/AnalyticsCategoryPlugin.xcodeproj/xcshareddata/xcschemes/AWSPinpointAnalyticsPlugin.xcscheme, AmplifyPlugins/Auth/AWSCognitoAuthPlugin.xcodeproj/xcshareddata/xcschemes/AWSCognitoAuthPlugin.xcscheme, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/InitialSync/ReadyEventEmitterTests.swift, AmplifyPlugins/DataStore/DataStoreCategoryPlugin.xcodeproj/xcshareddata/xcschemes/AWSDataStoreCategoryPlugin.xcscheme, AmplifyPlugins/Predictions/PredictionsCategoryPlugin.xcodeproj/xcshareddata/xcschemes/AWSPredictionsPlugin.xcscheme, AmplifyPlugins/Predictions/PredictionsCategoryPlugin.xcodeproj/xcshareddata/xcschemes/CoreMLPredictionsPlugin.xcscheme, AmplifyPlugins/Storage/StoragePlugin.xcodeproj/xcshareddata/xcschemes/AWSS3StoragePlugin.xcscheme
Previous configuration reported code coverage for the Test modules as well as
the library modules themselves. This change removes test targets from the
report.
=> chore: Target code coverage to only library modules

AmplifyPlugins/API/Podfile.lock, AmplifyPlugins/Analytics/Podfile.lock, AmplifyPlugins/Auth/Podfile.lock, AmplifyPlugins/DataStore/Podfile.lock, AmplifyPlugins/Predictions/Podfile.lock, AmplifyPlugins/Storage/Podfile.lock, Podfile.lock
=> chore: Update dependencies

Amplify.xcodeproj/project.pbxproj, Amplify/Categories/DataStore/Model/Internal/Schema/Model+Schema.swift, Amplify/Categories/DataStore/Model/Internal/Schema/ModelField+Association.swift, Amplify/Categories/DataStore/Model/Internal/Schema/ModelSchema+Definition.swift, Amplify/Categories/DataStore/Model/Internal/Schema/ModelSchema.swift, AmplifyPlugins/API/Podfile.lock, AmplifyPlugins/Analytics/Podfile.lock, AmplifyPlugins/Auth/Podfile.lock, AmplifyPlugins/Core/AWSPluginsCore/Model/GraphQLRequest/GraphQLRequest+AnyModelWithSync.swift, AmplifyPlugins/Core/AWSPluginsCore/Model/GraphQLRequest/GraphQLRequest+Model.swift, AmplifyPlugins/Core/AWSPluginsCore/Model/Support/Model+GraphQL.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/Model+SQLite.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/SQLStatement+CreateTable.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/SQLStatement+Select.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/StorageEngineAdapter+SQLite.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/TestSupport/Mocks/TestModelRegistration.swift, AmplifyPlugins/DataStore/Podfile.lock, AmplifyPlugins/Predictions/Podfile.lock, AmplifyPlugins/Storage/Podfile.lock, AmplifyTests/CategoryTests/DataStore/ModelFieldAssociationTests.swift, Podfile.lock
*Issue:* https://github.com/aws-amplify/amplify-ios/issues/882
*Description of changes:*  Regression bug caused by changing the public enum value
- Added static functions inside enum to match the previous enum cases to make it backward compatible.
- Unit tests for the changes.
=> fix(datastore): Regression bug caused by changing the public enum value

AmplifyPlugins/API/AWSAPICategoryPlugin/Reachability/NetworkReachabilityNotifier.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/OutgoingMutationQueue/MutationRetryNotifier.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/MutationQueue/SyncMutationToCloudOperationTests.swift
=> fix(DataStore): failed subscriptions lead to instability in sync engine

Amplify.podspec, Amplify/DevMenu/DevMenuPresentationContextProvider.swift, Amplify/DevMenu/Trigger/TriggerDelegate.swift
*Issue #, if available:* https://github.com/aws-amplify/amplify-ios/issues/878
Explicitly notes SwiftUI as a `weak_framework` to work around what I'm assuming is an Xcode or CocoaPods bug where SwiftUI isn't properly weak-linked by Xcode the way other frameworks (such as Combine) are.
This change also adds an `@available` guard on the `DevMenuPresentationContextProvider` protocol, to ensure that calling apps using the DevMenu are properly guarding their own code with availability checks or a sufficiently high minimum deployment target.
=> fix: Designate SwiftUI a weak_framework in podspec

Amplify/Categories/DataStore/Query/QueryPredicate.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/Support/QueryPredicateGraphQLTests.swift
For Reference, android code:
https://github.com/aws-amplify/amplify-android/blame/12ec8e9819228f63bd677a0431a5ab191f79d9e1/core/src/main/java/com/amplifyframework/core/model/query/predicate/QueryPredicateGroup.java#L77
=> fix(DataStore): Nested query predicates are not stored properly

Amplify.xcodeproj/project.pbxproj, Amplify/Categories/DataStore/Model/Internal/Persistable.swift, Amplify/Categories/DataStore/Query/Evaluable.swift, Amplify/Categories/DataStore/Query/QueryOperator.swift, Amplify/Categories/DataStore/Query/QueryPredicate.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Query/QueryPredicateEvaluateGeneratedBoolTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Query/QueryPredicateEvaluateGeneratedDateTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Query/QueryPredicateEvaluateGeneratedDateTimeTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Query/QueryPredicateEvaluateGeneratedDoubleIntTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Query/QueryPredicateEvaluateGeneratedDoubleTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Query/QueryPredicateEvaluateGeneratedIntDoubleTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Query/QueryPredicateEvaluateGeneratedIntTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Query/QueryPredicateEvaluateGeneratedStringTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Query/QueryPredicateEvaluateGeneratedTimeTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Query/QueryPredicateEvaluateGenerator.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Query/QueryPredicateEvaluateTests.swift, AmplifyTestCommon/Models/QPredGen+Schema.swift, AmplifyTestCommon/Models/QPredGen.swift
What to review in this PR:
```
Evaluable.swift
project.pbxproj
Persistable.swift
QueryOperator.swift
QueryPredicate.swift
QueryPredicateEvaluateTests.swift
QPredGen+Schema.swift
QPredGen.swift
```
What you might want to review, but..... eh, might not want to review is:
```
QueryPredicateEvaluateGenerator
```
You might want to spot check:
```
any generated tests
```
=> chore(DataStore): Ability to evaluate QueryPredicate on Model instances

AmplifyPlugins/Predictions/AWSPredictionsPluginTests/Mocks/Service/MockTextractBehavior.swift, AmplifyPlugins/Predictions/AWSPredictionsPluginTests/Mocks/Service/MockTranscribeStreamingBehavior.swift, AmplifyPlugins/Predictions/AWSPredictionsPluginTests/Service/PredictionsTest/PredictionsServiceComprehendTests.swift, AmplifyPlugins/Predictions/AWSPredictionsPluginTests/Service/PredictionsTest/PredictionsServiceRekognitionTests.swift, AmplifyPlugins/Predictions/AWSPredictionsPluginTests/Service/PredictionsTest/PredictionsServiceTextractTests.swift, AmplifyPlugins/Predictions/AWSPredictionsPluginTests/Service/PredictionsTest/PredictionsServiceTranscribeTests.swift, AmplifyPlugins/Predictions/AWSPredictionsPluginTests/Service/PredictionsTest/PredictionsServiceTranslateTests.swift
This PR solved several issues I found in unit tests:
1. Added `Expectation`, `fullfil()` and `wait()` to every test
2. Avoid force unwrap of error, otherwise fails the tests: https://github.com/aws-amplify/amplify-ios/pull/903/files#r527990223
3. Properly set `AWSTranscribeStreamingClientDelegate` in MockTranscribeStreamingBehavior.swift: https://github.com/aws-amplify/amplify-ios/pull/903/files#diff-36fd00eb37548e02a87ce71ab27eaaf5b486a863f2350501c4059c62efc319a5R39-R40, otherwise, the checking in callback is never run.
4. PredictionsServiceTextractTests should conforms to `XCTestCase` instead of `XCTest` otherwise, all the tests are not going to run: https://github.com/aws-amplify/amplify-ios/pull/903/files#diff-9db6d14f94733eac54f7efb37e462e3872117c41f5caf6e47d …
=> fix(Predictions): Fix of PredicationPlugin unit tests

AmplifyPlugins/Predictions/AWSPredictionsPlugin/Service/Predictions/AWSPredictionsService+Rekognition.swift, AmplifyPlugins/Predictions/AWSPredictionsPluginTests/Service/PredictionsTest/PredictionsServiceRekognitionTests.swift
1. It's a small PR regarding this comment: https://github.com/aws-amplify/amplify-ios/pull/903#discussion_r529797100
2. Added one unit test: 
=> fix(Predictions): Avoid Multiple Rekognition Error Return

AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/MutationQueue/SyncMutationToCloudOperationTests.swift
Addresses bug filed here:
https://github.com/aws-amplify/amplify-ios/issues/914
=> fix(DataStore): SyncMutationToCloudOperationTests thread sanitizer bug

AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Dependency/AuthorizationProviderAdapter+SignedInSession.swift
=> fix(auth): Fix an issue where the fetchAuthSession callback is called twice

AmplifyPlugins/Auth/AWSCognitoAuthPlugin.xcodeproj/project.pbxproj, AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Dependency/AuthorizationProviderAdapter+SignedInSession.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthorizationProviderTests/AuthorizationProviderSessionSignInTests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthorizationProviderTests/AuthorizationProviderSessionSignoutTests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthorizationProviderTests/BaseAuthorizationProviderTest.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/Mocks/MockAWSMobileClient.swift
1. Added all tests for `fetchAuthSession` in signedOut
2. Added few tests for `fetchAuthSession` in signedIn
Tests will fail until #922 is merged in.
=> test(auth): Added test for authorizationProvider

Amplify/Categories/DataStore/DataStoreCategory+Behavior.swift, Amplify/Categories/DataStore/DataStoreCategoryBehavior.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/AWSDataStorePlugin+DataStoreBaseBehavior.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/AWSDataStorePlugin.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/StorageEngine+SyncRequirement.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/StorageEngine.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/StorageEngineBehavior.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Core/AWSAPICategoryPluginTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Core/ConfigurationTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Core/SQLiteStorageEngineAdapterJsonTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/APICategoryDependencyTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/LocalSubscriptionTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/LocalSubscriptionWithJSONModelTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/MutationQueue/AWSMutationEventIngesterTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/MutationQueue/OutgoingMutationQueueTestsWithMockStateMachine.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/MutationQueue/ProcessMutationErrorFromCloudOperationTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/MutationQueue/SyncMutationToCloudOperationTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/RemoteSync/RemoteSyncAPIInvocationTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/ReconcileAndLocalSaveOperationTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/Support/MockSQLiteStorageEngineAdapter.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/Support/MockSQLiteStorageEngineAdapterResponders.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/TestSupport/BaseDataStoreTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/TestSupport/SyncEngineTestBase.swift, AmplifyPlugins/DataStore/DataStoreCategoryPlugin.xcodeproj/project.pbxproj, AmplifyTestCommon/Mocks/MockDataStoreCategoryPlugin.swift
First approach was here:
https://github.com/aws-amplify/amplify-ios/pull/917
I realized late that we have effectively coupled the instantiation of the storageEngine with starting the syncEngine.  The approach in this PR maintains this behavior in order to skirt around having to save state of whether or not the sync engine has been started in conjunction with the storage engine being instantiated.  I believe that by preserving this coupling, makes for a significantly more elegant approach than the design/implementation in PR 917.
=> feat(DataStore): Start/Stop implementation, 2nd approach

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/DataStoreConfiguration.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/DataStoreSyncExpression.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/InitialSync/InitialSyncOperation.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngine.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/AWSIncomingEventReconciliationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/AWSIncomingSubscriptionEventPublisher.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/IncomingAsyncSubscriptionEventPublisher.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/ReconcileAndLocalSave/AWSModelReconciliationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/InitialSync/InitialSyncOperationTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/InitialSync/SyncEventEmitterTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/AWSIncomingEventReconciliationQueueTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/ModelReconciliationQueueBehaviorTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/Support/MockModelReconciliatinQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/Support/MockModelReconciliationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/Support/ReconciliationQueueTestBase.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/TestSupport/Mocks/MockAWSIncomingEventReconciliationQueue.swift, AmplifyPlugins/DataStore/DataStoreCategoryPlugin.xcodeproj/project.pbxproj
Smoke tested with a basic case.
=> feat(datastore): selective sync on initial sync & incoming subscription models

AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthenticationProviderTests/AuthenticationProviderSigninTests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthenticationProviderTests/AuthenticationProviderSignoutTests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/Mocks/MockAWSMobileClient.swift
=> test(auth): Added authenticationprovider tests for signin, signinout

AmplifyPlugins/API/AWSAPICategoryPluginTests/Operation/AWSGraphQLSubscriptionOperationCancelTests.swift
While implementing start/stop for datastore, I noticed these tests were failing because the `SubscriptionConnectionFactory` was able to throw an exception and fail, prior to `cancel()` execution happening.  When this happens, the `operation` ends up in a `finished` state rather than the expected `canceled` state.
So.. to remedy this, I re-worked these tests by using the existing `MockSubscriptionConnectionFactory` to test various cases.
To reproduce the unexpected behavior, revert these changes, and add a `sleep(2)` right before the call to `operation.cancel()`, then run the test.
=> fix(API): subscription cancel unit test failing intermittently

AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthenticationProviderTests/AuthenticationProviderResendSignupCodeTests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/Mocks/MockAWSMobileClient.swift
=> test(Auth): resendSignUpCode unit tests

AmplifyPlugins/API/AWSAPICategoryPluginTests/AWSAPICategoryPlugin+ResetTests.swift, AmplifyPlugins/API/AWSAPICategoryPluginTests/AWSAPICategoryPluginTestBase.swift
My best analysis as to what is happening is the following:
Test case Post:
https://github.com/aws-amplify/amplify-ios/blob/main/AmplifyPlugins/API/AWSAPICategoryPluginTests/AWSAPICategoryPlugin+RESTClientBehaviorTests.swift
Test case reset:
https://github.com/aws-amplify/amplify-ios/blob/main/AmplifyPlugins/API/AWSAPICategoryPluginTests/AWSAPICategoryPlugin+ResetTests.swift
Base class
https://github.com/aws-amplify/amplify-ios/blob/main/AmplifyPlugins/API/AWSAPICategoryPluginTests/AWSAPICategoryPluginTestBase.swift
Imagine that test case “post” is running.  The Post test first kicks off an operation.  The operation continues to execute even after the actual test case finishes.  The problem is that we haven’t killed the operation associated with the Post unit test, and this operation …
=> fix(API): Fix unstable AWSAPICategoryPluginResetTests.testReset()

AmplifyPlugins/Predictions/AWSPredictionsPlugin/Service/Predictions/AWSPredictionsService+Comprehend.swift, AmplifyPlugins/Predictions/AWSPredictionsPluginIntegrationTests/InterpretBasicIntegrationTests.swift
Amazon Comprehend returns an array of Entity https://docs.aws.amazon.com/comprehend/latest/dg/API_Entity.html .
Each entity has a _beginOffset_ and _endOffset_ properties, which are positions of each UTF-8 "code point" in the string.
A [code point](https://www.unicode.org/glossary/#code_point) is a value in the Unicode codespace, the range of integers from 0 to 10FFFF, not all code points are assigned to encoded chars.
We need to use Swift strings underlying scalar view to compute indexes correctly and avoid crashes at runtime.
fix #873 
=> fix(predictions): use string's unicode scalars view to compute indexes for Comprehend results

.circleci/config.yml, .codecov.yml
- Improve codecov labels; limit packages to be reported
- Add codecov reporting for AWSPluginsCore
- Added a config file to set the failure threshold
This is an attempt to reduce spurious code coverage failures and alarming reports of low coverage for things like test targets.
=> chore: Improve codecov reporting

AmplifyPlugins/Core/AWSPluginsCore/ServiceConfiguration/AmplifyAWSServiceConfiguration+Platform.swift, AmplifyPlugins/Core/AWSPluginsCore/ServiceConfiguration/AmplifyAWSServiceConfiguration.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/ServiceConfiguration/AmplifyAWSServiceConfigurationTests.swift, AmplifyTestCommon/Mocks/MockDataStoreCategoryPlugin.swift
User agent string was malformed. Before this PR the user agent string was this:
```
amplify-iOS/(Function) iOS/14.0 en_US
```
After this PR
```
amplify-iOS/1.5.0 iOS/14.0 en_US
```
- Added unit test to check the version value.
=> bug(core): Pass the right amplify version in user agent

AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Dependency/AuthenticationProviderAdapter+SignIn.swift
https://github.com/aws-amplify/amplify-ios/issues/936
The buggy behavior is:
If user taps on `Cancel` button, the WebView is going to disappear without affecting other ui components, because it is cancelling both ViewControllers. But when user taps outside of the WebView, then other UI components will be blocked by the empty transparent `UIViewController`.
As we investigated, we believe it is a regression from Apple, it only happens on iPad running on iOS 14+.
Thanks for Wooj2's solution: disable view from disappearing if users tap outside.
=> fix(Auth): Dismiss empty UIViewController

AmplifyPlugins/DataStore/Podfile.lock
Oops, forgot about updating the DataStore `Podfile.lock` file.  In the last PR I only updated the one for API
=> chore(DataStore): Update podfile.lock to remove ReachabilitySwift

Amplify.xcodeproj/project.pbxproj, AmplifyPlugins/API/APICategoryPlugin.xcodeproj/project.pbxproj, AmplifyPlugins/API/APICategoryPlugin.xcodeproj/xcshareddata/xcschemes/AWSAPICategoryPluginFunctionalTests.xcscheme, AmplifyPlugins/API/AWSAPICategoryPluginFunctionalTests/GraphQLModelBased/GraphQLConnectionScenario1Tests.swift, AmplifyPlugins/API/AWSAPICategoryPluginFunctionalTests/GraphQLModelBased/GraphQLConnectionScenario2Tests.swift, AmplifyPlugins/API/AWSAPICategoryPluginFunctionalTests/GraphQLModelBased/GraphQLConnectionScenario3Tests+Helpers.swift, AmplifyPlugins/API/AWSAPICategoryPluginFunctionalTests/GraphQLModelBased/GraphQLConnectionScenario3Tests+Subscribe.swift, AmplifyPlugins/API/AWSAPICategoryPluginFunctionalTests/GraphQLModelBased/GraphQLConnectionScenario3Tests.swift, AmplifyPlugins/API/AWSAPICategoryPluginFunctionalTests/GraphQLModelBased/GraphQLConnectionScenario4Tests.swift, AmplifyPlugins/API/AWSAPICategoryPluginFunctionalTests/GraphQLModelBased/GraphQLConnectionScenario5Tests.swift, AmplifyPlugins/API/AWSAPICategoryPluginFunctionalTests/GraphQLModelBased/GraphQLConnectionScenario6Tests.swift, AmplifyPlugins/API/AWSAPICategoryPluginFunctionalTests/GraphQLModelBased/GraphQLModelBasedTests.swift, AmplifyPlugins/API/AWSAPICategoryPluginFunctionalTests/GraphQLModelBased/README.md, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginIntegrationTests/Connection/DataStoreConnectionScenario6Tests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginIntegrationTests/README.md, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginIntegrationTests/TestSupport/HubEventsIntegrationTestBase.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginIntegrationTests/TestSupport/SyncEngineIntegrationTestBase.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginIntegrationTests/TestSupport/TestModelRegistration.swift, AmplifyPlugins/DataStore/DataStoreCategoryPlugin.xcodeproj/project.pbxproj, AmplifyTestCommon/Models/Collection/6/Blog6+Schema.swift, AmplifyTestCommon/Models/Collection/6/Blog6.swift, AmplifyTestCommon/Models/Collection/6/Comment6+Schema.swift, AmplifyTestCommon/Models/Collection/6/Comment6.swift, AmplifyTestCommon/Models/Collection/6/Post6+Schema.swift, AmplifyTestCommon/Models/Collection/6/Post6.swift, AmplifyTestCommon/Models/Collection/connection-schema.graphql, AmplifyTestCommon/Models/schema.graphql
- Add the blog, post, comment schema that developers can get when they run `amplify add api`
- Add placeholder for API integration tests (this is in anticipation of lazy loading test for infinitely traversable data)
- Add datastore integration test
=> fix: add blog post comment schema and tests

Amplify/Categories/DataStore/Model/Internal/Embedded.swift, Amplify/Categories/DataStore/Model/Internal/Model+Array.swift, Amplify/Categories/DataStore/Model/Internal/Model+Codable.swift, Amplify/Categories/DataStore/Model/Internal/Model+DateFormatting.swift, Amplify/Categories/DataStore/Model/Internal/Model+Subscript.swift, Amplify/Categories/DataStore/Model/Internal/ModelRegistry+Syncable.swift, Amplify/Categories/DataStore/Model/Internal/Persistable.swift, Amplify/Categories/DataStore/Model/Internal/Schema/Model+Schema.swift, Amplify/Categories/DataStore/Model/Internal/Schema/ModelField+Association.swift, Amplify/Categories/DataStore/Model/Internal/Schema/ModelValueConverter.swift
=> chore(datastore): Update comment to reflect breaking change

AWSPluginsCore.podspec, AmplifyPlugins/API/AWSAPICategoryPlugin/Interceptor/RequestInterceptor/IAMURLRequestInterceptor.swift, AmplifyPlugins/API/AWSAPICategoryPlugin/Interceptor/RequestInterceptor/UserPoolRequestInterceptor.swift, AmplifyPlugins/API/Podfile.lock, AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/Dependency/AWSPinpointAdapter.swift, AmplifyPlugins/Analytics/Podfile.lock, AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Dependency/AuthenticationProviderAdapter+SignIn.swift, AmplifyPlugins/Auth/Podfile.lock, AmplifyPlugins/Core/AWSPluginsCore/Auth/AWSAuthService.swift, AmplifyPlugins/Core/AWSPluginsTestCommon/MockAWSAuthService.swift, AmplifyPlugins/DataStore/Podfile.lock, AmplifyPlugins/Predictions/AWSPredictionsPlugin/Operation/AWSTranscribeOperation.swift, AmplifyPlugins/Predictions/AWSPredictionsPlugin/Operation/IdentifyOperation.swift, AmplifyPlugins/Predictions/Podfile.lock, AmplifyPlugins/Storage/AWSS3StoragePlugin/Service/Storage/AWSS3StorageService.swift, AmplifyPlugins/Storage/AWSS3StoragePlugin/Support/Utils/StorageErrorHelper.swift, AmplifyPlugins/Storage/Podfile.lock, AmplifyTestCommon.podspec, Podfile, Podfile.lock
*Description of changes:* AWSPluginsCore has a dependency on AWSMobileClient which is not required. This PR removes the dependency from AWSMobileClient to the test package.
These are the changes in this PR:
- AWSPluginsCore depend on AWSCore instead of AWSMobileClient
- AmplifyTestCommon to depend on AWSMobileClient
- Remove AWSMobileClient import from unwanted places
- Code cleanup
=> chore(AWSPluginsCore): Remove unwanted AWSMobileClient dependency from AWSPluginsCore

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/SQLStatement+Condition.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginIntegrationTests/DataStoreLocalStoreTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Core/SQLStatementTests.swift
A fix for issue: https://github.com/aws-amplify/amplify-ios/issues/907
The previous translation from `QueryPredicate` to sql statement is incorrect
For example:
If I have a predicate like 
```swift
let predicate = (todo.name == "name2" && todo.tag == "optional") || todo.description == "wake up"
```
SQL statement generated by the incorrect code is:
```
select
"root"."id" as "id", "root"."description" as "description", "root"."name" as "name",
"root"."tag" as "tag"
from Todo as "root"
where 1 = 1
and (
or (
"root"."name" = ?
and "root"."tag" = ?
)
and "root"."description" = ?
)
```
which fails `DataStore.query()`
The correct one should be:
```
select
"root"."id" as "id", "root"."description" as "description", "root"."name" as "name", …
```
=> fix(DataStore): QueryPredicate translation

AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthenticationProviderTests/AuthenticationProviderSigninWithSocialWebUITests.swift
I'm reusing the code in `AuthenticationProviderSigninWithWebUITests.swift`
=> test(Auth): socialSignInWithWebUI unit tests

AmplifyPlugins/Core/AWSPluginsCore/Model/Decorator/FilterDecorator.swift, AmplifyPlugins/Core/AWSPluginsCore/Model/Support/QueryPredicate+GraphQL.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLRequest/GraphQLRequestAnyModelWithSyncTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/StorageEngine.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/InitialSync/InitialSyncOperationTests.swift
Customers will experience a crash in the event they define a sync query with the `.all` constant.  For example:
```
let syncExpression1 = DataStoreSyncExpression.syncExpression(Todo.schema, where: {
return QueryPredicateConstant.all
}
````
This code change remedies this by using `[:]` as the filter value -- effectively disabling the selective sync expression.
=> fix(DataStore): support for QueryPredicateConstant.all for graphql queries

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/StorageEngine+DeleteTransaction.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/StorageEngine.swift, AmplifyPlugins/DataStore/DataStoreCategoryPlugin.xcodeproj/project.pbxproj
This should be a relatively uneventful PR.
1.  Removed `syncDeletion`, and calling `syncDeletions` instead
2. Copy and pasted implementation of `queryAndDeleteTransaction` and `collapseResults`, removed `private` modifier and placed into a new file called `StorageEngine+DeleteTransaction.swift `
=> chore(DataStore): Minor refactor syncDeletion(s) and move queryAndDeleteTransaction

Amplify.xcodeproj/project.pbxproj, Amplify/Core/Support/Array+Extensions.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/StorageEngine+DeleteTransaction.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/StorageEngine.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Storage/StorageEngineTestsBase.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Storage/StorageEngineTestsHasMany.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Storage/StorageEngineTestsHasOne.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Storage/StorageEngineTestsManyToMany.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/TestSupport/Mocks/MockRemoteSyncEngine.swift, AmplifyPlugins/DataStore/DataStoreCategoryPlugin.xcodeproj/project.pbxproj, AmplifyTestCommon/Models/M2MPostEditorUser/M2MPost+Schema.swift, AmplifyTestCommon/Models/M2MPostEditorUser/M2MPost.swift, AmplifyTestCommon/Models/M2MPostEditorUser/M2MPostEditor+Schema.swift, AmplifyTestCommon/Models/M2MPostEditorUser/M2MPostEditor.swift, AmplifyTestCommon/Models/M2MPostEditorUser/M2MUser+Schema.swift, AmplifyTestCommon/Models/M2MPostEditorUser/M2MUser.swift, AmplifyTestCommon/Models/M2MPostEditorUser/schema.graphql, AmplifyTestCommon/Models/Restaurant/Dish+Schema.swift, AmplifyTestCommon/Models/Restaurant/Dish.swift, AmplifyTestCommon/Models/Restaurant/Menu+Schema.swift, AmplifyTestCommon/Models/Restaurant/Menu.swift, AmplifyTestCommon/Models/Restaurant/MenuType.swift, AmplifyTestCommon/Models/Restaurant/Restaurant+Schema.swift, AmplifyTestCommon/Models/Restaurant/Restaurant.swift, AmplifyTestCommon/Models/Restaurant/schema.graphql, AmplifyTestCommon/Models/TeamProject/Project+Schema.swift, AmplifyTestCommon/Models/TeamProject/Project.swift, AmplifyTestCommon/Models/TeamProject/Team+Schema.swift, AmplifyTestCommon/Models/TeamProject/Team.swift, AmplifyTestCommon/Models/TeamProject/schema.graphql
This PR addresses issue [#933](https://github.com/aws-amplify/amplify-ios/issues/933)
This PR relies on:
~~[965](https://github.com/aws-amplify/amplify-ios/pull/965) - Addressing columns~~ -- pushed to mainline
[986](https://github.com/aws-amplify/amplify-ios/pull/986) - minor refactor
(For reference only, the precursor to this pr is located here: https://github.com/aws-amplify/amplify-ios/pull/979 )
Did a high level overview/review with @palpatim -- two items that came up:
**Stress test case**
- See unit test `testStressDeleteTopLevelMultiLevelHasManyRelationship`
**Edge case with regards to foreign key constraints**
Tested an edge case where we have a `Blog` -> `Post` - > `Comment`
Steps:
1.  Updated the storageEngine's code to not send sync deletions for Post
```
+++ …
```
=> fix(DataStore): Generate mutation events for associatedModels

AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Dependency/AuthenticationProviderAdapter+SignIn.swift, AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Dependency/AuthenticationProviderAdapter+SignOut.swift, AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Models/Options/AWSAttributeResendConfirmationCodeOptions.swift, AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Support/Constants/AuthPluginErrorConstants.swift, AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Support/Utils/AuthErrorHelper.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthenticationProviderTests/AuthenticationProviderSigninWithSocialWebUITests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthenticationProviderTests/AuthenticationProviderSigninWithWebUITests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthenticationProviderTests/AuthenticationProviderSignoutTests.swift, AmplifyPlugins/Auth/Podfile.lock
*Issue #, if available:* https://github.com/aws-amplify/amplify-ios/issues/967
- This is a behavior change and potential break the current customers, please see Before and After effect below
- Cancelling HostedUI signOut now returns `userCancelled` similar to the cancelling signIn
- Added unit test for the hostedUI flow
*Other platform behavior:*
**Android**
Android currently returns AuthException that contains AWSMobileClient error AuthNavigationException. This certainly needs to change because Amplify apis should not return AWSMobileClient specific errors. 
```
AuthException{
message=Sign in with web UI failed
cause=AuthNavigationException{
message=user cancelled
}
recoverySuggestion=See attached exception for more details
}
```
Android PR to fix - …
=> feat(auth): Fix cancelling hostedUI returning a generic error

AmplifyPlugins/Auth/AWSCognitoAuthPlugin.xcodeproj/project.pbxproj, AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Dependency/AuthenticationProviderAdapter+SignIn.swift, AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Dependency/AuthenticationProviderAdapter+SignOut.swift, AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Dependency/AuthenticationProviderAdapter.swift, AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Models/Options/AWSAuthWebUISignInOptions.swift, AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Service/AWSMobileClient/AWSMobileClientAdapter.swift, AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Service/AWSMobileClient/AWSMobileClientBehavior.swift, AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Support/Utils/AWSCognitoAuthPluginUserDefaults.swift, AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Support/Utils/AWSCognitoAuthPluginUserDefaultsBehavior.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthenticationProviderTests/AuthenticationProviderSigninTests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthenticationProviderTests/AuthenticationProviderSigninWithWebUITests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthenticationProviderTests/AuthenticationProviderSignoutTests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthenticationProviderTests/BaseAuthenticationProviderTest.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/Mocks/MockAWSMobileClient.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/Mocks/MockUserDefaults.swift
*Issue #, if available:* https://github.com/aws-amplify/aws-sdk-ios/issues/3141
- HostedUI signIn defaults to `ASWebAuthenticationSession` in iOS 13.0+
- Added a new parameter in `AWSAuthWebUISignInOptions` called `preferPrivateSession` which will start the hostedUI in `prefersEphemeralWebBrowserSession` of `ASWebAuthenticationSession`.
_*Developer Experience*_
1. There is no change in the signIn or signOut api for existing developers if they do not need to add the new feature of preferPrivateSession.
2. Existing developer (including Flutter) need to update the userCancelled error if they are dependent on it, explained here - https://github.com/aws-amplify/amplify-ios/pull/982
3. New feature is only available for iOS >= 13.0, so if the app runs in a iOS version …
=> chore(auth): Updated the signInWithWebUI to use ASWebAuthenticationSession

AmplifyPlugins/API/AWSAPICategoryPluginTests/AWSAPICategoryPlugin+InterceptorBehaviorTests.swift
See below for the way the test was failing.  This should get fixed by this PR:
https://github.com/aws-amplify/amplify-ios/pull/937
```
Test Case '-[AWSAPICategoryPluginTests.AWSAPICategoryPluginGraphQLBehaviorTests testMutate]' started.
Test Case '-[AWSAPICategoryPluginTests.AWSAPICategoryPluginGraphQLBehaviorTests testMutate]' passed (0.007 seconds).
Test Case '-[AWSAPICategoryPluginTests.AWSAPICategoryPluginGraphQLBehaviorTests testQuery]' started.
Test Case '-[AWSAPICategoryPluginTests.AWSAPICategoryPluginGraphQLBehaviorTests testQuery]' passed (0.003 seconds).
Test Case '-[AWSAPICategoryPluginTests.AWSAPICategoryPluginGraphQLBehaviorTests testSubscribe]' started.
Test Case '-[AWSAPICategoryPluginTests.AWSAPICategoryPluginGraphQLBehaviorTests testSubscribe]' passed (0.005 seconds). …
```
=> chore(API): Optimistically remove comment in code

Amplify.xcodeproj/project.pbxproj, AmplifyPlugins/Core/AWSPluginsCore/API/AppSyncErrorType.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/API/AppSyncErrorTypeTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/OutgoingMutationQueue/ProcessMutationErrorFromCloudOperation.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/AWSIncomingEventReconciliationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/ReconcileAndLocalSave/AWSModelReconciliationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/ReconcileAndLocalSave/ModelReconciliationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/MutationQueue/ProcessMutationErrorFromCloudOperationTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/AWSIncomingEventReconciliationQueueTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/ModelReconciliationQueueBehaviorTests.swift
This PR introduces a set of changes to let DataStore process a new type of error _OperationDisabled_ without halting the sync engine.
Developers will be able to mark an operation as "disabled" by throwing an error directly from an AppSync resolver
```JavaScript
$util.error("Subscription are disabled.", "OperationDisabled")
```
=> feat(datastore): process OperationDisabled error

AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Models/Error/AWSCognitoAuthError.swift, AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Support/Constants/AuthPluginErrorConstants.swift, AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Support/Utils/AuthErrorHelper.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthUserBehaviorTests/UserBehaviorChangePasswordTests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthUserBehaviorTests/UserBehaviorConfirmAttributeTests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthUserBehaviorTests/UserBehaviorResendCodeTests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthenticationProviderTests/AuthenticationProviderConfirmResetPasswordTests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthenticationProviderTests/AuthenticationProviderConfirmSignupTests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthenticationProviderTests/AuthenticationProviderResendSignupCodeTests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthenticationProviderTests/AuthenticationProviderResetPasswordTests.swift
*Issue #, if available:* 1041
*Description of changes:* Removed the coupling tooManyRequests and limitExceeded in the switch block inside AuthErrorHelper 
~~Added new tests to cover change, if needed~~
~~Documentation update for the change if required~~
=> fix(auth): handle tooManyRequests and limitExceeded separately in AuthErrorHelper

Amplify/Categories/API/AmplifyAPICategory+APICategory.swift, Amplify/Categories/Analytics/AnalyticsCategory.swift, Amplify/Categories/Auth/AuthCategory.swift, Amplify/Categories/DataStore/DataStoreCategory.swift, Amplify/Categories/Predictions/PredictionsCategory.swift, Amplify/Categories/Storage/StorageCategory.swift, AmplifyTests/CategoryTests/API/APICategoryConfigurationTests.swift, AmplifyTests/CategoryTests/Analytics/AnalyticsCategoryConfigurationTests.swift, AmplifyTests/CategoryTests/Auth/AuthCategoryConfigurationTests.swift, AmplifyTests/CategoryTests/DataStore/DataStoreCategoryConfigurationTests.swift, AmplifyTests/CategoryTests/Predictions/PredictionsCategoryConfigurationTests.swift, AmplifyTests/CategoryTests/Storage/StorageCategoryConfigurationTests.swift
Ensures that `add` method for Auth, Analytics, Storage, Datastore, API and Predictions categories throw an error when attempt is made to add a plugin after configuration.
=> fix: throw error when plugin added post-configure

AmplifyPlugins/API/AWSAPICategoryPluginTests/Operation/AWSRESTOperationTests.swift, AmplifyPlugins/API/AWSAPICategoryPluginTests/Operation/GraphQLMutateCombineTests.swift, AmplifyPlugins/API/AWSAPICategoryPluginTests/Operation/GraphQLQueryCombineTests.swift, AmplifyPlugins/API/AWSAPICategoryPluginTests/Operation/GraphQLSubscribeTests.swift, AmplifyPlugins/API/AWSAPICategoryPluginTests/Operation/OperationTestBase.swift, AmplifyPlugins/API/AWSAPICategoryPluginTests/Operation/RESTCombineTests.swift
Unit test of API plugin is currently required to configure Amplify. This PR removes that dependency and makes the unit test light as possible and test the unit of code.
=> fix: API unit test to use only the plugin and not Amplify

Amplify.xcodeproj/project.pbxproj, Amplify/Categories/DataStore/Model/Internal/Schema/ModelSchema+Definition.swift, Amplify/Categories/DataStore/Model/Internal/Schema/ModelSchema.swift, AmplifyPlugins/Core/AWSPluginsCore/Model/Decorator/ModelDecorator.swift, AmplifyPlugins/Core/AWSPluginsCore/Model/GraphQLDocument/GraphQLMutation.swift, AmplifyPlugins/Core/AWSPluginsCore/Model/Support/Model+GraphQL.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLDocument/GraphQLCreateMutationTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLDocument/GraphQLDeleteMutationTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLDocument/GraphQLGetQueryTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLDocument/GraphQLUpdateMutationTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/Support/ModelGraphQLTests.swift, AmplifyTestCommon/Models/Record+Schema.swift, AmplifyTestCommon/Models/Record.swift, AmplifyTestCommon/Models/RecordCover+Schema.swift, AmplifyTestCommon/Models/RecordCover.swift
Amplify CLI generates `createdAt` and `updatedAt` fields on every `@model`, and customer can also specify custom field name by defining models as follows
```
type Todo @model(timestamps:{ createdAt: "createdOn", updatedAt: "updatedOn" }) {
id: ID!
name: String!
description: String
}
```
These fields are not currently included in autogenerated models thus are not accessible to customers.
Codegen is being updated to generate these fields (https://github.com/aws-amplify/amplify-codegen/pull/114) but, as they're fully managed by AppSync, they need a special treatment. To avoid AppSync throwing an error, they must NOT be included in the mutation _input_.
Since we can't rely on their name to omit `createdAt` and `updatedAt` from the mutation input, codegen will mark them as "read-only". This PR …
=> feat(datastore): support for readonly fields

AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Models/SignInResult+Extension.swift
Pass public challenge parameters (AdditionalInfo) when authenticating with custom challenge
*Issue #: aws-amplify/amplify-flutter#544*
Pass the expected `AdditionalInfo` parameter when calling `confirmSignInWithCustomChallenge()` instead of `nil`
**Note:** I am not familiar with this code base (or Swift for that matter), but I needed to patch this for my project. I'm currently using a fork of `amplify-ios` with this fix in place. I'm submitting this here for feedback. Let me know if there are additional changes required to get this merged into a future release.
=> Resolves aws-amplify/amplify-flutter#544

AmplifyPlugins/API/APICategoryPlugin.xcodeproj/project.pbxproj, AmplifyPlugins/API/AWSAPICategoryPlugin/AWSAPIPlugin+Reachability.swift, AmplifyPlugins/API/AWSAPICategoryPlugin/AWSAPIPlugin+Resettable.swift, AmplifyPlugins/API/AWSAPICategoryPlugin/AWSAPIPlugin.swift, AmplifyPlugins/API/AWSAPICategoryPlugin/Configuration/AWSAPICategoryPluginConfiguration+EndpointConfig.swift, AmplifyPlugins/API/AWSAPICategoryPluginTests/AWSAPICategoryPlugin+ReachabilityTests.swift, AmplifyPlugins/API/AWSAPICategoryPluginTests/Configuration/AWSAPICategoryPluginConfigurationEndpointConfigTests.swift
https://github.com/aws-amplify/amplify-ios/issues/1159
Part of https://github.com/aws-amplify/amplify-ios/issues/1103
This improves the endpoint resolution logic to return the GraphQL endpoint whenever it is possible to. This makes is so that when using DataStore, the APIPlugin's reachability by default will return the first GraphQL endpoint configured, even when there is more than one API. For example
1. one REST and one graphQL API will return the graphQL API
2. one REST and two graphQL APIs will return the REST API
3. two REST APIs and one GraphQL API wil return the GraphQL API
4. two REST APIs and two GraphQL APIs will not be able to resolve
By submitting this pull request, I confirm that my contribution is made under …
=> fix(API): Reachability resolve to GraphQL API

Package.resolved
Now that AppSyncRTClient 1.5.0 has been released, customer using Amplify via SPM will automatically pull in 1.5.0. We should keep the `Package.resolved` up to date with what the customer would potentially be pulling in on their app.
We do this in the [fastlane script](https://github.com/aws-amplify/amplify-ios/blob/main/fastlane/Fastfile#L126-L151) for pods that generates this [commit](https://github.com/aws-amplify/amplify-ios/commit/6e6fbd4e3e9e6cdbb11cac85dba83f0341420040) so I think we should be doing similarly for SPM `swift package update` as part of the finalize release as well.
This PR is to manually update the `Package.resolved`
By submitting this pull request, I confirm that my contribution is made under the …
=> chore: 1.9.1 release - swift package update AppSyncRTClient 1.5.0

AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Models/SignInResult+Extension.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthenticationProviderTests/AuthenticationProviderSigninTests.swift
*Issue #, if available:* https://github.com/aws-amplify/amplify-flutter/issues/544
Passes the additional info in the next step.
Similar logic in android [here](https://github.com/aws-amplify/amplify-android/blob/50b63dc25923ef54f2bbaf79590e673bd2542b88/aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.java#L1172)
=> fix: Pass additional info in signIn next step

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/ReconcileAndLocalSave/ReconcileAndLocalSaveOperation+Action.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/ReconcileAndLocalSave/ReconcileAndLocalSaveOperation+Resolver.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/ReconcileAndLocalSave/ReconcileAndLocalSaveOperation+State.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/ReconcileAndLocalSave/ReconcileAndLocalSaveOperation.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/ReconcileAndLocalSave/RemoteSyncReconciler.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/ReconcileAndLocalSaveOperationTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/RemoteSyncReconcilerTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/Support/EquatableExtensions.swift
This removes a redundant query performed in ReconcileAndLocalSaveOperation by extending the logic in  `RemoteSyncReconciler` to produce a disposition `.applyRemoteModel` containing the mutationType. A new behavior has also been introduced: When there is no local metadata, drop the remote model if it has been deleted (`remoteModel.syncMetadata.deleted == true`). Originally, the deleted remote model would result in an apply- calling storageAdapter.delete and saving the metadata containing the deleted version. In this change, the remote model will not result in the two SQL write attempts (DELETE model and INSERT metadata), but instead will be dropped. If a model is deleted and does not exist locally, it is unnecessary to store that metadata …
=> fix(DataStore): redundant local metadata query in ReconcileAndLocalSaveOperation

Amplify.xcodeproj/project.pbxproj, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/SQLStatement+CreateTable.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginIntegrationTests/DataStoreHubEventsTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Core/SQLStatementTests.swift, AmplifyTestCommon/Models/ReservedWords/Transaction+Schema.swift, AmplifyTestCommon/Models/ReservedWords/Transaction.swift
*Issue #, if available:*  https://github.com/aws-amplify/amplify-ios/issues/1232
- Quote table name in `CreateTableStatement`
- Reorder files in the AmplifyTestCommon Models directory to help me stop wincing every time I go into that dir :)
- Note: DataStore integ tests are unstable run in a batch. Failures appear to be related to `reset` flows, except for one that had a bad count of the number of models being synced.
=> fix: Quote table names in CreateTableStatement

Amplify/Categories/Predictions/Models/LanguageType.swift
Added documentation comments for all language types supported by Predictions category.  This increased our documentation coverage by 20% (38% -> 58%).
=> Chore (docs): Add doc comments for a Language Types

Amplify.xcodeproj/project.pbxproj, Amplify/Categories/DataStore/Model/Internal/Schema/AuthRule.swift, Amplify/Categories/DataStore/Model/Internal/Schema/Model+Schema.swift, AmplifyPlugins/Core/AWSPluginsCore/Model/Support/AuthRule+Extension.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/Support/AuthRuleExtensionTests.swift
This PR introduces changes to capture the value of `provider` in @auth directives as an `AuthRule` metadata.
=> feat(datastore): support for @auth provider

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/StorageEngineAdapter+SQLite.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/StorageEngine+DeleteTransaction.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/StorageEngineAdapter.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/InitialSync/InitialSyncOperation.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/AWSMutationDatabaseAdapter/AWSMutationDatabaseAdapter+MutationEventIngester.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/AWSIncomingEventReconciliationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/IncomingEventReconciliationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/ReconcileAndLocalSave/AWSModelReconciliationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/ReconcileAndLocalSave/ModelReconciliationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/ReconcileAndLocalSave/ReconcileAndLocalSaveOperation+Action.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/ReconcileAndLocalSave/ReconcileAndLocalSaveOperation+Resolver.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/ReconcileAndLocalSave/ReconcileAndLocalSaveOperation+State.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/ReconcileAndLocalSave/ReconcileAndLocalSaveOperation.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/ReconcileAndLocalSave/RemoteSyncReconciler.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/Support/MutationEvent+Query.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Core/SQLiteStorageEngineAdapterTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/InitialSync/InitialSyncOperationTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/ReconcileAndLocalSaveOperationTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/ReconcileAndSaveQueueTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/RemoteSyncReconcilerTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/Support/EquatableExtensions.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/Support/MockModelReconciliationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/Support/MockSQLiteStorageEngineAdapter.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/Support/MockSQLiteStorageEngineAdapterResponders.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/Support/MutationEventQueryTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/TestSupport/Mocks/MockAWSIncomingEventReconciliationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/TestSupport/Mocks/MockReconciliationQueue.swift, AmplifyPlugins/DataStore/DataStoreCategoryPlugin.xcodeproj/project.pbxproj
The baseline performance test done in the previous PR: https://github.com/aws-amplify/amplify-ios/pull/1215 shows time to sync 10k items is around 100s, (+/- 20s)
This change convert ReconcileAndLocalSaveOperation to reconcile multiple models of the same model schema. When the sync engine starts and a full sync is required, sync query is performed for each model type and paginated based on a default (and service maximum limit) of 1000 items per page. When the sync query results are returned, a ReconcileAndLocalSaveOperation is created with up to 1000 items, before ReconcileAndLocalSaveOperation's would be created per model instance.
By reconciling 1000 items at once, performed in a SQL transaction, this speed things up to sync 10k items …
=> feat(DataStore): Multiple models ReconcileAndLocalSave transaction

Amplify/Categories/DataStore/Model/Internal/Schema/ModelSchema+Attributes.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/Model+SQLite.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/InitialSync/InitialSyncOrchestrator.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/InitialSync/InitialSyncOrchestratorTests.swift
Increase the concurrency count for performing SyncOperation when it can be determined that the models have no associations. When models have no associations, we can perform SyncOperations for each model in parallel since there are no models that depend on another model's data to be present before it can be reconciled.
In the current system (left side of diagram), if a pre-determined order of model results in having a model with a large dataset in front of a model with a small dataset, the smaller dataset model will be blocked by the larger dataset's completion of the reconcilliation path. 
If models do not have any associations among them, perform the SyncOperation in parallel, which will enqueue reconcile operations to the queue in an …
=> fix: increase sync concurrency count based on associations

AmplifyPlugins/API/APICategoryPlugin.xcodeproj/project.pbxproj, AmplifyPlugins/API/AWSAPICategoryPlugin/Support/Internal/URLComponents+sigv4Encoding.swift, AmplifyPlugins/API/AWSAPICategoryPlugin/Support/Utils/RESTOperationRequestUtils.swift, AmplifyPlugins/API/AWSAPICategoryPluginIntegrationTests/REST/RESTWithIAMIntegrationTests/RESTWithIAMIntegrationTests.swift, AmplifyPlugins/API/AWSAPICategoryPluginIntegrationTests/REST/RESTWithUserPoolIntegrationTests/RESTWithUserPoolIntegrationTests.swift, AmplifyPlugins/API/AWSAPICategoryPluginTests/Support/Utils/RESTRequestUtilsTests.swift
*Issue #977*
This PR fixes an issue where querystring  parameters aren't correctly encoded according per [AWS reference guide ](https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html)
`URLComponents` encodes queryItems values by strictly following [`RFC 3986`](https://tools.ietf.org/html/rfc3986), thus characters in the set ` !*';:+$,/?()` aren't percent-encoded.
This PR adds necessary changes to make the querystring compliant to AWS guidelines without double encoding those characters already encoded by `URLComponents`.
**AWSAPIGatewayClient** adopts a similar strategy by encoding the request URL before generating the signature:
https://github.com/aws-amplify/aws-sdk-ios/blob/main/AWSAPIGateway/AWSAPIGatewayClient.m#L97
**Reference**
- …
=> feat(api): fix querystring encoding according to AWS SigV4

Amplify/Categories/Analytics/AnalyticsCategory+HubPayloadEventName.swift, Amplify/Categories/Analytics/AnalyticsCategoryConfiguration.swift, Amplify/Categories/Analytics/AnalyticsProfile.swift, Amplify/Categories/Analytics/Error/AnalyticsError.swift, Amplify/Categories/Analytics/Event/BasicAnalyticsEvent.swift, AmplifyPlugins/Core/AWSPluginsCore/Auth/Configuration/AWSAuthorizationConfiguration.swift, AmplifyPlugins/Core/AWSPluginsCore/Model/GraphQLRequest/GraphQLRequest+AnyModelWithSync.swift
The issue on flutter side shows that getting the name from the model is not working as expected:
```
AWSPluginsCore/ModelBasedGraphQLDocumentBuilder.swift:20: Fatal error: Missing ModelSchema in ModelRegistry for model name: FlutterSerializedModel
```
This changes the code in the delete mutation path to be the same as the create/update mutation,  that gets the modelName from the schema, ie. `modelSchema.name` instead of `model.modelName`
=> fix: GraphQLBuilder use model name from schema instead of model

AmplifyPlugins/Core/AWSPluginsCore/Model/Decorator/AuthRuleDecorator.swift, AmplifyPlugins/Core/AWSPluginsCore/Model/GraphQLRequest/GraphQLRequest+AnyModelWithSync.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/InitialSync/InitialSyncOrchestrator.swift
As we support different @auth rules on models, if a model initial sync returns an `unauthorized` error we should consider the sync successful so that DataStore can reach a "ready" state.
=> fix(datastore): initalSync should be successful in case of unauthorized errors

AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginIntegrationTests/DataStoreHubEventsTests.swift
Fix outdated DataStore Hub integration tests.
`TestModels` are 22
https://github.com/aws-amplify/amplify-ios/blob/main/AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginIntegrationTests/TestSupport/TestModelRegistration.swift
=> chore(datastore): fix outdated hub integration tests

Amplify/Categories/DataStore/Subscribe/MutationEvent+Model.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/Statement+AnyModel.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/Statement+Model.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/StorageEngineAdapter+SQLite.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/StorageEngineAdapter+UntypedModel.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/StorageEngine+DeleteTransaction.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/StorageEngine.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/StorageEngineAdapter.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Storage/StorageEngineTestsBase.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/LocalSubscriptionWithJSONModelTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/ModelReconciliationDeleteTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/Support/MockSQLiteStorageEngineAdapter.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/TestSupport/Mocks/TestModelRegistration.swift
DataStore.delete API performs cascade delete by first deleting the model from local store. Before performing the delete transaction, it collects all the associated models and it's children recursively, and delete those as well. All local deletes (the parent and child objects) are then synced to the cloud.
The problem can be seen in Flutter when performing a cascade delete. There are various places in the flow where the system gets a model name from the wrong place. Wrong places to get the model name:
- modelType.modelName
- model.modelName (Similar PR fix here: https://github.com/aws-amplify/amplify-ios/pull/1292)
The correct place to get the model name is from the schema `modelSchema.name`. This is difficult to do in the cascade delete …
=> fix(DataStore): dynamic model support for cascade delete

AmplifyTools/AmplifyXcode/AmplifyXcode.xcodeproj/project.pbxproj, AmplifyTools/AmplifyXcode/AmplifyXcode.xcodeproj/xcshareddata/xcschemes/AmplifyXcode-Package.xcscheme, AmplifyTools/AmplifyXcode/AmplifyXcode.xcodeproj/xcshareddata/xcschemes/AmplifyXcode.xcscheme, AmplifyTools/AmplifyXcode/Sources/AmplifyXcode/CLICommandReportable.swift, AmplifyTools/AmplifyXcode/Sources/AmplifyXcodeCore/Commands/CommandImportConfig.swift, AmplifyTools/AmplifyXcode/Sources/AmplifyXcodeCore/Commands/CommandImportModels.swift, AmplifyTools/AmplifyXcode/Sources/AmplifyXcodeCore/Environment/AmplifyCommandEnvironment.swift, AmplifyTools/AmplifyXcode/Sources/AmplifyXcodeCore/Environment/CommandEnvironment.swift, AmplifyTools/AmplifyXcode/Sources/AmplifyXcodeCore/Support/XcodeProj+Helpers.swift, AmplifyTools/AmplifyXcode/Sources/AmplifyXcodeCore/Support/XcodeProject.swift, AmplifyTools/AmplifyXcode/Tests/AmplifyXcodeCoreTests/Core/AmplifyCommandEnvironmentTests.swift, AmplifyTools/AmplifyXcode/Tests/AmplifyXcodeCoreTests/Mocks/MockAmplifyCommandEnvironment.swift
*Issue:* https://github.com/aws-amplify/amplify-codegen/issues/190 
This PR introduces changes to `amplify-xcode` necessary to add Amplify files only to the Xcode "primary" target.
A target is considered "primary" if has the same name as the project and has type "application".
In the future we should expand on this to consider more platforms and target types (i.e. macOS and WatchOS).
=> fix(amplify-xcode): add files to primary target

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/ModelStorageBehavior.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/StorageEngineAdapter+SQLite.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/StorageEngineAdapter.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/ReconcileAndLocalSave/ReconcileAndLocalSaveOperation.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/Support/SQLiteResultError.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Core/SQLiteStorageEngineAdapterTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/MutationQueue/ProcessMutationErrorFromCloudOperationTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/ReconcileAndLocalSaveOperationTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/Support/MockSQLiteStorageEngineAdapter.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/Support/MockSQLiteStorageEngineAdapterResponders.swift, AmplifyPlugins/DataStore/DataStoreCategoryPlugin.xcodeproj/project.pbxproj
https://github.com/aws-amplify/amplify-ios/issues/1157 -> cascade delete fails for various reasons causing remote store to be missing the parent object. datastore full sync will fail in ReconcileAndLocalSaveOperation with a foreign key constraint violation when saving the child object. The ready event is not sent due to this failure.
https://github.com/aws-amplify/amplify-ios/issues/1310 -> also related to cascade delete failing, possible a bug in the cascade delete, however this fix will still be applicable to get the system in a ready state.
https://github.com/aws-amplify/amplify-ios/discussions/1097#discussioncomment-471914 -> additional context from @anatomybook. Sounds like "children without parents" scenario is bound to happen, not just in cascade delete. …
=> fix(DataStore): drop failed constraint violation reconciliations

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/AWSDataStorePlugin+DataStoreBaseBehavior.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/AWSDataStorePlugin.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Core/AWSAPICategoryPluginTests.swift
*Issue #, if available:* https://github.com/aws-amplify/amplify-flutter/issues/395
*Description of changes:* `.finished` events are not sent to datastore plugin subscribers when `Datastore.clear()`  and `Datastore.stop` is called 
=> fix(DataStore): do not send completion event to publisher on DataStore.clear() and DataStore.stop()

.gitignore, Amplify.xcodeproj/project.pbxproj, Amplify/Categories/API/Error/APIError.swift, Amplify/Categories/Analytics/Error/AnalyticsError.swift, Amplify/Categories/Auth/Error/AuthError.swift, Amplify/Categories/DataStore/DataStoreError.swift, Amplify/Categories/Predictions/Error/PredictionsError.swift, Amplify/Categories/Storage/Error/StorageError.swift, Amplify/Core/Support/AmplifyOperation+Combine.swift, Amplify/Core/Support/AmplifyOperation.swift, Amplify/Core/Support/OperationCancelledError.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/InitialSync/ModelSyncedEventEmitter.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/OutgoingMutationQueue/OutgoingMutationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/OutgoingMutationQueue/ProcessMutationErrorFromCloudOperation.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/OutgoingMutationQueue/SyncMutationToCloudOperation.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginAuthIntegrationTests/MultiAuth/AWSDataStoreMultiAuthBaseTest.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginIntegrationTests/SubscriptionEndToEndTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/MutationQueue/OutgoingMutationQueueNetworkTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/MutationQueue/OutgoingMutationQueueTestsWithMockStateMachine.swift, AmplifyPlugins/DataStore/DataStoreCategoryPlugin.xcodeproj/xcshareddata/xcschemes/AWSDataStoreCategoryPluginAuthIntegrationTests.xcscheme, AmplifyPlugins/DataStore/DataStoreCategoryPlugin.xcodeproj/xcshareddata/xcschemes/AWSDataStoreCategoryPluginIntegrationTests.xcscheme, AmplifyTests/CoreTests/AtomicValueTests.swift
*Issue #, if available:* During some investigation into an unrelated issue, I encountered race conditions in the SyncMutationToCloudOperation. My original implementation incorrectly subclassed it as an `Operation` rather than an `AsynchronousOperation`, which meant that after I fixed retain cycles in that class, it was being released before completing the callback. Digging into that fix led to another issue where `ModelSyncedEmitter` wasn't properly invoking the completion callbacks during initial sync when the sync included dropped events.
=> fix(DataStore): Fix race condition in sync mutation to cloud

AmplifyPlugins/Core/AWSPluginsCoreTests/Auth/AuthModeStrategyTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/StorageEngine+SyncRequirement.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/StorageEngineSyncRequirementsTests.swift
API key authentication mode doesn't require an auth plugin
=> fix: storage engine doesn't need auth plugin for api key

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/Support/SQLiteResultError.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Core/SQLiteStorageEngineAdapterTests.swift
https://github.com/aws-amplify/amplify-ios/issues/1364
Add missing imports for use of the sqlite3 constants. Able to reproduce this when building using the swift package over the pod workspace
=> fix(DataStore): add missing SQLite3 import

Amplify.xcodeproj/project.pbxproj, Amplify/Core/Support/AtomicDictionary.swift, Amplify/Core/Support/AtomicValue+Bool.swift, Amplify/Core/Support/AtomicValue+Numeric.swift, Amplify/Core/Support/AtomicValue+RangeReplaceableCollection.swift, Amplify/Core/Support/AtomicValue.swift, Amplify/Core/Support/Internal/NSLocking+Execute.swift, AmplifyPlugins/API/AWSAPICategoryPlugin/AWSAPIPlugin+Reachability.swift, AmplifyPlugins/API/AWSAPICategoryPlugin/AWSAPIPlugin+Resettable.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/OutgoingMutationQueue/MutationRetryNotifier.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/OutgoingMutationQueue/OutgoingMutationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/OutgoingMutationQueue/SyncMutationToCloudOperation.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/Support/Stopwatch.swift, AmplifyTests/CoreTests/AtomicValue+RangeReplaceableCollectionTests.swift, AmplifyTests/CoreTests/AtomicValueTests.swift
Per [@kneekey23's suggestion](https://github.com/aws-amplify/amplify-ios/pull/1345#discussion_r679629689) #1345, added a locking utility to encapsulate a bit of the boilerplate around synchronizing code with NSLocking instances.
=> chore: Add LockAndExecute util

Amplify.xcodeproj/project.pbxproj, Amplify/Categories/DataStore/DataStoreCategoryBehavior.swift, Amplify/Categories/DataStore/Subscribe/DataStoreCategory+Subscribe.swift, Amplify/Categories/DataStore/Subscribe/DataStoreQuerySnapshot.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/AWSDataStorePlugin+DataStoreBaseBehavior.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/AWSDataStorePlugin+DataStoreSubscribeBehavior.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/AWSDataStorePlugin.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/QuerySort+SQLite.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Subscribe/DataStoreObserveQueryOperation.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Subscribe/Support/Model+Sort.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginIntegrationTests/DataStoreObserveQueryTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginIntegrationTests/TestSupport/SyncEngineIntegrationTestBase.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/AWSDataStorePluginSubscribeBehaviorTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Core/AWSAPICategoryPluginTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Subscribe/DataStoreObserveQueryOperationTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Subscribe/Support/ModelSortTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/Support/MockSQLiteStorageEngineAdapter.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/Support/MockSQLiteStorageEngineAdapterResponders.swift, AmplifyPlugins/DataStore/DataStoreCategoryPlugin.xcodeproj/project.pbxproj, AmplifyTestCommon/Mocks/MockDataStoreCategoryPlugin.swift
Adding DataStore ObserveQuery API to provide a API that combines both the real-time update API (`Amplify.DataStore.publisher`) and the query API (`Amplify.DataStore.query`) to stream query snapshot events.
=> feat(DataStore): observe query API

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/ReconcileAndLocalSave/ReconcileAndLocalSaveOperation.swift
Fix deadlock in sqlite Connection.sync by moving publishers off of "SQLite.Database" queue as described in https://github.com/aws-amplify/amplify-ios/issues/1405
use `subscribe(on:)` in the transaction completion handler to move work off of the sqlite synchronous queue to the datastore's work queue.
A `receive(on:)` before the sink would probably work as well, but it seems like this work should be on the work queue rather than sqlite's queue.
I've validated this fixes my issue, but have no idea how to construct a test this would resolve.
=> fix(Datastore): deadlock in sqlite Connection.sync

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/ReconcileAndLocalSave/ReconcileAndLocalSaveOperation.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginIntegrationTests/DataStoreEndToEndTests.swift
Update ReconcileAndLocalSave to use internal dispatch queue, to avoid using the SQL queue as described in https://github.com/aws-amplify/amplify-ios/pull/1406 and https://github.com/aws-amplify/amplify-ios/issues/1405
Add integration test for concurrently saving posts.
=> fix(DataStore): ReconcileAndLocalSave schedule on internal queue

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/OutgoingMutationQueue/OutgoingMutationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/Support/Model+Compare.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/Support/MutationEvent+Extensions.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginIntegrationTests/DataStoreConsecutiveUpdatesTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/Support/ModelCompareTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/Support/MutationEventExtensionsTests.swift, AmplifyPlugins/DataStore/DataStoreCategoryPlugin.xcodeproj/project.pbxproj
*Issue #, if available:* #1206
*Description of changes:* This PR contains fix for Consecutive Update (Save, Sync, Update and Immediately Delete Scenario). The head of mutation event table for a given model id is reconciled with the version of the model in the API response after the models in the API request and response are compared for equality.
=> fix(Datastore): Consecutive Updates (Save, Sync, Update and Immediately Delete Scenario)

AmplifyPlugins/Storage/AWSS3StoragePlugin/AWSS3StoragePlugin+ClientBehavior.swift, AmplifyPlugins/Storage/AWSS3StoragePlugin/AWSS3StoragePlugin.swift, AmplifyPlugins/Storage/AWSS3StoragePlugin/Configuration/AWSS3PluginPrefixResolver.swift, AmplifyPlugins/Storage/AWSS3StoragePlugin/Configuration/AWSS3StoragePluginConfiguration.swift, AmplifyPlugins/Storage/AWSS3StoragePlugin/Operation/AWSS3StorageDownloadDataOperation.swift, AmplifyPlugins/Storage/AWSS3StoragePlugin/Operation/AWSS3StorageDownloadFileOperation.swift, AmplifyPlugins/Storage/AWSS3StoragePlugin/Operation/AWSS3StorageGetURLOperation.swift, AmplifyPlugins/Storage/AWSS3StoragePlugin/Operation/AWSS3StorageListOperation.swift, AmplifyPlugins/Storage/AWSS3StoragePlugin/Operation/AWSS3StorageRemoveOperation.swift, AmplifyPlugins/Storage/AWSS3StoragePlugin/Operation/AWSS3StorageUploadDataOperation.swift, AmplifyPlugins/Storage/AWSS3StoragePlugin/Operation/AWSS3StorageUploadFileOperation.swift, AmplifyPlugins/Storage/AWSS3StoragePlugin/Support/Utils/StorageErrorHelper.swift, AmplifyPlugins/Storage/AWSS3StoragePlugin/Support/Utils/StorageRequestUtils+Getter.swift, AmplifyPlugins/Storage/AWSS3StoragePluginFunctionalTests/AWSS3StoragePluginAccessLevelTests.swift, AmplifyPlugins/Storage/AWSS3StoragePluginFunctionalTests/AWSS3StoragePluginPrefixKeyResolverTests.swift, AmplifyPlugins/Storage/AWSS3StoragePluginFunctionalTests/AWSS3StoragePluginTestBase.swift, AmplifyPlugins/Storage/AWSS3StoragePluginFunctionalTests/README.md, AmplifyPlugins/Storage/AWSS3StoragePluginTests/Configuration/AWSS3PluginPrefixResolverTests.swift, AmplifyPlugins/Storage/AWSS3StoragePluginTests/Configuration/AWSS3StoragePluginConfigurationTests.swift, AmplifyPlugins/Storage/AWSS3StoragePluginTests/Operation/AWSS3StorageDownloadFileOperationTests.swift, AmplifyPlugins/Storage/AWSS3StoragePluginTests/Operation/AWSS3StorageGetDataOperationTests.swift, AmplifyPlugins/Storage/AWSS3StoragePluginTests/Operation/AWSS3StorageGetURLOperationTests.swift, AmplifyPlugins/Storage/AWSS3StoragePluginTests/Operation/AWSS3StorageListOperationTests.swift, AmplifyPlugins/Storage/AWSS3StoragePluginTests/Operation/AWSS3StorageOperationTestBase.swift, AmplifyPlugins/Storage/AWSS3StoragePluginTests/Operation/AWSS3StoragePutDataOperationTests.swift, AmplifyPlugins/Storage/AWSS3StoragePluginTests/Operation/AWSS3StorageRemoveOperationTests.swift, AmplifyPlugins/Storage/AWSS3StoragePluginTests/Operation/AWSS3StorageUploadFileOperationTests.swift, AmplifyPlugins/Storage/AWSS3StoragePluginTests/Support/Utils/StorageRequestUtilsGetterTests.swift, AmplifyPlugins/Storage/StoragePlugin.xcodeproj/project.pbxproj
**What is changing?**
This PR introduces a mechanism to provide a prefix resolver for S3 requests when performing storage APIs. Currently the storage request (`StorageAccessLevel`, targetIdentityId) is used to perform S3 prefix resolution and maps closely with the Amplify CLI configured S3 bucket policies (https://docs.amplify.aws/lib/storage/configureaccess/q/platform/ios). This allows a hook into the plugin for developers to provide their own logic for resolving the the prefix string.
**Why are we introducing this change?**
1. We have seen customer requests to allow them to change the prefix added by the plugin to align with their own S3 bucket rules
a. iOS Issue: https://github.com/aws-amplify/amplify-ios/issues/916
b. Android Issue: …
=> feat(Storage): AWSS3PluginPrefixResolver

AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginIntegrationTests/Connection/DataStoreConnectionScenario6Tests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginIntegrationTests/DataStoreEndToEndTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/TestSupport/SyncEngineTestBase.swift
*Description of changes:*  
1. add integration tests for verifying eager loading in belongs to relationship between models
2. move `Amplify.reset()` to `teardown()` in `SyncEngineTestBase` for avoid data race on line 47 and 48 in the unit test `ModelReconciliationDeleteTests.testUpdateAfterDelete()`
~~- [] Documentation update for the change if required~~
=> test(DataStore): Integration tests to verify eager loading in belongs-to relationship

CHANGELOG.md
Remove PR that was reverted from `main` branch. Automation picked it up even though there was a revert commit. This seems like a very low occurance scenario that I don't think we need to complicate the release process to account for reverts
=> chore: Update changelog, remove observeQuery

.circleci/config.yml, .gitignore, .swiftpm/xcode/package.xcworkspace/contents.xcworkspacedata
Introducing step to use `xcodebuild` to build the SPM workspace created under `.swiftpm/xcode`. Testing locally with
```
cd .swiftpm/xcode
xcodebuild build-for-testing -workspace package.xcworkspace -scheme Amplify-Package -sdk iphonesimulator -destination "platform=iOS Simulator,name=IPhone 11" | xcpretty
```
Build is successful, then remove `import Foundation` from one of the files in DataStore and build again to see the error.
```
❌  /aws-amplify/amplify-ios/AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Subscribe/DataStoreObserveQueryOperation.swift:117:59: cannot find type 'DispatchQueue' in scope
private let itemsChangedPeriodicPublishTimeInSeconds: DispatchQueue.SchedulerTimeType.Stride = 2
^~~~~~~~~~~~~
** TEST BUILD FAILED …
```
=> chore: Build Amplify for SPM in CircleCI

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Migration/MutationSyncMetadataMigrationDelegate+SQLite.swift
The migration script for the scenario where there were duplicate id's found across models were not clearing the ModelSyncMetadata table.
=> fix(DataStore): clear ModelSyncMetadata on duplicate ids found

Amplify.xcodeproj/project.pbxproj, Amplify/Categories/DataStore/Query/QueryPredicate.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Query/QueryPredicateEvaluateGeneratedEnumTests.swift
Predicate evaluation on a model for a predicate with Enum value was not returning the correct result. For example, a predicate "not equals" to PostStatus.published (`Post.keys.status.eq(PostStatus.published)`) used to evaluate a model with status == published would evaluate to false when it should be true. Debugging the code looks like it was falling into the default case of return false. This PR adds the code necessary to extract the string value from the model correctly so that it can be compared to the predicate's value as a String comparison.
=> fix(DataStore): support predicate evaluation on model with Enum

AmplifyPlugins/Core/AWSPluginsCore/Model/Decorator/AuthRuleDecorator.swift, AmplifyPlugins/Core/AWSPluginsCore/Model/GraphQLRequest/GraphQLRequest+AnyModelWithSync.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/Decorator/AuthRuleDecorator/ModelWithOwnerFieldAuthRuleTests.swift
This PR fixes an issue when multiple authentication rules with `allow: owner` can override each other.
=> fix(datastore): fix owner based subscriptions queries w/ multiauth

Amplify/Core/Configuration/AmplifyConfiguration.swift, CHANGELOG.md
Previews crash when it is not possible to load `awsconfiguration.json` when `Amplify.configure` is run which prevents this feature from working in Xcode.
#1508 
=> feat:(Core) prevents `Amplify.configure` while running for SwiftUI Previews

AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginAuthIntegrationTests/DefaultAuthCognito/AWSDataStoreCategoryPluginAuthOwnerIntegrationTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginAuthIntegrationTests/DefaultAuthCognito/Models/TodoCognitoPrivate+Schema.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginAuthIntegrationTests/DefaultAuthCognito/Models/TodoCognitoPrivate.swift, AmplifyPlugins/DataStore/DataStoreCategoryPlugin.xcodeproj/project.pbxproj
`allow: private` auth rule integration tests
~- [ ] Added new tests to cover change, if needed~
~- [ ] Build succeeds with all target using Swift Package Manager~
=> chore(datastore): allow private auth rule integration tests

Amplify.xcodeproj/project.pbxproj, AmplifyPlugins/Core/AWSPluginsCore/Auth/AWSAuthService.swift, AmplifyPlugins/Core/AWSPluginsCore/Auth/AWSAuthServiceBehavior.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Auth/AWSAuthServiceBehaviorTests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Auth/AWSAuthServiceTests.swift, Podfile.lock
*Issue #, if available:* 
443
Add new non-blocking APIs to AWSAuthServiceBehavior and deprecate existing blocking APIs.
=> feat(AWSPluginsCore): Add non-blocking methods to AWSAuthServiceBehavior / deprecate existing blocking methods  

AmplifyPlugins/API/AWSAPICategoryPlugin/Operation/AWSAPIOperation+APIOperation.swift, AmplifyPlugins/API/AWSAPICategoryPlugin/Operation/AWSGraphQLOperation+APIOperation.swift, AmplifyPlugins/API/AWSAPICategoryPlugin/URLSessionBehavior/OperationTaskMapper.swift, AmplifyPlugins/API/AWSAPICategoryPluginTests/Operation/AWSGraphQLOperationTests.swift
- `GraphQLOperation` is being retained by `OperationTaskMapper` causing memory leakage for large sync operations
- Remove `GraphQLOperation` from `OperationTaskMapper` upon completion
=> fix(API): Memory leak in GraphQLOperation

Amplify/Categories/Auth/AuthCategoryBehavior.swift
add missing doc comment to Auth signOut API
- ~~[ ] PR title conforms to conventional commit style~~
=> chore: add missing doc comment to Auth signOut API

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/SQLStatement+CreateTable.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/SQLStatement+Delete.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/SQLStatement+Insert.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/SQLStatement+Select.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/StorageEngineAdapter+SQLite.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Core/SQLStatementTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Core/SQLiteStorageEngineAdapterTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Migration/SQLiteMutationSyncMetadataMigrationDelegateTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/TestSupport/Mocks/TestModelRegistration.swift, AmplifyTestCommon/Models/ReservedWords/Group+Schema.swift, AmplifyTestCommon/Models/ReservedWords/Group.swift, AmplifyTestCommon/Models/ReservedWords/Row+Schema.swift, AmplifyTestCommon/Models/ReservedWords/Row.swift
#1477 
Quote table name in create table-references SQL statement. 
Ref: [SQLite keywords](https://www.sqlite.org/lang_keywords.html)
=> fix(datastore): quote table name in create table-references SQL statement

AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Dependency/AuthorizationProviderAdapter+SignedInSession.swift
When fetching a session for a user account that is signed in, but has been deleted, perform the following actions:
1. Sign out locally
2. Emit signedOut hub event
3. Return a signed out session
=> fix(auth): handle deleted account when fetching signed in session

AmplifyPlugins.podspec, AmplifyPlugins/API/AWSAPICategoryPlugin/AWSAPIPlugin+Configure.swift, AmplifyPlugins/API/AWSAPICategoryPlugin/AWSAPIPlugin+Log.swift, AmplifyPlugins/API/AWSAPICategoryPluginFunctionalTests/GraphQLModelBased/GraphQLModelBasedTests.swift, AmplifyPlugins/API/AWSAPICategoryPluginTests/AWSAPICategoryPlugin+ReachabilityTests.swift, AmplifyPlugins/API/AWSAPICategoryPluginTests/AWSAPICategoryPluginTestBase.swift, AmplifyPlugins/API/AWSAPICategoryPluginTests/Operation/AWSGraphQLSubscriptionOperationCancelTests.swift, AmplifyPlugins/API/Podfile, AmplifyPlugins/API/Podfile.lock, AmplifyPlugins/DataStore/Podfile.lock, Package.resolved, Package.swift
Sets AppSyncRealTimeClient's log level based on Amplify.Logging.logLevel at config time
=> feat(API): Set AppSyncRTClient log level from Amplify log level

AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Dependency/AuthenticationProviderAdapter+SignIn.swift
*Issue #:* [1617](https://github.com/aws-amplify/amplify-ios/issues/1617)
fix(auth): handle errors returned from Social SignIn sessions
Lambda errors, along with other error types, are returned from Social SignIn sessions as "invalid request" errors.  Currently all these errors are being returned as "unknown error".  This change will wrap these errors in a service error and return them with the appropriate error description.
By submitting this pull request, I confirm that my contribution is made under the terms of …
=> feat(auth): handle errors returned from Social Sign In sessions

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/AWSMutationDatabaseAdapter/AWSMutationDatabaseAdapter+MutationEventIngester.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/AWSMutationDatabaseAdapter/AWSMutationDatabaseAdapter+MutationEventSource.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/AWSMutationDatabaseAdapter/AWSMutationDatabaseAdapter.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/OutgoingMutationQueue/ProcessMutationErrorFromCloudOperation.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/AWSDataStorePluginSubscribeBehaviorTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Subscribe/DataStoreObserveQueryOperationTests.swift, AmplifyPlugins/DataStore/DataStoreCategoryPlugin.xcodeproj/xcshareddata/xcschemes/AWSDataStoreCategoryPlugin.xcscheme, Package.resolved
https://github.com/aws-amplify/amplify-ios/issues/1434
- Use of `nextEventPromise` was not thread safe
- use of `mutationOperation` was not thread safe
- testing ObserveQuery snapshot exercises Combine's `.collect` that sometimes ran unexpectedly, so we assert on the minimum
- enable thread sanitzer by default
=> fix(DataStore): enable thread sanitzer, fix data races

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/IncomingAsyncSubscriptionEventPublisher.swift
Add additional logging around which model failed the subscription request.
```
API Subscription failed for model `User5` with error: Subscription item event failed with error
```
=> fix(DataStore): add logging with model name for failed subscription request

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Migration/MutationSyncMetadataMigrationDelegate+SQLite.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Migration/MutationSyncMetadataMigrationDelegate+SQLiteValidation.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/StorageEngineAdapter+SQLite.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/StorageEngineAdapter+UntypedModel.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/StorageEngineMigrationAdapter+SQLite.swift
https://github.com/aws-amplify/amplify-ios/issues/1459
When `DataStore.clear` is called during sync, `connection = nil` which will close the SQLite connection. If sync process is running, it will access the `connection` object that is force unwrapped. 
=> fix(DataStore): FatalError accessing SQLite connection

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Subscribe/DataStoreObserveQueryOperation.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Subscribe/Support/SortedList.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Subscribe/Support/SortedListTests.swift
*Issue #, if available:* https://github.com/aws-amplify/amplify-ios/issues/1627
=> fix(DataStore): ObserveQuery InitialQuery empty modelIds set

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/StorageEngineAdapter+SQLite.swift
During debugging, I'd like to view the DB file path so that I can view the SQLite contents using a SQLite browser.
This PR moves some of the private fields over to internal so that they can be accessed under `@testable` import.
```swift
import Foundation
import Amplify
@testable import AmplifyPlugins
struct DataStoreDebugger {
static var dbFilePath: URL? { getAdapter()?.dbFilePath }
static func getAdapter() -> SQLiteStorageEngineAdapter? {
if let dataStorePlugin = tryGetPlugin(),
let storageEngine = dataStorePlugin.storageEngine as? StorageEngine,
let adapter = storageEngine.storageAdapter as? SQLiteStorageEngineAdapter {
return adapter
}
print("Could not get `SQLiteStorageEngineAdapter` from DataStore")
return nil
}
static func …
```
=> fix(DataStore): Debugging - Access DB File path

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/AWSDataStorePlugin+DataStoreBaseBehavior.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/AWSDataStorePlugin+DataStoreSubscribeBehavior.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/AWSDataStorePlugin.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Core/AWSAPICategoryPluginTests.swift
Originally from https://github.com/aws-amplify/amplify-ios/pull/1438 picking this up and making a few more changes
- replacing the semaphore with dispatchqueue, using `sync` to serially access the `storageEngine`. The plugin holds a reference to storageEngine and will nil it out when it's cleared, the deinit chain will close the internal SQLite connection, which is the reason why we need to do this work under a semaphore or `sync` block.
- rebased with `main`
=> fix(DataStore): Clear API should delete local store

Package.swift
https://github.com/aws-amplify/amplify-ios/issues/1697
Bumps Swift SDK and ClientRuntime versions to `0.1.4` to support Swift 5.6
=> chore: bump swift sdk and clientruntime version to support Swift 5.6

AmplifyPlugins/API/AWSAPICategoryPlugin/AWSAPIPlugin.swift
*Description of changes:* Follow up PR to https://github.com/aws-amplify/amplify-ios/pull/1705. Remove `iReachabilityMap` field from `AWSAPIPlugin.swift`.
~~- [ ] All integration tests pass~~
=> chore(DataStore): Remove ireachabilityMap field

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/InitialSync/InitialSyncOperation.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/OutgoingMutationQueue/OutgoingMutationQueue+Action.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/OutgoingMutationQueue/OutgoingMutationQueue+Resolver.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/OutgoingMutationQueue/OutgoingMutationQueue+State.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/OutgoingMutationQueue/OutgoingMutationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngine+Action.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngine+IncomingEventReconciliationQueueEvent.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngine+Resolver.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngine+State.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngine.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/AWSIncomingEventReconciliationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/IncomingEventReconciliationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/ReconcileAndLocalSave/RemoteSyncReconciler.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginIntegrationTests/DataStoreEndToEndTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginIntegrationTests/TestSupport/DataStoreHubEvent.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/MutationQueue/OutgoingMutationQueueTestsWithMockStateMachine.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/RemoteSyncReconcilerTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/TestSupport/Mocks/MockAWSIncomingEventReconciliationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/TestSupport/Mocks/MockOutgoingMutationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/TestSupport/Mocks/MockReconciliationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/TestSupport/Mocks/NoOpMutationQueue.swift, AmplifyPlugins/DataStore/DataStoreCategoryPlugin.xcodeproj/project.pbxproj
Reconcile locally sourced mutations to save/update/delete the model and metadata into local store. The locally sourced mutation response is identical to the subscription event that would be received on subscriptions, so reuse the reconciliation queue to process it. 
A concern regarding this is the real-time events behavior of the additional event. Currently, locally sourced mutations with subscriptions enabled will emit 2 events, one from the operation on local store and one from the subscription event being reconciled to the local store. By handling the locally sourced mutation event, the subscription event would attribute to a third real-time event. The reconciliation logic has been updated to to ignore the remote model when the local …
=> fix(DataStore): Reconcile locally sourced mutations while subscriptions are disabled

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/OutgoingMutationQueue/SyncMutationToCloudOperation.mmd, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/OutgoingMutationQueue/SyncMutationToCloudOperation.swift
Related: https://github.com/aws-amplify/amplify-js/pull/9724
Analyze the sequence for sending mutations to AppSync
```mermaid
%% SyncToCloudOperation
sequenceDiagram
participant OutgoingMutationQueue
participant StorageAdapter
participant ProcessMutationErrorFromCloudOperation
participant SyncToCloudOperation
participant API
participant RequestRetryablePolicy
participant NetworkReachability
participant MutationRetryNotifier
participant Hub
OutgoingMutationQueue->>SyncToCloudOperation: Add SyncToCloudOperation(MutationEvent, authType)
SyncToCloudOperation->>SyncToCloudOperation: Create GraphQL request (mutationType, authType)
SyncToCloudOperation->>API: API.mutate(request)
alt Success
API->>SyncToCloudOperation: GraphQL response …
```
=> chore(DataStore): Add SyncToCloudOperation sequence

AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/Dependency/AWSPinpointAdapter.swift
https://github.com/aws-amplify/amplify-ios/issues/1307
https://github.com/aws-amplify/amplify-ios/issues/662
The current version makes it impossible to use APNS sandbox during development.
Changing the config from outside works but it updates the endpoint in an unstable way. Something like this:
```swift
let plugin = try Amplify.Analytics.getPlugin(for: PluginKey("awsPinpointAnalyticsPlugin")) as! AWSPinpointAnalyticsPlugin
let pinpoint = plugin.getEscapeHatch()
pinpoint.configuration.debug = true
```
This PR uses Xcode's `DEBUG` directive to turn on pinpoint debug mode.
=> fix(analytics): Set `pinpointConfiguration.debug` for APNS sandbox

Amplify/Categories/DataStore/DataStoreCategory+Behavior+Combine.swift, Amplify/Categories/DataStore/DataStoreCategory+Behavior.swift, Amplify/Categories/DataStore/DataStoreCategoryBehavior.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginIntegrationTests/Connection/DataStoreConnectionScenario6Tests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginIntegrationTests/DataStoreLocalStoreTests.swift, AmplifyTestCommon/Mocks/MockAuthCategoryPlugin.swift, AmplifyTestCommon/Mocks/MockDataStoreCategoryPlugin.swift, AmplifyTestCommon/Mocks/MockDataStoreResponders.swift
Related documentation update https://github.com/aws-amplify/docs/pull/4177
Make `delete(modelType:where:)` API publicly accessible.
- Delete all models of the modelType, according to the `where` predicate.
- the `where` parameter is required, to avoid accidentally deleting all models of the modelType without passing in the predicate to filter down the results, ie. developer cannot do this: `DataStore.delete(ModelType.self)`
- To delete all models of that modelType, pass in `QueryPredicateConstant.all` 
```swift
Amplify.DataStore.delete(Tag.self, where: QueryPredicateConstant.all) { result in
switch result {
case .success:
print("Deleted All")
case .failure(let error):
print("\(error)")
}
}
```
*Check points: (check or cross out if not …
=> feat(DataStore): DataStore.delete(modelType:where:) API

.github/workflows/integ_test.yml
*Description of changes:* Fix the github action integration workflow to separate different tests inside datastore and api. 
Before change:
After change:
=>  chore: Run api and datastore integ test as different jobs

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/AWSDataStorePlugin+DataStoreBaseBehavior.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/ModelStorageBehavior.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/StorageEngineAdapter+SQLite.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/StorageEngine+DeleteTransaction.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/StorageEngine.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/StorageEngineAdapter.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/AWSMutationDatabaseAdapter/AWSMutationDatabaseAdapter+MutationEventIngester.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/OutgoingMutationQueue/ProcessMutationErrorFromCloudOperation.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/ReconcileAndLocalSave/ReconcileAndLocalSaveOperation.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Core/SQLiteStorageEngineAdapterJsonTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Core/SQLiteStorageEngineAdapterTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Storage/StorageEngineTestsBase.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/Support/MockSQLiteStorageEngineAdapter.swift
Delete API has the following use cases
1. Delete model instance / delete model type by id (`DataStore.delete(model)` / `DataStore.delete(modelType:withId)`)
2. Delete model instance conditionally / delete model type by id and condition (`DataStore.delete(model:where)` / `DataStore.delete(modelType:withId:where)`)
3. Delete model type with filter (`DataStore.delete(modelType:where)`)
This internally renames `predicate` to `condition` for use case 2 and `filter` for use case 3 for better clarity on the type of `predicate` the parameter is. Also refactor some the caller code that calls `queryAndDeleteTransaction` 
By submitting this pull request, I confirm that my contribution is made …
=> chore(DataStore): Internal Delete API rename (predicate to condition and filter)

.github/composite_actions/run_xcodebuild_test/action.yml, .github/workflows/integ_test.yml
Add cocoapods caching to integration tests.  This will speed up tests and eliminate 429 throttling errors from repeatedly cloning pods repos.
- ~[ ] If breaking change, documentation/changelog update with migration instructions~
=> chore: add cocoapods caching to integration tests.

AmplifyPlugins/Core/AWSPluginsCore/ServiceConfiguration/AmplifyAWSServiceConfiguration.swift
Removed an outdated TODO about retrieving configs from a centralized location. That TODO was closed wontfix in 2021.
=> chore: Removed outdated TODO

AmplifyPlugins/Auth/AWSCognitoAuthPlugin/AWSCognitoAuthPlugin+Configure.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/ConfigurationTests/AWSCognitoAuthPluginConfigTests.swift, AmplifyPlugins/Core/AWSPluginsCore/ServiceConfiguration/AmplifyAWSServiceConfiguration.swift
Android SKD supports custom endpoint for Cognito User Pool, while iOS version isn't. This PR adds support of this.
=> Auth plugin: Add support of custom endpoint for CognitoUserPool

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/FetchAuthorizationSession/UserPool/ConfigureUserPoolToken.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Models/AWSAuthCognitoSession.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Models/AuthCognitoTokens+Validation.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ActionTests/FetchAuthSession/FetchUserPoolTokens/ConfigureUserPoolTokenTests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/Support/AWSAuthCognitoSessionTests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/Support/CognitoAuthTestHelper.swift
Fixing token expiring logic to use JWT tokens instead of the API response expiration date. 
=> bugfix(Auth): Fixing the token expiring logic

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/InitialSync/InitialSyncOrchestrator.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngine+Retryable.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/RemoteSyncEngineTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/TestSupport/Mocks/MockRequestRetryablePolicy.swift
This PR fixes **RemoteSyncEngine** to accurately determine whether it should retry based on the URLError. Previously, when errors were handled, they were ignored and a hardcoded `URLError.notConnected` is passed to the `retryRequestAdvice` method to get the advice to retry. This is a bug when the error is a non-retryable error, since the RemoteSyncEngine's retry attempt will immediately fall into the same errored state. For example, data decoding issues which should be non-retryable but the bug caused the sync engine to restart a number of times up to the limit determine by the algorithm in **RequestRetryablePolicy**.
- RemoteSyncEngine's error handling path to stop using the hardcoded `URLError` and start checking against a real URLError, retrieved from the underlying error. All …
=> fix(DataStore): retry initial sync network failures from RemoteSyncEngine

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RequestRetryablePolicy.swift
https://github.com/aws-amplify/amplify-ios/issues/1718#issuecomment-1122536571
We know from trial and error that when running on a device, the URLError returned after toggling the network state will return `.dataNotAllowed`. This is a quick fix to make sure the library handles this error by retrying. By not retrying, we are essentally classifying a retryable error as non retryable.
As a longer term follow-up, we should do more extensive testing on possible URLErrors returned, and essentially map the URLError codes https://developer.apple.com/documentation/foundation/urlerror/code to retryable and non-retryable. That exercise should result in either adding more to the list to retry, or we can invert the list to always retry except for a …
=> fix(DataStore): retry on URLError.dataNotAllowed

.swiftpm/xcode/xcshareddata/IDETemplateMacros.plist
Adding files in the xcodeproj generated by opening Package.swift doesn't produce the typical file header.
```
//
// Copyright Amazon.com Inc. or its affiliates.
// All Rights Reserved.
//
// SPDX-License-Identifier: Apache-2.0
//
```
This change adds an IDETemplateMacros.plist to the xcshareddata directory to autogenerate the correct file header when using Package.swift.
=> chore: Add IDETemplateMacros.plist for file header generation with spm [skip ci]

AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Support/Constants/AuthPluginErrorConstants.swift
[#1782 ](https://github.com/aws-amplify/amplify-ios/issues/1782)
Fixing a typo
=> fix(Auth): Fixing a typo in the Auth error message (#1782)

AmplifyPlugins/Auth/AWSCognitoAuthPlugin/AWSCognitoAuthPlugin+Configure.swift, AmplifyPlugins/Auth/AWSCognitoAuthPlugin/AWSCognitoAuthPlugin.swift, AmplifyPlugins/Auth/AWSCognitoAuthPlugin/ClientBehavior/AWSCognitoAuthPlugin+ClientBehavior.swift, AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Dependency/AuthenticationProviderAdapter+SignIn.swift, AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Models/Options/AWSAuthSignInOptions.swift, AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Operations/AWSAuthSignInOperation.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/AuthSignInTests/AuthUsernamePasswordSignInTests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthenticationProviderTests/AuthenticationProviderSigninTests.swift
*Description of changes:* Add runtime support for auth flow type. AWSCognitoPlugin currently supports SRP and Custom auth flow types to be changed during runtime.
Usage:
```
let options = AWSAuthSignInOptions(authFlowType: .custom)
Amplify.Auth.signIn(username: user,
password: password,
options: .init(pluginOptions: options))
```
=> feat(auth): Add support for authType as runtime parameter

AmplifyTestCommon/TestCommonConstants.swift
#1781
* Integration tests are passing when running locally and failing as part of Github Actions.  Updating the network timeout to see if this fixes integration tests running as part of GitHub Actions.
=> test: increase network timeout for integration tests

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/ModelSchema+SQLite.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/SQLStatement+CreateIndex.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Core/SQLStatementTests.swift
When a model has a composite primary key, codegen generates an `.index` attribute in the model schema with a `nil` name.
This PR re-introduces the necessary changes to create local secondary indexes on the fields that make up the primary key.
Since in this scenario the index name is `nil` a default name will be used by concatenating the names of fields separated by "_" with an additional suffix of "_pk".
=> fix(datastore): create indexes for custom primary key

Package.swift
None
A build flag will be defined for builds so the following block can wrap code which should not be included in the GA release.
```swift
#if DEV_PREVIEW_BUILD
// code which is being deprecated which will be removed before GA release
#else
#warning("Dead code, please remove before GA.")
#endif
```
Adopting Swift Concurrency with more async functions will require breaking changes and so temporary workarounds will be in place to help with migrating to the new APIs.
Defines a build flat for dev-preview.
=> adds DEV_PREVIEW_BUILD build flag to Package.swift for all plugin targets

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/AWSCognitoAuthPlugin+Configure.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/AWSCognitoAuthPlugin.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/AuthConfigureOperation.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Data/IdentityPoolConfigurationData.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Data/UserPoolConfigurationData.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/States/AuthState.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Helpers/ConfigurationHelper.swift
Moving the task of configuring the credential store and auth state machine to the operation queue. This way we can make sure that the statemachine are always configured before starting any operation. 
=> chore(auth): Change the configuration and add configure to the op-queue

AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/Dependency/AWSPinpointAdapter+AnalyticsClientBehavior.swift, AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/Dependency/Pinpoint/Analytics/AnalyticsClient.swift, AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/Dependency/Pinpoint/Endpoint/EndpointClient.swift, AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/Dependency/Pinpoint/PinpointContext.swift, AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/Dependency/Pinpoint/Session/SessionClient.swift
This PR introduces the changes to make `AnalyticsClient` an actor to enforce synchronization for reads/writes to its inner state.
The `createAppleMonetizationEvent`, `createVirtualMonetizationEvent`, `createMonetizationEvent` and `createEvent` APIs are marked as `nonisolated` as they're just factories to instantiate new events and don't mutate the internal state.
=> feat(analytics): protect AnalyticsClient state with actor

.github/composite_actions/run_xcodebuild_test/action.yml, .swiftpm/xcode/xcshareddata/xcschemes/Amplify.xcscheme
- Fixing `.github/composite_actions/run_xcodebuild_test/action.yml` to actually run the scheme passed in the input
- Adding `AmplifyTests` to the `Amplify` scheme
=> chore: fix unit tests workflow

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/AWSAuthSignInOperation.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/AWSAuthSignOutOperation.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/AmplifyConfirmSignInOperation.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/States/AuthorizationState.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/States/DebugInfo/AuthorizationState+Debug.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/Authorization/AuthorizationState+Resolver.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/SignOut/SignOutState+Resolver.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/StateMachineSupport/StateMachineEvent+Type.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/OperationTests/AWSAuthSignInOperationTests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ResolverTests/SignOutState/SignOutStateResolverTests.swift
*Description of changes:* Updates signIn, signOut and confirmSignIn to use the refactored flow.
This is the continuation of the PRs from: 
https://github.com/aws-amplify/amplify-ios/pull/1916 chore: Fix fetchauthsession helper
https://github.com/aws-amplify/amplify-ios/pull/1914 test(auth): Fix unit test errors for authorization statemachine refctor
https://github.com/aws-amplify/amplify-ios/pull/1897 chore: Refactor authorization flow, adds refresh flow
https://github.com/aws-amplify/amplify-ios/pull/1872 chore: Change credential state machine and authorization flow
Pending work:
=> fix: SignIn, signOut and confirmsignIn with new authorizationflow

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/AWSCognitoAuthPlugin+Configure.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/CredentialStore/MigrateLegacyCredentialStore.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/CredentialStorage/AWSCognitoAuthCredentialStore.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/CredentialStorage/AmplifyAuthCredentialStoreBehavior.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Environment/CredentialStoreEnvironment.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ActionTests/CredentialStore/MigrateLegacyCredentialStoreTests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ActionTests/CredentialStore/MockAmplifyCredentialStoreBehavior.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/Support/DefaultConfig.swift
*Description of changes:* Enable migration flow, after refactoring authorization flow.
This is the continuation of the PRs from: 
https://github.com/aws-amplify/amplify-ios/pull/1919 fix: SignIn, signOut and confirmsignIn with new authorizationflow
https://github.com/aws-amplify/amplify-ios/pull/1916 chore: Fix fetchauthsession helper
https://github.com/aws-amplify/amplify-ios/pull/1914 test(auth): Fix unit test errors for authorization statemachine refctor
https://github.com/aws-amplify/amplify-ios/pull/1897 chore: Refactor authorization flow, adds refresh flow
https://github.com/aws-amplify/amplify-ios/pull/1872 chore: Change credential state machine and authorization flow
Pending work:
By submitting this pull …
=> fix: Migration of legacy store with new authorization flow

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/AWSDataStorePlugin.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngine+IncomingEventReconciliationQueueEvent.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngine.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Core/AWSDataStorePluginTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/Support/MockSQLiteStorageEngineAdapter.swift, AmplifyPlugins/DataStore/DataStoreCategoryPlugin.xcodeproj/project.pbxproj
https://github.com/aws-amplify/amplify-ios/issues/1839
When the app is placed in the background for an extended period of time, the subscriptions get severed. This causes the sync engine to transition its state to cleanUp(error), and then scheduleRestartOrTerminate. Since the subscription error isn't handled as a retryable network error, the sync engine transitions to a terminal state. If the sync engine can accurately check the error from its downstream components as a retryable network error, then it can also perform the restart of the sync process. For this fix, we aren't addressing whether the subscription error should be handled as a retryable or non-retryable error at the moment, and generalize this problem to handling non-retryble …
=> fix(datastore): stop sync engine on non-retryable errors to allow restart

AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/AWSPinpointAnalyticsPlugin+Configure.swift, AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/Dependency/AWSPinpointAdapter.swift, AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/Dependency/Pinpoint/Analytics/AnalyticsClient.swift, AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/Dependency/Pinpoint/Analytics/EventRecorder.swift, AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/Dependency/Pinpoint/PinpointContext.swift, AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/Dependency/Pinpoint/Session/SessionClient.swift, AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/LocalStorage/LocalStorageError.swift, AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/LocalStorage/SQLiteLocalStorageAdapter.swift, AmplifyPlugins/Analytics/AWSPinpointAnalyticsPluginTests/AWSPinpointAnalyticsPluginConfigureTests.swift, AmplifyPlugins/Analytics/AWSPinpointAnalyticsPluginTests/AnalyticsEventStorageTests.swift, AmplifyPlugins/Analytics/AWSPinpointAnalyticsPluginTests/Mocks/Pinpoint/MockEventRecorder.swift, AmplifyPlugins/Analytics/AWSPinpointAnalyticsPluginTests/Mocks/Pinpoint/MockFileManager.swift, AmplifyPlugins/Analytics/AWSPinpointAnalyticsPluginTests/Pinpoint/AnalyticsClientTests.swift, AmplifyPlugins/Analytics/AWSPinpointAnalyticsPluginTests/SQLiteLocalStorageAdapterTests.swift
- Adding unit tests for `AnalyticsClient`
- Doing some refactoring/clean up in order to facilitate testing and de-couple certain classes from each other.
- Automatically starting app session tracking if the flag is enabled in the configuration.
- Simplifying `SQLiteLocalStorageAdapterTests` and `AnalyticsEventStorageTests` with a mocked FileManager.
=> feat(Analytics): Adding unit tests for AnalyticsClient

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/ModelSchema+SQLite.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Core/SQLStatementTests.swift, AmplifyTestCommon/Models/CustomPrimaryKey/CommentWithCompositeKeyAndIndex+Schema.swift, AmplifyTestCommon/Models/CustomPrimaryKey/CommentWithCompositeKeyAndIndex.swift, AmplifyTestCommon/Models/CustomPrimaryKey/PostWithCompositeKeyAndIndex+Schema.swift, AmplifyTestCommon/Models/CustomPrimaryKey/PostWithCompositeKeyAndIndex.swift, AmplifyTestCommon/Models/CustomPrimaryKey/primarykey_schema.graphql
This PR introduces a change that skip SQL indexes creation when the fields involved are used to represent associations.
=> fix(datastore): avoid creating index on foreign key fields

AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/ReconcileAndLocalSaveOperationTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/Support/MutationEventExtensionsTests.swift, AmplifyPlugins/DataStore/DataStoreCategoryPlugin.xcodeproj/xcshareddata/xcschemes/AWSDataStoreCategoryPlugin.xcscheme
*Issue #1903*
chore(datastore): skip broken datastore tests until they can be fixed
- ~~[ ] Security oriented best practices and standards are followed (e.g. using input sanitization, principle of least privilege, etc)~~
=> chore(datastore): skip broken datastore tests

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/Model+SQLite.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Models/SQLModelValueConverterTests.swift, AmplifyTestCommon/Models/CustomPrimaryKey/CommentWithCompositeKeyAndIndex+Schema.swift, AmplifyTestCommon/Models/CustomPrimaryKey/CommentWithCompositeKeyAndIndex.swift, AmplifyTestCommon/Models/CustomPrimaryKey/PostTagsWithCompositeKey+Schema.swift, AmplifyTestCommon/Models/CustomPrimaryKey/PostTagsWithCompositeKey.swift, AmplifyTestCommon/Models/CustomPrimaryKey/PostWithCompositeKeyAndIndex+Schema.swift, AmplifyTestCommon/Models/CustomPrimaryKey/PostWithCompositeKeyAndIndex.swift, AmplifyTestCommon/Models/CustomPrimaryKey/PostWithTagsCompositeKey+Schema.swift, AmplifyTestCommon/Models/CustomPrimaryKey/PostWithTagsCompositeKey.swift, AmplifyTestCommon/Models/CustomPrimaryKey/TagWithCompositeKey+Schema.swift, AmplifyTestCommon/Models/CustomPrimaryKey/TagWithCompositeKey.swift
This PR introduces the necessary changes to produce the correct SQL values for a serialized JSON model used in an association.
=> fix(datastore): resolve PK value in JSONValue models

.github/workflows/integ_test.yml
https://github.com/aws-amplify/amplify-ios/issues/1781
This PR adds fine grain control over the tests in the integration test workflow. Each test is a step which can be run, continue if error, or skipped:
- completely skipped: `if: ${{ false }}`
- continue on error: `continue-on-error: true`
Example workflow: https://github.com/aws-amplify/amplify-ios/actions/runs/2542707371 . This workflow passed even though storage and datastore tests failed. At this time, we'll enable most of the base integration tests of each plugin. This includes storage, auth, api and datastore's first tests, geo, analytics. For flaky base tests, set `continue-on-error` for storage, auth, api, datastore. So, geo and analytics will fail the workflow if it fails. And …
=> chore: enable integ workflow and disable specific steps

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/ClientBehavior/AWSCognitoAuthPlugin+ClientBehavior.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/UserOperations/AWSAuthResendSignUpCodeOperation.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/UserOperations/AWSAuthResetPasswordOperation.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Service/CognitoUserPoolBehavior.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Service/ErrorMapping/ForgotPasswordOutputError+AuthError.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Request/AuthResetPasswordRequest+Validation.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/OperationTests/ClientBehaviorTests/AWSCognitoAuthClientBehaviorTests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/OperationTests/ClientBehaviorTests/ClientBehaviorResetPasswordTests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/Support/MockIdentityProvider.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthHostApp.xcodeproj/project.pbxproj, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/ResetPasswordTests/AuthResetPasswordTests.swift
*Description of changes:* Add resetPassword API implementation based on `aws-sdk-swift`.
=> feat(auth): Add Reset Password API implementation

.github/workflows/new_issue_maintainer.yml
N/A
Adds a GitHub Action to comment the following on issues opened by maintainers.
> This issue was opened by a maintainer of this repository; updates will be posted here. If you are also experiencing this issue, please comment here with any relevant information so that we're aware and can prioritize accordingly.
*We should look accessing the list of maintainers from the GitHub API or through a txt file. We're now maintaining this list here and in `notify_new_issue_comment`, which isn't great.
=> chore: add action to post message for maintainer opened issues

AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/AWSPinpointAnalyticsPlugin+ClientBehavior.swift, AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/Dependency/Pinpoint/Analytics/AnalyticsClient.swift, AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/Dependency/Pinpoint/Analytics/EventRecorder.swift, AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/Dependency/Pinpoint/Analytics/PinpointEvent+AnalyticsEvent.swift, AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/Dependency/Pinpoint/Analytics/PinpointEvent+PinpointClientTypes.swift, AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/Dependency/Pinpoint/Analytics/PinpointEvent.swift, AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/Dependency/Pinpoint/Endpoint/EndpointClient.swift, AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/Dependency/Pinpoint/Session/PinpointSession.swift, AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/LocalStorage/PinpointEvent+Bindings.swift, AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/Support/Extensions/AWSPinpointAnalyticsPlugin+HubCategory.swift, AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/Support/Extensions/Date+Formatting.swift, AmplifyPlugins/Analytics/AWSPinpointAnalyticsPluginTests/AWSPinpointAnalyticsPluginClientBehaviorTests.swift, AmplifyPlugins/Analytics/AWSPinpointAnalyticsPluginTests/AnalyticsEventStorageTests.swift, AmplifyPlugins/Analytics/AWSPinpointAnalyticsPluginTests/EventRecorderTests.swift, AmplifyPlugins/Analytics/AWSPinpointAnalyticsPluginTests/Mocks/Pinpoint/MockEndpointClient.swift, AmplifyPlugins/Analytics/AWSPinpointAnalyticsPluginTests/Pinpoint/EndpointClientTests.swift
**Description of changes:**
This PR does a couple of things, but mainly focuses in fixing some issues that prevented events from being submitted to the Pinpoint backend and/or to show correctly in the console:
- Forced the ISO8061 format to have an explicit trailing `Z` instead of the `+0000` offset, as otherwise the request was rejected. Did so by creating our own `DateFormatter` and extensions so that it's easier to use.
- Fixed the Event timestamp being calculated wrong before submission (they were stored in milliseconds but used as seconds, resulting in dates many many years in the future 😆 )
- Removed the empty string we were using for the `SdkVersion`, as it was rejected otherwise. A `nil` value is accepted for now, but I've kept the `//TODO` comment so we don't forget to follow up. …
=> feat(Analytics): Fixing issues when submitting events

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/ClientBehavior/AWSCognitoAuthPlugin+ClientBehavior.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/UserOperations/AWSAuthConfirmResetPasswordOperation.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Service/CognitoUserPoolBehavior.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Service/ErrorMapping/ConfirmForgotPasswordOutputError+AuthError.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Request/AuthConfirmResetPasswordRequest+Validation.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/OperationTests/ClientBehaviorTests/ClientBehaviorConfirmResetPasswordTests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/Support/MockIdentityProvider.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthHostApp.xcodeproj/project.pbxproj, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/ResetPasswordTests/AuthConfirmResetPasswordTests.swift
*Description of changes:* Add confirm reset password API implementation based on `aws-swift-sdk`
=> feat(auth): Add Confirm Reset Password API implementation

.github/workflows/integ_test.yml, AmplifyPlugins/API/APICategoryPlugin.xcodeproj/xcshareddata/xcschemes/GraphQLWithUserPoolIntegrationTests.xcscheme, AmplifyPlugins/API/AWSAPICategoryPluginIntegrationTests/GraphQL/GraphQLWithUserPoolIntegrationTests/GraphQLWithUserPoolIntegrationTests.swift, AmplifyPlugins/API/AWSAPICategoryPluginTestCommon/Model/Todo.swift
Overall this enables one test class called **GraphQLWithUserPoolIntegrationTests.swift** and makes sure the tests are passing based on the latest provisioning steps. 
=> chore(api): clean up and enable user pool integ test

AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Dependency/AuthUserServiceAdapter.swift, AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Support/Constants/AuthPluginErrorConstants.swift
*Issue #, if available:* https://github.com/aws-amplify/amplify-ios/issues/1985
With the changes made in https://github.com/aws-amplify/aws-sdk-ios/pull/4215, an `.unableToSignIn` error will be returned when the token is expired, so we need to propagate a proper error message to Amplify users.
=> fix(Auth): Handling unableToSign error on changePassword 

AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/AWSPinpointAnalyticsPlugin+ClientBehavior.swift, AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/AWSPinpointAnalyticsPlugin+Configure.swift, AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/Dependency/AWSPinpointBehavior.swift, AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/Dependency/Pinpoint/PinpointContext+AWSPinpointBehavior.swift, AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/Dependency/Pinpoint/PinpointContext.swift, AmplifyPlugins/Analytics/AWSPinpointAnalyticsPluginTests/Mocks/MockAWSPinpoint.swift
Dropping support for different regions for Pinpoint Analytics and Pinpoint Targeting, so we only keep one low-level client for both operations.
=> fix(Analytics): Remove support for different targeting region.

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/ClientBehavior/AWSCognitoAuthPlugin+DeviceBehavior.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/AWSAuthRememberDeviceOperation.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Service/CognitoUserPoolBehavior.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Service/ErrorMapping/UpdateDeviceStatusOutputError+AuthError.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/OperationTests/DeviceBehaviorTests/DeviceBehaviorRememberDeviceTests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/Support/MockIdentityProvider.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthHostApp.xcodeproj/project.pbxproj, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/DeviceTests/AuthFetchDeviceTests.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/DeviceTests/AuthRememberDeviceTests.swift
*Description of changes:* Add Remember Device API implementation based on `aws-sdk-swift`
=> feat(auth): Add Remember Device API implementation

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/RefreshSession/RefreshSessionState+Resolver.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/OperationTests/AuthorizationTests/AWSAuthFetchSignInSessionOperationTests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ResolverTests/AuthorizationState/AuthorizationTestData.swift
*Description of changes:* UnAuth AWS Credentials refresh was not completing
=> fix(auth): Statemachine action for refreshing unauth credentials

.swiftpm/xcode/xcshareddata/xcschemes/Amplify-Package.xcscheme, Amplify/Categories/API/AuthProvider/APIAuthProviderFactory.swift, AmplifyPlugins/API/AWSAPICategoryPlugin/Interceptor/RequestInterceptor/AuthTokenProviderWrapper.swift, AmplifyPlugins/API/AWSAPICategoryPlugin/Interceptor/RequestInterceptor/AuthTokenURLRequestInterceptor.swift, AmplifyPlugins/API/AWSAPICategoryPluginTests/Configuration/AWSAPICategoryPluginConfigurationTests.swift, AmplifyPlugins/API/AWSAPICategoryPluginTests/Interceptor/AuthTokenURLRequestInterceptorTests.swift, AmplifyPlugins/API/AWSAPICategoryPluginTests/Interceptor/SubscriptionInterceptor/AuthenticationTokenAuthInterceptorTests.swift, AmplifyPlugins/Analytics/AWSPinpointAnalyticsPluginTests/Mocks/MockAWSAuthService.swift, AmplifyPlugins/Core/AWSPluginsCore/Auth/AWSAuthService.swift, AmplifyPlugins/Core/AWSPluginsCore/Auth/AWSAuthServiceBehavior.swift, AmplifyPlugins/Core/AWSPluginsCore/Auth/Provider/AmplifyAWSCredentialsProvider.swift, AmplifyPlugins/Core/AWSPluginsCore/Auth/Provider/AuthTokenProvider.swift, AmplifyPlugins/Core/AWSPluginsTestCommon/MockAWSAuthService.swift, AmplifyTestCommon/Mocks/MockAPICategoryPlugin.swift
fix: remove dependencies on deprecated auth methods from amplify core
=> fix: remove dependencies on deprecated auth methods from amplify core

AmplifyPlugins/Analytics/AWSPinpointAnalyticsPluginIntegrationTests/AWSPinpointAnalyticsPluginIntegrationTests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Dependency/AuthDeviceServiceAdapter.swift, AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Support/Constants/AuthPluginErrorConstants.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/AuthDeviceTests/AuthDeviceOperationTests.swift
**Auth**
- Handling the `notSignedIn` error coming from `mobileClient` when the token can't be retrieved for a Device Operation so that it returns a `AuthError.signedOut` error.
- Updating integration tests to check:
- a `deviceNotTraked` error when invoked for an unknown/untracked device
- a `signedOut` error when invoked with a signed out user
**Analytics**
- Updating integration test to un-assign the current endpoint after testing `identifyUser`, to prevent for having multiple active endpoints for the same userId.
=> fix(Auth): Handling error when attempting device operations with a signed out user

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/Helpers/UpdateAttributesOperationHelper.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/OperationTests/UserBehaviourTests/UserBehaviorUpdateAttributeTests.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/AuthUserAttributesTests/AuthUserAttributesTests.swift
Fixing to avoid throwing an error when the `codeDeliveryDetailsList ` is nil. This could happen in cases where all the attributes don't require a code.  
=> fix(Auth): Fixing update user attribute helper

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/HubEvents/AuthHubEventHandler.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/AWSAuthConfirmSignUpOperation.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/AWSAuthDeleteUserOperation.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/HubEventTests/AuthHubEventHandlerTests.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/AuthEventTests/AuthEventIntegrationTests.swift
*Description of changes:* Add support for `userDeleted`,  `confirmSignIn`, `sessionExpired` Auth hub events
=> Add support for deletedUser, sessionExpired and confirmSignIn auth hub event

Amplify/Categories/Auth/Request/AuthConfirmSignInRequest.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/VerifySignInChallenge.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Models/AuthChallengeType.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/AWSAuthConfirmSignInOperation.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Data/ConfirmSignInEventData.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Data/RespondToAuthChallenge.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Data/SignUpEventData.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Events/SignInChallengeEvent.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/SignIn/SignInChallengeState+Resolver.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Constants/AuthPluginConstants.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthHostApp.xcodeproj/xcshareddata/xcschemes/AuthHostApp.xcscheme, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/SignInTests/AuthSRPSignInTests.swift
The purpose of the PR is to add support for new password required for confirm sign in API. 
=> feat(Auth): Adding support for confirming newPasswordRequired challenge

Amplify/Categories/DataStore/DataStoreCategory+Behavior.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/AWSDataStorePlugin+DataStoreBaseBehavior.swift
Merging to: https://github.com/aws-amplify/amplify-ios/pull/1752
Add default value for `where` predicate 
=> fix(datastore): Add default value for where predicate

Amplify/Categories/DataStore/Model/Collection/List+Model.swift, Amplify/Categories/DataStore/Model/Collection/List+Pagination.swift, Amplify/Categories/DataStore/Model/Internal/ModelListProvider.swift, AmplifyPlugins/API/Sources/AWSAPIPlugin/Core/AppSyncListProvider.swift, AmplifyPlugins/API/Tests/AWSAPIPluginTests/Core/AppSyncListProviderTests.swift, AmplifyPlugins/API/Tests/AWSAPIPluginTests/Core/ListTests.swift, AmplifyPlugins/API/Tests/AWSAPIPluginTests/Support/Decode/GraphQLResponseDecoder+DecodeDataTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Core/DataStoreListProvider.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Core/DataStoreListProviderFunctionalTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Core/DataStoreListProviderTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Core/ListTests.swift, AmplifyTests/CategoryTests/DataStore/Model/ListPaginationTests.swift, AmplifyTests/CategoryTests/DataStore/Model/ListTests.swift
This removes the behavior of implicitly lazy loading elements from the list when accessed, and requires explicit `fetch` call to be made access the elements.
=> feat(datastore): Remove synchronous load from List

.swiftpm/xcode/xcshareddata/xcschemes/Amplify-Package.xcscheme, AmplifyPlugins/API/Sources/AWSAPIPlugin/Interceptor/RequestInterceptor/AuthTokenProviderWrapper.swift, AmplifyPlugins/API/Sources/AWSAPIPlugin/Interceptor/SubscriptionInterceptor/OIDCAuthProviderWrapper.swift, AmplifyPlugins/API/Sources/AWSAPIPlugin/SubscriptionFactory/AWSOIDCAuthProvider.swift, AmplifyPlugins/API/Sources/AWSAPIPlugin/SubscriptionFactory/AWSSubscriptionConnectionFactory.swift, AmplifyPlugins/API/Tests/AWSAPIPluginTests/Configuration/AWSAPICategoryPluginConfigurationTests.swift, AmplifyPlugins/API/Tests/AWSAPIPluginTests/Interceptor/AuthTokenURLRequestInterceptorTests.swift, AmplifyPlugins/API/Tests/AWSAPIPluginTests/Interceptor/SubscriptionInterceptor/AuthenticationTokenAuthInterceptorTests.swift, AmplifyPlugins/Analytics/AWSPinpointAnalyticsPluginTests/Mocks/MockAWSAuthService.swift, AmplifyPlugins/Core/AWSPluginsCore/Auth/AWSAuthService.swift, AmplifyPlugins/Core/AWSPluginsCore/Auth/AWSAuthServiceBehavior.swift, AmplifyPlugins/Core/AWSPluginsTestCommon/MockAWSAuthService.swift, AmplifyTestCommon/Mocks/MockAPICategoryPlugin.swift, Package.resolved, Package.swift
fix(api): remove consumers of deprecated auth methods from API plugin
=> fix(api): remove consumers of deprecated auth methods from API plugin

AmplifyPlugins/API/Tests/APIHostApp/APIHostApp.xcodeproj/project.pbxproj
- Removes the hack for adding AmplifyTestCommon files to the integration test app
- Adds the local swift package, renamed to `amplify-ios-staging` like AuthHostApp's set up
=> fix(api): fix package reference in api integ test host app

Amplify/Categories/DataStore/Model/ModelIdentifiable.swift
https://github.com/aws-amplify/amplify-ios/pull/1752#discussion_r917123859
When compiling Amplify DataStore's category APIs using Xcode 14 Beta 4, for an API like
```swift
func query<M: Model>(_ modelType: M.Type,
byIdentifier id: String,
completion: DataStoreCallback<M?>) where M: ModelIdentifiable,
M.IdentifierFormat == ModelIdentifierFormat.Default
```
the error shown is
There are two `Identifier`, where `M: Model` and `Model` contains `Identifier`:
and where `M: ModelIdentifiable`, and `ModelIdentifiable` contains `Identifer`:
This PR adds a default conformance of String to ModelIdentifierProtocol. By conforming to `ModelIdentifierProtocol`, unfortunately makes all String values be able to return "fields" as `(name: "id", value: …
=> fix(datastore): String conform to ModelIdentifierProtocol

Amplify/Categories/DataStore/Model/Collection/ArrayLiteralListProvider.swift, Amplify/Categories/DataStore/Model/Collection/List+Model.swift, Amplify/Categories/DataStore/Model/Internal/ModelListProvider.swift, AmplifyPlugins/API/Sources/AWSAPIPlugin/Core/AppSyncListProvider.swift, AmplifyPlugins/API/Tests/APIHostApp/APIHostApp.xcodeproj/xcshareddata/xcschemes/AWSAPIPluginFunctionalTests.xcscheme, AmplifyPlugins/API/Tests/APIHostApp/AWSAPIPluginFunctionalTests/GraphQLConnectionScenario3Tests+List.swift, AmplifyPlugins/API/Tests/APIHostApp/AWSAPIPluginFunctionalTests/GraphQLModelBasedTests+List.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Core/DataStoreListProvider.swift, AmplifyTests/CategoryTests/DataStore/Model/ListTests.swift
This PR fixes the use case for directly retrieving List objects via Amplify.API.query(.list). The API should return a loaded list but was instantiating it as not loaded. To achieve this, we introduce a new API on the list provider to get the state of the list, to instantiate the list as loaded or not.
This also makes sure most of the APIFunctionalTests are passing
=> fix(api): Add ListProvider state to create loaded lists

.swiftpm/xcode/xcshareddata/xcschemes/Amplify-Package.xcscheme, Package.swift
Remove integration tests from Package.swift and cleanup Amplify-Package scheme
=> chore: Remove integration tests from Package.swift and cleanup Amplify-Package scheme

Amplify/Core/Support/Task+Seconds.swift
Task has a sleep function which uses nanoseconds. A double value for seconds is easier to use.
=> Implement Task.sleep with seconds

AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Core/AWSDataStorePluginTests.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Sync/MutationQueue/OutgoingMutationQueueTestsWithMockStateMachine.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/TestSupport/BaseDataStoreTests.swift
=> chore(datastore): remove semaphore usage from unit tests

Amplify/Categories/DataStore/Model/ModelIdentifiable.swift, AmplifyPlugins/Core/AWSPluginsCore/Sync/MutationSync/MutationSyncMetadata+Schema.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Core/SQLStatementTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Models/SQLModelValueConverterTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Storage/CascadeDeleteOperationTests.swift, AmplifyTestCommon/Models/CustomPrimaryKey/CommentWithCompositeKey+Schema.swift, AmplifyTestCommon/Models/CustomPrimaryKey/CommentWithCompositeKeyAndIndex+Schema.swift, AmplifyTestCommon/Models/CustomPrimaryKey/CommentWithCompositeKeyUnidirectional+Schema.swift, AmplifyTestCommon/Models/CustomPrimaryKey/ModelCompositeIntPk+Schema.swift, AmplifyTestCommon/Models/CustomPrimaryKey/ModelCompositePk+Schema.swift, AmplifyTestCommon/Models/CustomPrimaryKey/ModelCompositePkBelongsTo+Schema.swift, AmplifyTestCommon/Models/CustomPrimaryKey/ModelCompositePkWithAssociation+Schema.swift, AmplifyTestCommon/Models/CustomPrimaryKey/ModelCustomPkDefined+Schema.swift, AmplifyTestCommon/Models/CustomPrimaryKey/ModelExplicitCustomPk+Schema.swift, AmplifyTestCommon/Models/CustomPrimaryKey/ModelExplicitDefaultPk+Schema.swift, AmplifyTestCommon/Models/CustomPrimaryKey/ModelImplicitDefaultPk+Schema.swift, AmplifyTestCommon/Models/CustomPrimaryKey/PostTagsWithCompositeKey+Schema.swift, AmplifyTestCommon/Models/CustomPrimaryKey/PostWithCompositeKey+Schema.swift, AmplifyTestCommon/Models/CustomPrimaryKey/PostWithCompositeKeyAndIndex+Schema.swift, AmplifyTestCommon/Models/CustomPrimaryKey/PostWithCompositeKeyUnidirectional+Schema.swift, AmplifyTestCommon/Models/CustomPrimaryKey/PostWithTagsCompositeKey+Schema.swift, AmplifyTestCommon/Models/CustomPrimaryKey/TagWithCompositeKey+Schema.swift
We originally started seeing this issue on Xcode 14 Beta 3 and Beta 4 here: https://github.com/aws-amplify/amplify-ios/pull/1752#discussion_r917123859
The attempted fix from https://github.com/aws-amplify/amplify-ios/pull/2067 to add default conformance for String seems to allow the API to compile.
We saw that this fix actually doesn't work at the call site of the API:
In this example, it appears Model.Identifier defined in Amplify continues to conflict with ModelExplicitDefaultPK.Identifier (codegenerated into ModelExplicitDefaultPK+Schema.swift).
This PR goes with the alternative 2 from https://github.com/aws-amplify/amplify-ios/pull/2067 to rename ModelIdentifiable.IdentifierProtocol so that the two "Identifier" will stop conflicting. …
=> fix(datastore): Rename ModelIdentifiable.Identifier to IdentifierProtocol

AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/RemoteSyncEngine.swift
Previously the code would use a semaphore to block on returning from `performInitialSync()` but it doesn't matter if it returns since the call to `self.stateMachine.notify(action: .performedInitialSync)` is what transitioned the state to perform the next action. Since we are no longer blocking, `performInitialSync` will return, and the `stateMachine.notify` will cause it to move onto `activateCloudSubscriptions()`, which now sets `self.initialSyncOrchestrator = nil`.
The current PR appears to be a feasible solution but couples `activateCloudSubscriptions` with the previous action, it knows that it's the step after performInitialSync and sets `initialSyncOrchestrator` to nil. Was the semaphore there because the following would have no …
=> fix(datastore): Remove DispatchSemaphore - RemoteSyncEngine.performInitialSync

AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/MutationSync/AWSMutationDatabaseAdapter/AWSMutationDatabaseAdapter+MutationEventIngester.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/SubscriptionSync/ReconcileAndLocalSave/ReconcileAndLocalSaveOperation.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/Support/MutationEvent+Query.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Sync/MutationQueue/MutationIngesterConflictResolutionTests.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Sync/SubscriptionSync/ModelReconciliationQueueBehaviorTests.swift, Package.swift
fix(datastore): remove blocking semaphore in MutationEvent.pendingMutationEvents
=> fix(datastore): remove blocking semaphore in MutationEvent.pendingMutationEvents

AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/MutationSync/AWSMutationDatabaseAdapter/AWSMutationDatabaseAdapter+MutationEventIngester.swift
fix(datastore): remove blocking DispatchGroup from AWSMutationDatabaseAdapter.resolve
=> fix(datastore): remove blocking DispatchGroup from AWSMutationDatabaseAdapter.resolve

AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Storage/CascadeDeleteOperation.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Storage/CascadeDeleteOperationTests.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Storage/StorageEngineTestsBase.swift
This started off by removing the DispatchSemaphore in CascadeDeleteOperation.queryAssociatedModels which then cacaded to a few other changes to make the calling code use async.
=> fix(datastore): Remove DispatchSemaphore in CascadeDeleteOperation

Amplify/Categories/API/Internal/APICategory+Resettable.swift, Amplify/Categories/Analytics/Internal/AnalyticsCategory+Resettable.swift, Amplify/Categories/Auth/Internal/AuthCategory+Resettable.swift, Amplify/Categories/DataStore/Internal/DataStoreCategory+Resettable.swift, Amplify/Categories/Geo/Internal/GeoCategory+Resettable.swift, Amplify/Categories/Hub/Internal/HubCategory+Resettable.swift, Amplify/Categories/Predictions/Internal/PredictionsCategory+Resettable.swift, Amplify/Categories/Storage/Internal/StorageCategory+Resettable.swift
make TaskGroups wait for all tasks to complete in category resets
=> fix: make TaskGroups wait for all tasks to complete during resets

AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Subscribe/DataStoreObserveQueryOperation.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/DataStoreObserveQueryTests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/TestSupport/SyncEngineIntegrationTestBase.swift
Fix ObserveQuery integration tests
=> chore(datastore): fix ObserveQuery integ tests

.github/workflows/integ_test_api.yml, .gitignore, AmplifyPlugins/API/Tests/APIHostApp/APIHostApp.xcodeproj/project.pbxproj, AmplifyPlugins/API/Tests/APIHostApp/APIHostApp.xcodeproj/project.xcworkspace/contents.xcworkspacedata, AmplifyPlugins/API/Tests/APIHostApp/APIHostApp.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, AmplifyPlugins/API/Tests/APIHostApp/APIHostApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, AmplifyPlugins/API/Tests/APIHostApp/APIHostApp.xcodeproj/xcshareddata/xcschemes/AWSAPIPluginGraphQLIAMTests.xcscheme, AmplifyPlugins/API/Tests/APIHostApp/APIHostApp/APIHostAppApp.swift, AmplifyPlugins/API/Tests/APIHostApp/APIHostApp/Info.plist
Similar to DataStore (https://github.com/aws-amplify/amplify-ios/pull/2115), added API integration testing into the github actions workflows 
=> chore(api): Add github workflow for Functional and GraphQLIAM tests

Amplify/Core/Support/AsyncChannel.swift, Amplify/Core/Support/AsyncThrowingChannel.swift, AmplifyTests/CoreTests/AsyncChannelTests.swift
adds AsyncChannel and AsyncThrowingChannel with tests
=> adds AsyncChannel and AsyncThrowingChannel with tests

.swiftpm/xcode/xcshareddata/xcschemes/AWSDataStorePlugin.xcscheme, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Storage/CascadeDeleteOperation.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Storage/StorageEngine.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/MutationSync/AWSMutationDatabaseAdapter/AWSMutationDatabaseAdapter+MutationEventIngester.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/MutationSync/MutationEvent/MutationEventIngester.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/RemoteSyncEngine.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/RemoteSyncEngineBehavior.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Storage/CascadeDeleteOperationTests.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Storage/StorageEngineTestsDelete.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Storage/StorageEngineTestsHasMany.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Storage/StorageEngineTestsHasOne.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Storage/StorageEngineTestsManyToMany.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Sync/MutationQueue/OutgoingMutationQueueNetworkTests.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/TestSupport/Mocks/MockRemoteSyncEngine.swift
fix(datastore): fix crash in OutgoingMutationQueue
=> fix(datastore): fix crash in OutgoingMutationQueue

AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/Dependency/Pinpoint/Endpoint/EndpointInformation.swift
Uses `current` property which is public.
=> Fixes build failure due to use of private initializer in DeviceInfo

Amplify/Categories/API/ClientBehavior/APICategory+GraphQLBehavior.swift, Amplify/Categories/API/ClientBehavior/APICategory+RESTBehavior.swift, Amplify/Categories/API/ClientBehavior/APICategoryGraphQLBehavior.swift, Amplify/Categories/API/ClientBehavior/APICategoryRESTBehavior.swift, Amplify/Categories/API/Operation/GraphQLOperation.swift, Amplify/Categories/API/Operation/RESTOperation.swift, Amplify/Core/Support/AmplifyTask.swift, AmplifyPlugins/API/Sources/AWSAPIPlugin/AWSAPIPlugin+GraphQLBehavior.swift, AmplifyPlugins/API/Sources/AWSAPIPlugin/AWSAPIPlugin+RESTBehavior.swift, AmplifyPlugins/API/Sources/AWSAPIPlugin/Operation/AWSGraphQLSubscriptionOperation.swift, AmplifyPlugins/API/Tests/APIHostApp/APIHostApp.xcodeproj/project.pbxproj, AmplifyPlugins/API/Tests/APIHostApp/APIHostApp/SubscriptionView.swift, AmplifyPlugins/API/Tests/APIHostApp/AWSAPIPluginFunctionalTests/Base/AsyncExpectation.swift, AmplifyPlugins/API/Tests/APIHostApp/AWSAPIPluginFunctionalTests/GraphQLConnectionScenario1Tests.swift, AmplifyPlugins/API/Tests/APIHostApp/AWSAPIPluginFunctionalTests/GraphQLConnectionScenario3Tests+Subscribe.swift, AmplifyPlugins/API/Tests/APIHostApp/AWSAPIPluginFunctionalTests/GraphQLModelBasedTests.swift, AmplifyPlugins/API/Tests/AWSAPIPluginTests/Operation/AWSGraphQLSubscriptionOperationCancelTests.swift, AmplifyTestCommon/Mocks/MockAPICategoryPlugin.swift
Update the AWSAPIPlugin APIs to based on **Adds AmplifyTask and Task Adapter for Operations** [PR 2128](https://github.com/aws-amplify/amplify-ios/pull/2128)
=> feat(api): Add Async APIs

Amplify/Core/Support/AsyncPassthroughSubject.swift, AmplifyTests/CoreTests/AsyncPassthroughSubjectTests.swift
When a sink is cancelled on `AnyPublisher` it should cancel the task which is waiting on the value which would be sent to the `PassthroughSubject`.
=> adds task cancellation to AsyncPassthroughSubject

Amplify/Categories/DataStore/Model/Collection/ArrayLiteralListProvider.swift, Amplify/Categories/DataStore/Model/Collection/List+LazyLoad.swift, Amplify/Categories/DataStore/Model/Collection/List+Pagination.swift, Amplify/Categories/DataStore/Model/Internal/ModelListProvider.swift, AmplifyPlugins/API/Sources/AWSAPIPlugin/Core/AppSyncListProvider.swift, AmplifyPlugins/API/Tests/AWSAPIPluginTests/Core/AppSyncListProviderPaginationTests.swift, AmplifyPlugins/API/Tests/AWSAPIPluginTests/Core/ListTests.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Core/DataStoreListProvider.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/AWSDataStoreLocalStoreTests.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Core/DataStoreListProviderFunctionalTests.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Core/DataStoreListProviderTests.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Core/ListTests.swift, AmplifyTestCommon/Mocks/MockAPICategoryPlugin.swift, AmplifyTestCommon/Mocks/MockAPIResponders.swift, AmplifyTestCommon/Mocks/MockDataStoreCategoryPlugin.swift, AmplifyTests/CategoryTests/DataStore/Model/Collection/ArrayLiteralListProviderTests.swift, AmplifyTests/CategoryTests/DataStore/Model/ListTests.swift
This is based on the async APIs for APIPlugin (https://github.com/aws-amplify/amplify-ios/pull/2140) and async APIs for DataStore. This PR adds the `async` versions of the APIs for List such as `fetch`, `load`, `getNextPage`. 
=> feat: add async List APIs for DataStore and API

.swiftpm/xcode/xcshareddata/xcschemes/Amplify-Package.xcscheme, Amplify/Categories/API/Operation/GraphQLOperation.swift, Amplify/Core/Support/AmplifyAsyncSequence.swift, Amplify/Core/Support/AmplifyTask+OperationTaskAdapters.swift, Amplify/Core/Support/AmplifyTask.swift, Amplify/Core/Support/ChildTask.swift, AmplifyTests/CoreTests/AmplifyAsyncSequenceTests.swift
* renames AmplifySequence to AmplifyAsyncSequence
* adds optional parent which is Cancellable
* conforms AmplifyAsyncSequence to Cancellable
* adds new unit tests to cover new behavior
* tests run 100 times each pass without any tsan violations
=> Revises AsyncSequence support to cover optional parent cancellation

Amplify/Categories/DataStore/DataStoreCategory+Behavior+Combine.swift, Amplify/Categories/DataStore/DataStoreCategory+Behavior.swift, Amplify/Categories/DataStore/DataStoreCategoryBehavior.swift, AmplifyPlugins/API/Sources/AWSAPIPlugin/Core/AppSyncListProvider.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/AnyModel/AnyModelTester.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/AWSDataStorePlugin+DataStoreBaseBehavior.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Core/DataStoreListProvider.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Storage/ModelStorageBehavior.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Storage/SQLite/StorageEngineAdapter+SQLite.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Storage/StorageEngineAdapter.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Subscribe/Support/SortedList.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/MutationSync/AWSMutationDatabaseAdapter/AWSMutationDatabaseAdapter+MutationEventIngester.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/MutationSync/OutgoingMutationQueue/ProcessMutationErrorFromCloudOperation.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/SubscriptionSync/ReconcileAndLocalSave/ReconcileAndLocalSaveOperation.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/Support/MutationEvent+Query.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Core/DataStoreListProviderFunctionalTests.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Core/ListTests.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Core/SQLiteStorageEngineAdapterJsonTests.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Core/SQLiteStorageEngineAdapterTests.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Sync/SubscriptionSync/Support/MockSQLiteStorageEngineAdapter.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/DataStoreCustomPrimaryKeyTests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/Models/CustomerOrder+Schema.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/TestSupport/HubEventsIntegrationTestBase.swift, AmplifyTests/CategoryTests/DataStore/DataStoreCategoryClientAPITests.swift, AmplifyTests/CategoryTests/DataStore/Model/Collection/ArrayLiteralListProviderTests.swift, AmplifyTests/CategoryTests/DataStore/Model/ListTests.swift
*Description of changes:* Remove deprecated usages of `Model.Identifier`
=> chore(datastore): remove model.identifier deprecated usage

AmplifyPlugins/API/Tests/APIHostApp/AWSAPIPluginFunctionalTests/GraphQLConnectionScenario1Tests.swift, AmplifyPlugins/API/Tests/APIHostApp/AWSAPIPluginFunctionalTests/GraphQLModelBasedTests+Concurrency.swift, AmplifyPlugins/API/Tests/APIHostApp/AWSAPIPluginFunctionalTests/GraphQLModelBasedTests+List.swift, AmplifyPlugins/API/Tests/APIHostApp/AWSAPIPluginFunctionalTests/GraphQLModelBasedTests.swift, AmplifyPlugins/API/Tests/APIHostApp/AWSAPIPluginFunctionalTests/README.md
fixed all the tests in `GraphQLModelBasedTests.swift` from old apis to new async apis except for a test `testConcurrentSubscriptions()`
Also covered extension tests of `GraphQLModelBasedTests` as well :
- testPaginatedListFetch
- testPaginatedListFetchValidationError
- testFetchListOfCommentsFromPostFails
=> chore(api): fix GraphQLModelBasedTests to async

Package.swift
* bumps Swift tools version to 5.6
* uses new syntax for Package.swift
* makes dependency on Swift SDK the exact version
=> Revised Package.swift for Xcode 13.4 with Swift 5.6

AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/TestSupport/SyncEngineTestBase.swift
make startAmplify async in SyncEngineTestBase
=> fix(datastore): make startAmplify async in SyncEngineTestBase

Amplify/Categories/DataStore/DataStoreCategoryBehavior.swift, Amplify/Categories/DataStore/Subscribe/DataStoreCategory+Subscribe.swift, Amplify/Categories/DataStore/Subscribe/MutationEvent.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/AWSDataStorePlugin+DataStoreSubscribeBehavior.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Subscribe/DataStorePublisher.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Subscribe/ObserveTaskRunner.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Subscribe/ObserveTaskRunnerTests.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Sync/LocalSubscriptionTests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/Connection/DataStoreConnectionScenario6Tests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/DataStoreEndToEndTests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/DataStoreObserveQueryTests.swift, AmplifyTestCommon/Mocks/MockDataStoreCategoryPlugin.swift
This PR replaces the previous `DataStore.publisher(for modelType:)` API with `DataStore.observe(_ modelType:)` with the new AmplifyAsyncThrowingSequence return type. We take this opportunity to align the naming with other platforms on the API name:
In JS
```javascript
const subscription = DataStore.observe(Post).subscribe(msg => {
console.log(msg.model, msg.opType, msg.element);
});
```
In Android
```java
Amplify.DataStore.observe(Post.class,
cancelable -> Log.i("MyAmplifyApp", "Observation began."),
postChanged -> {
Post post = postChanged.item();
Log.i("MyAmplifyApp", "Post: " + post);
},
failure -> Log.e("MyAmplifyApp", "Observation failed.", failure),
() -> Log.i("MyAmplifyApp", "Observation complete.")
);
```
In Flutter
```dart …
```
=> feat(datastore): Add AsyncThrowingSequence Observe API

AmplifyPlugins/API/Sources/AWSAPIPlugin/Operation/AWSHTTPURLResponse.swift, AmplifyPlugins/API/Tests/AWSAPIPluginTests/Operation/AWSHTTPURLResponseTests.swift, AmplifyTests/CategoryTests/DataStore/DataStoreCategoryConfigurationTests.swift
*Description of changes:* Update `NSKeyedArchiver.Data(withRootObject:)` and `NSKeyedUnarchiver.unarchiveObject(with:)` APIs with `archivedDataWithRootObject:requiringSecureCoding:error)` and `unarchivedObjectOfClass:fromData:error)`
=> chore(datastore): Fix deprecated NSKeyedArchiver and NSKeyedUnarchiver APIs

Amplify/Categories/Storage/StorageCategory+ClientBehavior.swift
=> deprecates Storage listeners API in client behavior extension

Amplify/Categories/API/ClientBehavior/APICategory+GraphQLBehavior.swift, Amplify/Categories/API/ClientBehavior/APICategoryGraphQLBehavior.swift, Amplify/Categories/API/Operation/GraphQLOperation.swift, Amplify/Categories/API/Response/SubscriptionConnectionState.swift, Amplify/Categories/API/Response/SubscriptionEvent.swift, AmplifyPlugins/API/Sources/AWSAPIPlugin/AWSAPIPlugin+GraphQLBehavior.swift, AmplifyPlugins/API/Sources/AWSAPIPlugin/Operation/AWSGraphQLSubscriptionTaskRunner.swift, AmplifyPlugins/API/Tests/APIHostApp/APIHostApp/SubscriptionView.swift, AmplifyPlugins/API/Tests/APIHostApp/AWSAPIPluginFunctionalTests/GraphQLConnectionScenario3Tests+Subscribe.swift, AmplifyPlugins/API/Tests/APIHostApp/AWSAPIPluginFunctionalTests/GraphQLConnectionScenario6Tests.swift, AmplifyPlugins/API/Tests/APIHostApp/AWSAPIPluginFunctionalTests/GraphQLModelBasedTests+Concurrency.swift, AmplifyPlugins/API/Tests/APIHostApp/AWSAPIPluginFunctionalTests/GraphQLModelBasedTests.swift, AmplifyPlugins/API/Tests/AWSAPIPluginTests/Operation/AWSGraphQLSubscriptionTaskRunnerCancelTests.swift, AmplifyPlugins/API/Tests/AWSAPIPluginTests/Operation/GraphQLSubscribeTaskTests.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/SubscriptionSync/IncomingAsyncSubscriptionEventPublisher.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/SubscriptionSync/IncomingAsyncSubscriptionEventToAnyModelMapper.swift, AmplifyTestCommon/Mocks/MockAPICategoryPlugin.swift
This PR introduces the AsyncThrowingSequence version of API.subscribe.
```swift
func subscribe<R>(request: GraphQLRequest<R>) -> AmplifyAsyncThrowingSequence<GraphQLSubscriptionEvent<R>>
```
I also took the opportunity to rename the subscription event that is received from `SubscriptionEvent<GraphQLResponse<T>>` to `GraphQLSubscriptionEvent<T>`. A subscription event is always going to be a GraphQLResponse on the `data` case, so there's no need for a nested generic. 
=> feat(api): Add AsyncThrowingSequence API.subscribe

.swiftpm/xcode/xcshareddata/xcschemes/Amplify.xcscheme, Amplify/Categories/API/ClientBehavior/APICategory+GraphQLBehavior.swift, Amplify/Categories/API/ClientBehavior/APICategoryGraphQLBehavior.swift, AmplifyPlugins/API/Sources/AWSAPIPlugin/AWSAPIPlugin.swift, AmplifyPlugins/Core/AWSPluginsCore/API/APICategoryGraphQLBehaviorExtended.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Storage/StorageEngine+SyncRequirement.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/InitialSync/InitialSyncOperation.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/InitialSync/InitialSyncOrchestrator.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/MutationSync/OutgoingMutationQueue/OutgoingMutationQueue+Action.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/MutationSync/OutgoingMutationQueue/OutgoingMutationQueue+State.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/MutationSync/OutgoingMutationQueue/OutgoingMutationQueue.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/MutationSync/OutgoingMutationQueue/ProcessMutationErrorFromCloudOperation.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/MutationSync/OutgoingMutationQueue/SyncMutationToCloudOperation.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/RemoteSyncEngine+Action.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/RemoteSyncEngine+State.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/RemoteSyncEngine.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/RemoteSyncEngineBehavior.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/SubscriptionSync/AWSIncomingEventReconciliationQueue.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/SubscriptionSync/AWSIncomingSubscriptionEventPublisher.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/SubscriptionSync/IncomingAsyncSubscriptionEventPublisher.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/SubscriptionSync/ReconcileAndLocalSave/AWSModelReconciliationQueue.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Sync/RemoteSyncEngineTests.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/TestSupport/Mocks/MockOutgoingMutationQueue.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/TestSupport/Mocks/MockRemoteSyncEngine.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/TestSupport/Mocks/NoOpMutationQueue.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/DataStoreConsecutiveUpdatesTests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/SubscriptionEndToEndTests.swift, AmplifyTestCommon/Mocks/MockAPICategoryPlugin.swift
Related https://github.com/aws-amplify/amplify-ios/issues/2252
To provide a path forward in removing the APIPlugin's callback APIs, they have been moved from Amplify over to AWSPluginsCore in this PR. This way, a developer does not have access to the APIs through Amplify.API, while DataStore and if other consumers really want, can cast the plugin to APICategoryGraphQLBehaviorExtended to get the GraphQL callback based APIs. APICategoryGraphQLBehaviorExtended and APICategoryGraphQLCallbackBehavior has been marked with a warning on that it has to be public but is not meant for public use, and can change without a major version bump.
By submitting this pull request, I confirm that my …
=> fix: deprecate callback GraphQL APIs with APICategoryGraphQLBehaviorExtended

Amplify/DefaultPlugins/AWSHubPlugin/AWSHubPlugin.swift, Amplify/DefaultPlugins/AWSHubPlugin/Internal/HubChannelDispatcher.swift
fix: improve hub reset() compatibility with swift concurrency
=> fix: improve hub reset() compatibility with swift concurrency

.github/workflows/integ_test_api.yml, .github/workflows/integ_test_datastore.yml, .github/workflows/release_kickoff.yml
update integration test runners to use macOS 12
=> chore: update integration test runners to use macOS 12

AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Sync/InitialSync/InitialSyncOrchestratorTests.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Sync/MutationQueue/OutgoingMutationQueueTests.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Sync/RemoteSyncEngineTests.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Sync/SubscriptionSync/ModelReconciliationDeleteTests.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/TestSupport/SyncEngineTestBase.swift, AmplifyTestCommon/Helpers/HubListenerTestUtilities.swift, AmplifyTests/CategoryTests/Hub/AmplifyOperationHubTests.swift, AmplifyTests/CategoryTests/Hub/DefaultPluginTests/DefaultHubPluginConcurrencyTests.swift, AmplifyTests/CategoryTests/Hub/DefaultPluginTests/DefaultHubPluginCustomChannelTests.swift, AmplifyTests/CategoryTests/Hub/DefaultPluginTests/DefaultHubPluginTests.swift
make HubListenerTestUtilities.waitForListener async
=> fix: make HubListenerTestUtilities.waitForListener async

AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginAuthIAMTests/AWSDataStoreAuthBaseTest.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginAuthIAMTests/AWSDataStoreCategoryPluginIAMAuthIntegrationTests.swift
*Issue #, if available:* None 
*Description of changes:* Update AWSDataStoreCategoryPluginIAMAuthIntegrationTests with `async` APIs
=> chore(datastore): Fix AWSDataStoreCategoryPluginIAMAuthIntegrationTests

AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Dependency/AWSS3Adapter.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Dependency/AWSS3ListObjectsV2Request.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Dependency/AWSS3PreSignedURLBuilderBehavior.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Dependency/S3Client+deleteObject.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Service/Storage/AWSS3StorageService+GetPreSignedURLBehavior.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Service/Storage/AWSS3StorageService+ListBehavior.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/FileSystem.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/StorageTransferResponse.swift
Fixing the following Storage issues:
**Download**
- Attempting to download to a file always fails with "file already exists". Caused by a missing `!` in a validation.
- `.httpStatusError` is returned instead of `.keyNotFound` and `accessDenied` when applicable. Fixed by implementing a check for these status codes in `StorageTransferResponse.responseError`.
**List**
- Setting a `path` value in its options results in said value being removed from each `item.key` that is returned. 
E.g. if you provide the full path for a given item, the item will have an empty key. If you provide the folder, each `item.key` will not include the folder.
Fixed by adding a `path` attribute to the `AWSS3ListObjectsV2Request` instead of concatenating everything into its `prefix`. …
=> fix(Storage): Various bug fixes

AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginMultiAuthTests/AWSDataStoreAuthBaseTest.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginMultiAuthTests/AWSDataStoreMultiAuthCombinationTests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginMultiAuthTests/AWSDataStoreMultiAuthSingleRuleTests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginMultiAuthTests/AWSDataStoreMultiAuthThreeRulesTests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginMultiAuthTests/AWSDataStoreMultiAuthTwoRulesTests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/DataStoreHostApp.xcodeproj/project.pbxproj, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/DataStoreHostApp.xcodeproj/xcshareddata/xcschemes/AWSDataStorePluginMultiAuthTests.xcscheme, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/DataStoreHostApp/HubListenerTestUtilities.swift
*Description of changes:* Update `AWSDataStorePluginMultiAuthTests` with `async` APIs
=> chore(datastore): Fix AWSDataStorePluginMultiAuthTests

AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Sync/LocalSubscriptionTests.swift
Tests for `LocalSubscriptionTests.swift` were failing
small fix of `LocalSubscriptionTests.swift` to `async` so that all the tests successfully run.
=> chore(datastore): fix LocalSubscriptionTests 

.github/workflows/integ_test.yml
*Issue #, if available:* Swiftlint requires minimum Swift v5.6 https://github.com/realm/SwiftLint/releases/tag/0.49.0 which needs minimum Xcode 13.3.0 to build
*Description of changes:* Update macos version for Github actions for integration tests to `macos-12` according to https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md which has the default Xcode version `13.4.1`
=> chore: Update Xcode version for github actions for integration tests

Amplify/Categories/Storage/StorageCategory+ClientBehavior+Combine.swift
[Issue#2185](https://github.com/aws-amplify/amplify-ios/issues/2185)
- Use parameter `options` instead of `nil` for function StorageCategoryBehavior [getURL(key:options:)](https://github.com/aws-amplify/amplify-ios/blob/main/Amplify/Categories/Storage/StorageCategory%2BClientBehavior%2BCombine.swift#L64).
=> fix(Storage): getURL to use function parameter 'options'

Amplify/Categories/Analytics/AnalyticsCategory+ClientBehavior.swift, Amplify/Categories/Analytics/AnalyticsCategoryBehavior.swift, AmplifyPlugins/Analytics/Sources/AWSPinpointAnalyticsPlugin/AWSPinpointAnalyticsPlugin+ClientBehavior.swift, AmplifyPlugins/Analytics/Sources/AWSPinpointAnalyticsPlugin/Dependency/Pinpoint/Endpoint/PinpointEndpointProfile.swift, AmplifyPlugins/Analytics/Tests/AWSPinpointAnalyticsPluginUnitTests/AWSPinpointAnalyticsPluginClientBehaviorTests.swift, AmplifyPlugins/Analytics/Tests/AnalyticsHostApp/AWSPinpointAnalyticsPluginIntegrationTests/AWSPinpointAnalyticsPluginIntegrationTests.swift, AmplifyTestCommon/Mocks/MockAnalyticsCategoryPlugin.swift, AmplifyTests/CategoryTests/Analytics/AnalyticsCategoryClientAPITests.swift, AmplifyTests/CoreTests/NotificationListeningAnalyticsPlugin.swift
https://github.com/aws-amplify/amplify-ios/issues/466
Updating the `identifyUser` signature to
```swift
func identifyUser(userId: String, userProfile: AnalyticsUserProfile?)
```
This will bring [parity with Flutter](https://github.com/aws-amplify/amplify-flutter/blob/main/packages/analytics/amplify_analytics_pinpoint/lib/method_channel_amplify.dart#L110-L113), as well as improve readability for this method and make it clear what arguments to provide.
=> chore(Analytics): Renaming `identityId` to `userId`

AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/AWSAuthBaseTest.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/AuthDeleteUserTests/AuthDeleteUserTests.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/AuthEventTests/AuthEventIntegrationTests.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/AuthUserAttributesTests/AuthUserAttributesTests.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/CredentialStore/CredentialStoreConfigurationTests.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/DeviceTests/AuthFetchDeviceTests.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/DeviceTests/AuthForgetDeviceTests.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/DeviceTests/AuthRememberDeviceTests.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/Helpers/AuthSignInHelper.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/ResetPasswordTests/AuthConfirmResetPasswordTests.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/ResetPasswordTests/AuthResetPasswordTests.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/SessionTests/FederatedSessionTests.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/SessionTests/SignedInAuthSessionTests.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/SessionTests/SignedOutAuthSessionTests.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/SignInTests/AuthCustomSignInTests.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/SignInTests/AuthSRPSignInTests.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/SignOutTests/AuthSignOutTests.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/SignUpTests/AuthConfirmSignUpTests.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/SignUpTests/AuthResendSignUpCodeTests.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/SignUpTests/AuthSignUpTests.swift
Most tests were failing because sign in or sign up was attempted while there was already a signed in user, so I've put a `signOut` request on all test's `setUp`.
Also made `setUp` and `tearDown` part of `AWSAuthBaseTest`, since all tests were doing basically the same.
=> chore(Auth): Fixing integration tests

.circleci/config.yml
Enhancement for the getting started workflow in circleCI(https://github.com/aws-amplify/amplify-ios/pull/1884). We added cloudwatch monitoring for the workflow, so the devops team could get notified right away if there's any issues with the workflow. The change should not alter any existing behavior.
=> chore(ci): add cloudwatch monitoring for getting started smoke test

Amplify/Core/Support/Amplify+Publisher.swift, README-combine-support.md
update Amplify.Publisher documentation examples to reflect the fact that Amplify.API.subscribe is no longer async and no longer throws
=> chore: update Amplify.Publisher documentation examples to reflect the fact that Amplify.API.subscribe is no longer async and no longer throws

AmplifyPlugins/Storage/AWSS3StoragePluginFunctionalTests/AWSS3StoragePluginBasicIntegrationTests.swift
Use `TestCommonConstants.networkTimeout` instead of hardcoded literal value for expectation in  `testUploadLargeFile`
=> fix(storage): update expectation timeout in integration test

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/InitialSync/InitialSyncOrchestrator.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/InitialSync/ModelSyncedEventEmitter.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngine+IncomingEventReconciliationQueueEvent.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngine.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/AWSIncomingEventReconciliationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/AWSIncomingSubscriptionEventPublisher.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/IncomingAsyncSubscriptionEventPublisher.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/IncomingEventReconciliationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/ReconcileAndLocalSave/AWSModelReconciliationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/ReconcileAndLocalSave/ModelReconciliationQueue.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/AWSIncomingEventReconciliationQueueTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/ModelReconciliationQueueBehaviorTests.swift
When the sync process starts (RemoteSyncEngine) and initializes API subscriptions, this work is performed through various components that publish events through Combine publishers backed by a PassThroughSubject, in this pattern:
```
let component = Component()
let sink = component.publisher.sink { event in 
// handle event
}
```
The problem with this pattern is that the subscriber to the publisher may miss some values if the Component's initialization code results in sending values before it returns, which occurs before `component.publisher.sink` is finished. 
In this specific case where subscriptions are being established through API usually take a few network trips to perform the websocket handshake, in which the Component calling code …
=> fix(datastore): InitializeSubscription race condition disconnected event

Amplify/Core/Support/TimeInterval+Helper.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/InitialSync/InitialSyncOperation.swift
This is a cherry-pick of https://github.com/aws-amplify/amplify-ios/pull/2034 from `main` branch
=> fix(datastore): refactor to use TimeInterval.milliseconds (#2034)

AmplifyPlugins/Auth/AWSCognitoAuthPlugin/AWSCognitoAuthPlugin+Configure.swift, AmplifyPlugins/Auth/AWSCognitoAuthPlugin/AWSCognitoAuthPlugin.swift, AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Models/AWSCognitoNetworkPreferences.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/ConfigurationTests/AWSCognitoAuthPluginConfigTests.swift
*Issue https://github.com/aws-amplify/amplify-ios/issues/1060
Add a new constructor to AWSCognitoAuthPlugin with network preferences for custom timeout and retry. 
<del> - [  ] If breaking change, documentation/changelog update with migration instructions
=> Add custom network preferences for AWSCognitoAuthPlugin

.swiftpm/xcode/xcshareddata/xcschemes/AWSDataStorePlugin.xcscheme, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/InitialSync/InitialSyncOrchestrator.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/InitialSync/ModelSyncedEventEmitter.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/RemoteSyncEngine+IncomingEventReconciliationQueueEvent.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/RemoteSyncEngine.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/SubscriptionSync/AWSIncomingEventReconciliationQueue.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/SubscriptionSync/IncomingAsyncSubscriptionEventPublisher.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/SubscriptionSync/IncomingEventReconciliationQueue.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/SubscriptionSync/ReconcileAndLocalSave/AWSModelReconciliationQueue.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/SubscriptionSync/ReconcileAndLocalSave/ModelReconciliationQueue.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Sync/SubscriptionSync/AWSIncomingEventReconciliationQueueTests.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Sync/SubscriptionSync/ModelReconciliationQueueBehaviorTests.swift
This PR is the V2 version of https://github.com/aws-amplify/amplify-ios/pull/2319
=> fix(datastore-v2): InitializeSubscription race condition disconnected event

README.md
https://github.com/aws-amplify/amplify-ios/issues/2330
- Fix API Documentation link
- Add Getting Started Guide link
- Fix links for `questions` and `feature requests` stat buttons.
=> chore(docs): fix broken links in readme

.github/workflows/new_issue_maintainer.yml
N/A
Remove `diegocstn` and add `5d` in the maintainer list for GitHub action `new_issue_maintainer`.
Adds members of @aws-amplify/amplify-data to maintainer check.
=> chore: update maintainer list in new_issue action

AmplifyPlugins/Core/AWSPluginsCore/Model/Support/Model+GraphQL.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginIntegrationTests/TransformerV2/DataStoreConnectionOptionalAssociations.swift
https://github.com/aws-amplify/amplify-ios/issues/2336
Verified that there was a regression from the CPK changes at this file: https://github.com/aws-amplify/amplify-ios/pull/1752/files#diff-2fa30b26d50da3e22bdbe4d8e4eb16bb22011672699f804c0926fa34629c5cc2 CPK was released in 1.28.0, and verified that the failing test `DataStoreConnectionOptionalAssociations.testRemovePostFromCommentAndBlogFromPost` is passing in 1.27.1 (last 1.27.x version).
This PR updates the logic for translating a model instance over to the GraphQL request variables "input" object. 
The following example uses Comment and Post, where a post has many comments and the comment belongs to a post.
Previously, before CPK changes, when a model with an associated field with …
=> fix(datastore): Setting nil values for empty associated models

AmplifyPlugins/Analytics/Tests/AWSPinpointAnalyticsPluginUnitTests/Pinpoint/SessionClientTests.swift
Since events are recoded asynchronously by the `SessionClient`, it's not safe to assume their order in the mocked `AnalyticsClient`.
So I'm instead just validating that they exist.
=> fix(Analytics): Fixing flaky unit tests

AmplifyPlugins/Analytics/Sources/AWSPinpointAnalyticsPlugin/AWSPinpointAnalyticsPlugin+Configure.swift, AmplifyPlugins/Analytics/Sources/AWSPinpointAnalyticsPlugin/Configuration/AWSPinpointAnalyticsPluginConfiguration.swift, AmplifyPlugins/Analytics/Sources/AWSPinpointAnalyticsPlugin/Support/Constants/AnalyticsErrorConstants.swift, AmplifyPlugins/Analytics/Tests/AWSPinpointAnalyticsPluginUnitTests/Configuration/AWSPinpointAnalyticsPluginConfigurationTests.swift
Removing `targetingRegion` from `AWSPinpointAnalyticsPluginConfiguration` as it's not used, and it will allow us to update the docs to remove it from the manual configuration steps.
I've kept a warn log just in case someone manually defines different regions in their config file, informing that it's not supported.
=> fix(Analytics): Removing targetingRegion from the configuration struct

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/AWSDataStorePlugin.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Subscribe/DataStoreObserveQueryOperation.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginIntegrationTests/DataStoreObserveQueryTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Subscribe/DataStoreObserveQueryOperationTests.swift
#1759
adding this https://github.com/aws-amplify/amplify-ios/pull/2296 code change here on `main` for a customer awaiting on these changes
=> fix(datastore-v1): observeQuery snapshot on .modelSynced event

AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/AWSDataStorePlugin.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Subscribe/DataStoreObserveQueryOperation.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Subscribe/ObserveQueryTaskRunnerTests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/DataStoreObserveQueryTests.swift
https://github.com/aws-amplify/amplify-ios/issues/1759
(reference taken from https://github.com/aws-amplify/amplify-ios/pull/2105)
Datastore `observeQuery` is an API that produces streamlines of data snapshots along with its' syncState.
While producing data snapshots and syncing to the cloud, the `isSynced` value remains `false` and is toggled to `true` when the syncing process is complete. But there can be potential loss of snapshots in the toggle from the last snapshot during the sync and the first snapshot after the sync as there can be lot of items being changed at that point after toggle. And the snapshot to be produced after the sync is delayed as it waits for any new changes.
The fix is to listen on datastore `.modelSynced` where …
=> fix(datastore-v2): observeQuery snapshot on .modelSynced event

Amplify/Categories/DataStore/DataStoreCategory+Behavior.swift, Amplify/Categories/DataStore/DataStoreCategoryBehavior.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/AWSDataStorePlugin+DataStoreBaseBehavior.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Storage/ModelStorageBehavior.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Storage/SQLite/StorageEngineAdapter+SQLite.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Sync/SubscriptionSync/Support/MockSQLiteStorageEngineAdapter.swift
This PR adds back `delete(modelType:withId)`. It was incorrectly removed during the migration to Async APIs
=> fix(datastore): Add back delete(modelType:withId) API

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Models/AWSCognitoSignOutResult.swift
N/A
A few properties related to `AWSCognitoSignOutResult` are internal. This change makes them publicly accessible.
- `AWSCognitoSignOutResult`
- `signOutLocally`
- `AWSCognitoRevokeTokenError`
- `refreshToken`
- `error`
- `AWSCognitoGlobalSignOutError`
- `refreshToken`
- `error`
- `AWSCognitoHostedUIError`
- `error`
=> fix(auth): access control in signoutresult and errors

Package.resolved, Package.swift
=> chore: Pin AWS SDK for Swift to 0.2.7

Amplify/Core/Support/Amplify+Publisher.swift
N/A
`Amplify.Publisher.create` allows for converting an async throwing function (e.g. `func foo() async throws -> Int`) into a `AnyPublisher<Int, Error>`. This publisher can then be leveraged like so:
```swift
Amplify.Publisher.create { 
try await foo()
}.sink(
receiveCompletion: { competion in 
// handle completion
},
receiveValue: { value in 
// handle value
}
)
```
The `receiveValue` block will be invoked upon `foo()` successfully returning an `Int` and the `receiveCompletion` block will be invoked if `foo()` decides to throw. 
This works perfectly when the function throws, but is less ergonomic and borderline confusing when an async non-throwing function is passed into `create(_:)`. Let's look at an example: 
```swift
func bar() async …
```
=> chore: add non-throwing create publisher overload

README.md
Cherry-picking the changes from https://github.com/aws-amplify/amplify-ios/pull/2331 to `dev-preview`
Also fixing the counters so they correctly display the number of questions and feature requests.
=> chore(docs): fix broken links in readme (#2331)

AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Sync/Support/MutationEventExtensionsTests.swift
Skipping flaky Datastore unit tests.
Tracked on https://github.com/aws-amplify/amplify-ios/issues/1831
=> chore(datastore): skipping flaky tests

.github/workflows/integ_test.yml
The failing integration tests creates an ❌ on the pipeline. If flaky tests need to be tested on Github Actions, they can be done via a separate branch until they are consistent or in a forked repo
=> test(datastore): disable integration test workflows

Amplify/Core/Support/AmplifyTask+OperationTaskAdapters.swift, Amplify/Core/Support/AtomicDictionary.swift, Amplify/DefaultPlugins/AWSHubPlugin/AWSHubPlugin.swift, Amplify/DefaultPlugins/AWSHubPlugin/Internal/HubChannelDispatcher.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Support/Internal/StorageBackgroundEventsRegistryTests.swift
- Making `AtomicDictionary` a class again with an `NSLock` mechanism, as the `actor` approach created issues when the result was immediately dispatched without having time to register the listener (due to being an asynchronous call made inside the synchronous `subscribe` method)
- Wrapping operation listeners in closures that don't retain the adapter, so they are not kept around after the operations complete.
- Fixing `StorageBackgroundEventsRegistryTests.testRegisteringAndUnregister` which was attempting to resume a continuation before it finished being stored in the registry.
=> fix(Storage): Addressing issues with race conditions

AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/CredentialStore/CredentialStoreOperationClientTests.swift
Moving `expectation.fulfill()` to the end of the Auth operations, otherwise the test completes and everything starts to get deallocated at the same time that the remaining operations attempt to continue. 
=> fix(Auth): Fixing unit test

.swiftpm/xcode/xcshareddata/xcschemes/AWSCognitoAuthPlugin.xcscheme, AmplifyPlugins/Auth/Sources/libtommath/README.md, AmplifyPlugins/Auth/Sources/libtommath/amplify_bn_s_mp_rand_platform.c, Package.swift
SPM does not support using unsafe flag in a versioned release.  This PR changes the internal implementation of libtommath to remove unused code for un-supported platforms, so that we no longer need to use unsafeflag for dead code elimintation.
=> fix(auth): Build failure due to unsafe flag

Package.swift
*Issue #, if available:* N/A
*Description of changes:* Re-enables `AWSPluginsCore` as a public product of amplify-swift
=> fix: Make AWSPluginsCore public

AmplifyPlugins/Analytics/Sources/AWSPinpointAnalyticsPlugin/Dependency/Pinpoint/Analytics/PinpointEvent.swift
https://github.com/aws-amplify/amplify-swift/issues/2471
* Updating pinpoint event max attributes limit and value length to match [Pinpoint documentation](https://docs.aws.amazon.com/pinpoint/latest/developerguide/quotas.html#quotas-events)
=> fix(analytics): update pinpoint event attribute limits to match docum

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/Federation/ClearFederationToIdentityPool.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/CredentialStorage/AmplifyCredentials+CognitoSession.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/Helpers/ClearFederationOperationHelper.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/Helpers/FetchAuthSessionOperationHelper.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Errors/FetchSessionError.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/States/AuthorizationState.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/States/DebugInfo/AuthorizationState+Debug.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/Authentication/AuthenticationState+Resolver.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/Authorization/AuthorizationState+Resolver.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/HubEventTests/AuthHubEventHandlerTests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/Support/DefaultConfig.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/AuthorizationTests/AWSAuthFederationToIdentityPoolTests.swift
* Adding the ability to clear credentials when in an error state
* Fixing fetchAuthSession and federation workflows when in an error state
=> fix(Auth): Making improvements to federation flow

AmplifyPlugins/Analytics/Sources/AWSPinpointAnalyticsPlugin/AWSPinpointAnalyticsPlugin+ClientBehavior.swift, AmplifyPlugins/Analytics/Sources/AWSPinpointAnalyticsPlugin/AWSPinpointAnalyticsPlugin+Configure.swift, AmplifyPlugins/Analytics/Sources/AWSPinpointAnalyticsPlugin/AWSPinpointAnalyticsPlugin+Reset.swift, AmplifyPlugins/Analytics/Sources/AWSPinpointAnalyticsPlugin/AWSPinpointAnalyticsPlugin.swift, AmplifyPlugins/Analytics/Sources/AWSPinpointAnalyticsPlugin/Dependency/Pinpoint/Analytics/EventRecorder.swift, AmplifyPlugins/Analytics/Sources/AWSPinpointAnalyticsPlugin/Dependency/Pinpoint/Analytics/PinpointEvent.swift, AmplifyPlugins/Analytics/Sources/AWSPinpointAnalyticsPlugin/LocalStorage/AnalyticsEventSQLStorage.swift, AmplifyPlugins/Analytics/Sources/AWSPinpointAnalyticsPlugin/LocalStorage/PinpointEvent+Bindings.swift, AmplifyPlugins/Analytics/Sources/AWSPinpointAnalyticsPlugin/Support/Constants/AWSPinpointAnalyticsConstants.swift, AmplifyPlugins/Analytics/Sources/AWSPinpointAnalyticsPlugin/Support/Constants/AnalyticsErrorConstants.swift, AmplifyPlugins/Analytics/Sources/AWSPinpointAnalyticsPlugin/Support/Extensions/AWSPinpointAnalyticsPlugin+HubCategory.swift, AmplifyPlugins/Analytics/Sources/AWSPinpointAnalyticsPlugin/Support/Extensions/SDKModels+AmplifyStringConvertible.swift, AmplifyPlugins/Analytics/Sources/AWSPinpointAnalyticsPlugin/Support/Utils/AmplifyStringConvertible.swift, AmplifyPlugins/Analytics/Sources/AWSPinpointAnalyticsPlugin/Support/Utils/AnalyticsErrorHelper.swift, AmplifyPlugins/Analytics/Sources/AWSPinpointAnalyticsPlugin/Support/Utils/NetworkMonitor.swift, AmplifyPlugins/Analytics/Sources/AWSPinpointAnalyticsPlugin/Support/Utils/SdkError+Analytics.swift, AmplifyPlugins/Analytics/Tests/AWSPinpointAnalyticsPluginUnitTests/AWSPinpointAnalyticsPluginClientBehaviorTests.swift, AmplifyPlugins/Analytics/Tests/AWSPinpointAnalyticsPluginUnitTests/AWSPinpointAnalyticsPluginTestBase.swift, AmplifyPlugins/Analytics/Tests/AWSPinpointAnalyticsPluginUnitTests/Mocks/MockNetworkMonitor.swift, AmplifyPlugins/Analytics/Tests/AnalyticsHostApp/AWSPinpointAnalyticsPluginIntegrationTests/AWSPinpointAnalyticsPluginIntegrationTests.swift
This PR addresses four issues with the current Analytics implementation:
----
If the `pinpoint.putEvents(input:)` call inside the [`submit(pinpointEvents:endpointProfile)` method](https://github.com/aws-amplify/amplify-swift/blob/main/AmplifyPlugins/Analytics/Sources/AWSPinpointAnalyticsPlugin/Dependency/Pinpoint/Analytics/EventRecorder.swift#L104-L105) throws an error, we handle it [inside a `catch` block](https://github.com/aws-amplify/amplify-swift/blob/main/AmplifyPlugins/Analytics/Sources/AWSPinpointAnalyticsPlugin/Dependency/Pinpoint/Analytics/EventRecorder.swift#L155) that updates the events accordingly (i.e. either increases the counter or marks it as dirty, depending on the type of error thrown) and we [rethrow the …
=> fix(Analytics): Fixing Analytics issues

.circleci/config.yml, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/AWSDataStorePlugin+DataStoreBaseBehavior.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/TestSupport/SyncEngineTestBase.swift, canaries/example/Gemfile.lock
- Update the canaries script to use the right devices. Now it has two test, one against the latest supported device and the other against minimum support
- Made some the datastore plugin to have explicit type info 
=> test: Update the canaries script to use the right devices

AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/AWSPinpointAnalyticsPlugin+ClientBehavior.swift, AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/Support/Constants/AnalyticsErrorConstants.swift, AmplifyPlugins/Analytics/AWSPinpointAnalyticsPlugin/Support/Utils/AnalyticsErrorHelper.swift, AmplifyPlugins/Analytics/AWSPinpointAnalyticsPluginTests/AWSPinpointAnalyticsPluginClientBehaviorTests.swift
Fixing some issues when calling `Amplify.Analytics.flushEvents()` so they match what we do in `v2`:
- `AWSPinpointAnalyticsClient.submitEvents()` returns an error when there are no events to submit, which we are then dispatching to the Hub. This is problematic with Amplify's automatic flush of events, as it would spam the Hub with errors that are not really errors. So whenever we get a `"No events to submit."` error, I'm dispatching an empty array instead.
- Dispatching a customized error for connectivity issues, for better readability in logs.
=> fix(Analytics): Fixing issues when calling flushEvents

AmplifyPlugins/Analytics/Sources/AWSPinpointAnalyticsPlugin/Dependency/Pinpoint/Analytics/PinpointEvent+PinpointClientTypes.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/SRPAuth/SRPSignInHelper.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Helpers/ClientSecretHelper.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Utils/ConfirmSignUpInput+Amplify.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Utils/InitiateAuthInput+Amplify.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Utils/RespondToAuthChallengeInput+Amplify.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Utils/SignUpInput+Amplify.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthConfirmResetPasswordTask.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthResendSignUpCodeTask.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthResetPasswordTask.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ConfigurationTests/ClientSecretConfigurationTests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/ClientBehaviorTests/AWSAuthSignUpAPITests.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/ServiceConfiguration/AmplifyAWSServiceConfigurationTests.swift
*Issue #, if available:* https://github.com/aws-amplify/amplify-swift/issues/2524
=> fix(auth): Add secrethash to the resetPassword/resendSignUpCode

.github/PULL_REQUEST_TEMPLATE.md
Until the integration tests are running consistently successfully in github actions, add a PR template reminder to run the integration tests manually.
=> chore(datastore): update PR template with checkpoints

.github/PULL_REQUEST_TEMPLATE.md
similar reminder on `dev-preview` https://github.com/aws-amplify/amplify-ios/pull/2393 
=> chore(datastore): update PR template with checkpoints 

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/AWSDataStorePlugin+DataStoreBaseBehavior.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/AWSDataStorePlugin.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginIntegrationTests/DataStoreEndToEndTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginIntegrationTests/TestSupport/SyncEngineIntegrationTestBase.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Core/AWSDataStorePluginTests.swift
https://github.com/aws-amplify/amplify-swift/issues/2167
This PR fixes a problem with the following code snippets:
```swift
Amplify.DataStore.stop { _ in 
Amplify.DataStore.start { _ in       
}
}
```
`stop` enters the queue.sync block and calls its completion handler which calls `start`. `start` attempts to enter the queue and waits for `stop` to finish, which will never happen. This PR prevents a crash by calling `completion` from a different thread.
`main` PR https://github.com/aws-amplify/amplify-swift/pull/2529
=> fix(datastore): fix stop then start API call pattern

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/OutgoingMutationQueue/ProcessMutationErrorFromCloudOperation.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RequestRetryablePolicy.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/MutationQueue/ProcessMutationErrorFromCloudOperationTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/RequestRetryablePolicyTests.swift
https://github.com/aws-amplify/amplify-swift/issues/2523
1. **`v1` PR https://github.com/aws-amplify/amplify-swift/pull/2532**  (You are here)
2. `main` PR https://github.com/aws-amplify/amplify-swift/pull/2536
In the scenario of toggling Wifi off and then saving a model, a mutation event will be produced and sent to AppSync. The API call can fail undeterministically with different URLError's. Most of the time it's the error "The Internet connection appears to be offline." corresponding to `.notConnectedToInternet` and the retry mechanism kicks in.
Sometimes it's "cannot parse response" which gets processed by `ProcessMutationErrorFromCloudOperation` as no-op, returns success to the OutgoingMutationQueue, which will then delete mutation …
=> fix(datastore): improve sync event error handling - cannotParseResponse

.github/workflows/integ_test_datastore_v2.yml
=> chore(datastore): update timeout of TransformerV2 tests to 30mins

Amplify/Categories/Storage/StorageCategory+ClientBehavior.swift, Amplify/Categories/Storage/StorageCategoryBehavior.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/AWSS3StoragePlugin+AsyncClientBehavior.swift, AmplifyPlugins/Storage/Tests/StorageHostApp/AWSS3StoragePluginIntegrationTests/AWSS3StoragePluginProgressTests.swift, AmplifyPlugins/Storage/Tests/StorageHostApp/AWSS3StoragePluginIntegrationTests/AWSS3StoragePluginTestBase.swift, AmplifyPlugins/Storage/Tests/StorageHostApp/AWSS3StoragePluginIntegrationTests/ResumabilityTests/AWSS3StoragePluginGetDataResumabilityTests.swift, AmplifyPlugins/Storage/Tests/StorageHostApp/AWSS3StoragePluginIntegrationTests/ResumabilityTests/AWSS3StoragePluginPutDataResumabilityTests.swift, AmplifyPlugins/Storage/Tests/StorageHostApp/StorageHostApp.xcodeproj/project.pbxproj, AmplifyPlugins/Storage/Tests/StorageHostApp/StorageHostApp/Info.plist, AmplifyTestCommon/Mocks/MockStorageCategoryPlugin.swift, AmplifyTests/CategoryTests/Hub/AmplifyOperationHubTests.swift, CHANGELOG.md
*Issue #, if available:* https://github.com/aws-amplify/amplify-swift/issues/2546
Update the storage api to remove the `async throws` from apis that return task.
=> feat(storage): Remove the async throws from the apis that return task

AmplifyPlugins/Predictions/AWSPredictionsPluginIntegrationTests/IdentifyBasicIntegrationTests.swift
Updating the `testIdentifyTextForms` integration test to validate that it recognized the words instead of just the number of words, as the latter can change if the service is updated.
=> chore(Predictions): Fixing integration test.

AmplifyPlugins/Geo/Sources/AWSLocationGeoPlugin/Dependency/AWSDeviceTracker.swift, AmplifyPlugins/Geo/Sources/AWSLocationGeoPlugin/Support/Constants/GeoPluginErrorConstants.swift, AmplifyPlugins/Geo/Tests/AWSLocationGeoPluginTests/AWSDeviceTrackerTests.swift, AmplifyPlugins/Geo/Tests/AWSLocationGeoPluginTests/Mocks/MockLocationManager.swift, Package.swift
*Description of changes:* Update startTracking() to throw error when called multiple times with different devices and update tests
~~- [] Documentation update for the change if required~~
=> chore(geo): update startTracking() and update tests

AmplifyPlugins/API/Sources/AWSAPIPlugin/Operation/AWSGraphQLSubscriptionTaskRunner.swift, AmplifyPlugins/API/Tests/APIHostApp/APIHostApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, AmplifyPlugins/API/Tests/AWSAPIPluginTests/Operation/GraphQLSubscribeTaskTests.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/RemoteSyncEngine+Retryable.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/RequestRetryablePolicy.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Sync/RequestRetryablePolicyTests.swift
https://github.com/aws-amplify/amplify-swift/issues/2152
- `main` PR https://github.com/aws-amplify/amplify-swift/pull/2571 (This PR)
- `v1` PR https://github.com/aws-amplify/amplify-swift/pull/2581 
Once DataStore is in an active state, then the network goes down, then recovers, the subscription websocket will send an error on network recovery. This error propagated back to API/DataStore which handles the error by moving DataStore to a stopped state. It is not processed as retryable. This delays the recoverability of DataStore until the next DataStore operation is called, since it remains in a stopped state. The scenario is reproducible by running an iOS app on a device or running a macOS app on the macbook. Running on an iOS simulator …
=> fix(datastore): retry on subscription connection error

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthConfirmSignInTask.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/AWSAuthSignInPluginTests.swift
*#2586*
There are 2 changes being made: 
* Introduce sending of the `confirmSignIn` event outside of the state machine listener. 
* When in `waitingForAnswer` state, validate and return the `nextStep` based on the result
=> fix(Auth): Add correct validation for initial state when executing confirm sign in

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/Helpers/HostedUISignInHelper.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthSignInTask.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/AWSAuthSignInPluginTests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/HostedUITests/AWSAuthHostedUISignInTests.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthHostApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/SignInTests/AuthSRPSignInTests.swift
*Issue #, if available:* https://github.com/aws-amplify/amplify-swift/issues/2605
Fix to allow user to restart a signIn flow in the middle of an existing signIn flow. This feature allows the user to retry a signIn with a different username if they entered a wrong username and the plugin is waiting for some signIn verification. 
=> fix(auth): Enable signIn restart while another signIn is in progress

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Service/ErrorMapping/ChangePasswordOutputError+AuthError.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Service/ErrorMapping/ConfirmForgotPasswordOutputError+AuthError.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Service/ErrorMapping/ConfirmSignUpOutputError+AuthError.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Service/ErrorMapping/DeleteUserOutputError+AuthError.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Service/ErrorMapping/ForgetDeviceOutputError+AuthError.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Service/ErrorMapping/ForgotPasswordOutputError+AuthError.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Service/ErrorMapping/GetCredentialsForIdentityOutputError+AuthError.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Service/ErrorMapping/GetIdOutputError+AuthError.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Service/ErrorMapping/GetUserAttributeVerificationCodeOutputError+AuthError.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Service/ErrorMapping/GetUserOutputError+AuthError.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Service/ErrorMapping/InitiateAuthOutputError+AuthError.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Service/ErrorMapping/ListDevicesOutputError+AuthError.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Service/ErrorMapping/ResendConfirmationCodeOutputError+Error.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Service/ErrorMapping/RespondToAuthChallengeOutputError+AuthError.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Service/ErrorMapping/SdkError+AuthError.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Service/ErrorMapping/SignUpOutputError+AuthError.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Service/ErrorMapping/UpdateDeviceStatusOutputError+AuthError.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Service/ErrorMapping/UpdateUserAttributesOutputError+AuthError.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Service/ErrorMapping/VerifyUserAttributeOutputError+AuthError.swift
* Removing `unknown default` since it will never get executed
=> chore(auth): remove unknown default enum case from error mapping

Amplify/Categories/Auth/Error/AuthError.swift, Amplify/Core/Support/AmplifyErrorMessages.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/Helpers/HostedUISignInHelper.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Data/DeviceMetadata.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/Authentication/AuthenticationState+Resolver.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/CustomAuth/CustomSignInState+Resolver.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/MigrateAuth/MigrateSignInState+Resolver.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/SRP/SRPSignInState+Resolver.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/SignIn/HostedUISignInState+Resolver.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthSignInTask.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/AWSAuthSignInPluginTests.swift
- When an error happens in Auth signIn flow, we return the statemachine with an error and sends two parallel events: one for cancelling signIn flow and another to update authentication state to error. Both of these could be processed after the running signIn flow is completed, which can affect a new signIn flow that immediately follow. This PR removes the parallel events and moves the cancel signIn flow to the Task so that the current signIn flow is complete only when the state machine is cleared up.
- The line number and file info passed in recovery suggestion is not giving any useful information. This PR removes those details from the message.
- Masked device meta data information …
=> fix(auth): Remove parallel event that moves auth plugin to an error state and other cleanups

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/ClientBehavior/AWSCognitoAuthPlugin+ClientBehavior.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/States/DebugInfo/SignInChallengeState+Debug.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/States/SignInChallengeState.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/SignIn/SignInChallengeState+Resolver.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthConfirmSignInTask.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthSignInTask.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/ClientBehaviorTests/AWSAuthConfirmSignInTaskTests.swift
*Issue #, if available:* https://github.com/aws-amplify/amplify-swift/issues/2615
*Description of changes:* Confirm signIn initial validation step did not check if the previous confirm signIn was in an error state. This PR enables that which allows to retry failed confirm signin. 
=> fix(auth): Enable retrying when confirm signIn fails

.github/workflows/release_block_manual_pr.yml
Remove exit-with-failure from block-manual-release workflow.  Because of the way the workflow works, it only runs when it’s not run by another workflow.  It closes the PR so that it cannot be merged.  It also previously exited the a failed check, but since it's designed to never run except when it should "fail", the failed check remained on subsequent PRs that were created by the release workflow.  This removes the failed exit on the end since it's not necessary and pollutes future release PRs.
*DataStore …
=> chore: remove exit-with-failure from block-manual-release workflow

.github/workflows/integ_test.yml, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthHostApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, AmplifyPlugins/Geo/Tests/GeoHostApp/GeoHostApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
*Description of changes:* Integration tests apps for each category has now multiple schemes e.g integration tests and stress tests. This PR is to change the scheme for integration tests github action from the HostApp to integration tests.
=> fix: Change Integration Test Github action to run only integration test scheme

.github/workflows/integ_test.yml, AmplifyPlugins/Analytics/Tests/AnalyticsHostApp/AnalyticsHostApp.xcodeproj/xcshareddata/xcschemes/AWSPinpointAnalyticsPluginIntegrationTests.xcscheme, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthHostApp.xcodeproj/xcshareddata/xcschemes/AuthIntegrationTests.xcscheme, AmplifyPlugins/Storage/Tests/StorageHostApp/StorageHostApp.xcodeproj/xcshareddata/xcschemes/AWSS3StoragePluginIntegrationTests.xcscheme
*Description of changes:* Add missing integration test scheme for Storage and Analytics
=> fix: Add missing integration test scheme for Storage and Analytics

AmplifyPlugins/Geo/Tests/GeoHostApp/AWSLocationGeoPluginIntegrationTests/AWSLocationGeoPluginIntegrationTests.swift, AmplifyPlugins/Geo/Tests/GeoHostApp/GeoHostApp.xcodeproj/project.pbxproj, AmplifyPlugins/Geo/Tests/GeoHostApp/GeoHostApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, AmplifyPlugins/Geo/Tests/GeoHostApp/GeoHostApp.xcodeproj/xcshareddata/xcschemes/GeoHostApp.xcscheme, AmplifyPlugins/Geo/Tests/GeoHostApp/GeoHostApp.xcodeproj/xcshareddata/xcschemes/GeoStressTests.xcscheme, AmplifyPlugins/Geo/Tests/GeoHostApp/GeoStressTests/GeoStressTests.swift, AmplifyPlugins/Geo/Tests/GeoHostApp/GeoStressTests/README.md
*Description of changes:* Add stress tests for Geo checking for concurrent executions of `searchForText()` and `searchForCoordinates()` API.
=> chore(geo): Add stress tests for Geo category

.github/workflows/stress_test.yml, AmplifyPlugins/Analytics/Tests/AnalyticsHostApp/AnalyticsStressTests/AnalyticsStressTests.swift, AmplifyPlugins/Analytics/Tests/AnalyticsHostApp/AnalyticsStressTests/README.md, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthHostApp.xcodeproj/project.pbxproj, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthStressTests/AuthStressBaseTest.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthStressTests/AuthStressTests.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthStressTests/README.md, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/DataStoreStressTests/DataStoreStressBaseTest.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/DataStoreStressTests/DataStoreStressTests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/DataStoreStressTests/README.md, AmplifyPlugins/Geo/Tests/GeoHostApp/GeoStressTests/GeoStressTests.swift, AmplifyPlugins/Geo/Tests/GeoHostApp/GeoStressTests/README.md, AmplifyPlugins/Storage/Tests/StorageHostApp/StorageStressTests/README.md, AmplifyPlugins/Storage/Tests/StorageHostApp/StorageStressTests/StorageStressTests.swift
*Issue #, if available:* None 
Add github action for stress tests in all categories. 
All categories except GraphQLAPI use the same configuration file (all categories are added to a single Amplify app).
**Note: GraphQLAPI stress tests need a separate configuration file as conflict detection needs to be turned on for Datastore Stress tests.**
=> chore: Add github action for stress tests in all categories

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/FetchAuthorizationSession/FetchIdentity/FetchAuthIdentityId.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/FetchAuthorizationSession/InformSessionError.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Service/ErrorMapping/SdkError+AuthError.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/ErrorMapping/SignInError+Helper.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Helpers/UserPoolSignInHelper.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/AuthorizationTests/AWSAuthFetchSignInSessionOperationTests.swift
*Issue #, if available:* https://github.com/aws-amplify/amplify-swift/issues/2599
=> fix(auth): Return session expired on revoke token

Amplify/Categories/API/Request/RESTRequest.swift, AmplifyPlugins/API/Sources/AWSAPIPlugin/Support/Utils/GraphQLOperationRequestUtils.swift, AmplifyPlugins/API/Tests/AWSAPIPluginTests/Request/GraphQLOperationRequestUtilsTests.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Service/Storage/AWSS3StorageService.swift, AmplifyTests/CategoryTests/API/APICategoryClientRESTTests.swift
*Description of changes:* Updates the cache control of Storage and API category to disable caching by default. This can be overridden by setting the Cache-Control request header for API rest category.
=> feat(api): Update url cache for storage and api to nil

Amplify/Categories/API/Request/RESTRequest.swift, Amplify/Categories/DataStore/DataStoreCategory+Behavior+Combine.swift, AmplifyPlugins/API/AWSAPICategoryPlugin/Support/Utils/GraphQLOperationRequestUtils.swift, AmplifyPlugins/API/AWSAPICategoryPluginTests/Request/GraphQLOperationRequestUtilsTests.swift, AmplifyPlugins/Core/AWSPluginsCore/Model/Support/Model+GraphQL.swift, AmplifyTests/CategoryTests/API/APICategoryClientRESTTests.swift
*Description of changes:* Updates the cache control of API category to disable caching by default. This can be overridden by setting the Cache-Control request header for API rest category.
=> feat(api): Add no store for the cache in urlsession for API category

AmplifyPlugins/Storage/AWSS3StoragePlugin/Operation/AWSS3StorageUploadFileOperation.swift, AmplifyPlugins/Storage/AWSS3StoragePluginTests/Operation/AWSS3StorageUploadFileOperationTests2.swift, AmplifyPlugins/Storage/StoragePlugin.xcodeproj/project.pbxproj
https://github.com/aws-amplify/amplify-swift/issues/2355
**v1** fix for https://github.com/aws-amplify/amplify-swift/issues/2355 where upload will do an early return if the file represented by the given URL is innaccessible.
=> fix(storage) Storage.uploadFile exits early on access denied

AmplifyPlugins/API/Tests/APIHostApp/AWSAPIPluginFunctionalTests/GraphQLConnectionScenario3Tests+List.swift, AmplifyPlugins/API/Tests/APIHostApp/AWSAPIPluginFunctionalTests/GraphQLModelBasedTests.swift
This API integration test, APIFunctionalTests, has been failing sometimes on asserting the count. This test code change will exhaust the pages until there's a count. If there are no pages left and count == 0, will break out of the loop and continue to fail on the count assertion.
Github Actions workflow run: https://github.com/aws-amplify/amplify-swift/actions/runs/3896568033 ✅
=> chore(api): functional integ tests - paginate on list requests

AmplifyPlugins/Auth/AWSCognitoAuthPlugin.xcodeproj/project.pbxproj, AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/HubEventTests/AuthHubEventHandlerFetchSessionApiTests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/HubEventTests/AuthHubEventHandlerSignInApiTests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/HubEventTests/AuthHubEventHandlerSignOutTests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/HubEventTests/AuthHubEventHandlerTests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/HubEventTests/AuthHubEventHandlerUserDeletedTests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/Mocks/MockAuthCognitoTokens.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/Mocks/MockAuthSession.swift
https://github.com/aws-amplify/amplify-swift/issues/2681
Ensuring AuthHubEventHandler has 100% code coverage during unit testing.
=> chore(auth) Test AuthHubEventHandler.

AmplifyPlugins/Auth/AWSCognitoAuthPlugin.xcodeproj/project.pbxproj, AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Support/Utils/AWSCognitoAuthPluginUserDefaults.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AWSCognitoAuthPluginTests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthenticationProviderTests/AuthenticationProviderAdapterTests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/AuthorizationProviderTests/AuthorizationProviderAdapterTests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/ClientBehaviorAPITests/AWSCognitoAuthClientBehaviorTests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/ClientBehaviorAPITests/AWSCognitoAuthUserBehaviorTests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/Mocks/MockAWSMobileClient.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/Mocks/MockAuthDeviceServiceBehavior.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/Mocks/MockAuthHubEventBehavior.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/Mocks/MockAuthUserServiceBehavior.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/Mocks/MockAuthenticationProviderBehavior.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/Mocks/MockAuthorizationProviderBehavior.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginTests/Utils/AWSCognitoAuthPluginUserDefaultsTests.swift
https://github.com/aws-amplify/amplify-swift/issues/2685
This commit ensures that auth unit tests wait for operations they create complete. There are also a few minor additional unit tests for low-hanging fruit.
=> Amplify.Auth v1: Fix asynchronous operations outlive unit tests

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/States/AuthorizationState.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/States/DebugInfo/AuthorizationState+Debug.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/Authorization/AuthorizationState+Resolver.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/AuthorizationTests/AWSAuthFetchSignInSessionOperationTests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TestHarness/CodableStates/AuthorizationState+Codable.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TestResources/states/SigningIn_SigningIn.json
https://github.com/aws-amplify/amplify-swift/issues/2608
Current implementation of the auth state machine blocks any fetch Auth session call to be invoked if there is a signIn is in progress. This causes issue if we want to call fetchAuthSession when the library is waiting for user input for confirm signIn. This PR unblocks the fetchAuthSession api during signIn invocation. 
Note that this does not interfere in a signIn flow because only one api will be executing at a time in the auth plugin.
=> fix(auth): Unblock fetchAuthSession call during a signIn flow

AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/AWSAuthBaseTest.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/AuthSessionTests/SignedInAuthSessionTests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/README.md, AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/Support/AuthSessionHelper.swift
https://github.com/aws-amplify/amplify-swift/issues/2692
This SignedInAuthSessionTests fix ensures that:
1. The assertions made in SignedInAuthSessionTests fail as early as possible.
2. AuthSessionHelper normalizes its namespace before performing operations on the keychain dictionary.
=> chore(auth): Fix SignedInAuthSessionTests

AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/AWSAuthBaseTest.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/AuthDeleteUserTests/AuthDeleteUserTests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/AuthDeviceTests/AuthDeviceOperationTests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/AuthSessionTests/SignedInAuthSessionTests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/AuthSessionTests/SignedOutAuthSessionTests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/AuthSignInTests/AuthUsernamePasswordSignInTests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/AuthSignOutTests/AuthSignOutTests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/AuthSignUpTests/AuthConfirmSignUpTests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/AuthSignUpTests/AuthResendSignUpCodeTests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/AuthSignUpTests/AuthSignUpTests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/AuthUserAttributesTests/AuthUserAttributesTests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/AuthUserTests/AuthUserTests.swift
https://github.com/aws-amplify/amplify-swift/issues/2695
This fix ensures AWSAuthBaseTest subclasses setup fail if `initializeAmplify()` fails.
=> chore(auth): Ensure AWSAuthBaseTest subclasses setup fail if initializeAmplify fails

AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/AuthDeleteUserTests/AuthDeleteUserTests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/AuthDeviceTests/AuthDeviceOperationTests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/AuthSignInTests/AuthUsernamePasswordSignInTests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/AuthSignOutTests/AuthSignOutTests.swift, AmplifyPlugins/Auth/AWSCognitoAuthPluginIntegrationTests/AuthUserAttributesTests/AuthUserAttributesTests.swift
https://github.com/aws-amplify/amplify-swift/issues/2705
Ensuring integration tests fail fast on assertions such as those for a successful sign-in. This helps reduce noise during investigations. Think of this as the unit test equivalent of an [andon cord](https://en.wikipedia.org/wiki/Andon_(manufacturing)).
=> chore(auth): Integration tests fail fast on failed assertions

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/RefreshAuthorizationSession/UserPool/RefreshUserPoolTokens.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/DeviceSRPAuth/InitiateAuthDeviceSRP.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/IntializeSignInFlow.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Helpers/DeviceMetadataHelper.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/DeviceTasks/AWSAuthForgetDeviceTask.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/DeviceTasks/AWSAuthRememberDeviceTask.swift
NA
- Adds a method to clear devicemetadata from keychain, this will be used for device meta data cleanup during signIn.
- Change the `getDeviceMetaData` property to accurately say that it is fetching deviceMetaData for a user. 
=> chore(auth): Adds device helper method to clear devicemeta data info

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/DeviceSRPAuth/InitiateAuthDeviceSRP.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/DeviceSRPAuth/VerifyDevicePasswordSRP.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/SRPAuth/InitiateAuthSRP.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/SRPAuth/VerifyPasswordSRP.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Data/SRPStateData.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Utils/RespondToAuthChallengeInput+Amplify.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ResolverTests/SRPSignInState/SRPTestData.swift
NA
DeviceMetaData is stored in keychain which are mapped to `username`. But the `username` value changes during the signIn flow, because in the username defined by Cognito is different from the one entered by user. For example in case of user alias if user entered a phone number as `username`, on `initiateAuth` will return a UUID as `username`. 
We should use this username to see if we have a mapping of deviceMetaData on the next step of authflow and should not keep a static deviceMetadata.
=> fix(auth): Remove static deviceMetaData in auth flow

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/SRPAuth/VerifyPasswordSRP.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/VerifySignInChallenge.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Utils/RespondToAuthChallengeInput+Amplify.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ActionTests/InitiateAuthSRP/VerifyPasswordSRPTests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ActionTests/VerifySignInChallenge/VerifySignInChallengeTests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ResolverTests/SRPSignInState/SRPTestData.swift
- Pass deviceMetadata in RespondToAuthChallenge for signIn challenges, this value was only passed for SRP flow. PR changes that and deviceMetaData is passed for MFA challenge and other related flows.
- Some code cleanup which are used by the next PR - https://github.com/aws-amplify/amplify-swift/pull/2699
=> fix(auth): Pass deviceMetadata in RespondToAuthChallenge for signIn challenges

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/SRPAuth/VerifyPasswordSRP.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/VerifySignInChallenge.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Events/SignInChallengeEvent.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Events/SignInEvent.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/SRP/SRPSignInState+Resolver.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/SignIn/SignInChallengeState+Resolver.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Helpers/DeviceMetadataHelper.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Helpers/UserPoolSignInHelper.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ActionTests/InitiateAuthSRP/VerifyPasswordSRPTests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ActionTests/VerifySignInChallenge/VerifySignInChallengeTests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/ClientBehaviorTests/AWSAuthConfirmSignInTaskTests.swift
Add logic to retry the respondToAuthChallenge in case device not found was received.
=> fix(auth): Device binding add retry incase of device not found

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/DeleteUser/DeleteUser.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/ClientBehavior/AWSCognitoAuthPlugin+ClientBehavior.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/Helpers/FetchAuthSessionOperationHelper.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Service/ErrorMapping/AuthErrorConvertible.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Service/ErrorMapping/SdkError+AuthError.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Events/AuthEvents.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/AuthState/AuthState+Resolver.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/RefreshSession/RefreshSessionState+Resolver.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthDeleteUserTask.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/AuthenticationProviderDeleteUserTests.swift
*Issue #, if available:* https://github.com/aws-amplify/amplify-swift/issues/2643
When delete user fails, the auth state machine reaches a terminal state and it never recovers from there. This PR changes that and if the delete user fails, auth state machine will try to configure back to the previous state using the cached credentials.
=> fix(auth): Delete user api get stuck on no network

.github/composite_actions/run_xcodebuild_test/action.yml, .github/workflows/nightly_repeated_unittest.yml
Adds the unit test to run repeated iteration nightly.
Sample test run - https://github.com/aws-amplify/amplify-swift/actions/runs/3899004585/jobs/6658264423
=> test: Add nightly repeated unit test

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/Helpers/FetchAuthSessionOperationHelper.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/Helpers/HostedUISignInHelper.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Helpers/UserPoolSignInHelper.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthChangePasswordTask.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthClearFederationToIdentityPoolTask.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthConfirmResetPasswordTask.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthConfirmSignInTask.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthConfirmSignUpTask.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthDeleteUserTask.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthFederateToIdentityPoolTask.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthFetchSessionTask.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthResendSignUpCodeTask.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthResetPasswordTask.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthSignInTask.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthSignOutTask.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthSignUpTask.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthWebUISignInTask.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/Helpers/AWSAuthTaskHelper.swift
Adds more logs in verbose for easier debugging. Example of logs:
```
2023-01-27 13:38:18.432817-0800 AmplifyAuthSample[48850:3388855] [AWSAuthSignInTask] Starting execution
2023-01-27 13:38:18.433187-0800 AmplifyAuthSample[48850:3388855] [AWSAuthTaskHelper] Check if authstate configured
2023-01-27 13:38:18.433271-0800 AmplifyAuthSample[48850:3388855] [AWSAuthTaskHelper] Auth state configured
2023-01-27 13:38:18.433389-0800 AmplifyAuthSample[48850:3388855] [AWSAuthSignInTask] Validating current state
2023-01-27 13:38:18.433786-0800 AmplifyAuthSample[48850:3388855] [AWSAuthSignInTask] Signing with customWithSRP
2023-01-27 13:38:18.433846-0800 AmplifyAuthSample[48850:3388855] [AWSAuthSignInTask] Sending signIn event
2023-01-27 13:38:18.434026-0800 AmplifyAuthSample[48850:3388855] …
```
=> chore(auth): Add more verbose logging for easier debugging

.github/CODEOWNERS
N/A
Remove amplify-data team from codeowners
- ~[ ] Build succeeds with all target using Swift Package Manager~
- ~[ ] All unit tests pass~
- ~[ ] Security oriented best practices and standards are followed (e.g. using input sanitization, principle of least privilege, etc)~
- ~[ ] PR title conforms to conventional commit style~
- ~[ ] New or updated tests include `Given When Then` inline code documentation and are named accordingly `testThing_condition_expectation()`~
- ~[ ] If breaking change, documentation/changelog update with migration instructions~
By submitting this pull request, I confirm that my contribution is made under the terms of the …
=> chore: remove amplify-data from codeowners

.github/CODEOWNERS
N/A
Remove amplify-data team from codeowners
- ~[ ] Build succeeds with all target using Swift Package Manager~
- ~[ ] All unit tests pass~
- ~[ ] Security oriented best practices and standards are followed (e.g. using input sanitization, principle of least privilege, etc)~
- ~[ ] PR title conforms to conventional commit style~
- ~[ ] New or updated tests include `Given When Then` inline code documentation and are named accordingly `testThing_condition_expectation()`~
- ~[ ] If breaking change, documentation/changelog update with migration instructions~
By submitting this pull request, I confirm that my contribution is made under the terms of the …
=> chore: v1 - remove amplify-data from codeowners

fastlane/Fastfile
None 
Remove the character v from release tags so that SPM correctly imports the major version
=> chore: Remove v from release tags

Amplify/Categories/DataStore/Model/Internal/Schema/ModelField+Association.swift, Amplify/Categories/DataStore/Model/Internal/Schema/ModelSchema+Definition.swift, AmplifyPlugins/Core/AWSPluginsCore/Model/Support/Model+GraphQL.swift, AmplifyPlugins/Core/AWSPluginsCore/Model/Support/QueryPredicate+GraphQL.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/ModelSchema+SQLite.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Subscribe/DataStoreObserveQueryOperationTests.swift, AmplifyTests/CategoryTests/DataStore/ModelFieldAssociationTests.swift
- Library Changes `data-dev-preview` https://github.com/aws-amplify/amplify-swift/pull/2730 
- Library Changes `v1` - https://github.com/aws-amplify/amplify-swift/pull/2734 (You are here)
- Library Changes `main` - https://github.com/aws-amplify/amplify-swift/pull/2735
- Codegen Changes - https://github.com/aws-amplify/amplify-codegen/pull/538 
- Codegen Changes has-one - https://github.com/aws-amplify/amplify-codegen/pull/541
This PR does not attempt to fix the uni-directional has-many lazy loading list issue, see https://github.com/aws-amplify/amplify-swift/pull/2730  for more details and the fix. Since the CPK codegen changes (https://github.com/aws-amplify/amplify-codegen/pull/538 ) are available in `v1`, this PR introduces that parameter to make sure newly generated types continue to …
=> fix(v1): CPK has-many has-one associatedFields

Amplify/Categories/DataStore/Model/Lazy/DefaultModelProvider.swift, AmplifyPlugins/API/Tests/APIHostApp/APIHostApp.xcodeproj/project.pbxproj, AmplifyPlugins/API/Tests/APIHostApp/AWSAPIPluginLazyLoadTests/LL12/CompositePK/CompositePKParent+Schema.swift, AmplifyPlugins/API/Tests/APIHostApp/AWSAPIPluginLazyLoadTests/LL12/CompositePK/GraphQLLazyLoadCompositePKChildSansTests.swift, AmplifyPlugins/API/Tests/APIHostApp/AWSAPIPluginLazyLoadTests/LL12/CompositePK/GraphQLLazyLoadCompositePKChildTests.swift, AmplifyPlugins/API/Tests/APIHostApp/AWSAPIPluginLazyLoadTests/LL12/CompositePK/GraphQLLazyLoadCompositePKImplicitTests.swift, AmplifyPlugins/API/Tests/APIHostApp/AWSAPIPluginLazyLoadTests/LL12/CompositePK/GraphQLLazyLoadCompositePKStrangeExplicitTests.swift, AmplifyPlugins/API/Tests/APIHostApp/AWSAPIPluginLazyLoadTests/LL12/CompositePK/GraphQLLazyLoadCompositePKTests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginLazyLoadTests/LL12/CompositePK/AWSDataStoreLazyLoadCompositePKChildSansTests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginLazyLoadTests/LL12/CompositePK/AWSDataStoreLazyLoadCompositePKChildTests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginLazyLoadTests/LL12/CompositePK/AWSDataStoreLazyLoadCompositePKImplicitTests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginLazyLoadTests/LL12/CompositePK/AWSDataStoreLazyLoadCompositePKStrangeExplicitTests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginLazyLoadTests/LL12/CompositePK/AWSDataStoreLazyLoadCompositePKTests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginLazyLoadTests/LL12/CompositePK/CompositePKChild.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginLazyLoadTests/LL12/CompositePK/CompositePKParent+Schema.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginLazyLoadTests/LL12/CompositePK/StrangeExplicitChild.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/DataStoreHostApp.xcodeproj/project.pbxproj
When there is no metadata to create a ModelProvider, the lazy reference will be instantiated with `nil` identifiers with a DefaultModelProvider. When this happens, `try await` on the computed property should simply return `nil` on `get()` and throw on `require()`. 
=> fix: DefaultModelProvider return nil from not loaded state

Amplify/Categories/DataStore/Model/Internal/Schema/ModelField+Association.swift, Amplify/Categories/DataStore/Model/Internal/Schema/ModelSchema+Definition.swift, AmplifyPlugins/Core/AWSPluginsCore/Model/Support/Model+GraphQL.swift, AmplifyPlugins/Core/AWSPluginsCore/Model/Support/QueryPredicate+GraphQL.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/ModelSchema+SQLite.swift, AmplifyTests/CategoryTests/DataStore/ModelFieldAssociationTests.swift
We recently added this change https://github.com/aws-amplify/amplify-swift/pull/2734 expecting codegen to generate  has-one with `associatedFields` in https://github.com/aws-amplify/amplify-codegen/pull/541. We were working through some implementation details in https://github.com/aws-amplify/amplify-swift/pull/2737 that no longer depends on has-one to have `associatedFields`. This change is to revert it until we identify an actual need to move forward with the codegen changes. 
=> fix: revert CPK has-one associatedFields

.github/workflows/integ_test_api.yml, .github/workflows/integ_test_datastore_lazy_load.yml
Enable DataStore and API's lazy loading test targets
=> chore: enable ds/api lazy load tests

AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginV2Tests/TransformerV2/DataStoreConnectionOptionalAssociations.swift
While going over previous integration tests, specifically DataStoreTransformerV2 tests. One of the tests was failing because we were trying to send `nil` values of the foreign key for create mutations. We shouldn't be sending a create mutation, but rather an update mutation on an existing model. updateMutations will set `nil` values for the FK to act as an removal of an assocation. The implementation change was introduced in https://github.com/aws-amplify/amplify-swift/pull/2701 to `data-dev-preview` and this test was not run to catch the failure
=> fix(test): DS transformer V2 tests should be update mutation on existing model

AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/DataStoreObserveQueryTests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/TestSupport/SyncEngineIntegrationTestBase.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/DataStoreHostApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
As described in [doc](https://docs.amplify.aws/lib/datastore/sync/q/platform/ios/#selectively-syncing-a-subset-of-your-data), the datastore plugin is syncing the entire contents from cloud to local up to the max number of records set in configuration(*default is 1000*). 
For the case of `testInitialSyncWithPredicate`, it clears the whole database and trying to sync back to the latest created records. It will be failed if the cloud data set has more records than the max number of records that could be synced to local.
This fix setups the DataStore plugin with sync predication to only sync recent records.
=> test(datastore): fix ObserveQuery with predicate test case

AmplifyPlugins/API/Tests/APIHostApp/APIHostApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, AmplifyPlugins/API/Tests/APIHostApp/AWSAPIPluginFunctionalTests/GraphQLConnectionScenario2Tests.swift, AmplifyPlugins/API/Tests/APIHostApp/AWSAPIPluginFunctionalTests/GraphQLConnectionScenario3Tests+List.swift, AmplifyPlugins/API/Tests/APIHostApp/AWSAPIPluginFunctionalTests/GraphQLConnectionScenario3Tests.swift, AmplifyPlugins/API/Tests/APIHostApp/AWSAPIPluginLazyLoadTests/GraphQLLazyLoadBaseTest.swift
API category flaky test case `testListCommentsByPostID`.
If the backend storage is DynamoDB and no GSI on the query predication fields, the `query` GraphQL list operation may return items with empty list of items and an non-null next token.
=> test(api): fix flaky integration test cases

Amplify/Core/Support/Optional+Extension.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/MutationSync/AWSMutationDatabaseAdapter/AWSMutationDatabaseAdapter+MutationEventIngester.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/DataStoreEndToEndTests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/DataStoreHostApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, AmplifyTests/CoreTests/Optional+ExtentionTests.swift
https://github.com/aws-amplify/amplify-swift/issues/2059
v1 fix - https://github.com/aws-amplify/amplify-swift/pull/2782
In the `MutationEvent` [saving](https://github.com/aws-amplify/amplify-swift/blob/ac2b6a0/AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/MutationSync/AWSMutationDatabaseAdapter/AWSMutationDatabaseAdapter%2BMutationEventIngester.swift#L218-L242) implementation, we check `nextEventPromise` at the beginning to detect wether put the `MutationEvent` to `inProgress` status. After it's written to database, we change the `nextEventPromise` to `nil`. The operation between `non-nil` check at the beginning and set value `nil` for `nextEventPromise` doesn't lock the access of `nextEventPromise`. It may took over hundred milliseconds for writing to the database. In this …
=> fix(datastore): mutation event got ignored while executing parallel saving

AmplifyPlugins/API/Sources/AWSAPIPlugin/AWSAPIPlugin+Resettable.swift, AmplifyPlugins/API/Tests/APIHostApp/AWSAPIPluginGraphQLIAMTests/GraphQLWithIAMIntegrationTests.swift, AmplifyPlugins/API/Tests/APIHostApp/AWSAPIPluginGraphQLIAMTests/README.md
*Issue #, if available:* https://github.com/aws-amplify/amplify-swift/issues/2120
*Description of changes:* Use async APIs in GraphQL IAM integration tests and remove cleanUp() from AWSAPIPlugin.reset()
=> fix(api): Remove optional cleanUp() method from AWSAPIPlugin.reset()

AmplifyPlugins/Notifications/Push/Tests/PushNotificationHostApp/PushNotificationHostApp/ContentView.swift
rename hub payload event requestNotificationsPermissions in integration tests
=> fix(notifications): rename hub payload event requestNotificationsPermissions in integration tests

AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/AWSDataStorePlugin+DataStoreBaseBehavior.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/AWSDataStorePluginConfigurationTests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/Connection/DataStoreConnectionScenario6Tests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/DataStoreConfigurationTests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/DataStoreEndToEndTests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/TestSupport/HubEventsIntegrationTestBase.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/TestSupport/SyncEngineIntegrationTestBase.swift
- add 1 second sleep after `Amplify.reset()`
- fix the amplify setUp order of `SyncEngineIntegrationTestBase`
=> test(datastore): fix datastore integration test

.github/workflows/integ_test.yml, AmplifyPlugins/Notifications/Push/Tests/PushNotificationHostApp/PushNotificationHostApp.xcodeproj/project.pbxproj, AmplifyPlugins/Notifications/Push/Tests/PushNotificationHostApp/PushNotificationHostAppUITests/PushNotificationHostAppUITests.swift
- fix local integration tests
- disable notifications CI tests
- fix reference to amplify-swift package in notifications host app
=> chore(notifications): fix local integration tests and disable notifications CI tests

Amplify/Categories/DataStore/Query/ModelKey.swift, Amplify/Categories/DataStore/Query/QueryField.swift, Amplify/Categories/DataStore/Query/QueryOperator.swift, AmplifyPlugins/Core/AWSPluginsCore/Model/Support/QueryPredicate+GraphQL.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Storage/SQLite/QueryPredicate+SQLite.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/AWSDataStoreLocalStoreTests.swift
https://github.com/aws-amplify/amplify-swift/issues/1049
Related Android PR: https://github.com/aws-amplify/amplify-android/pull/1145
This change adds support for the `notContains` predicate for DataStore `query` and `delete` operations. This is a documented feature [[docs/swift/datastore/data-access/predicates](https://docs.amplify.aws/lib/datastore/data-access/q/platform/ios/#predicates)], however it is currently not supported in Amplify Swift. This addition reaches feature parity with regards to `notContains` with Android.
Functionally, it exposes a new static method `notContains(_ value: String) -> QueryPredicateOperation`, which is mapped to a `NOT LIKE '%value%'` operator.
Add tests cover multiple scenarios included `query` and `delete`, along with test cases for chained predicates …
=> feat(datastore): add notContains query operator

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Helpers/ConfigurationHelper.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/HostedUI/HostedUIRequestHelper.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/Support/HostedUIRequestHelperTests.swift
https://github.com/aws-amplify/amplify-swift/issues/2799
Adding the missing `Authorization` header to HostedUI requests when an `AppClientSecret` is defined.
=> fix(Auth): Adding missing Authorization header when a Client Secret is defined.

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthDeleteUserTask.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthSignOutTask.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/Helpers/AWSAuthTaskHelper.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/AuthenticationProviderDeleteUserTests.swift
Clear the existing user data by signing out when we get a user not found exception during a delete process. During this scenario, the delete user task is stuck in signed in state even though the user does not exist. 
=> fix(Auth): Sign out when user does not exist during delete user task

Amplify/Core/Support/Optional+Extension.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/AWSMutationDatabaseAdapter/AWSMutationDatabaseAdapter+MutationEventIngester.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginIntegrationTests/DataStoreEndToEndTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginIntegrationTests/TestSupport/SyncEngineIntegrationTestBase.swift, AmplifyPlugins/DataStore/Podfile.lock, AmplifyTests/CoreTests/Optional+ExtensionTests.swift
https://github.com/aws-amplify/amplify-swift/issues/2059
v2 fix - https://github.com/aws-amplify/amplify-swift/pull/2781
In the `MutationEvent` [saving](https://github.com/aws-amplify/amplify-swift/blob/ac2b6a0/AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/MutationSync/AWSMutationDatabaseAdapter/AWSMutationDatabaseAdapter%2BMutationEventIngester.swift#L218-L242) implementation, we check `nextEventPromise` at the beginning to detect wether put the `MutationEvent` to `inProgress` status. After it's written to database, we change the `nextEventPromise` to `nil`. The operation between `non-nil` check at the beginning and set value `nil` for `nextEventPromise` doesn't lock the access of `nextEventPromise`. It may took over hundred milliseconds for writing to the database. In this …
=> fix(datastore-v1): mutation event got ignored while executing parallel saving

AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/FileSystem.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Support/Internal/FileSystemTests.swift
https://github.com/aws-amplify/amplify-swift/issues/2607
Update Storage V2 to support downloading of file that already exists locally.  This matches current behavior in Amplify Swift V1 and Amplify Android library.
=> fix(storage): update storage to support downloading if a file already exist locally

.github/workflows/integ_test.yml
- enable push notification integration test
- added new amplify app and upload the configuration file to s3 for integration test
=> ci: enable push notification category integration test

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/QueryPredicate+SQLite.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/SQLite/SQLStatement+Condition.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginIntegrationTests/DataStoreLocalStoreTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Core/SQLStatementTests.swift
Moving from like to instr for DataStore predicates.
*Simplified overview for brevity, the actual SQL queries use bindings
| API                                     | Previous                   | New                               |
|--------------------------|---------------------|-----------------------|
| `foo.contains("bar")`       | `like "%bar%"`        | `instr(foo, "bar") > 0` |
| `foo.notContains("bar")` | `not like "%bar%"` | `instr(foo, "bar") = 0` |
| `foo.beginsWith("bar")`    | `like "bar%"`           | `instr(foo, "bar") = 1` |
=> fix(datastore): v1 swap `like` for `instr` in sql queries

AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Storage/SQLite/QueryPredicate+SQLite.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Storage/SQLite/SQLStatement+Condition.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/AWSDataStoreLocalStoreTests.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Core/SQLStatementTests.swift
Moving from `like` to `instr` for DataStore predicates.
*Simplified overview for brevity, the actual SQL queries use bindings
| API                                     | Previous                   | New                               |
|--------------------------|---------------------|-----------------------|
| `foo.contains("bar")`       | `like "%bar%"`        | `instr(foo, "bar") > 0` |
| `foo.notContains("bar")` | `not like "%bar%"` | `instr(foo, "bar") = 0` |
| `foo.beginsWith("bar")`    | `like "bar%"`           | `instr(foo, "bar") = 1` |
1 million simple entries
| # | `like` | `instr` |
|---|----|----|
| 1 | 0.08s user 0.02s system 72% cpu 0.147 total | 0.08s user 0.03s system 82% cpu 0.129 total |
| 2 | 0.08s user 0.02s system 77% cpu 0.139 total | 0.08s user 0.02s system 82% cpu …
=> fix(datastore): swap `like` for `instr` in sql queries

AmplifyPlugins/Internal/Sources/InternalAWSPinpoint/Context/AWSPinpointFactory.swift, AmplifyPlugins/Internal/Sources/InternalAWSPinpoint/Support/Utils/ProvisioningProfileReader.swift, AmplifyPlugins/Internal/Tests/InternalAWSPinpointUnitTests/AWSPinpointFactoryTests.swift, AmplifyPlugins/Internal/Tests/InternalAWSPinpointUnitTests/Mocks/MockProvisioningProfileReader.swift
https://github.com/aws-amplify/amplify-swift/issues/2809
For some reason, apps distributed through TestFlight using a release config seem to incorrectly set `isDebug` to `true` in the `PinpointConfiguration`, which then results in the `APNS_SANDBOX` channel being used instead of `APNS`.
@iheffernan suggested to read for the [APS entitlement](https://developer.apple.com/documentation/bundleresources/entitlements/aps-environment) in the provisioning profile (if there is one present) and use that to determine the debug status, and that seemed to resolve their issue.
I'm keeping the `DEBUG` flag check as a fallback for when there is no provisioning profile, or the APS entitlement can't be found.
By submitting this pull request, I confirm that my contribution is made under the terms of the …
=> fix(PushNotifications): Checking if there is a Provisioning Profile with the APS Entitlement in order to determine the ChannelType

Amplify/Categories/Storage/Operation/Request/StorageListRequest.swift, Amplify/Categories/Storage/Result/StorageListResult.swift, Amplify/Categories/Storage/StorageCategoryBehavior.swift, Amplify/Categories/Storage/StorageCategoryPlugin.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Service/Storage/AWSS3StorageService+ListBehavior.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Request/AWSS3StorageListRequestTests.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Service/Storage/AWSS3StorageServiceListTests.swift, AmplifyPlugins/Storage/Tests/StorageHostApp/AWSS3StoragePluginIntegrationTests/AWSS3StoragePluginBasicIntegrationTests.swift
https://github.com/aws-amplify/amplify-swift/issues/1286
This change brings the Swift implementation of Storage to parity with other libraries as it relates to listing pagination support.
=> feat(storage): Add pagination support.

AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/MutationSync/AWSMutationDatabaseAdapter/AWSMutationDatabaseAdapter+MutationEventIngester.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/SubscriptionSync/ReconcileAndLocalSave/ReconcileAndLocalSaveOperation.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/Support/MutationEvent+Extensions.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/Support/MutationEvent+Query.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Sync/SubscriptionSync/ReconcileAndLocalSaveOperationTests.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Sync/Support/MutationEventExtensionsTests.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Sync/Support/MutationEventQueryTests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/DataStoreEndToEndTests.swift
https://github.com/aws-amplify/amplify-swift/issues/2832
Currently, detecting mutation event duplication is only by model's primary key value. Logically, this should be the combination of model type name and model's primary key.
=> fix(datastore): detect duplicate mutation event by both modelName and modelId

AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginIntegrationTests/DataStoreObserveQueryTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginIntegrationTests/TestSupport/SyncEngineIntegrationTestBase.swift
refer to the description of PR for v2: https://github.com/aws-amplify/amplify-swift/pull/2784
=> test(datastore-v1): fix ObserveQuery with predicate test case

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/MutationSync/AWSMutationDatabaseAdapter/AWSMutationDatabaseAdapter+MutationEventIngester.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/ReconcileAndLocalSave/ReconcileAndLocalSaveOperation.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/Support/MutationEvent+Extensions.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/Support/MutationEvent+Query.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginIntegrationTests/DataStoreEndToEndTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/SubscriptionSync/ReconcileAndLocalSaveOperationTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/Support/MutationEventExtensionsTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/Support/MutationEventQueryTests.swift
https://github.com/aws-amplify/amplify-swift/issues/2832
- [v2 PR](https://github.com/aws-amplify/amplify-swift/pull/2834)
Currently, detecting mutation event duplication is only by model's primary key value. Logically, this should be the combination of model type name and model's primary key.
=> fix(datastore-v1): detect duplicate mutation event by both modelName and modelId

.circleci/config.yml, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/DataStoreHostApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
CI testing script is cloning whole repo history.
- Change to shallow checkout with default depth 1.
- Remove unnecessary cache.
=> ci: use shallow checkout with depth 1

.circleci/config.yml, CircleciScripts/jazzy_doc_gen.sh
`deploy` step relies on git history to [generate](https://github.com/aws-amplify/amplify-ci-support/blob/main/src/fastlane/release_actions/lib/fastlane/plugin/release_actions/helper/git.rb#L6-L13) the tag for releases. We may need to change the implementation of customize fastlane actions in [amplify-ci-support](https://github.com/aws-amplify/amplify-ci-support/tree/main).
For doc generation step, we don't need clone and install jazz as we've done in the previous steps of CI workflow.
- roll back to use offical full checkout for `deploy` step
- simplify doc generation step
=> ci: use default checkout action on deploy step

Amplify/Core/Support/ChildTask.swift, AmplifyPlugins/Storage/Tests/StorageHostApp/AWSS3StoragePluginIntegrationTests/AWSS3StoragePluginProgressTests.swift, AmplifyTests/CoreTests/AmplifyTaskTests.swift, AmplifyTests/CoreTests/ChildTaskTests.swift
https://github.com/aws-amplify/amplify-swift/issues/2840
This fix ensures that calling something like this **does not hang**:
```
let task = Amplify.Storage.uploadFile(key: key, local: url)
for await progress in await task.progress {
...
}
```
=> fix(storage): Ensure progress from Amplify.Storage.uploadFile completes

.circleci/config.yml, CircleciScripts/jazzy_doc_gen.sh
Shallow checkout doesn't apply to generate api doc step as several skip ci commits will be pushed to `release` branch. The shallow checkout depends on the current branch HEAD hash is same to the CircleCI job commit hash.
- roll back to normal checkout
- set git user to CircleCI predefined one for doc commit
=> ci: fix doc generation step

AmplifyPlugins/Predictions/AWSPredictionsPlugin/AWSPredictionsPlugin.swift, Package.swift
Makes `AWSPredictionsPlugin.init` internal until the v2 implementation lands to avoid accidentally calling unimplemented (`fatalError`) APIs.
=> fix(predictions): make predictions plugin init internal

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthChangePasswordTask.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthConfirmResetPasswordTask.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthResendSignUpCodeTask.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthResetPasswordTask.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/DeviceTasks/AWSAuthFetchDevicesTask.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/DeviceTasks/AWSAuthForgetDeviceTask.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/DeviceTasks/AWSAuthRememberDeviceTask.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/UserTasks/AWSAuthAttributeResendConfirmationCodeTask.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/UserTasks/AWSAuthConfirmUserAttributeTask.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/UserTasks/AWSAuthFetchUserAttributeTask.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/UserTasks/AWSAuthUpdateUserAttributeTask.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/UserTasks/AWSAuthUpdateUserAttributesTask.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/ClientBehaviorTests/AWSAuthConfirmSignUpAPITests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/ClientBehaviorTests/AWSAuthResendSignUpCodeAPITests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/ClientBehaviorTests/AWSAuthSignUpAPITests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/ClientBehaviorTests/ClientBehaviorConfirmResetPasswordTests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/ClientBehaviorTests/ClientBehaviorResetPasswordTests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/DeviceBehaviorTests/DeviceBehaviorFetchDevicesTests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/DeviceBehaviorTests/DeviceBehaviorForgetDeviceTests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/DeviceBehaviorTests/DeviceBehaviorRememberDeviceTests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/UserBehaviourTests/UserBehaviorChangePasswordTests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/UserBehaviourTests/UserBehaviorConfirmAttributeTests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/UserBehaviourTests/UserBehaviorFetchAttributeTests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/UserBehaviourTests/UserBehaviorResendCodeTests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/UserBehaviourTests/UserBehaviorUpdateAttributeTests.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthHostApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
#2857 
Some of the Auth Tasks were not catching the SdkErrors correctly. Added correct handling and tests. 
=> fix(Auth): Fixing handling of service SdkError in Auth tasks

.circleci/config.yml, AmplifyPlugins/Internal/Tests/InternalAWSPinpointUnitTests/Mocks/MockAnalyticsClient.swift, AmplifyPlugins/Internal/Tests/InternalAWSPinpointUnitTests/SessionClientTests.swift, Package.swift
fix internal pinpoint tests that were broken by latest swift concurrency updates and enable them to run in CI
- ~~[ ] New or updated tests include `Given When Then` inline code documentation and are named accordingly `testThing_condition_expectation()`~~
=> chore: fix internal pinpoint tests that were broken by latest swift concurrency updates and enable them to run in CI

Amplify/Categories/API/AuthProvider/APIAuthProviderFactory.swift, AmplifyPlugins.podspec, AmplifyPlugins/API/AWSAPICategoryPlugin/Interceptor/RequestInterceptor/AuthTokenProviderWrapper.swift, AmplifyPlugins/API/AWSAPICategoryPlugin/Interceptor/SubscriptionInterceptor/AuthenticationTokenAuthInterceptor.swift, AmplifyPlugins/API/AWSAPICategoryPlugin/Interceptor/SubscriptionInterceptor/IAMAuthInterceptor.swift, AmplifyPlugins/API/AWSAPICategoryPlugin/Interceptor/SubscriptionInterceptor/OIDCAuthProviderWrapper.swift, AmplifyPlugins/API/AWSAPICategoryPluginTests/Configuration/AWSAPICategoryPluginConfigurationTests.swift, AmplifyPlugins/API/AWSAPICategoryPluginTests/Interceptor/AuthTokenURLRequestInterceptorTests.swift, AmplifyPlugins/API/Podfile, AmplifyPlugins/API/Podfile.lock, AmplifyPlugins/Core/AWSPluginsCore/Auth/Provider/AuthTokenProvider.swift, AmplifyPlugins/DataStore/Podfile.lock, Package.resolved, Package.swift
- Adds async version of protocol `AmplifyAuthTokenProvider`
- Adds async version of protocol `AuthTokenProvider`
- Depends on `AppSyncRealTimeClient` >= 3.1.0
- All changes are backward compatible and should not break existing behavior
=> feat(api): Add async protocol implementation for token request interceptors

AmplifyPlugins/API/APICategoryPlugin.xcodeproj/project.pbxproj, AmplifyPlugins/API/AWSAPICategoryPlugin/Interceptor/SubscriptionInterceptor/HeaderIAMSigningHelper.swift, AmplifyPlugins/API/AWSAPICategoryPlugin/Interceptor/SubscriptionInterceptor/IAMAuthInterceptor.swift, AmplifyPlugins/API/AWSAPICategoryPluginTests/Interceptor/SubscriptionInterceptor/IAMAuthInterceptorTests.swift, AmplifyPlugins/API/Podfile.lock
- Add Async flavor for IAMAuthInterceptor protocol
=> feat(api): Async IAM signing

AmplifyPlugins/Geo/Podfile.lock, AmplifyPlugins/Predictions/Podfile.lock, build-support/dependencies.rb
Test build were failing with iOS mismatch error. Looks like CwlCatchException increased the iOS version support, this PR pins the version so that CwlPreconditionTesting will pick the supported version.
=> test: Fix CwlPreconditionTesting to successfully build test

Amplify/Categories/Predictions/PredictionsCategory+ClientBehavior.swift, Amplify/Categories/Predictions/Request/Convert/Convert+SpeechToText+Options.swift, Amplify/Categories/Predictions/Request/Convert/Convert+SpeechToText+Request.swift, Amplify/Categories/Predictions/Request/Convert/Convert+SpeechToText+Result.swift, Amplify/Categories/Predictions/Request/Convert/Convert+SpeechToText.swift, Amplify/Categories/Predictions/Request/Convert/Convert+TextToSpeech+Options.swift, Amplify/Categories/Predictions/Request/Convert/Convert+TextToSpeech+Request.swift, Amplify/Categories/Predictions/Request/Convert/Convert+TextToSpeech+Result.swift, Amplify/Categories/Predictions/Request/Convert/Convert+TextToSpeech.swift, Amplify/Categories/Predictions/Request/Convert/Convert+TranslateText+Options.swift, Amplify/Categories/Predictions/Request/Convert/Convert+TranslateText+Request.swift, Amplify/Categories/Predictions/Request/Convert/Convert+TranslateText+Result.swift, Amplify/Categories/Predictions/Request/Convert/Convert+TranslateText.swift, Amplify/Categories/Predictions/Request/Convert/Convert.swift, Amplify/Categories/Predictions/Request/Identify/Identify+Celebrities+Result.swift, Amplify/Categories/Predictions/Request/Identify/Identify+Celebrities.swift, Amplify/Categories/Predictions/Request/Identify/Identify+Document.swift, Amplify/Categories/Predictions/Request/Identify/Identify+DocumentText+Result.swift, Amplify/Categories/Predictions/Request/Identify/Identify+Entities+Result.swift, Amplify/Categories/Predictions/Request/Identify/Identify+Entities.swift, Amplify/Categories/Predictions/Request/Identify/Identify+EntityMatches+Result.swift, Amplify/Categories/Predictions/Request/Identify/Identify+EntityMatches.swift, Amplify/Categories/Predictions/Request/Identify/Identify+Labels+Result.swift, Amplify/Categories/Predictions/Request/Identify/Identify+Labels.swift, Amplify/Categories/Predictions/Request/Identify/Identify+Text+Result.swift, Amplify/Categories/Predictions/Request/Identify/Identify+Text.swift, Amplify/Categories/Predictions/Request/Identify/Identify.swift
- adds category supporting types for requests / responses
=> feat(predictions): add category request supporting types

Amplify/Categories/Predictions/Error/PredictionsError.swift, Amplify/Categories/Predictions/PredictionsCategory.swift, Amplify/Categories/Predictions/Request/Interpret/Interpret+Result.swift
- makes `ClientError` and `ServiceError` inits public
- fixes errors thrown during configuration
=> fix(predictions): public error inits + config error handling

Amplify/Categories/Predictions/Error/PredictionsError+ClientError.swift, Amplify/Categories/Predictions/Error/PredictionsError+ServiceError.swift, AmplifyPlugins/Predictions/Tests/AWSPredictionsPluginUnitTests/ErrorMapping/PollyErrorMappingTestCase.swift, AmplifyPlugins/Predictions/Tests/AWSPredictionsPluginUnitTests/ErrorMapping/TextractErrorMappingTestCase.swift
- adds `Equatable` conformance to errors.
- add some error mapping test cases
=> fix(predictions): add equatable conformance to errors

AmplifyPlugins/Storage/Tests/StorageHostApp/StorageHostApp.xcodeproj/project.pbxproj, AmplifyPlugins/Storage/Tests/StorageHostApp/copy_configuration.sh
https://github.com/aws-amplify/amplify-swift/issues/2916
My previous pull request broke in CircleCI. This addresses the break.
~~- [ ] All unit tests pass~~
=> chore(storage): Consolidated copy configuration build phase

AmplifyPlugins/Storage/Tests/StorageHostApp/StorageHostApp.xcodeproj/project.pbxproj, AmplifyPlugins/Storage/Tests/StorageHostApp/copy_configuration.sh
https://github.com/aws-amplify/amplify-swift/issues/2916
Copying amplifyconfiguration.json to app bundle instead of xctest bundles.
~~- [ ] All unit tests pass~~
=> Copying amplifyconfiguration.json to app bundle instead of xctest bundles

AmplifyPlugins/Storage/Tests/StorageHostApp/copy_configuration.sh
https://github.com/aws-amplify/amplify-swift/issues/2916
In order to keep backend configurations separate, conditionally copying AWSAmplifyStressTests and AWSS3StoragePluginTests
~~- [ ] Build succeeds with all target using Swift Package Manager~~
~~- [ ] All unit tests pass~~
By submitting this pull request, I …
=> chore(storage): Conditionally copying AWSAmplifyStressTests and AWSS3StoragePluginTests

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/Helpers/HostedUISignInHelper.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Errors/AuthorizationError.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Errors/FetchSessionError.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/Authentication/AuthenticationState+Resolver.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Helpers/UserPoolSignInHelper.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthSignInTask.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/AWSAuthSignInPluginTests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/AuthorizationTests/AWSAuthFederationToIdentityPoolTests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/UserBehaviourTests/BasePluginTest.swift
#2864 
The changes are aimed at resolving Authorization Errors during sign in correctly. 
=> fix(Auth): Fixing throwing of AuthError when Authorization fails during signIn

AmplifyPlugins/Predictions/Tests/PredictionsHostApp/.gitignore, AmplifyPlugins/Predictions/Tests/PredictionsHostApp/AWSPredictionsPluginIntegrationTests/AWSPredictionsPluginTestBase.swift, AmplifyPlugins/Predictions/Tests/PredictionsHostApp/AWSPredictionsPluginIntegrationTests/IdentifyBasicIntegrationTests.swift, AmplifyPlugins/Predictions/Tests/PredictionsHostApp/PredictionsHostApp.xcodeproj/project.pbxproj
https://github.com/aws-amplify/amplify-swift/issues/2916
This updates the Prediction integration test harness in order to:
1. Make it compatible with `amplify pull`
2. Retain compatibility with `$HOME/.aws-amplify/amplify-ios/testconfiguration`
3. Make it compatible with running under new CICD system.
~~- [ ] Build succeeds with all target using Swift Package Manager~~
~~- [ ] All unit tests pass~~
~~- …
=> chore(predictions): Simplifying amplifyconfig.json setup

AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/Events/LivenessEvent.swift, AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/SPI/AWSPredictionsPlugin+Liveness.swift, AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/SPI/LivenessCredentials.swift, AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/Service/FaceLivenessSession.swift, AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/Service/FaceLivenessSessionRepresentable.swift, AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/Service/WebSocketSession.swift
Some service exceptions are not properly being reported through the liveness session. Instead the session is defaulting to a fallback error, which isn't very helpful.
This update allows the liveness session to report applicable service exceptions to the callsite.
=> fix: liveness service error reporting

AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/AWSDataStorePlugin+DataStoreBaseBehavior.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/AWSDataStorePlugin.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Storage/StorageEngine+SyncRequirement.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Storage/StorageEngine.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Storage/StorageEngineBehavior.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/RemoteSyncEngine.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/RemoteSyncEngineBehavior.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Core/AWSDataStorePluginTests.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Sync/SubscriptionSync/Support/MockSQLiteStorageEngineAdapter.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/TestSupport/Mocks/MockRemoteSyncEngine.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/Connection/DataStoreConnectionScenario6Tests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/DataStoreEndToEndTests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/DataStoreObserveQueryTests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/DataStoreHostApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
This is the ported fix for v1 https://github.com/aws-amplify/amplify-swift/pull/2863
In the current implementation, if the customer triggers DataStore.stop, it's possible that the local DB connection may not be closed immediately. If the customer attempts to perform another DataStore operation while this connection is still open, a second connection to the database may be initiated from a different process. This could cause conflicts with the [SQLite locking system](https://www.sqlite.org/lockingv3.html) and potentially result in a failed write operation.
This PR is to address the issue with minimal changes. Specifically, when the `DataStore.stop` API is called, only the `SyncEngine` is stopped and set to nil, while the `StorageEngine` remains active to preserve the connection to local …
=> fix(datastore): stop datastore plugin only stops syncEngine

AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/AWSS3StoragePlugin+Configure.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/AWSS3StoragePlugin.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Operation/AWSS3StorageDownloadDataOperation.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Operation/AWSS3StorageDownloadFileOperation.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Operation/AWSS3StorageRemoveOperation.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Operation/AWSS3StorageUploadDataOperation.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Operation/AWSS3StorageUploadFileOperation.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Service/Storage/AWSS3StorageService.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Service/Storage/AWSS3StorageServiceBehavior.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/DefaultStorageTransferDatabase.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/StorageMultipartUploadSession.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/StorageTransferDatabase.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/StorageTransferType.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Mocks/MockAWSS3StorageService.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Support/Internal/MockStorageTransferDatabase.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Support/Internal/StorageMultipartUploadSessionTests.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Support/Internal/StorageTransferDatabaseTests.swift
In order to conform to our style guide, this PR renames the **internal** protocol `AWSS3StorageServiceBehaviour` to `AWSS3StorageServiceBehavior`
=> chore(storage): Renamed AWSS3StorageServiceBehaviour to AWSS3StorageServiceBehavior

AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/AWSS3StoragePlugin+Configure.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/AWSS3StoragePlugin.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Service/Storage/AWSS3StorageService+DownloadBehavior.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Service/Storage/AWSS3StorageService+UploadBehavior.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Service/Storage/AWSS3StorageService.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/StorageMultipartUploadClient.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/StorageServiceProxy.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Utils/HttpClientEngineProxy.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Utils/URLRequestDelegate.swift, AmplifyPlugins/Storage/Tests/StorageHostApp/AWSS3StoragePluginIntegrationTests/AWSS3StoragePluginBasicIntegrationTests.swift, AmplifyPlugins/Storage/Tests/StorageHostApp/AWSS3StoragePluginIntegrationTests/AWSS3StoragePluginRequestRecorder.swift, AmplifyPlugins/Storage/Tests/StorageHostApp/AWSS3StoragePluginIntegrationTests/AWSS3StoragePluginTestBase.swift, AmplifyPlugins/Storage/Tests/StorageHostApp/StorageHostApp.xcodeproj/project.pbxproj, AmplifyPlugins/Storage/Tests/StorageHostApp/StorageHostApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
This PR supersedes https://github.com/aws-amplify/amplify-swift/pull/2363 - it also adds the User-Agent header to upload and download URLRequests but also includes tests to ensure the header is as expected for both corresponding URLRequests and each SDK operation.
By submitting this pull request, I confirm that my …
=> chore(storage): Added User-Agent to upload and download URLRequests

AmplifyPlugins/Core/AWSPluginsCore/ServiceConfiguration/AmplifyAWSServiceConfiguration.swift, AmplifyPlugins/Storage/Tests/StorageHostApp/AWSS3StoragePluginIntegrationTests/AWSS3StoragePluginBasicIntegrationTests.swift
Added `AmplifyAWSServiceConfiguration.frameworkMetaDataWithOS` and is used for the AWSS3StoragePlugin's `User-Agent`.
=> chore(core): Added AmplifyAWSServiceConfiguration.frameworkMetaDataWithOS

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Models/Options/AWSAuthSignInOptions.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthSignInTask.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/HubEventTests/AuthHubEventHandlerTests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/AWSAuthSignInOptionsTestCase.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/AWSAuthSignInPluginTests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/HostedUITests/AWSAuthHostedUISignInTests.swift
- https://github.com/aws-amplify/amplify-swift/issues/2595
- Deprecates `AWSAuthSignInOptions.validationData` and `AWSSignInOptions.init(validationData:metadata:authFlowType:)`.
- Changes the (now) deprecated `validationData` to a var to avoid the deprecation warning in the new `init`.
- Updates tests to not use the deprecated property / `init`.
```swift
// ✅ no warning
let signInOptions = AWSAuthSignInOptions()
// ✅ no warning
let signInOptions = AWSAuthSignInOptions(
metadata: [:]
)
// ✅ no warning
let signInOptions = AWSAuthSignInOptions(
authFlowType: nil
)
// ✅ no warning
let signInOptions = AWSAuthSignInOptions(
metadata: [:],
authFlowType: nil
)
// ⚠️ 'init(validationData:metadata:authFlowType:)' is deprecated: replaced by 'init(metadata:authFlowType:)'
let signInOptions = …
```
=> feat(auth): deprecate AWSAuthSignInOptions.validationData

.github/composite_actions/run_xcodebuild_test/action.yml, .github/workflows/integ_test_datastore.yml, .github/workflows/integ_test_datastore_v2.yml, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/Connection/DataStoreConnectionScenario2Tests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/Connection/DataStoreConnectionScenario3Tests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/DataStoreConsecutiveUpdatesTests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/DataStoreEndToEndTests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/DataStoreHubEventsTests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/TestSupport/SyncEngineIntegrationTestBase.swift
With the recent release of [Xcode v14.3](https://developer.apple.com/documentation/xcode-release-notes/xcode-14_3-release-notes), awaiting expectations requires the use of the new [fulfillment API](https://developer.apple.com/documentation/xctest/xctestcase/4109476-fulfillment). However, our current GitHub integration workflows do not provide an option to utilize this feature.
- add new option `xcode_path` to choose the expected Xcode version
- change datastore integration test workflow to use the latest runner macos-13 with the latest Xcode 14.3.
- fix some integration test cases to use the fulfillment API.
=> ci: add option in github action to use latest xcode

AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Service/Storage/AWSS3StorageService.swift, AmplifyPlugins/Storage/Tests/StorageHostApp/AWSS3StoragePluginIntegrationTests/AWSS3StoragePluginBasicIntegrationTests.swift
Ensured userAgent is built with `frameworkMetaData(includeOS: true)`
~- [ ] Security oriented best practices and standards are followed (e.g. using input sanitization, principle of least privilege, etc)~
~- [ ] New or updated tests include `Given When Then` inline code documentation and are named accordingly `testThing_condition_expectation()`~
=> chore(storage): Ensured userAgent is built with frameworkMetaData(includeOS: true)

AmplifyPlugins/Core/AWSPluginsCore/Keychain/KeychainStore.swift, AmplifyPlugins/Core/AWSPluginsCore/Keychain/KeychainStoreAttributes.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Keychain/KeychainStoreAttributesTests.swift
#2945 
Amplify V1 made a change to keychain accessibility to prevent Amplify keychain being backed up and restored on another device. Backing up and restoring Amplify keychain items is not a supported feature. The PR for the change is https://github.com/aws-amplify/aws-sdk-ios/pull/4159. 
Amplify V2 refactored the Keychain implementation and started using default queries to retrieve data from the keychain. This default query also has `kSecAttrAccessible` as a query parameter. Amplify V2 sets a default value to `AttributeAccessibleAfterFirstUnlockThisDeviceOnly` and is not customizable by the customer. 
Due to this, querying for keychain items from Amplify V1 which has `kSecAttrAccessible` set to `AWSUICKeyChainStoreAccessibilityAfterFirstUnlock` would fail, because `kSecAttrAccessible` …
=> fix(Auth): Use correct queries when getting and setting keychain items

Amplify.xcodeproj/project.pbxproj, Amplify/Categories/DataStore/Model/Collection/ArrayLiteralListProvider.swift, Amplify/Categories/DataStore/Model/Internal/ModelListProvider.swift, Amplify/Categories/DataStore/Model/Internal/ModelProvider.swift, Amplify/Categories/DataStore/Model/Internal/ModelProviderDecoder.swift, Amplify/Categories/DataStore/Model/Lazy/DefaultModelProvider.swift, Amplify/Categories/DataStore/Model/Lazy/LazyReference.swift, Amplify/Categories/DataStore/Model/PropertyPath.swift, AmplifyPlugins/API/AWSAPICategoryPlugin/Core/AppSyncListProvider.swift, AmplifyPlugins/API/AWSAPICategoryPluginTests/Core/AppSyncListDecoderTests.swift, AmplifyPlugins/API/AWSAPICategoryPluginTests/Core/AppSyncListProviderPaginationTests.swift, AmplifyPlugins/API/AWSAPICategoryPluginTests/Core/AppSyncListProviderTests.swift, AmplifyPlugins/API/Podfile.lock, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Core/DataStoreListDecoder.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Core/DataStoreListProvider.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Core/DataStoreListDecoderTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Core/DataStoreListProviderFunctionalTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Core/DataStoreListProviderTests.swift, AmplifyPlugins/DataStore/Podfile.lock, AmplifyTests/CategoryTests/DataStore/Model/ListTests.swift, Package.resolved, Podfile.lock
- Picks Lazy reference models from the PR https://github.com/aws-amplify/amplify-swift/pull/2711/, originally authored by @lawmicha 
- These changes are similar to the implementation that we have in v2 of datastore https://github.com/aws-amplify/amplify-swift/pull/2583
- Adds `@available(iOS 13.0.0, *)` for `async` functions
---
This PR introduces the LazyReference type. The post reference in the Comment type is replaced with an instance of LazyReference<Post>.
Before:
```
struct Comment: Model {
let id: String
var content: String?
var post: Post
}
```
After:
```
struct Comment: Model {
let _post: LazyReference<Post>
public let post: Post { 
get async throws {
try await _post.require()
}
}
}
```
The computed property `post` is backed by the internal `_post` of type `LazyReference`. The …
=> feat(datastore): Add Lazy reference types to Amplify core

.github/workflows/integ_test_api.yml, .github/workflows/integ_test_api_graphql_auth_directive.yml, .github/workflows/integ_test_api_graphql_iam.yml, .github/workflows/integ_test_api_graphql_user_pool.yml, .github/workflows/integ_test_api_rest_user_pool.yml, .github/workflows/integ_test_datastore.yml
Some reusable workflows for specific integration tests are disabled at the child workflow level. This prevents us from kicking them off manually through a `workflow_dispatch`. This change moves the `if ${{ false}}` checks to the parent workflow, which disables the child workflows from running on commits to `main`, but allows us to kick the off manually.
It also additionally disables the following test suites. This is a temporary change until these tests are fixed.
- graphql-lazy-load-test
- datastore-multi-auth-test
- datastore-transformer-v2-test
=> chore(test): move test disabling from child to parent workflows

AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Subscribe/DataStoreObserveQueryOperation.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/InitialSync/ModelSyncedEventEmitter.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/DataStoreObserveQueryTests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/DataStoreHostApp.xcodeproj/project.pbxproj
https://github.com/aws-amplify/amplify-swift/issues/2575
The ModelSynced snapshot is created using a buffered or periodic event. It is possible that the default buffer size is larger than the total size of the customer's observeQuery. 
In such cases, we temporarily hold the incoming MutationEvents and handle them until periodic time window is reached. If a snapshot is generated during this period, it will result in an empty array with isSynced set to true.
This PR separates the logic for handling mutation events from the logic responsible for generating periodic snapshots. With this change, the incoming mutation events will be promptly handled as soon as they are received.
=> fix(datastore): extract mutation events handling out of periodic snapshot generate logic

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/Authorization/AuthorizationState+Resolver.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthHostApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/SessionTests/SignedInAuthSessionTests.swift, AmplifyPlugins/Core/AWSPluginsCore/Keychain/KeychainStore.swift, AmplifyPlugins/Core/AWSPluginsCore/Keychain/KeychainStoreAttributes.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Keychain/KeychainStoreAttributesTests.swift
#2945 
This PR is a follow up of #2965 which was causing problems setting items in the keychain with incorrect attributes. 
=> fix(Auth): Fixing keychain migration issue

Amplify/Categories/DataStore/Model/Internal/Schema/ModelSchema+Identifiers.swift, Amplify/Categories/DataStore/Model/Lazy/LazyReference.swift, AmplifyTests/CategoryTests/DataStore/Model/LazyReferenceTests.swift
-  The decoding logic of LazyReference relied on ModelProviderRegistry.decoders to handle the decoding process.
- In case the ModelProviderRegistry.decoders failed to decode, the logic attempted to decode it into a model instance.
- However, if required fields were missing from the JSON, the decode failed and returned nil.
- Handling this scenario by returning the unloaded model state instead of nil was missing.
- Fixed this issue by adding a logic that handles not fully loaded models.
=> fix(datastore): fix sync with lazy references

AmplifyPlugins/API/Tests/APIHostApp/APIHostApp.xcodeproj/project.pbxproj, AmplifyPlugins/API/Tests/APIHostApp/APIHostApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginAuthCognitoTests/AWSDataStoreAuthBaseTest.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginAuthIAMTests/AWSDataStoreAuthBaseTest.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/PrimaryKey/AWSDataStorePrimaryKeyBaseTest.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginFlutterTests/TestSupport/SyncEngineFlutterIntegrationTestBase.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/DataStoreHubEventsTests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/TestSupport/HubEventsIntegrationTestBase.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/TestSupport/SyncEngineIntegrationTestBase.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/TestSupport/SyncEngineIntegrationV2TestBase.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginLazyLoadTests/LazyLoadBase/AWSDataStoreLazyLoadBaseTest.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginLazyLoadTests/LazyLoadBase/TestConfigHelper.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginMultiAuthTests/AWSDataStoreAuthBaseTest.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginV2Tests/TestSupport/SyncEngineIntegrationV2TestBase.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/DataStoreHostApp.xcodeproj/project.pbxproj, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/DataStoreHostApp/AmplifyURLSession.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/DataStoreHostApp/AmplifyURLSessionFactory.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/DataStoreStressTests/DataStoreStressBaseTest.swift
When performing `Amplify.reset`, th `URLSession` of the API plugin is also invalidated and reset. This means that any ongoing operations that utilize this `URLSession` to create new URL tasks may encounter an exception with the message `"Terminating app due to uncaught exception 'NSGenericException', reason: 'Task created in a session that has been invalidated'"` Unfortunately, `URLSession` does not provide a method to check if the current session has been invalidated.
- create a new class called `AmplifyURLSession` that acts as a wrapper for `URLSession` and also conforms to the `URLSessionBehavior` protocol.
- in the `AmplifyURLSession` class, include a variable that tracks the state of the `URLSession`.
- when attempting to generate a dataTask, check the state of the `URLSession` in …
=> fix(api): wrap URLSession with validation state

AmplifyPlugins/API/Tests/APIHostApp/APIHostApp.xcodeproj/project.pbxproj, AmplifyPlugins/API/Tests/APIHostApp/APIHostApp/SubscriptionView.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginAuthIAMTests/TestConfigHelper.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/Base/TestConfigHelper.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginMultiAuthTests/TestConfigHelper.swift
https://github.com/aws-amplify/amplify-swift/pull/2979
After importing `DataStoreHostApp`, there are redundant declarations of extesnsion for String to confirm `Error` protocol. The build target is also downgrade to iOS13 with adding `availablility` check for `StateObject`.
=> fix(datastore): fix failed test cases for PR#2979

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/SRPAuth/InitiateAuthSRP.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/SRPAuth/VerifyPasswordSRP.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Events/SignInEvent.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/SRP/SRPSignInState+Resolver.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Utils/RespondToAuthChallengeInput+Amplify.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ActionTests/InitiateAuthSRP/InitiateAuthSRPTests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ActionTests/InitiateAuthSRP/VerifyPasswordSRPTests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ResolverTests/SRPSignInState/SRPTestData.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ResolverTests/SignUpState/RespondToAuthInputTests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/AWSAuthSignInPluginTests.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthHostApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
#2983 
Adding the missing implementation of passing client metadata for RespondToAuthChallenge cases with Cognito. 
=> fix(Auth): Pass client metadata to password verifier during SRP sign in

.circleci/config.yml
The final step of publishing a new unstable version in the unstable release CircleCI job failed due to the absence of OIDC context necessary for retrieving the CocoaPod Trunk Token.
- add OIDC context for unstable release lane.
=> ci(v1): add oidc context to unstable release lane

fastlane/Fastfile
related issue: https://github.com/aws-amplify/amplify-swift/pull/2990
This PR moves the procedure the process of retrieving the CocoaPods trunk token from AWS SecretManager to the fastlane `release_pods` function, allowing it to be used for both `unstable` and `stable` releases.
=> ci(v1): read CocoaPods token before publishing

.github/workflows/integ_test_datastore_v2.yml, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/DataStoreEndToEndTests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/TestSupport/SyncEngineIntegrationTestBase.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginV2Tests/TestSupport/SyncEngineIntegrationV2TestBase.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginV2Tests/TransformerV2/DataStoreConnectionOptionalAssociations.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginV2Tests/TransformerV2/DataStoreConnectionScenario1V2Tests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginV2Tests/TransformerV2/DataStoreConnectionScenario2V2Tests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginV2Tests/TransformerV2/DataStoreConnectionScenario3V2Tests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginV2Tests/TransformerV2/DataStoreConnectionScenario3aV2Tests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginV2Tests/TransformerV2/DataStoreConnectionScenario4V2Tests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginV2Tests/TransformerV2/DataStoreConnectionScenario5V2Tests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginV2Tests/TransformerV2/DataStoreConnectionScenario6V2Tests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginV2Tests/TransformerV2/DataStoreConnectionScenario7V2Tests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginV2Tests/TransformerV2/DataStoreConnectionScenario8V2Tests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/DataStoreHostApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
The concurrent test executions occtionally failed due to the mismatch of the registered model schemas.
- changed all async test cases to use new concurrency-safe API [`fulfillment`](https://developer.apple.com/documentation/xctest/xctestcase/4109476-fulfillment).
=> test(datastore): fix integration test errors for AWSDataStorePluginV2Tests

.swiftpm/xcode/xcshareddata/xcschemes/AWSAPIPlugin.xcscheme, .swiftpm/xcode/xcshareddata/xcschemes/AWSCognitoAuthPlugin.xcscheme, .swiftpm/xcode/xcshareddata/xcschemes/AWSDataStorePlugin.xcscheme, .swiftpm/xcode/xcshareddata/xcschemes/AWSPinpointAnalyticsPlugin.xcscheme, .swiftpm/xcode/xcshareddata/xcschemes/AWSPinpointPushNotificationsPlugin.xcscheme, .swiftpm/xcode/xcshareddata/xcschemes/AWSPluginsCore.xcscheme, .swiftpm/xcode/xcshareddata/xcschemes/AWSPredictionsPlugin.xcscheme, .swiftpm/xcode/xcshareddata/xcschemes/AWSS3StoragePlugin.xcscheme, .swiftpm/xcode/xcshareddata/xcschemes/Amplify-Package.xcscheme, .swiftpm/xcode/xcshareddata/xcschemes/Amplify.xcscheme, .swiftpm/xcode/xcshareddata/xcschemes/CoreMLPredictionsPlugin.xcscheme, AmplifyPlugins/Predictions/Tests/CoreMLPredictionsPluginUnitTests/DependencyTests/CoreMLVisionAdapterTests.swift
Adds test coverage reporting (in Xcode) for each target.
=> chore(test): target specific coverage reporting

AmplifyPlugins/Predictions/AWSPredictionsPlugin/AWSPredictionsPlugin.swift, AmplifyPlugins/Predictions/Tests/AWSPredictionsPluginUnitTests/PredictionsPluginInit.swift
https://github.com/aws-amplify/amplify-swift/issues/3009
`AWSPredictionsPlugin` init was made internal to prevent configuring it in v2 for the time period that the target was added (for liveness support) and predictions v2 was released. The plugin initializer needs to be public now.
=> fix(predictions): plugin public init

.github/workflows/integ_test_datastore_cpk.yml, AmplifyPlugins/Core/AWSPluginsCore/Model/Decorator/ModelIdDecorator.swift, AmplifyPlugins/Core/AWSPluginsCore/Model/GraphQLDocument/SingleDirectiveGraphQLDocument.swift, AmplifyPlugins/Core/AWSPluginsCore/Model/Support/GraphQLDocumentInputValue.swift, AmplifyPlugins/Core/AWSPluginsCore/Model/Support/GraphQLDocumentnputValue.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/GraphQLRequest/GraphQLRequestSyncCustomPrimaryKeyTests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/PrimaryKey/11/AWSDataStoreIntSortKeyTest.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/PrimaryKey/11/Post11+Schema.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/PrimaryKey/11/Post11.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/PrimaryKey/12/AWSDataStoreFloatSortKeyTest.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/PrimaryKey/12/Post12+Schema.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/PrimaryKey/12/Post12.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/PrimaryKey/9/AWSDataStoreCompositeSortKeyIdentifierTest.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/PrimaryKey/9/Comment9+Schema.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/PrimaryKey/9/Comment9.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/PrimaryKey/9/Post9+Schema.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/PrimaryKey/9/Post9.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/PrimaryKey/AWSDataStorePrimaryKeyBaseTest.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/PrimaryKey/primarykey_schema.graphql, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/TestSupport/SyncEngineIntegrationTestBase.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/DataStoreHostApp.xcodeproj/project.pbxproj
Currently, the Composite Primary Key feature assumes that the sortKey in GraphQL must be of type `String`, and it generates queries based on this assumption. However, this is inaccurate and will result in a GraphQL type mismatch error if the sortKey is actually other types, for instance `ID`.
- add support for CPK to use inline value for get queries.
=> fix(datastore): support CPK with sortKey for GraphQL scalar types

AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/PrimaryKey/11/AWSDataStoreIntSortKeyTest.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/PrimaryKey/12/AWSDataStoreFloatSortKeyTest.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/PrimaryKey/13/AWSDataStoreDateTimeSortKeyTest.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/PrimaryKey/14/AWSDataStoreDateSortKeyTest.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/PrimaryKey/15/AWSDataStoreTimeSortKeyTest.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/PrimaryKey/16/AWSDataStoreAWSURLSortKeyTest.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/PrimaryKey/16/Post16+Schema.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/PrimaryKey/16/Post16.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/PrimaryKey/17/AWSDataStoreAWSEmailSortKeyTest.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/PrimaryKey/17/Post17+Schema.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/PrimaryKey/17/Post17.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/PrimaryKey/18/AWSDataStoreAWSPhoneSortKeyTest.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/PrimaryKey/18/Post18+Schema.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/PrimaryKey/18/Post18.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/PrimaryKey/19/AWSDataStoreAWSIPAddressSortKeyTest.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/PrimaryKey/19/Post19+Schema.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/PrimaryKey/19/Post19.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/PrimaryKey/20/AWSDataStoreAWSTimestampSortKeyTest.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/PrimaryKey/20/Post20+Schema.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/PrimaryKey/20/Post20.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/PrimaryKey/AWSDataStoreSortKeyBaseTest.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginCPKTests/PrimaryKey/primarykey_schema.graphql, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/DataStoreHostApp.xcodeproj/project.pbxproj
- add integration test cases for other AWS scalar types
- AWSPhone
- AWSURL
- AWSEmail
- AWSIPAddress
- AWSTimestamp
=> test(datastore): add integ test cases for other aws scalar types as CPK sort key

AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginLazyLoadTests/LL1/AWSDataStoreLazyLoadPostComment4V2Tests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginLazyLoadTests/LL10/AWSDataStoreLazyLoadPostComment7Tests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginLazyLoadTests/LL11/AWSDataStoreLazyLoadPostComment8Tests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginLazyLoadTests/LL12/CompositePK/AWSDataStoreLazyLoadCompositePKChildSansTests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginLazyLoadTests/LL12/CompositePK/AWSDataStoreLazyLoadCompositePKChildTests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginLazyLoadTests/LL12/CompositePK/AWSDataStoreLazyLoadCompositePKImplicitTests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginLazyLoadTests/LL12/CompositePK/AWSDataStoreLazyLoadCompositePKStrangeExplicitTests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginLazyLoadTests/LL12/CompositePK/AWSDataStoreLazyLoadCompositePKTests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginLazyLoadTests/LL12/DefaultPK/AWSDataStoreLazyLoadDefaultPKTests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginLazyLoadTests/LL12/HasOneParentChild/AWSDataStoreLazyLoadHasOneTests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginLazyLoadTests/LL13/AWSDataStoreLazyLoadPhoneCallTests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginLazyLoadTests/LL14/AWSDataStoreLazyLoadUserPostCommentTests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginLazyLoadTests/LL2/AWSDataStoreLazyLoadBlogPostComment8V2Tests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginLazyLoadTests/LL3/AWSDataStoreLazyLoadPostCommentWithCompositeKeyTests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginLazyLoadTests/LL4/AWSDataStoreLazyLoadPostTagTests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginLazyLoadTests/LL5/AWSDataStoreLazyLoadProjectTeam1Tests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginLazyLoadTests/LL6/AWSDataStoreLazyLoadProjectTeam2Tests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginLazyLoadTests/LL7/AWSDataStoreLazyLoadPostComment4Tests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginLazyLoadTests/LL8/AWSDataStoreLazyLoadProjectTeam5Tests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginLazyLoadTests/LL9/AWSDataStoreLazyLoadProjectTeam6Tests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginLazyLoadTests/LazyLoadBase/AWSDataStoreLazyLoadBaseTest.swift
- change test helper method to use both `mutationType` and `version` to filter incoming mutationEvent from remote server
=> test(datastore): fix lazy load integration test helper method

.circleci/config.yml
Building for tvOS/watchOS requires Xcode 14.3, so this PR updates the CircleCI settings to support that:
- Setting the resource class to `macos.x86.medium.gen2` for all builds. The default `medium` one is now [deprecated](https://discuss.circleci.com/t/macos-resource-deprecation-update/46891) and does not support Xcode 14.3
- I originally only did this for the macOS/tvOS builds, but considering that CircleCI will change the default to that one in October, I figured it was best to be proactive.
- The `xcode-version` parameter in the `unit-test` job was actually being ignored 😅. So fixing that.
- Setting `xcode-version: 14.3.0` argument for tvOS/watchOS unit tests.
=> chore: Updating CircleCI settings

.circleci/config.yml, Amplify/Categories/DataStore/Model/Internal/Model+Codable.swift, Amplify/Categories/DataStore/Model/Internal/Schema/ModelValueConverter.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/CredentialStore/CredentialStoreOperationClientTests.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Models/SQLModelValueConverterTests.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Sync/MutationQueue/MutationIngesterConflictResolutionTests.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Sync/MutationQueue/OutgoingMutationQueueNetworkTests.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/TestSupport/Mocks/MockRequestRetryablePolicy.swift, AmplifyPlugins/Internal/Tests/InternalAWSPinpointUnitTests/PinpointRequestsRegistryTests.swift, AmplifyPlugins/Predictions/Tests/AWSPredictionsPluginUnitTests/EventStreamCodingTests/EventStreamCoderTestCase.swift, AmplifyTests/CategoryTests/API/APICategoryClientRESTTests.swift, AmplifyTests/CategoryTests/DataStore/Model/LazyReferenceTests.swift, AmplifyTests/CoreTests/AnyEncodableTests.swift, AmplifyTests/CoreTests/Model+CodableTests.swift
- All remaining unit test suites now run on Xcode 14.3. This is necessary due to required change from `waitForExpectations(_:)` to `fulfillment(of:timeout:enforceOrder:)`.
- `toJSON` methods now set `outputFormatting = .sortedKeys` on `JSONEncoder` except when the encoder is supplied by the callsite and has multiple references. 
- Miscellaneous changes to tests.
=> fix: encoded key ordering

.github/workflows/integ_test_storage.yml, AmplifyPlugins/API/Tests/AWSAPIPluginTests/Operation/GraphQLMutateCombineTests.swift, AmplifyPlugins/Predictions/Tests/PredictionsHostApp/PredictionsHostApp.xcodeproj/xcshareddata/xcschemes/AWSPredictionsPluginIntegrationTests.xcscheme, AmplifyPlugins/Predictions/Tests/PredictionsHostApp/PredictionsHostApp.xcodeproj/xcshareddata/xcschemes/PredictionsWatchApp.xcscheme, AmplifyPlugins/Storage/Tests/StorageHostApp/AWSS3StoragePluginIntegrationTests/AWSS3StoragePluginOptionsUsabilityTests.swift
Makes a few necessary changes to tests.
- Disables test parallelization in Predictions integration tests.
- Increases timeout for `GraphQLMutateCombineTests.testMutateFails` due to watchOS timeouts.
- Asserts on 4xx for expired presigned URL instead of 403.
=> test: timeouts, parallelization, and 4xx assertion

Amplify/Categories/Auth/AuthCategory+ClientBehavior.swift, Amplify/Categories/Auth/AuthCategoryBehavior.swift, Amplify/Categories/Auth/Models/AuthSignInStep.swift, Amplify/Categories/Auth/Models/MFAType.swift, Amplify/Categories/Auth/Models/TOTPSetupDetails.swift, Amplify/Categories/Auth/Request/SetUpTOTPRequest.swift, Amplify/Categories/Auth/Request/VerifyTOTPSetupRequest.swift
Adding TOTP support in Amplify Auth Category
* Adding public API's
* Adding changes to the Auth next steps
* Adding other models updates and additions
_NOTE: The unit and integration tests will fail until all changes make it to the feature branch_
(The PR is directed towards a feature branch)
=> feat(Auth): Adding TOTP support in Amplify Auth category

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/SoftwareTokenSetup/CompleteTOTPSetup.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/SoftwareTokenSetup/InitializeTOTPSetup.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/SoftwareTokenSetup/SetUpTOTP.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/SoftwareTokenSetup/VerifyTOTPSetup.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Request/FetchMFAPreferenceRequest.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Request/UpdateMFAPreferenceRequest.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Constants/AuthPluginErrorConstants.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Helpers/UserPoolSignInHelper.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthConfirmSignInTask.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/SetUpTOTPTask.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/VerifyTOTPSetupTask.swift
Depends on: 
* #3040 
* #3041 
* #3042
* #3043 
Changes
* Adds implementation of actions needed by the State Machine
* Update UserPoolSignIn Helper to add details about TOTP
_NOTE: The unit and integration tests will fail until all changes make it to the feature branch_
(The PR is directed towards a feature branch)
=> feat(Auth): Adding TOTP state machine actions

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/DeviceSRPAuth/InitiateAuthDeviceSRP.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Data/ConfirmSignInEventData.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Data/RespondToAuthChallenge.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Data/SignInTOTPSetupData.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Events/SetUpTOTPEvent.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Events/SignInEvent.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/States/DebugInfo/SignInState+Debug.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/States/DebugInfo/SignInTOTPSetupState+Debug.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/States/SignInState.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/States/SignInTOTPSetupState.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/ErrorMapping/SignInError+Helper.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/SignIn/SignInState+Resolver.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/Resolvers/TOTPSetup/SignInTOTPSetupState+Resolver.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Helpers/UserPoolSignInHelper.swift
Depends on: 
* #3040 
* #3041 
* #3042
* #3043 
* #3044 
Changes
* Add new states, event for TOTP
* Add the implementation of resolvers
* Add all the data models related to the new states and events
_NOTE: The unit and integration tests will fail until all changes make it to the feature branch_
(The PR is directed towards a feature branch)
=> feat(Auth): Adding TOTP states, events, data models and resolvers

AmplifyPlugins/Auth/Tests/AuthHostApp/AuthHostApp.xcodeproj/project.pbxproj, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthHostApp.xcodeproj/xcshareddata/xcschemes/AuthIntegrationTests.xcscheme, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthHostApp.xcodeproj/xcshareddata/xcschemes/AuthIntegrationTestsWatch.xcscheme, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthHostApp.xcodeproj/xcshareddata/xcschemes/AuthWatchApp.xcscheme, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/SignInTests/AuthCustomSignInTests.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/SignInTests/AuthSRPSignInTests.swift
Enabled TOTP tests on watchOS and tvOS.
=> feat(Auth): Enable tests for watchOS and tvOS

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/DeviceSRPAuth/InitiateAuthDeviceSRP.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/SoftwareTokenSetup/CompleteTOTPSetup.swift
Removed the TODO's pending for TOTP. 
* Validated that deviceNotFound use case is not valid when setting up TOTP during sign in.
=> feat(Auth): Removed deviceNotFound TODO which is not applicable for TOTP

Amplify/Categories/Auth/AuthCategoryBehavior.swift, Amplify/Categories/Auth/Models/AuthSession.swift, Amplify/Core/Support/TaskQueue.swift, AmplifyPlugins/Core/AWSPluginsCore/Auth/AWSAuthSessionBehavior.swift, AmplifyPlugins/Core/AWSPluginsCore/Auth/Provider/AuthAWSCredentialsProvider.swift, AmplifyPlugins/Core/AWSPluginsCore/Auth/Provider/AuthCognitoIdentityProvider.swift, AmplifyTests/CoreTests/AmplifyTaskQueueTests.swift
* feat(auth): Add definitions for supporting OIDC plugin
* chore: OIDC support API docs
* feat: Add default reset method for Plugins
* test: Add TaskQueue sync test; chore: Document TaskQueue
* feat: Add default conformance to AuthAWSCredentialsProvider.getAWSCredentials()
* feat: Add default conformance for AuthCognitoIdentityProvider methods
---------
None 
This is a merge PR for #3064 to `main`. It adds new API definitions for supporting OIDC plugins. All the PRs have been previously approved.
=> feat(auth): Add OIDC support types & docs (#3064)

Amplify/Categories/Logging/Internal/LoggingCategory+CategoryConfigurable.swift, Amplify/Categories/Logging/LoggingCategory+HubPayloadEventName.swift, Amplify/DefaultPlugins/AWSUnifiedLoggingPlugin/AWSUnifiedLoggingPlugin.swift, Amplify/DefaultPlugins/AWSUnifiedLoggingPlugin/Internal/ConsoleLoggingConfiguration.swift, AmplifyPlugins/Logging/Sources/AWSCloudWatchLoggingPlugin/AWSCloudWatchLoggingSessionController.swift, AmplifyPlugins/Logging/Sources/AWSCloudWatchLoggingPlugin/Persistence/LogFile.swift, AmplifyPlugins/Logging/Sources/AWSCloudWatchLoggingPlugin/Producer/RotatingLogger.swift, AmplifyPlugins/Logging/Tests/AWSCloudWatchLoggingPluginTests/AWSCloudWatchLoggingSessionControllerTests.swift, AmplifyPlugins/Logging/Tests/AWSCloudWatchLoggingPluginTests/LogFileTests.swift
Fix the following logger issue:
* fix issue with disabling the console logger via json configuration file
* add Logging Hub events to handle cases where logging fails to write or flush log events
* remove check that prevents persisting of log messages larger than the log file size and allow logs to persist.
=> fix(logging): handle write and flush errors

AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/AWSS3StoragePlugin+AsyncClientBehavior.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Configuration/AWSS3PluginOptions.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Dependency/AWSS3PreSignedURLBuilderAdapter.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Dependency/AWSS3PreSignedURLBuilderBehavior.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Dependency/S3ClientConfigurationProxy.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Operation/AWSS3StorageDownloadDataOperation.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Operation/AWSS3StorageDownloadFileOperation.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Operation/AWSS3StorageUploadDataOperation.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Operation/AWSS3StorageUploadFileOperation.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Service/Storage/AWSS3StorageService+DownloadBehavior.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Service/Storage/AWSS3StorageService+GetPreSignedURLBehavior.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Service/Storage/AWSS3StorageService+MultiPartUploadBehavior.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Service/Storage/AWSS3StorageService+UploadBehavior.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Service/Storage/AWSS3StorageServiceBehavior.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/StorageMultipartUploadClient.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/AWSS3StoragePluginGetPresignedUrlTests.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Configuration/S3ClientConfigurationProxyTests.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Mocks/MockAWSS3PreSignedURLBuilder.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Mocks/MockAWSS3StorageService.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Service/Storage/AWSS3StorageServiceGetPreSignedURLBehaviorTests.swift, AmplifyPlugins/Storage/Tests/StorageHostApp/AWSS3StoragePluginIntegrationTests/AWSS3StoragePluginAccelerateIntegrationTests.swift, AmplifyPlugins/Storage/Tests/StorageHostApp/StorageHostApp.xcodeproj/project.pbxproj, Package.resolved
Originally opened by @jcjimenez in #2631 ... Taking up the work from there to finish it. 
https://github.com/aws-amplify/amplify-swift/issues/2591
https://github.com/aws-amplify/amplify-swift/issues/1542
This change makes it possible to leverage the existing AWS SDK S3 configuration in the same way [that it is done for Javascript/React](https://docs.amplify.aws/lib/storage/transfer-acceleration/q/platform/js/). #featureparity
1. Ensure the S3 bucket used by Amplify has **Transfer Acceleration** _disabled_.
2. Ensure all integration tests pass.
3. Enable transfer acceleration locally by updating the tests under `AWSS3StoragePluginAccelerateIntegrationTests` setting `useAccelerateEndpoint` to  **true**.
4. Run the integration tests. They should all **fail**.
5. Enable **Transfer …
=> feat(storage) Parity: AWS SDK S3 accelerate via useAccelerateEndpoint pluginOptions.

AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/AWSS3StoragePlugin+AsyncClientBehavior.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Configuration/AWSS3PluginOptions.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Dependency/AWSS3PreSignedURLBuilderAdapter.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Dependency/AWSS3PreSignedURLBuilderBehavior.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Dependency/S3ClientConfigurationProxy.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Operation/AWSS3StorageDownloadDataOperation.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Operation/AWSS3StorageDownloadFileOperation.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Operation/AWSS3StorageUploadDataOperation.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Operation/AWSS3StorageUploadFileOperation.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Service/Storage/AWSS3StorageService+DownloadBehavior.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Service/Storage/AWSS3StorageService+GetPreSignedURLBehavior.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Service/Storage/AWSS3StorageService+MultiPartUploadBehavior.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Service/Storage/AWSS3StorageService+UploadBehavior.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Service/Storage/AWSS3StorageServiceBehavior.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/StorageMultipartUploadClient.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/AWSS3StoragePluginGetPresignedUrlTests.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Configuration/S3ClientConfigurationProxyTests.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Mocks/MockAWSS3PreSignedURLBuilder.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Mocks/MockAWSS3StorageService.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Service/Storage/AWSS3StorageServiceGetPreSignedURLBehaviorTests.swift, AmplifyPlugins/Storage/Tests/StorageHostApp/AWSS3StoragePluginIntegrationTests/AWSS3StoragePluginAccelerateIntegrationTests.swift, AmplifyPlugins/Storage/Tests/StorageHostApp/StorageHostApp.xcodeproj/project.pbxproj, Package.resolved
Original PR that was reverted. https://github.com/aws-amplify/amplify-swift/pull/3087
=> feat(storage) Parity: AWS SDK S3 accelerate via useAccelerateEndpoint pluginOptions

AmplifyPlugins/Logging/Sources/AWSCloudWatchLoggingPlugin/AWSCloudWatchLoggingSessionController.swift, AmplifyPlugins/Logging/Sources/AWSCloudWatchLoggingPlugin/Persistence/LogActor.swift, AmplifyPlugins/Logging/Sources/AWSCloudWatchLoggingPlugin/Producer/RotatingLogger.swift, AmplifyPlugins/Logging/Tests/AWSCloudWatchLoggingPluginTests/AWSCloudWatchLoggingSessionControllerTests.swift, AmplifyPlugins/Logging/Tests/AWSCloudWatchLoggingPluginTests/LogActorTests.swift, AmplifyPlugins/Logging/Tests/AWSCloudWatchLoggingPluginTests/LogRotationTests.swift
Update logger so that existing logs are deleted the user identifier changes due to sign in or sign out
=> fix(logging): delete logs when user identifier changes

.github/workflows/deploy_package.yml, .github/workflows/integ_test.yml
This PR makes the following changes to the deploy workflow:
- adds the `secrets: inherit` attribute when calling the fortify workflow, so that it can access the environment's secrets
- removes the integration tests as dependency, to match `main` (since one of the test keeps hanging and blocking the release).
=> chore: [v1] Fixing release workflow

.github/workflows/deploy_package.yml, .github/workflows/integ_test.yml
This PR removes the integration tests workflow from being a dependency of the release workflow and returns to it just being triggered on a push to main (as it was before the migration).
For some reason, one of the tests keeps hanging (not failing), which makes it impossible to continue with the release.
=> chore: Removing integ tests from release workflow

AmplifyPlugins/Logging/Sources/AWSCloudWatchLoggingPlugin/AWSCloudWatchLoggingSessionController.swift, AmplifyPlugins/Logging/Sources/AWSCloudWatchLoggingPlugin/Persistence/LogActor.swift, AmplifyPlugins/Logging/Sources/AWSCloudWatchLoggingPlugin/Producer/RotatingLogger.swift, AmplifyPlugins/Logging/Tests/AWSCloudWatchLoggingPluginTests/LogActorTests.swift, AmplifyPlugins/Logging/Tests/AWSCloudWatchLoggingPluginTests/RotatingLoggerTests.swift
update logging flushlog call to be async and blocking end to end.
=> fix(logging): update flushlog to be blocking end to end

.github/workflows/deploy_package.yml
Unquoting the retrieved token on the release workflow, as it caused the checkout to fail.
=> chore: Fixing wrong parsing in release workflow

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/RefreshAuthorizationSession/UserPool/RefreshHostedUITokens.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/SignIn/HostedUI/FetchHostedUISignInToken.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Models/AWSCognitoUserPoolTokens.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/Mocks/MockData/AWSCognitoUserPoolTokens+Mock.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/HostedUITests/AWSAuthHostedUISignInTests.swift
#3107 
Using the min expiration time of the idToken and accessToken to detemine Authentication result expiry in the abscence of expiry details from the service. 
=> fix(Auth): Refactor the expires in logic of the authentication result

.github/workflows/integ_test_push_notifications.yml
This PR fixes the hanging/failing tvOS and watchOS Push Notifications integration tests.
We were using `OS=latest` and `xcode_path: '/Applications/Xcode_14.3.app'`, which resulted in the tests being run in the beta `tvOS 17.0` and `watchOS 10.0`, as it seems they are installed in the runners now.
By setting them to `16.4` and `9.4`, they now behave properly.
I am also setting a `timeout` for these tests, so that in case they hang again we don't have to wait forever to retry.
=> chore: Fixing Integration Test for Push Notifications

.github/workflows/run_xcodebuild_test_platforms.yml
Fixing typo in codecov flags, which had an extra `$` and caused the report to not be uploaded. 
Also adding names to tests job in order to differentiate them when they run as part of the release workflows.
=> chore: Fixing typo in codecov flags. 

.github/workflows/build_amplify_swift.yml, .github/workflows/fortify_scan.yml, .github/workflows/integ_test.yml, .github/workflows/unit_test.yml
- canceling pervious running workflows by grouping in PR number or branch name.
- remove push trigger in `build` workflow as the unit test workflow will trigger it.
=> ci: cancel previous running workflow with same PR or branch name

AmplifyTools/AmplifyXcode/Package.resolved, AmplifyTools/AmplifyXcode/Package.swift
- https://github.com/aws-amplify/amplify-cli/issues/12998
Updates dependency versioning rules for XcodeProj to [include support for `com.apple.product-type.extensionkit-extension` extension product types](https://github.com/tuist/XcodeProj/blob/main/Sources/XcodeProj/Objects/Targets/PBXProductType.swift#L15) added in [8.8.0](https://github.com/tuist/XcodeProj/releases/tag/8.8.0).
After this is merged to `main`, we'll cut a PR to https://github.com/aws-amplify/amplify-cli with a prebuilt binary to include in their next available release.
---
For anyone tracking this, I recommend waiting until the new version lands in Amplify CLI. However, if you need an immediate workaround:
```bash
AMP_XCODE_DIR=~/.amplify/lib/aws-amplify-amplify-frontend-ios/resources
mv $AMP_XCODE_PATH/amplify-xcode …
```
=> fix: update dep versions for xcodeproj and xcodegen

.github/workflows/build_amplify_swift.yml, .github/workflows/fortify_scan.yml, .github/workflows/integ_test.yml, .github/workflows/integ_test_api.yml, .github/workflows/unit_test.yml
- don't cancel the workflows on main branch
=> ci: ignore deduplicate workflow for unstable release on main branch

AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Operation/AWSS3StorageDownloadFileOperationTests.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Operation/AWSS3StorageGetDataOperationTests.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Operation/AWSS3StorageOperationTestBase.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Operation/AWSS3StoragePutDataOperationTests.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Operation/AWSS3StorageRemoveOperationTests.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Operation/AWSS3StorageUploadFileOperationTests.swift
#2442 
* remove Thread.sleep in Storage operation unit tests and revert back to `XCTAssertTrue(operation.isFinished)`
* Ran unit tests at 100 iterations repeated on iOS and macOS without any failures
=> chore: remove Thread.sleep in storage operation unit tests

.github/composite_actions/run_xcodebuild_test/action.yml, .github/workflows/run_xcodebuild_test_platforms.yml, .github/workflows/unit_test.yml, .github/workflows/upload_coverage_report.yml
While the bash script is more reliable when uploading, Codecov seems to have a pretty tight "timeout" when it comes to considering a workflow "stale", which starts when the first report is received for the same workflow.
To prevent this, instead of having each scheme report their coverage as soon as the tests are done running, I'm instead caching them and bulk reporting all once the unit test succeeded. This also enables us to re-run any failed unit test job without worrying it would take too long.
=> chore: Submitting all coverage reports at the same time

.github/workflows/canary.yml
Updates min. and max. Xcode versions for running canary test workflow.
=> chore: update xcode version for canary test

.github/workflows/canary.yml
- update os runner version for xcode 14.3.1
- according to [runner description](https://github.com/actions/runner-images/blob/macOS-12/20230812.3/images/macos/macos-13-Readme.md), only macos-13 has support for xcode 14.3.1. 
=> ci: update os runner version for xcode 14.3.1

.github/workflows/deploy_package.yml, .github/workflows/fortify_scan.yml, .github/workflows/integ_test.yml, .github/workflows/unit_test.yml
The same as issue https://github.com/aws-amplify/aws-sdk-ios/pull/4915, currency workflow with group name format `<github.workflow>-<PRNumber or branchName>` will have the same group name when triggered by `workflow_call` event. Adding the input field `identifier` to specify the workflow name.
=> ci: add required identifier fiedl for workflow_call

.github/composite_actions/run_xcodebuild/action.yml, .github/composite_actions/run_xcodebuild_test/action.yml, .github/workflows/build_amplify_swift.yml, .github/workflows/deploy_package.yml, .github/workflows/run_xcodebuild_test_platforms.yml, .github/workflows/unit_test.yml, .github/workflows/upload_coverage_report.yml
This PR makes several changes in our workflows in order to:
- Cache the Amplify package's dependencies, so we save some time when building/testing
- Add new inputs to both `run_xcodebuild` and `run_xcodebuild_test` actions to support the new behaviour
- GitHub stores caches per branch. A workflow will first look the cache in its branch and if not found will look in `main`, so we're only explicitly saving the cache when running in `main`,  otherwise we'll have many caches as we have many branches for dev.
- Immediately retry a failing test run. This is probably not the _correct™_ thing to do to deal with our flaky tests, but it is what it is until we actually fix them/upgrade the runners. It's also significantly faster because we already have everything we need and don't have to build …
=> chore: Caching dependencies when building and testing

.github/workflows/build_amplify_swift.yml
We only want to save the dependencies to the cache when building in `main`. This was done for iOS, but not for the other platforms.
=> chore: Only cache dependencies on main

AmplifyPlugins/Core/AWSPluginsCore/Keychain/KeychainStore.swift, AmplifyPlugins/Core/AWSPluginsCore/Keychain/KeychainStoreAttributes.swift
Update keychain setter to delete and add new values instead of update an existing key/value when on macOS.
=> fix(core): update keychain setter for macOS

.github/workflows/nightly_repeated_unittest.yml, .github/workflows/run_xcodebuild_test_platforms.yml
This job was always failing because it's using an unsupported Xcode version. 
Now it still fails, but because some of the test do eventually fail after running them 100 times :P
Additional changes:
- Adding the missing schemes
- I'm now using `run_xcodebuild_test_platforms` to take advantage of its awesome caching features, but had to tweak it a little bit to disable automatic retrying and to accept custom input flags as well.
=> chore: Fixing the nightly unit tests workflow

.github/workflows/run_xcodebuild_test_platforms.yml
As `inputs.retry_on_error` is a `boolean`, comparing its value with the string `'true'` always returns `false` 🤦‍♂️ .
Fixing that.
=> chore: Fixing retry step when running the tests workflow

Amplify/Categories/Auth/Result/AuthSignUpResult.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Service/Helpers/SignUpOutputResponse+Helper.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthConfirmSignUpTask.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/ClientBehaviorTests/SignUp/AWSAuthConfirmSignUpTaskTests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/ClientBehaviorTests/SignUp/AWSAuthSignUpAPITests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/ClientBehaviorTests/SignUp/AWSAuthSignUpTaskTests.swift
Adds a `userID` property to `AuthSignUpResult`. 
Currently, this property is accessible when the `AuthSignUpResult().nextStep` is `AuthSignUpStep.confirmUser` through the case's associated values. 
The typical flow is `signUp() --> .confirmUser --> confirmSignUp() --> .done`.  
`confirmSignUp` ([ConfirmSignUp](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_ConfirmSignUp.html)) doesn't return a `userID` (`UserSub`). However, `signUp() --> .done` is also a valid flow with the use of a custom verification flow. In this case, we receive the `userID` but we're preventing the caller from accessing it. This change provides the `userID` in the `AuthSignUpResult` if it's returned by the service, regardless of the `nextStep`.
This change brings Amplify Swift in …
=> feat(auth): add userID property to AuthSignUpResult

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Models/MFAPreference.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/UpdateMFAPreferenceTask.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/ClientBehaviorTests/MFA/UpdateMFAPreferenceTaskTests.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/MFATests/MFAPreferenceTests.swift, CHANGELOG.md
Fixing the logic of the udpateMFAPreference API to make sure old preferred values stay intact. 
=> fix(Auth): Adding the ability to keep old preferred methods

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/HostedUI/HostedUIASWebAuthenticationSession.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/HostedUITests/AWSAuthHostedUISignInTests.swift
- https://github.com/aws-amplify/amplify-swift/issues/3176
If an `error` query parameter is included in the HostedUI callback, we currently throw a `.service` error with the value of the `error` key, omitting important information that may be needed by the caller. With this change, we now attempt to extract and use the value from `error_description`; if it doesn't exist, we fall back to the `error` we know is there. The fall back to `error` is necessary because `error_description` is optional according to the [spec](https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.2.1).
This change brings Amplify Swift in parity with Android, Flutter, and JS.
- [Amplify Android](https://github.com/aws-amplify/amplify-android/blob/aac074ab49b44ccea0c9eb12d996f7033c20e3b7/aws-auth-cognito/src/main/j …
=> fix(auth): hostedui extract error_description query pararm

AmplifyPlugins/Logging/Sources/AWSCloudWatchLoggingPlugin/Persistence/LogActor.swift, AmplifyPlugins/Logging/Sources/AWSCloudWatchLoggingPlugin/Persistence/LogRotation.swift, AmplifyPlugins/Logging/Tests/AWSCloudWatchLoggingPluginTests/LogActorTests.swift
https://github.com/aws-amplify/amplify-swift/issues/3199
* update logging write logic to create log file if it doesn't exist (this could occur if the logs were previously flushed and removed)
=> fix(logging): create log file if it doesn't exist

AmplifyPlugins/Storage/Tests/StorageHostApp/AWSS3StoragePluginIntegrationTests/AWSS3StoragePluginOptionsUsabilityTests.swift
Fix flakey storage integration test in GH actions by increasing url expiration duration
=> test(storage): update storage integration test with longer expiration duration

AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/SubscriptionSync/ReconcileAndLocalSave/ReconcileAndLocalSaveOperation.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Sync/SubscriptionSync/ReconcileAndLocalSaveOperationTests.swift
https://github.com/aws-amplify/amplify-swift/issues/1903
We apply remote update events in batch. The existing code converts all the update operations into `Future<Void, DataStoreError>`, and merge them into one stream. The problem arises when a `Future` completes with an error; it causes the entire stream to terminate as an error. This behavior is unintentional and results in some update operations being silently discarded.
The solution here is simply change `Future<Void, DataStoreError>` to `Future<Result<Void, DataStoreError>, Never>`, which wraps the failure to a result type and makes the operation stream never fail.
=> fix(datastore): wrap failures to result when applying remote update events

AmplifyPlugins/Logging/Sources/AWSCloudWatchLoggingPlugin/AWSCloudWatchLoggingCategoryClient.swift, AmplifyPlugins/Logging/Sources/AWSCloudWatchLoggingPlugin/AWSCloudWatchLoggingPlugin.swift, AmplifyPlugins/Logging/Sources/AWSCloudWatchLoggingPlugin/AWSCloudWatchLoggingSessionController.swift, AmplifyPlugins/Logging/Tests/AWSCloudWatchLoggingPluginTests/AWSCloudWatchLoggingPluginTests.swift
* Fix issue where creating a logger with a category and namespace doesn't set the namespace value
=> fix(logging): fix issue with logger namespace not being set

AmplifyPlugins/API/Sources/AWSAPIPlugin/Configuration/AWSAPICategoryPluginConfiguration.swift, AmplifyPlugins/API/Sources/AWSAPIPlugin/Configuration/AWSAPIEndpointInterceptors.swift, AmplifyPlugins/API/Sources/AWSAPIPlugin/Interceptor/RequestInterceptor/AuthTokenURLRequestInterceptor.swift, AmplifyPlugins/API/Sources/AWSAPIPlugin/Interceptor/RequestInterceptor/IAMURLRequestInterceptor.swift, AmplifyPlugins/API/Sources/AWSAPIPlugin/Operation/AWSGraphQLOperation.swift, AmplifyPlugins/API/Sources/AWSAPIPlugin/Operation/AWSRESTOperation.swift, AmplifyPlugins/API/Sources/AWSAPIPlugin/Support/Utils/GraphQLOperationRequestUtils.swift, AmplifyPlugins/API/Sources/AWSAPIPlugin/Support/Utils/RESTOperationRequestUtils.swift, AmplifyPlugins/API/Sources/AWSAPIPlugin/Support/Utils/Result+Async.swift, AmplifyPlugins/API/Tests/APIHostApp/AWSAPIPluginFunctionalTests/GraphQLConnectionScenario4Tests.swift, AmplifyPlugins/API/Tests/APIHostApp/AWSAPIPluginFunctionalTests/GraphQLModelBasedTests+List.swift, AmplifyPlugins/API/Tests/APIHostApp/AWSAPIPluginRESTIAMTests/RESTWithIAMIntegrationTests.swift, AmplifyPlugins/API/Tests/AWSAPIPluginTests/AWSAPICategoryPlugin+InterceptorBehaviorTests.swift, AmplifyPlugins/API/Tests/AWSAPIPluginTests/Configuration/AWSAPICategoryPluginConfigurationTests.swift, AmplifyPlugins/API/Tests/AWSAPIPluginTests/Configuration/AWSAPIEndpointInterceptorsTests.swift, AmplifyPlugins/API/Tests/AWSAPIPluginTests/Interceptor/AuthTokenURLRequestInterceptorTests.swift, AmplifyPlugins/API/Tests/AWSAPIPluginTests/Operation/AWSRESTOperationTests.swift, AmplifyPlugins/API/Tests/AWSAPIPluginTests/Support/Utils/RESTRequestUtilsTests.swift, AmplifyPlugins/API/Tests/AWSAPIPluginTests/Support/Utils/Result+AsyncTests.swift
https://github.com/aws-amplify/amplify-swift/issues/3184
The existing implementation of the URLRequest interceptor proceeds as follows:
1. Applying customized headers.
2. Applying library predefined interceptors.
3. Applying user-defined interceptors.
However, this approach has certain issues. For instance, one of the Amplify predefined interceptors requires the calculation of the Sigv4 authentication header for the request. This calculation involves certain headers. Making it impossible for customers to modify these header fields within their own custom interceptors.
After some discussions, we have divided the library predefined interceptors into prelude and postlude interceptors, and the interceptor logic should be as follows:
1. Applying Amplify prelude interceptors.
2. Applying …
=> fix(api): change request interceptors applying logic

.github/workflows/integ_test_datastore_auth_iam.yml, .github/workflows/integ_test_datastore_multi_auth.yml, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginAuthIAMTests/AWSDataStoreAuthBaseTest.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginAuthIAMTests/AWSDataStoreCategoryPluginIAMAuthIntegrationTests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginMultiAuthTests/AWSDataStoreAuthBaseTest.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginMultiAuthTests/AWSDataStoreMultiAuthCombinationTests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginMultiAuthTests/AWSDataStoreMultiAuthSingleRuleTests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginMultiAuthTests/AWSDataStoreMultiAuthThreeRulesTests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginMultiAuthTests/AWSDataStoreMultiAuthTwoRulesTests.swift
We used to use custome interceptor to verify the final request headers for datastore multiAuth test cases. As we've [changed](https://github.com/aws-amplify/amplify-swift/pull/3190) the order of applying custome interceptors, this approach is no longer workable for verifying the final request.
This PR change to use a subclass of `URLProtocol` to monitor the final request and publish the header info to test cases.
=> fix(datastore): using URLProtocol monitor auth request headers

AmplifyPlugins/API/Tests/APIHostApp/APIHostApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/AWSDataStorePlugin+DataStoreBaseBehavior.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/AWSDataStorePlugin+DataStoreSubscribeBehavior.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/AWSDataStorePlugin.swift
https://github.com/aws-amplify/amplify-swift/issues/3198
Made datastore local operations (`save`, `query`, `delete`) using the instance of initStorageEngine result.
=> fix(datastore): use unwrapped storageEngine to perform datastore operations

Package.swift
Bump to Swift 5.7
Documentation changes already merged:
- https://github.com/aws-amplify/docs/pull/5659
- [README > Installation lists Xcode 14.1 (Swift 5.7) as prereq](https://github.com/aws-amplify/amplify-swift/blob/main/README.md#installation)
=> feat: change swift-tools-version to 5.7

AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/InitialSync/InitialSyncOperation.swift
https://github.com/aws-amplify/amplify-swift/issues/3028
DataStore's sync operation performs paginated sync query operations for each model, in the order of the model graph. Whenever the network request fails, we should provide that information to the `errorHandler` for visibility. Before this change, it was calling the `errorHandler` only on auth signed out errors. 
Similar to the discussion we had in https://github.com/aws-amplify/amplify-swift/pull/2532#discussion_r1014284029 / https://github.com/aws-amplify/amplify-swift/issues/3232, this PR only focuses on passing the error back to the developer. We have not improved the error handling experience by mapping it to a well defined "SyncError" type.
If we did, it would be the equivalent of the `ProcessName.sync` in JS.
By submitting this …
=> fix(datastore): call errorHandler in Sync operation when failure

Package.swift
Removing unused dependency in the logger plugin target
=> chore: remove unnecessary CloudWatch dependency from logger plugin

AmplifyPlugins/Core/AWSPluginsCore/Model/Decorator/AuthRuleDecorator.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Model/Decorator/AuthRuleDecorator/ModelMultipleOwnerAuthRuleTests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginAuthCognitoTests/AWSDataStoreCategoryPluginAuthOwnerIntegrationTests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginAuthCognitoTests/Models/TodoCognitoMultiOwner+Schema.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginAuthCognitoTests/Models/TodoCognitoMultiOwner.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginAuthCognitoTests/Models/TodoCognitoPrivate+Schema.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginAuthCognitoTests/Models/TodoCustomOwnerExplicit+Schema.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginAuthCognitoTests/Models/TodoCustomOwnerImplicit+Schema.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginAuthCognitoTests/Models/TodoExplicitOwnerField+Schema.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginAuthCognitoTests/Models/TodoImplicitOwnerField+Schema.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginAuthCognitoTests/README.md, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginAuthCognitoTests/singleauth-cognito-schema.graphql, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/DataStoreHostApp.xcodeproj/project.pbxproj
Taking this PR forward: https://github.com/aws-amplify/amplify-swift/pull/1606
This PR enables the use case of having multiple "owner" auth rules on a single model type. 
Instead of using the hand written swift types in the Integration test from #1606, it makes more sense to update the schema file for that test suite. In `singleauth-cogniot-schema.graphql`, I added the use case:
```
type TodoCognitoMultiOwner @model
@auth(rules: [
{ allow: owner },
{ allow: owner, ownerField: "editors", operations: [update, read]} ]) {
id: ID!
title: String!
content: String
owner: String
editors: [String]
}
```
I believe the use cases are
1. Signed in Cognito User Pool user, "user1", can perform all operations on models created by them.
2. "user2" can subscribe to onCreate, onUpdate, onDelete …
=> feat(datastore): support multi owner auth rules

AmplifyPlugins/DataStore/Tests/DataStoreHostApp/DataStoreHostApp.xcodeproj/project.pbxproj
Related PR with test issue https://github.com/aws-amplify/amplify-swift/pull/3223
Test is missing file added to watchOS target (https://github.com/aws-amplify/amplify-swift/actions/runs/6340116424/job/17222695667#logs)
```
❌  /Users/runner/work/amplify-swift/amplify-swift/AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginAuthCognitoTests/AWSDataStoreCategoryPluginAuthOwnerIntegrationTests.swift:225:47: cannot find 'TodoCognitoMultiOwner' in scope
ModelRegistry.register(modelType: TodoCognitoMultiOwner.self)
^~~~~~~~~~~~~~~~~~~~~
```
=> test: add TodoCognitoMultiOwner to watchOS target for DataStore test

AmplifyPlugins/Core/AWSPluginsCore/Auth/AWSAuthService.swift, AmplifyPlugins/Core/AWSPluginsCore/Auth/AWSAuthServiceBehavior.swift, AmplifyPlugins/Core/AWSPluginsCore/Auth/Provider/AmplifyAWSCredentialsProvider.swift, AmplifyPlugins/Core/AWSPluginsCore/Auth/Provider/AmplifyAWSSignatureV4Signer.swift, AmplifyPlugins/Core/AWSPluginsCore/Auth/Provider/IAMCredentialProvider.swift, AmplifyPlugins/Core/AWSPluginsCore/ServiceConfiguration/AmplifyAWSServiceConfiguration.swift, AmplifyPlugins/Core/AWSPluginsCore/Utils/CustomHttpClientEngine/ClientRuntimeFoundationBridge.swift, AmplifyPlugins/Core/AWSPluginsCore/Utils/CustomHttpClientEngine/FoundationClientEngine.swift, AmplifyPlugins/Core/AWSPluginsCore/Utils/CustomHttpClientEngine/UserAgentSuffixAppender.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Utils/UserAgentSuffixAppenderTests.swift, AmplifyPlugins/Core/AWSPluginsTestCommon/MockAWSAuthService.swift, AmplifyPlugins/Core/AWSPluginsTestCommon/MockAWSSignatureV4Signer.swift, Package.resolved, Package.swift
Makes necessary changes to get AWSPluginsCore to compile.
- Added new `FrameworkMetadata` type that needs to be removed in a subsequent PR
=> fix: resolve compiler errors in AWSPluginsCore after sdk update

AmplifyPlugins/API/Tests/APIHostApp/APIHostApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, AmplifyPlugins/API/Tests/APIHostApp/AWSAPIPluginFunctionalTests/GraphQLConnectionScenario6Tests.swift
The test was incorrectly aggregating the results from the list instance. The test will fail if the results came back on the first fetch call as it was getting dropped
```
AWSAPIPluginFunctionalTests.GraphQLConnectionScenario6Tests
testGetBlogThenFetchPostsThenFetchComments, XCTAssertEqual failed: ("0") is not equal to ("2")
/Users/runner/work/amplify-swift/amplify-swift/AmplifyPlugins/API/Tests/APIHostApp/AWSAPIPluginFunctionalTests/GraphQLConnectionScenario6Tests.swift:99
```
let allPosts = try await getAll(list: resultPosts)
XCTAssertEqual(allPosts.count, 2)
guard let fetchedPost = allPosts.first(where: { (post) -> Bool in
```
testGetBlogThenFetchPostsThenFetchComments, failed - Could not set up - failed to get a post and its comments …
```
=> test: fix API integration getAll list elements

AmplifyPlugins/Internal/Sources/InternalAWSPinpoint/Support/Utils/PinpointRequestsRegistry.swift
- Adds back in a local property unintentionally removed in https://github.com/aws-amplify/amplify-swift/pull/3264
none
=> fix(analytics): add missing headers prop

AmplifyPlugins/Internal/Sources/InternalAWSPinpoint/Extensions/CommonRunTimeError+isConnectivityError.swift
Add explicit return in InternalAWSPinpoint to compile < 5.9
[Analytics integration tests are also now passing](https://github.com/aws-amplify/amplify-swift/actions/runs/6394386068/job/17355658106)
none
=> fix(analytics): add explicit return cause 5.7

.github/workflows/notify_issue_comment.yml, .github/workflows/notify_new_issue.yml, .github/workflows/notify_release.yml
Updating the notifications workflows to:
- Filter by `author_association` instead of hardcoding aliases, for both comments and issues
- Notify the comment author instead of the issue author
- Remove notifications for draft releases, they are just spammy
=> chore: Tweaking notification workflows

.github/workflows/notify_release.yml
Sending `github.event.repository.name` instead of `github.event.repository.html_url` to the Slack webhook, since the release url already includes a link.
=> chore: Sending repo name instead of URL in release notification [skip ci]

AmplifyPlugins/Internal/Tests/InternalAWSPinpointUnitTests/Mocks/MockEndpointClient.swift, AmplifyPlugins/Internal/Tests/InternalAWSPinpointUnitTests/Mocks/MockPinpointClient.swift, AmplifyPlugins/Internal/Tests/InternalAWSPinpointUnitTests/PinpointRequestsRegistryTests.swift
Minor changes to InternalAWSPinpointUnitTests target to account for new Swift SDK types / methods.
none
=> fix(internal-pinpoint-tests): update tests for new sdk version

AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Configuration/S3ClientConfigurationProxyTests.swift
- Adds region to client configuration used in tests.
- Configuration copy semantics test case now use identity operator checks instead of built in XCTest methods.
none
=> fix(storage-test): use identity comparison operators not XCTest methods

AmplifyPlugins/Predictions/AWSPredictionsPlugin/Service/Predictions/AWSPredictionsService+Polly.swift, AmplifyPlugins/Predictions/Tests/PredictionsHostApp/PredictionsHostApp.xcodeproj/project.pbxproj
- Uses provided `readData()` method on `ByteStream` in Polly response for `textToSpeech`
- Removes linked libraries from test targets causing problems with Xcode 15.
- Resolves open item in base branch:
> There's a new error branch in AWSPredictionsService+Polly that now throws an .unknown error. Take another look at it to see if there's a more appropriate error than can be thrown there. Added in https://github.com/aws-amplify/amplify-swift/pull/3257
none
=> fix(predictions): use readData on textToSpeech bytestream

.github/workflows/integ_test_auth.yml, .github/workflows/integ_test_predictions.yml, AmplifyPlugins/Analytics/Tests/AnalyticsHostApp/AnalyticsHostApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthHostApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/AuthDeleteUserTests/AuthDeleteUserTests.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/DeviceTests/AuthForgetDeviceTests.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/SignInTests/AuthSRPSignInTests.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/SignUpTests/AuthResendSignUpCodeTests.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/SignUpTests/AuthSignUpTests.swift, AmplifyPlugins/Auth/Tests/AuthHostedUIApp/AuthHostedUIApp.xcodeproj/xcshareddata/xcschemes/AuthHostedUIApp.xcscheme, AmplifyPlugins/Core/AWSPluginsCore/ServiceConfiguration/AmplifyAWSServiceConfiguration.swift, AmplifyPlugins/Predictions/Tests/PredictionsHostApp/CoreMLPredictionsPluginIntegrationTests/CoreMLPredictionsPluginIntegrationTest.swift, AmplifyPlugins/Predictions/Tests/PredictionsHostApp/PredictionsHostApp.xcodeproj/project.pbxproj, AmplifyPlugins/Predictions/Tests/PredictionsHostApp/PredictionsHostApp/ContentView.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Service/Storage/AWSS3StorageService.swift, AmplifyPlugins/Storage/Tests/StorageHostApp/AWSS3StoragePluginIntegrationTests/AWSS3StoragePluginBasicIntegrationTests.swift, AmplifyPlugins/Storage/Tests/StorageHostApp/AWSS3StoragePluginIntegrationTests/AWSS3StoragePluginTestBase.swift, AmplifyPlugins/Storage/Tests/StorageHostApp/StorageHostApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, AmplifyPlugins/Storage/Tests/StorageHostApp/StorageHostApp.xcodeproj/xcshareddata/xcschemes/StorageHostApp.xcscheme
- Predictions and Auth integration tests use macos-13 runner w/ Xcode 14.3.1
- Updates Package.resolved for new dependency versions in a few HostApp targets.
- Relaxes assertions in Auth integration test cases expecting `userNotFound` to allow for `limitedExceeded` exceptions.
- Switches over to `fulfillment(of:)` in a couple tests within async contexts.
- Disables parallel execution of AuthHostedUIApp integration test cases (doesn't play nice with action runners).
- Adds `userAgentOS` to `AmplifyAWSServiceConfiguration` for Storage requests that aren't generated or executed through the Swift SDK.
- Fixes incorrect assertion in CoreMLPredictionsPluginIntegrationTests.
- Removes non-executed code paths from PredictionsHostApp.
none
By submitting this pull request, I confirm that my …
=> fix: remaining integration tests for sdk update

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Service/ErrorMapping/CommonRunTimeError+AuthErrorConvertible.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/ClientBehaviorTests/AuthenticationProviderDeleteUserTests.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/AuthDeleteUserTests/AuthDeleteUserTests.swift, AmplifyPlugins/Core/AWSPluginsCore/Utils/CustomHttpClientEngine/ClientRuntimeFoundationBridge.swift
- Adds `AuthErrorConvertible` conformance to `CommonRuntimeError` to map client side network errors.
none
=> fix: add AuthErrorConvertible conformance to CommonRuntimeError

README.md
Fix branch name typo in README.
=> chore: fix readme typo and make instructions clearer [skip ci]

AmplifyPlugins/Auth/Tests/AuthHostApp/AuthHostApp.xcodeproj/xcshareddata/xcschemes/AuthHostApp.xcscheme, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthHostApp.xcodeproj/xcshareddata/xcschemes/AuthIntegrationTests.xcscheme
n/a 
- Turns off parallelizable for Auth integration tests
- parallel test runs seem to be messing with CI test runs and they're not providing any value.
- Turns of TSan for Auth integration tests
=> test(auth): turn off parallelizable and tsan in integration tests

.github/workflows/run_xcodebuild_test_platforms.yml
Only setting `test-without-building` to `true` if there was a cache for the exact SHA that's being tested, **or** if there wasn't a main build cached.
Otherwise the retry would end up using an old successful build and result in a success, even if the actual tests in the current commit are not passing.
=> chore: Fixing retries in unit tests workflow

.github/workflows/integ_test_analytics.yml, .github/workflows/integ_test_api.yml, .github/workflows/integ_test_api_functional.yml, .github/workflows/integ_test_api_graphql_auth_directive.yml, .github/workflows/integ_test_api_graphql_iam.yml, .github/workflows/integ_test_api_graphql_lambda_auth.yml, .github/workflows/integ_test_api_graphql_lazy_load.yml, .github/workflows/integ_test_api_graphql_user_pool.yml, .github/workflows/integ_test_api_rest_iam.yml, .github/workflows/integ_test_api_rest_user_pool.yml, .github/workflows/integ_test_auth.yml, .github/workflows/integ_test_datastore_auth_cognito.yml, .github/workflows/integ_test_geo.yml, .github/workflows/integ_test_logging.yml, .github/workflows/integ_test_push_notifications.yml
n/a 
- Moves from macos-12 / Xcode 14.2 --> Use macos-13 / Xcode 14.3 in remaining integration tests.
- Increases some timeouts that occasionally get hit in integration test suites.
=> chore(integration-tests): use macos-13 and xcode 14.3 - increase timeouts [skip ci]

AmplifyPlugins/Auth/Tests/AuthHostedUIApp/AuthHostedUIAppUITests/Screen/AuthenticatedScreen.swift, AmplifyPlugins/Auth/Tests/AuthHostedUIApp/AuthHostedUIAppUITests/Screen/SignInScreen.swift, AmplifyPlugins/Auth/Tests/AuthHostedUIApp/AuthHostedUIAppUITests/Screen/SignUpScreen.swift
n/a
The (lack of) speed in our current CI runner results in timeouts in HostedUI integration tests.
- increases timeout for affected UI tests.
=> fix(integration-tests): increase timeout of hostedui ui tests [skip ci]

AmplifyPlugins/API/Tests/APIHostApp/APIHostApp.xcodeproj/xcshareddata/xcschemes/AWSAPIPluginFunctionalTests.xcscheme, AmplifyPlugins/API/Tests/APIHostApp/AWSAPIPluginFunctionalTests/Base/TestConfigHelper.swift, AmplifyPlugins/API/Tests/APIHostApp/AWSAPIPluginFunctionalTests/GraphQLConnectionScenario1APISwiftTests.swift, AmplifyPlugins/API/Tests/APIHostApp/AWSAPIPluginFunctionalTests/GraphQLConnectionScenario1Tests.swift, AmplifyPlugins/API/Tests/APIHostApp/AWSAPIPluginFunctionalTests/GraphQLConnectionScenario2Tests.swift, AmplifyPlugins/API/Tests/APIHostApp/AWSAPIPluginFunctionalTests/GraphQLConnectionScenario3Tests+List.swift, AmplifyPlugins/API/Tests/APIHostApp/AWSAPIPluginFunctionalTests/GraphQLConnectionScenario3Tests.swift, AmplifyPlugins/API/Tests/APIHostApp/AWSAPIPluginFunctionalTests/GraphQLConnectionScenario4Tests.swift, AmplifyPlugins/API/Tests/APIHostApp/AWSAPIPluginFunctionalTests/GraphQLConnectionScenario5Tests.swift, AmplifyPlugins/API/Tests/APIHostApp/AWSAPIPluginFunctionalTests/GraphQLConnectionScenario6Tests.swift, AmplifyPlugins/API/Tests/APIHostApp/AWSAPIPluginFunctionalTests/GraphQLScalarTests.swift, AmplifyPlugins/API/Tests/APIHostApp/AWSAPIPluginGraphQLUserPoolTests/Base/AsyncExpectation.swift
n/a
When the API (GraphQL) integration test suite runs in parallel, predicate based queries can result in failing assertions.
This happens today when running test suites on the various supported platforms concurrently in CI.
This can also happen when tests are automatically running in the release process and have been manually kicked off on a different branch for testing.
- Appends UUIDs to various string values in models that are / can be queried for in tests.
=> fix(api): sprinkle in some uuids to prevent parallel run clashes [skip ci]

AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/AWSS3StoragePlugin+AsyncClientBehavior.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Dependency/AWSS3PreSignedURLBuilderAdapter.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Dependency/AWSS3PreSignedURLBuilderBehavior.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Service/Storage/AWSS3StorageService+DownloadBehavior.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Service/Storage/AWSS3StorageService+GetPreSignedURLBehavior.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Service/Storage/AWSS3StorageService+MultiPartUploadBehavior.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Service/Storage/AWSS3StorageService+UploadBehavior.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Service/Storage/AWSS3StorageServiceBehavior.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/StorageMultipartUploadClient.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/AWSS3StoragePluginGetPresignedUrlTests.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Mocks/MockAWSS3PreSignedURLBuilder.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Mocks/MockAWSS3StorageService.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Service/Storage/AWSS3StorageServiceGetPreSignedURLBehaviorTests.swift
https://github.com/aws-amplify/amplify-swift/issues/2744
* Include metadata in s3 uploads
=> fix(storage): add metadata support to uploads

.github/workflows/integ_test.yml, .github/workflows/integ_test_api_functional.yml, .github/workflows/integ_test_api_graphql_auth_directive.yml, .github/workflows/integ_test_api_graphql_iam.yml, .github/workflows/integ_test_api_graphql_lambda_auth.yml, .github/workflows/integ_test_api_graphql_lazy_load.yml, .github/workflows/integ_test_api_graphql_user_pool.yml, .github/workflows/integ_test_api_rest_iam.yml, .github/workflows/integ_test_api_rest_user_pool.yml, .github/workflows/integ_test_auth.yml, .github/workflows/integ_test_datastore.yml, .github/workflows/integ_test_datastore_auth_cognito.yml, .github/workflows/integ_test_datastore_auth_iam.yml, .github/workflows/integ_test_datastore_base.yml, .github/workflows/integ_test_datastore_cpk.yml, .github/workflows/integ_test_datastore_lazy_load.yml, .github/workflows/integ_test_datastore_multi_auth.yml, .github/workflows/integ_test_datastore_v2.yml, .github/workflows/integ_test_geo.yml, .github/workflows/integ_test_logging.yml, .github/workflows/integ_test_predictions.yml, .github/workflows/integ_test_storage.yml, .github/workflows/stress_test.yml, AmplifyPlugins/Storage/Tests/StorageHostApp/StorageStressTests/StorageStressTests.swift
Stress tests are failing because they're still running on macos-12 runners that don't have Xcode 14.3, which added the `fulfillment(of:)` API.
- Updates stress tests to run on macos-13
It looks like tests are taking longer when using `OS=latest` for iOS test runs. Using an explicit version sped up the PushNotifications integration tests dramatically.
- Specifies exact iOS version in integration tests (`OS=16.4`)
=> test: use macos-13 runners for stress tests and use explicit iOS version

Amplify/Categories/DataStore/Model/Lazy/List+Model.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Core/ListTests.swift
https://github.com/aws-amplify/amplify-swift/issues/3286
This public API change adds a `isLoaded` property in the `List+Model` public to help customers check if the list is loaded before calling `fetch()` to avoid network calls.
=> feat(datastore): Add `isLoaded` public property in List+Model

.github/workflows/integ_test_datastore_auth_cognito.yml, .github/workflows/integ_test_datastore_auth_iam.yml, .github/workflows/integ_test_datastore_base.yml, .github/workflows/integ_test_datastore_cpk.yml, .github/workflows/integ_test_datastore_lazy_load.yml, .github/workflows/integ_test_datastore_multi_auth.yml, .github/workflows/integ_test_datastore_v2.yml, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginAuthCognitoTests/AWSDataStoreCategoryPluginAuthIntegrationTests.swift, AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/DataStoreObserveQueryTests.swift
A few DataStore integration tests were consistently failing after moving away from `AsyncExpectation` / `await wait(for:)` to `XCTestExpectation` / `await fulfillment(of:)` in https://github.com/aws-amplify/amplify-swift/pull/3305
These failures were caused by double waits on a single expectation.
- Removes double wait in two remaining cases.
Another test was somewhat consistently failing due to a timeout. The test takes almost 10 seconds to run on my M1 Pro, so there's little chance it's going to make it before timing out in our CI.
- Increases timeout from 10 to 60 seconds.
=> test: fix datastore integration tests

AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Operation/AWSS3StorageUploadDataOperation.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Operation/AWSS3StorageUploadFileOperation.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/StorageMultipartUploadClient.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Utils/StorageRequestUtils+Getter.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Operation/AWSS3StoragePutDataOperationTests.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Operation/AWSS3StorageUploadFileOperationTests.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Support/Utils/StorageRequestUtilsGetterTests.swift, AmplifyPlugins/Storage/Tests/StorageHostApp/AWSS3StoragePluginIntegrationTests/AWSS3StoragePluginUploadMetadataTestCase.swift, AmplifyPlugins/Storage/Tests/StorageHostApp/AWSS3StoragePluginIntegrationTests/Helpers/TestConfigHelper.swift, AmplifyPlugins/Storage/Tests/StorageHostApp/StorageHostApp.xcodeproj/project.pbxproj
- https://github.com/aws-amplify/amplify-swift/issues/2744
[User-defined metadata](https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingMetadata.html#UserMetadata) passed to Storage upload functions (`uploadData` / `uploadFile`) was not being included in PutObject/MPU requests to S3. This was fixed in AWS SDK for Swift, and subsequently in Amplify Swift [v2.20.1](https://github.com/aws-amplify/amplify-swift/releases/tag/2.20.1). However, this introduced an issue with double prefixing metadata keys. While testing, another related issue was uncovered; both are addressed in this PR.
1. Amplify Swift *and* AWS SDK for Swift were both prepending `x-amz-meta-` to each metadata key-value pair's key. This leads to metadata defined as `"foo": "bar"` being transformed into …
=> fix(storage): include user-controlled metadata in upload requests

.github/workflows/integ_test_analytics.yml, .github/workflows/integ_test_api_functional.yml, .github/workflows/integ_test_api_graphql_auth_directive.yml, .github/workflows/integ_test_api_graphql_iam.yml, .github/workflows/integ_test_api_graphql_lambda_auth.yml, .github/workflows/integ_test_api_graphql_lazy_load.yml, .github/workflows/integ_test_api_graphql_user_pool.yml, .github/workflows/integ_test_api_rest_iam.yml, .github/workflows/integ_test_api_rest_user_pool.yml, .github/workflows/integ_test_auth.yml, .github/workflows/integ_test_datastore_auth_cognito.yml, .github/workflows/integ_test_datastore_auth_iam.yml, .github/workflows/integ_test_datastore_base.yml, .github/workflows/integ_test_datastore_cpk.yml, .github/workflows/integ_test_datastore_lazy_load.yml, .github/workflows/integ_test_datastore_multi_auth.yml, .github/workflows/integ_test_datastore_v2.yml, .github/workflows/integ_test_geo.yml, .github/workflows/integ_test_logging.yml, .github/workflows/integ_test_predictions.yml, .github/workflows/integ_test_push_notifications.yml, .github/workflows/integ_test_storage.yml
Sometimes we want to manually kick off integration tests in CI for a specific platform. https://github.com/aws-amplify/amplify-swift/pull/2974 split out our integration tests into reusable workflows, but didn't get down to platform level granularity. 
- Adds `workflow_dispatch` inputs to all integration tests, allowing an operator to trigger / omit tests for any combination of available platforms.
By default, all platforms are preselected.
And can be toggled as necessary. 
=> test: [skip ci] add workflow dispatch inputs for platform-specific integration tests

AmplifyPlugins/Analytics/Sources/AWSPinpointAnalyticsPlugin/Support/Utils/AnalyticsErrorHelper.swift, AmplifyPlugins/Internal/Sources/InternalAWSPinpoint/Analytics/EventRecorder.swift, AmplifyPlugins/Internal/Tests/InternalAWSPinpointUnitTests/EventRecorderTests.swift, AmplifyPlugins/Internal/Tests/InternalAWSPinpointUnitTests/Mocks/MockAnalyticsEventStorage.swift, AmplifyPlugins/Internal/Tests/InternalAWSPinpointUnitTests/Mocks/MockPinpointClient.swift
If guest/unauthenticated access is disabled, attempting to submit cached events with a user signed our or with an expired token will fail and all events will be discarded. This happens because this failure is considered non-retryable.
This PR fixes that by considering the following `AuthError`s to be retryable without affecting the events retry count:
- `.sessionExpired`
-  `.signedOut`
- `.service` with an underlying error of type `AWSCognitoAuthError.invalidAccountTypeException`
This is similar as to how connectivity issues are handled.
=> fix(Analytics): Handling certain auth errors as retryable errors

.swiftpm/xcode/xcshareddata/xcschemes/AWSCognitoAuthPlugin.xcscheme, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Models/AWSAuthCognitoSession.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Models/AWSCognitoUserPoolTokens.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Helpers/AuthCognitoSignedOutSessionHelper.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/HostedUI/HostedUIASWebAuthenticationSession.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ActionTests/CredentialStore/MigrateLegacyCredentialStoreTests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ActionTests/FetchAuthSession/FetchUserPoolTokens/RefreshHostedUITokensTests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ActionTests/InitiateAuthSRP/VerifyDevicePasswordSRPSignatureTests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ActionTests/SignOut/ShowHostedUISignOutTests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/CognitoASFTests/CognitoUserPoolASFTests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ConfigurationTests/EscapeHatchTests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/Support/AWSAuthCognitoSessionTests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/Support/HostedUIASWebAuthenticationSessionTests.swift, AmplifyPlugins/Notifications/Push/Tests/AWSPinpointPushNotificationsPluginUnitTests/ErrorPushNotificationsTests.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Dependency/AWSS3Adapter.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Dependency/AWSS3Behavior.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Service/Storage/AWSS3StorageService.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/StorageMultipartUploadSession.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/StorageTransferTask.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Dependency/AWSS3AdapterTests.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Service/Storage/AWSS3StorageServiceTests.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Support/Internal/DefaultStorageMultipartUploadClientTests.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Support/Internal/DefaultStorageTransferDatabaseTests.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Support/Internal/StorageMultipartUploadSessionTests.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Support/Internal/StorageServiceSessionDelegateTests.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Support/Internal/StorageTransferTaskTests.swift
This PR adds additional unit tests to the following targets:
- AWSCognitoAuthPlugin
- AWSStoragePlugin
- AWSPinpointPushNotificationsPlugin
It also removes some orphaned code found around :)
=> chore(unit tests): Adding additional unit tests

Package.swift
- https://github.com/aws-amplify/amplify-swift/issues/3324
Bumps AWS SDK for Swift from 0.26.0 to 0.26.1.
[0.26.1](https://github.com/awslabs/aws-sdk-swift/releases/tag/0.26.1) pins aws-crt-swift 0.17.0, which puts the `common_cryptor_spi.h` behind an `#ifdef` directive to prevent the non-public symbols from being included in release builds.
This fix was confirmed through manual testing - uploading an app to App Store Connect that embeds a `.framework`, which wraps Amplify Swift + plugin targets.
In addition to confirming that the upload to App Store Connect succeeded, the non-public `CCCryptorGCM...` symbols were confirmed to not be included in release build artifacts.
**Prior to Change / Before**
```bash
> nm -m <archive-path>.xcarchive/Products/Applications/my_app.app/Frameworks/wrapper …
```
=> fix: bump swift sdk to 0.26.1

AmplifyPlugins/Internal/Sources/InternalAWSPinpoint/Analytics/AnalyticsClient.swift, AmplifyPlugins/Internal/Sources/InternalAWSPinpoint/Analytics/EventRecorder.swift, AmplifyPlugins/Internal/Tests/InternalAWSPinpointUnitTests/AnalyticsClientTests.swift, AmplifyPlugins/Internal/Tests/InternalAWSPinpointUnitTests/EventRecorderTests.swift, AmplifyPlugins/Internal/Tests/InternalAWSPinpointUnitTests/Mocks/MockEventRecorder.swift
- https://github.com/aws-amplify/amplify-swift/issues/3328
This PR fixes a crash that was happening when `EventRecorder.submitAllEvents()` was called while a previous submission was still ongoing.
This happened because the `submittedEvents` array was being populated by the previous submission, while the very first thing a new one does is to set it to `[]`.
I am changing the behaviour so that `submitAllEvents` now waits until the previous submission ends before continuing. I've explored just using a lock to manipulate the array instead, but while that did fix the crash, it would still produce undetermined behaviour when the array was emptied.
=> fix(Analytics): Fixing crash when attempting to submit events while a previous submission is in progress

Amplify/Categories/DataStore/Model/Internal/Schema/AuthRule.swift, AmplifyPlugins/Core/AWSPluginsCore/Auth/AWSAuthModeStrategy.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Auth/AuthModeStrategyTests.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/SubscriptionSync/IncomingAsyncSubscriptionEventPublisher.swift
https://github.com/aws-amplify/amplify-swift/issues/2873
Subscriptions for read auth rule were not processed inside Datastore. read auth rule can subscribe to onCreateX, onUpdateX and onDeleteX.
This PR is ported from `v1` to `main` : https://github.com/aws-amplify/amplify-swift/pull/3029
A Test app was setup with the same schema as in https://github.com/aws-amplify/amplify-swift/issues/2873 and `Amplify.Datastore.start()` was called without no user signed in. The logs below capture the difference where in ModelB and ModelC subscriptions are succesfully connected for the unauthenticated user.
```
[InitializeSubscription] initializeSubscriptions(api:storageAdapter:)
[InitializeSubscription.5] Sink reconciliationQueues ModelB 1
[InitializeSubscription.5] Sink done reconciliationQueues …
```
=> fix(datastore): multi auth rule for read subscription

AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/AWSAuthBaseTest.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/MFATests/MFAPreferenceTests.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/MFATests/MFASignInTests.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/MFATests/TOTPSetupWhenAuthenticatedTests.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/MFATests/TOTPSetupWhenUnauthenticatedTests.swift
Some of the MFA integration tests are reusing the same email address or telephone number. This leads to intermittent test failures when tests suites are running concurrently -- either on different platforms in the same test run, or concurrent test runs.
This change addresses this by using random emails and telephone numbers where applicable to prevent collisions.
=> test: update mfa e2e tests to prevent concurrent run user collisions

.github/workflows/deploy_release.yml, .github/workflows/deploy_unstable.yml
GitHub Actions have a limit of 3 reusable workflow depth. Unfortunately we've exceeded that limit during the release workflows, with the recent introduction of `run_unit_tests_paltforms`:
- deploy_unstable -> deploy_package -> run_unit_tests_platforms -> run_unit_tests
- deploy_stable -> deploy_package -> run_unit_tests_platforms -> run_unit_tests
So to unblock us quickly I'm just adding the required jobs and steps to the `deploy_unstable` and `deploy_stable` workflows, so they don't need to call `deploy_package`.
I will explore better options in a follow up PR, such as either using composite actions for releases, or tweaking the test workflows further.
=> chore(workflows): Fixing release workflows depth

Amplify/Categories/Auth/AuthCategory+ClientBehavior.swift, Amplify/Categories/Auth/AuthCategoryBehavior.swift, Amplify/Categories/Auth/Models/AuthPasswordless.swift, Amplify/Categories/Auth/Models/AuthPasswordlessDeliveryDestination.swift, Amplify/Categories/Auth/Models/AuthPasswordlessFlow.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/ClientBehavior/AWSCognitoAuthPlugin+ClientBehavior.swift, AmplifyTestCommon/Mocks/MockAuthCategoryPlugin.swift
None
Add public API definitions for Sign in with Magiclink
=> feat(auth): Add magic link API public definitions

AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/MutationSync/OutgoingMutationQueue/OutgoingMutationQueue.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/MutationSync/OutgoingMutationQueue/ProcessMutationErrorFromCloudOperation.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Sync/MutationQueue/ProcessMutationErrorFromCloudOperationTests.swift
This PR passes the reconciliationQueue to the **ProcessMutationErrorFromCloudOperation** to reconcile conflict-handler resulting mutation responses. Reconciliation will update the local model's metadata version to keep it up to date. 
The impact; normally this is not needed since the subscription events should funnel into the reconciliation queue, however this is not the case for apps that have disabled subscriptions. There are some clients that disable subscriptions for various reasons, to have a limited functioning DataStore without real-time updates. For these apps, DataStore will continue to reoncile responses from locally sourced mutations so that that data local to the app will be kept up to date with the remote store as much as possible.
By submitting this pull request, I confirm …
=> fix(DataStore): Reconcile mutation responses from conflict handler path

.github/workflows/closed_issue_message.yml
Comments on closed issues can go unnoticed; the general guidance we give customers is to open a new issue. This automates that process using [aws-actions/closed-issue-message](aws-actions/closed-issue-message).
Example:
=> chore: add closed issue visibility auto comment action workflow

Amplify/Categories/Auth/AuthCategory+ClientBehavior.swift, Amplify/Categories/Auth/AuthCategoryBehavior.swift, Amplify/Categories/Auth/Models/AuthPasswordlessDeliveryDestination.swift, Amplify/Categories/Auth/Models/AuthPasswordlessFlow.swift, Amplify/Categories/Auth/Models/AuthSignInStep.swift, Amplify/Categories/Auth/Request/AuthPasswordlessMagicLinkRequest.swift, Amplify/Categories/Auth/Request/AuthPasswordlessOTPRequest.swift, Amplify/Categories/Auth/Request/AuthPasswordlessRequest.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/ClientBehavior/AWSCognitoAuthPlugin+ClientBehavior.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Models/Options/AWSAuthSignInPasswordlessOptions.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Models/Options/AWSAuthSignUpAndSignInPasswordlessOptions.swift, AmplifyTestCommon/Mocks/MockAuthCategoryPlugin.swift
None
Update public API request and options parameters
=> feat(auth): Update public API request and options parameters

.github/workflows/release_kickoff.yml
This PR adds a couple of checkbox validations when triggering the release workflow:
- That we are in CLEAR DAYs or we have approval
- That we have reverted everything in main (This one is temporary)
=> chore: Adding checkbox validations to the release workflow trigger

AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/Bytes.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/FileHandle+UInt64.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/FileSystem.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/StoragePersistableTransferTask.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/StorageServiceSessionDelegate.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/StorageUploadPart.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/StorageUploadPartEvent.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Support/Internal/FileHandleTests.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Support/Internal/FileSystemTests.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Support/Internal/MockMultipartUploadClient.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Support/Internal/StorageMultipartUploadSessionTests.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Support/Internal/StorageTransferDatabaseTests.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Support/Internal/StorageUploadPartSizeTests.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Support/Internal/StorageUploadPartTests.swift
- https://github.com/aws-amplify/amplify-swift/issues/3378
This PR changes `Int` to `UInt64` in several Storage objects when representing bytes.
watchOS's `Int` is actually a `Int32` due to its **arm64_32** architecture, so attempting to convert >= 2GB into bytes results in an overflown error.
The only special handing is our usage of [`FileHandle.read(upToCount:)`](https://developer.apple.com/documentation/foundation/filehandle/3516317-read), which we use to split a file into parts for multipart uploads.
Since the `count` attribute is an `Int`, but the theoretical maximum size for a part is 5GB, attempting to directly cast it could crash. In practice, this **very** unlikely to happen as having a part with size >= 2GB with the current implementation can only happen for files of size bigger …
=> fix(storage): Fixing watchOS crash when dealing with big files

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/AWSCognitoAuthPlugin+Configure.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/ClientBehavior/AWSCognitoAuthPlugin+ClientBehavior.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Environment/AuthEnvironment.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Environment/AuthPasswordlessEnvironment.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Environment/AuthenticationEnvironment.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/Helpers/PasswordlessSignInHelper.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/Helpers/PasswordlessSignUpHelper.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/CodeGen/Data/UserPoolConfigurationData.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Helpers/ConfigurationHelper.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Passwordless/AWSAuthPasswordlessClient.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Passwordless/AuthPasswordlessBehavior.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthConfirmSignInWithMagicLinkTask.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthConfirmSignInWithOTPTask.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthSignInWithMagicLinkTask.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthSignInWithOTPTask.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/Mocks/MockAuthPasswordlessBehavior.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/Support/DefaultConfig.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/ClientBehaviorTests/SignIn/AWSAuthConfirmSignInTaskTests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/ClientBehaviorTests/SignIn/AWSAuthSignInWithMagicLinkTaskTests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/ClientBehaviorTests/SignIn/AWSAuthSignInWithOTPTaskTests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/ClientBehaviorTests/SignIn/ConfirmSignInTOTPTaskTests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/ClientBehaviorTests/SignIn/ConfirmSignInWithMFASelectionTaskTests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/ClientBehaviorTests/SignIn/ConfirmSignInWithSetUpMFATaskTests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/UserBehaviourTests/BasePluginTest.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TestHarness/Mocks/MockedAuthCognitoPlugin.swift
None 
- Add sign up implementation for OTP
- Add sign up implementation for MagicLink
=> feat(auth): add sign up implementation for otp and magiclink

Package.resolved
Taking on this version of AppSyncRealTimeClient will enable a few use cases from APIPlugin and DataStore
APIPlugin will allow watchOS subscriptions to be established during special circumstances. Otherwise, it wil timeout according to the client timeout logic built in the AppSyncRealTimeClient
DataStore will alow the sync engine to successfully establish subscriptions if disableSubscriptions are set to false. 
https://github.com/aws-amplify/aws-appsync-realtime-client-ios/releases/tag/3.1.2
fix: watchOS support - disable network monitoring, add client timeout (https://github.com/aws-amplify/aws-appsync-realtime-client-ios/pull/141)
=> fix: appsync-realtime-client 3.1.2 watchOS support

Amplify/Categories/DataStore/Model/Internal/Persistable.swift, Amplify/Categories/DataStore/Query/QueryOperator.swift, Amplify/Categories/DataStore/Query/QueryPredicate.swift, AmplifyPlugins/Core/AWSPluginsCore/Sync/ModelSync/ModelSyncMetadata+Schema.swift, AmplifyPlugins/Core/AWSPluginsCore/Sync/ModelSync/ModelSyncMetadata.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Migration/ModelSyncMetadataMigration.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Storage/SQLite/SQLStatement+AlterTable.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Storage/SQLite/SQLStatement+TableInfoStatement.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Storage/SQLite/StorageEngineAdapter+SQLite.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/InitialSync/InitialSyncOperation.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Core/QueryPredicateTests.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Migration/ModelSyncMutationMigrationTests.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Sync/InitialSync/InitialSyncOperationTests.swift
https://github.com/aws-amplify/amplify-swift/issues/3383
Perform a full sync when the sync expression for the model changes. To do this, we have to persist and retrieve it from the sync metadata table for comparison with the incoming sync predicate.
The sync expression can be made up of mulitple predicates, each correponding to a specific model. InitialSyncOperation extracts out the first sync predicate from the sync expression for the corresponding model. This `QueryPredicate` is then used to compare with the existing persisted sync predicate from the last sync run, stored in the ModelSyncMetadata table.
We extend the ModelSyncMetadata table to add a new column, make QueryPredicate Encodable so we can encode the sync predicate and store it as a String. The encoder has the output …
=> fix(datastore): full sync when sync predicate changes

AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Storage/StorageEngine+SyncRequirement.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Storage/StorageEngineBehavior.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Subscribe/DataStoreObserveQueryOperation.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Sync/SubscriptionSync/Support/MockSQLiteStorageEngineAdapter.swift
- https://github.com/aws-amplify/amplify-swift/issues/3100
`DataStore.observeQuery(...)` has some internal logic to batch snapshots received based on total count or time elapsed while syncing. This logic is applied when `DataStore` thinks it is hasn't yet completed syncing. 
When `DataStore` is in local only mode (i.e. when `AWSAPIPlugin` isn't being used), it is never "completed syncing", leading to the same throttling logic.
This change ensures that the throttling / collect logic is **not** applied when `DataStore` is in local only mode.
=> fix(datastore): observequery local only collect

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/UserTasks/AWSAuthSendUserAttributeVerificationCodeTask.swift
Follow up to: 
- https://github.com/aws-amplify/amplify-swift/pull/3365
`AWSAuthSendUserAttributeVerificationCodeTask` was missing `DefaultLogger` conformance leading to a compiler error in CI.
=> fix(Auth): add DefaultLogger conformance to remaining auth task

AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Sync/InitialSync/InitialSyncOperationTests.swift
DataStore watchOS unit tests are currently failing on `main` due to a missing required argument `disableSubscriptions` for watchOS (introduced: https://github.com/aws-amplify/amplify-swift/pull/3368) to tests added in https://github.com/aws-amplify/amplify-swift/pull/2757
=> test(datastore): fix compiler errors in watchos unit tests due to missing `disableSubscriptions` arg

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/Helpers/PasswordlessConfirmSignInHelper.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Operations/Helpers/PasswordlessSignInHelper.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthConfirmSignInWithMagicLinkTask.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/ClientBehaviorTests/SignIn/AWSAuthConfirmSignInWithMagicLinkTaskTests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/ClientBehaviorTests/SignIn/AWSAuthConfirmSignInWithOTPTaskTests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/ClientBehaviorTests/SignIn/AWSAuthSignInPluginTests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/ClientBehaviorTests/SignIn/AWSAuthSignInWithMagicLinkTaskTests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/TaskTests/ClientBehaviorTests/SignIn/AWSAuthSignInWithOTPTaskTests.swift
=> feat(Auth): Add passwordless unit tests

AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Sync/InitialSync/InitialSyncOperationTests.swift
=> test(datastore): add watchos checks to initialsync test cases for disableSubscriptions

Amplify/Categories/DataStore/Model/Internal/Model+DateFormatting.swift, Amplify/Categories/DataStore/Model/Temporal/Date.swift, Amplify/Categories/DataStore/Model/Temporal/DateTime.swift, Amplify/Categories/DataStore/Model/Temporal/SpecBasedDateConverting.swift, Amplify/Categories/DataStore/Model/Temporal/Temporal+Comparable.swift, Amplify/Categories/DataStore/Model/Temporal/Temporal.swift, Amplify/Categories/DataStore/Model/Temporal/TemporalOperation.swift, Amplify/Categories/DataStore/Model/Temporal/Time.swift, Amplify/Categories/DataStore/Model/Temporal/TimeZone+Extension.swift, AmplifyTests/CategoryTests/DataStore/TemporalTests.swift, AmplifyTests/CoreTests/Model+CodableTests.swift
https://github.com/aws-amplify/amplify-swift/issues/1175
- add timezone information while encoding/decoding `Temporal.DateTime` to `ISO8601` date string.
=> fix(datastore): store time zone info in Temporal.DateTime

Amplify/Categories/DataStore/Model/Internal/Model+Codable.swift, Amplify/Categories/DataStore/Model/Internal/Schema/ModelValueConverter.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Models/SQLModelValueConverterTests.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/MutationQueue/ProcessMutationErrorFromCloudOperationTests.swift, AmplifyTests/CoreTests/Model+CodableTests.swift
https://github.com/aws-amplify/amplify-swift/pull/3057
- configure json encoder with sorted key
=> fix(datastore): configure json encoder with sorted key

.github/workflows/closed_issue_message.yml
The `closed-issue-message` action added in https://github.com/aws-amplify/amplify-swift/pull/3374 doesn't have the necessary permissions to post a comment to an issue.
Example failure: https://github.com/aws-amplify/amplify-swift/actions/runs/7172825929/job/19530846804
This PR adds the `write` permission to the workflow to allow the action to carry out its duties.
This change mirrors the existing permissions used by other comment actions e.g. [new_issue_maintainer](https://github.com/aws-amplify/amplify-swift/blob/main/.github/workflows/new_issue_maintainer.yml#L7-L8)
=> chore: add necessary write permission to closed issue message actions workflow

AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/MutationSync/OutgoingMutationQueue/OutgoingMutationQueue.swift
https://github.com/aws-amplify/amplify-swift/issues/3325
The crash in the issue above points to OutgoingMutationQueue.swift:142
```swift
self.operationQueue.isSuspended = false
```
In this PR, we're addressing strong reference cycles in OutgoingMutationQueue by adding `weak self`. Calls to `Amplify.DataStore.stop()` will deintialize RemoteSyncEngine, which holds a single instance of the OutgoingMutationQueue. It's likely that OutgoingMutationQueue (`self`) is deallocated before one of the closures that have strong reference to `self` is executed. Then later, when it executes, it tries to access the deallocated `self` and crashes
=> fix(DataStore): Add 'weak self' to prevent retain cycles in OutgoingMutationQueue

AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Configuration/DataStoreConfiguration+Helper.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Core/DataStoreCategoryConfigurationTests.swift
`subscriptionsDisabled` was incorrectly setting `disableSubscriptions` to return false. This wasn't caught since the  developers tracking the original PR https://github.com/aws-amplify/amplify-swift/pull/3368 were using `.custom(disableSubscriptions)` as communicated to them. `subscriptionDisabled` is available as well and more targetted for customers that don't expect to change the `disableSubscriptions` return value.
=> fix(DataStore): watchOS subscription disabled configuration value

Amplify.xcodeproj/project.pbxproj, Amplify/Categories/DataStore/Model/Internal/Model+DateFormatting.swift, Amplify/Categories/DataStore/Model/Temporal/Date.swift, Amplify/Categories/DataStore/Model/Temporal/DateTime.swift, Amplify/Categories/DataStore/Model/Temporal/SpecBasedDateConverting.swift, Amplify/Categories/DataStore/Model/Temporal/Temporal+Comparable.swift, Amplify/Categories/DataStore/Model/Temporal/Temporal.swift, Amplify/Categories/DataStore/Model/Temporal/TemporalOperation.swift, Amplify/Categories/DataStore/Model/Temporal/Time.swift, Amplify/Categories/DataStore/Model/Temporal/TimeZone+Extension.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/Support/ModelCompareTests.swift, AmplifyTests/CategoryTests/DataStore/TemporalTests.swift, AmplifyTests/CoreTests/Model+CodableTests.swift
ported from https://github.com/aws-amplify/amplify-swift/pull/3393/
- store time zone info in Temporal.DateTime 
=> fix(datastore-v1): store time zone info in Temporal.DateTime

.git-blame-ignore-revs, .github/workflows/swiftlint.yml, .swiftlint.yml, AmplifySwiftXcode/AmplifySwiftXcode.xcodeproj/project.pbxproj
* Add .git-blame-ignore-revs file
* update SwiftLint configuration
* add SwiftLint GH Action
* add a convenience xcodeproj that includes swiftlint build phase script
=> chore: add swiftlint GH action

AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/MutationSync/OutgoingMutationQueue/OutgoingMutationQueue.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/MutationSync/OutgoingMutationQueue/SyncMutationToCloudOperation.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/Support/MutationEvent+Extensions.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Sync/Support/MutationEventExtensionsTests.swift
- rollback the logic for updating the version of pending mutation events in the queue upon receiving a mutation response from the remote server with the same model id.
- detect the mutation event version based on both latest synced metadata and existing mutation event's version.
=> fix(datastore): update pending mutation events version from mutation response

.github/workflows/issue_closed.yml
Remove "tag a team member" wording in closed issue visibility comment.
=> chore: clarify wording in closed issue visibility comment

AmplifyPlugins/Analytics/Sources/AWSPinpointAnalyticsPlugin/AWSPinpointAnalyticsPlugin+ClientBehavior.swift, AmplifyPlugins/Analytics/Tests/AWSPinpointAnalyticsPluginUnitTests/AWSPinpointAnalyticsPluginClientBehaviorTests.swift, AmplifyPlugins/Analytics/Tests/AnalyticsHostApp/AWSPinpointAnalyticsPluginIntegrationTests/AWSPinpointAnalyticsPluginIntegrationTests.swift, AmplifyPlugins/Internal/Sources/InternalAWSPinpoint/Endpoint/EndpointClient.swift, AmplifyPlugins/Internal/Sources/InternalAWSPinpoint/Endpoint/PinpointEndpointProfile.swift, AmplifyPlugins/Internal/Tests/InternalAWSPinpointUnitTests/EndpointClientTests.swift, AmplifyPlugins/Notifications/Push/Sources/AWSPinpointPushNotificationsPlugin/AWSPinpointPushNotificationsPlugin+ClientBehaviour.swift, AmplifyPlugins/Notifications/Push/Tests/AWSPinpointPushNotificationsPluginUnitTests/AWSPinpointPushNotificationsPluginClientBehaviourTests.swift, AmplifyPlugins/Notifications/Push/Tests/AWSPinpointPushNotificationsPluginUnitTests/Mocks/MockAWSPinpoint.swift
- https://github.com/aws-amplify/amplify-swift/issues/3439
This PR makes the `PinpointEndpointProfile` a `struct` to prevent race conditions crashes when two different `identifyUser` invocations attempt to modify it.
- [PushNotifications](https://github.com/aws-amplify/amplify-swift/actions/runs/7450866796)
- [Analytics](https://github.com/aws-amplify/amplify-swift/actions/runs/7451233515)
=> fix(Analytics): Making PinpointEndpointProfile thread safe.

.github/composite_actions/get_platform_parameters/action.yml, .github/workflows/build_amplify_swift.yml, .github/workflows/build_minimum_supported_swift_platforms.yml
- add action workflow for building package with minimum supported sdk version
- when commit is pushing to `main` branch
- also can dispatch on any branch manually
=> ci: add action workflow for ensuring minimum sdk version support

.github/composite_actions/get_platform_parameters/action.yml, .github/composite_actions/run_xcodebuild_test/action.yml, .github/workflows/build_amplify_swift.yml, .github/workflows/build_minimum_supported_swift_platforms.yml, .github/workflows/integ_test_analytics.yml, .github/workflows/integ_test_api_functional.yml, .github/workflows/integ_test_api_graphql_auth_directive.yml, .github/workflows/integ_test_api_graphql_iam.yml, .github/workflows/integ_test_api_graphql_lambda_auth.yml, .github/workflows/integ_test_api_graphql_lazy_load.yml, .github/workflows/integ_test_api_graphql_user_pool.yml, .github/workflows/integ_test_api_rest_iam.yml, .github/workflows/integ_test_api_rest_user_pool.yml, .github/workflows/integ_test_auth.yml, .github/workflows/integ_test_datastore_auth_cognito.yml, .github/workflows/integ_test_datastore_auth_iam.yml, .github/workflows/integ_test_datastore_base.yml, .github/workflows/integ_test_datastore_cpk.yml, .github/workflows/integ_test_datastore_lazy_load.yml, .github/workflows/integ_test_datastore_multi_auth.yml, .github/workflows/integ_test_datastore_v2.yml, .github/workflows/integ_test_geo.yml, .github/workflows/integ_test_logging.yml, .github/workflows/integ_test_predictions.yml, .github/workflows/integ_test_push_notifications.yml, .github/workflows/integ_test_storage.yml, .github/workflows/run_integration_tests.yml, .github/workflows/run_unit_tests.yml, .github/workflows/run_unit_tests_platforms.yml, .github/workflows/stress_test.yml
- add alias `latest` and `minimum` to represent xcode cmd tool version
- `latest` is xcode 14.3.1
- `minimum` is xcode 14.0.1
=> ci: use alias latest and minimum to represent xcode cmd tool version

.github/workflows/stress_test.yml
There is an issue to use `get_platform_parameters` composite action in stress test workflow.
Related action workflows:
- https://github.com/aws-amplify/amplify-swift/actions/runs/7494183065/job/20401536288
- https://github.com/aws-amplify/amplify-swift/actions/runs/7507029707/job/20439736522
The problem was resolved by combining the outputs of the get-platform-build-params and prepare-for-test jobs, and exporting the results from the get-platform-build-params job separately.
=> ci: fix stress test workflow

Amplify/Categories/API/Response/GraphQLError.swift, AmplifyPlugins/Core/AWSPluginsCore/Sync/PaginatedList.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Sync/PaginatedListTests.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/InitialSync/InitialSyncOperation.swift
https://github.com/aws-amplify/amplify-swift/issues/3259
- decoding the `PaginatedList` optimistically
=> fix(datastore): decode optimistically with paginated list response type

Amplify/Categories/API/Response/GraphQLError.swift, AmplifyPlugins/Core/AWSPluginsCore/Sync/PaginatedList.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Sync/PaginatedListTests.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/InitialSync/InitialSyncOperation.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/MutationSync/OutgoingMutationQueue/SyncMutationToCloudOperation.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/RequestRetryablePolicy.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Sync/RequestRetryablePolicyTests.swift
https://github.com/aws-amplify/amplify-swift/issues/3259
This PR combines the the three PRs below:
https://github.com/aws-amplify/amplify-swift/pull/3474
https://github.com/aws-amplify/amplify-swift/pull/3475
https://github.com/aws-amplify/amplify-swift/pull/3477
=> fix(datastore): fix syncQuery for partial success-error responses and update retry mechanism for error codes

.github/workflows/build_minimum_supported_swift_platforms.yml
- disable minimum build workflow on main branch
=> fix(ci): disable minimum build workflow on main branch

AmplifyPlugins/API/Sources/AWSAPIPlugin/Configuration/AWSAPIEndpointInterceptors.swift, AmplifyPlugins/API/Sources/AWSAPIPlugin/Interceptor/RequestInterceptor/AuthTokenURLRequestInterceptor.swift, AmplifyPlugins/API/Tests/AWSAPIPluginTests/Configuration/AWSAPIEndpointInterceptorsTests.swift, AmplifyPlugins/API/Tests/AWSAPIPluginTests/Interceptor/AuthTokenURLRequestInterceptorTests.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/MutationSync/OutgoingMutationQueue/SyncMutationToCloudOperation.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Sync/MutationQueue/SyncMutationToCloudOperationTests.swift
Continuation from https://github.com/aws-amplify/amplify-swift/issues/3259#issuecomment-1910524131
This PR is a change in DataStore's SyncMutationToCloudOperation to determine whether mutation events are retryable.
1. A mutation event is deemed retryable when the underlying auth error is `AuthError.signedOut`. If the user is signed out, we could not attempt the request and therefore, should be retried. 
2. A mutation event should be retried on session expired. Changes to API plugin returns `API.operationError` with underlying `AuthError.sessionExpired` when the token is expired. If authService provides APIPlugin with an expired token, it will fail fast during the request interception, and pass this error back. No additional changes necessary needed in DataStore since it is already …
=> fix(DataStore): retry MutationEvents on signed-out and token expired errors

AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/StorageEngine+SyncRequirement.swift, AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginTests/Sync/StorageEngineSyncRequirementsTests.swift
https://github.com/aws-amplify/amplify-flutter/issues/3967
https://github.com/aws-amplify/amplify-flutter/issues/3967#issuecomment-1875988560
This is a port of https://github.com/aws-amplify/amplify-swift/pull/3453
=> fix(DataStore-v1): auth plugin requirement for single auth rule

AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Storage/StorageEngine+SyncRequirement.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Sync/StorageEngineSyncRequirementsTests.swift
https://github.com/aws-amplify/amplify-flutter/issues/3967
https://github.com/aws-amplify/amplify-flutter/issues/3967#issuecomment-1875988560
The auth mode strategy and the auth rules are used in determination of whether the auth plugin is required for DataStore. Some common scenarios are
- No auth rules on the models does not require auth plugin
- Single auth rule on a model should make its determination based on the provider. 
- OIDC/lambda - does not require auth plugin, but requires auth provider on the APIPLugin
- APIKey - does not require auth plugin, the key is the configuration of the APIPlugin.
- UserPools/IAM - requires auth plugin
- Multi-Auth rules with multi-auth enabled, require auth plugin if any of the rules requires auth plugin.
The issue in …
=> fix(DataStore): auth plugin requirement for single auth rule

AmplifyPlugins/Logging/Sources/AWSCloudWatchLoggingPlugin/Configuration/DefaultRemoteLoggingConstraintsProvider.swift
Update the Logging remote constraint provider to fetch the configuration and look up the `ETag` in the response header.  `If-None-Match` should only be in the request header not the response header, keeping this logic in so that it is not a breaking change to existing customers.
=> chore(logging): update logging remote constraint ETag caching

AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Storage/CascadeDeleteOperation.swift
https://github.com/aws-amplify/amplify-swift/issues/3499
This PR fixes build in Xcode 15.3 beta 2 when Amplify package is used in a project.
=> fix(build): update code to fix build in xcode 15.3 beta 2

AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/Attempt.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Support/Internal/AttemptTests.swift
https://github.com/aws-amplify/amplify-swift/issues/3499
This PR fixes build in Xcode 15.3 beta 2 build.
=> fix(build): build fix for xcode 15.3 beta 2

AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/SubscriptionSync/IncomingAsyncSubscriptionEventPublisher.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Sync/SubscriptionSync/IncomingAsyncSubscriptionEventPublisherTests.swift
https://github.com/aws-amplify/amplify-swift/issues/2982#issuecomment-1671713659
Before the PR changes, the publisher would emit events concurrently which caused some of them to be missed by the subscriber even though the subscriber applied back pressure to process one event at a time (demand of `max(1)`). For more details regarding back-pressure, see https://developer.apple.com/documentation/combine/processing-published-elements-with-subscribers
The change, to publish the events though the same TaskQueue ensures that the events are properly buffered and sent only when the subscriber demands for it.
=> fix(DataStore): serialize IncomingAsyncSubscriptionEventPublisher events

.github/workflows/integ_test.yml, .github/workflows/nightly_repeated_unittest.yml, .github/workflows/run_unit_tests.yml, .github/workflows/run_unit_tests_platforms.yml, AmplifyPlugins/API/Tests/APIHostApp/APIHostApp.xcodeproj/project.pbxproj
This PR fixes the following:
- The API Integration Tests not being able to run with the latest dependencies cache. This was caused because the `APIHostApp` project's **CwlPreconditionTesting** dependency was set to "Up to next minor", while the `Amplify-Package` target that caches dependencies has it as "Up to next major". 
- The "Amplify Nightly Repeated Unit Tests" workflow not being able to run. This happened because the reused workflow changed its parameters and it wasn't updated in the nightly workflow, so I've added a new `test_iterations_flags` that can be set accordingly but defaults to the existing behaviour.
- Renamed the "Integration Tests" workflow to "Integration Test (Except DataStore & API)" to prevent confusion. 
- We still cannot group all the integration tests in just …
=> chore: Fixing workflows

AmplifyPlugins/Core/AWSPluginsCore/Auth/AWSAuthModeStrategy.swift, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/MutationSync/OutgoingMutationQueue/SyncMutationToCloudOperation.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Sync/MutationQueue/SyncMutationToCloudOperationTests.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Sync/Support/AWSAuthorizationTypeIteratorTests.swift
#3511 
When server respond with 401 error on request mutation, DataStore will try to retry this request endlessly.
=> fix(DataStore): endless retry of mutation request when server responds with 401 error code (#3511)

Amplify/Resources/PrivacyInfo.xcprivacy, AmplifyPlugins/API/Sources/AWSAPIPlugin/Resources/PrivacyInfo.xcprivacy, AmplifyPlugins/Analytics/Sources/AWSPinpointAnalyticsPlugin/Resources/PrivacyInfo.xcprivacy, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Resources/PrivacyInfo.xcprivacy, AmplifyPlugins/Core/AWSPluginsCore/Resources/PrivacyInfo.xcprivacy, AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Resources/PrivacyInfo.xcprivacy, AmplifyPlugins/Geo/Sources/AWSLocationGeoPlugin/Resources/PrivacyInfo.xcprivacy, AmplifyPlugins/Internal/Sources/InternalAWSPinpoint/Resources/PrivacyInfo.xcprivacy, AmplifyPlugins/Logging/Sources/AWSCloudWatchLoggingPlugin/Resources/PrivacyInfo.xcprivacy, AmplifyPlugins/Notifications/Push/Sources/AWSPinpointPushNotificationsPlugin/Resources/PrivacyInfo.xcprivacy, AmplifyPlugins/Predictions/AWSPredictionsPlugin/Resources/PrivacyInfo.xcprivacy, AmplifyPlugins/Predictions/CoreMLPredictionsPlugin/Resources/PrivacyInfo.xcprivacy, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Resources/PrivacyInfo.xcprivacy
Docs Update required for this change: https://github.com/aws-amplify/docs/pull/6938
Customer issue related to missing key in privacy manfiest: https://github.com/aws-amplify/amplify-swift/issues/3552
This PR adds the data collected section in the privacy manifests. In each target are the following reasons
- **Amplify**: no corresponding AWS service, no data is collected
- **AWSAPIPlugin** - adds Amplify's user-agent to AppSync / APIGateway requests
- **AWSPinpointAnalyticsPlugin** - adds Amplify's user-agent to Amazon Pinpoint requests
- **AWSCognitoAuthPlugin** - adds Amplify's user-agent to Cognito requests
- **AWSPluginsCore** - no corresponding AWS service, no data is collected
- **AWSDataStorePlugin** - Makes calls through AWSAPIPlugin, thus it's privacy manifest is reflected by …
=> fix: add collected data types to privacy manifests

AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/Service/FaceLivenessSession.swift, AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/Service/FaceLivenessSessionRepresentable.swift
Some customer Liveness sessions using the Amplify iOS SDK fail midway through the session with the error:
```
InvalidSignatureException: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
```
Video and client events over the web socket from different threads. If a video and client event are sent at identical time, prior signatures may get mixed up, causing an invalid signature event. This PR introduces a change to use a serial dispatch queue to send web socket events.
Manual testing done on the `HostApp` in the `amplify-ui-swift-liveness` repo.
=> fix(predictions): Serialize the dispatch of web socket events

AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/SubscriptionSync/ReconcileAndLocalSave/RemoteSyncReconciler.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Sync/SubscriptionSync/RemoteSyncReconcilerTests.swift
=> fix(DataStore): created and deleted model on one device appears as created on the other

AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/StoragePath+Extensions.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Operation/AWSS3StorageDownloadFileOperationTests.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Operation/AWSS3StorageGetDataOperationTests.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Operation/AWSS3StoragePutDataOperationTests.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Operation/AWSS3StorageUploadFileOperationTests.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Tasks/AWSS3StorageGetURLTaskTests.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Tasks/AWSS3StorageListObjectsTaskTests.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Tasks/AWSS3StorageRemoveTaskTests.swift
* Update `StoragePath` validation rule to not allow leading `/` in the path
* Update related unit tests based on the new validation rule change
=> chore(storage): update storage path validation rule

AmplifyPlugins/API/Sources/AWSAPIPlugin/SubscriptionFactory/AppSyncRealTimeClientFactory.swift, AmplifyPlugins/API/Sources/AWSAPIPlugin/Support/Constants/URLRequestConstants.swift, AmplifyPlugins/API/Tests/APIHostApp/AWSAPIPluginFunctionalTests/AppSyncRealTimeClientTests.swift, AmplifyPlugins/Core/AWSPluginsCore/WebSocket/WebSocketClient.swift
- add library `user-agent` value for appsync handshake request
=> fix(api): add user-agent header to appsync websocket handshake request

AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/StoragePath+Extensions.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Operation/AWSS3StorageDownloadFileOperationTests.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Operation/AWSS3StorageGetDataOperationTests.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Operation/AWSS3StoragePutDataOperationTests.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Operation/AWSS3StorageUploadFileOperationTests.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Tasks/AWSS3StorageGetURLTaskTests.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Tasks/AWSS3StorageListObjectsTaskTests.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Tasks/AWSS3StorageRemoveTaskTests.swift
* Update `StoragePath` validation for empty/white spaces in the path and throw a validation exception
=> chore(storage): update storage path validation to include empty/whitespace

AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Storage/StorageEngine.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Storage/StorageEngineTestsHasOne.swift
- https://github.com/aws-amplify/amplify-swift/issues/3595
Setting a predicate on a `save` operation with a model that does not exist is not supported. The `StorageEngine` performs this validation and reports a failure to the completion handler if attempted. However, the execution is not interrupted and then `StorageAdapter` is still invoked, which also fails and also reports a failure.
This results in the plugin's `continuation` being resumed twice, which results in a crash with `SWIFT TASK CONTINUATION MISUSE`.
The fix is simple, we're just missing a `return` statement in the initial validation after we invoke the completion callback.
- DataStore: https://github.com/aws-amplify/amplify-swift/actions/runs/8602460009
By submitting this pull request, I confirm that my contribution is made …
=> fix(DataStore): Fixing a crash when attempting to create a model with a predicate

AmplifyPlugins/API/Sources/AWSAPIPlugin/Operation/AWSGraphQLSubscriptionTaskRunner.swift, AmplifyPlugins/API/Sources/AWSAPIPlugin/Support/Utils/Array+Error+TypeCast.swift, AmplifyPlugins/API/Tests/AWSAPIPluginTests/Support/Utils/Array+Error+TypeCastTests.swift
Swift Collection type casting is introduced in `Swift 5.8`. As our library is still supporting `Swift 5.7`, adding backward compatibility support for collection casting.
=> fix(api): add collection type casting in swift 5.7

AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/StoragePath+Extensions.swift
Aligning `StoragePath` validation exception message with Amplify Android.
=> chore(storage): align storage validation exception message with Amplify Android

AmplifyPlugins/API/Sources/AWSAPIPlugin/Operation/AWSGraphQLSubscriptionTaskRunner.swift
Amplify fails to cancel/deallocate `AppSyncRealTimeSubscription` because `AWSGraphQLSubscriptionTaskRunner` gets released before it has a chance to tell `AppSyncRealTimeClient` to unsubscribe the subscription. 
If you keep cancelling and creating new subscriptions (for example when you minimize and open the app) at some point the number of active subscriptions reaches 100 and the app starts to crash.
edit: 
- this is reproducible in `2.29.1`
=> fix(api): AWSGraphQLSubscriptionTaskRunner failing to cancel AppSyncRealTimeSubscription

AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/Events/LivenessEvent.swift, AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/Events/LivenessFinalClientEvent.swift, AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/Events/LivenessFreshnessEvent.swift, AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/Events/LivenessInitialClientEvent.swift, AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/Model/DTOMapping.swift, AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/Model/FaceLivenessSession+SessionConfiguration.swift, AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/SPI/AWSPredictionsPlugin+Liveness.swift, AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/SPI/LivenessStreamingURL.swift, AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/Service/FaceLivenessSession.swift, AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/Service/FaceLivenessSessionRepresentable.swift, AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/ServiceModel/ClientChallenge.swift, AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/ServiceModel/ServerChallenge.swift
None
Add implementation for no light support
=> feat(predictions): add implementation for no light support

AmplifyPlugins/API/Sources/AWSAPIPlugin/AppSyncRealTimeClient/AppSyncRealTimeClient.swift, AmplifyPlugins/API/Sources/AWSAPIPlugin/Operation/AWSGraphQLSubscriptionTaskRunner.swift, AmplifyPlugins/API/Tests/APIHostApp/AWSAPIPluginFunctionalTests/GraphQLModelBasedTests.swift
This PR addresses a similar issue to PR #3615, it fixes the `AWSGraphQLSubscriptionOperation` to ensure that the unsubscribe method is called during the cancellation of the operation. Additionally, an integration test case has been added to verify that subscriptions are properly unsubscribed and removed from the AppSyncRealTimeClient.
=> fix(API): make sure unsubscribe is invoked when subscription cancelled

AmplifyPlugins/API/Sources/AWSAPIPlugin/AWSAPIPlugin.swift, AmplifyPlugins/API/Sources/AWSAPIPlugin/Configuration/AWSAPICategoryPluginConfiguration.swift, AmplifyPlugins/API/Tests/AWSAPIPluginTests/AWSAPICategoryPlugin+ConfigureTests.swift
Android change https://github.com/aws-amplify/amplify-android/pull/2791
Gen2 doesn't have a concept of API names when using `defineData` for the data category configuration. We are hardcoding a default name for customers to use for use cases where the name is required. For example, adding a custom interceptor:
```swift
struct CustomInterceptor: URLRequestInterceptor {
func intercept(_ request: URLRequest) throws -> URLRequest {
var request = request
request.setValue("headerValue", forHTTPHeaderField: "headerKey")
return request
}
}
let apiPlugin = try AWSAPIPlugin()
try Amplify.addPlugin(apiPlugin)
try Amplify.configure()
try apiPlugin.add(interceptor: CustomInterceptor(), for: AWSAPIPlugin.defaultGraphQLAPI)
```
The global name is 
```swift
public class AWSAPIPlugin {
public static let …
```
=> feat(api): Expose a constant for the API name used by Gen2 data category

AmplifyPlugins/Storage/Tests/StorageHostApp/copy_configuration.sh
This fixes the copy configuration script, which was modified to copy the outputs file. but replaced the previous `amplifyconfiguration.json` instead of it being an addition
The change that introduced the issue https://github.com/aws-amplify/amplify-swift/pull/3567/files#diff-afbd7f754fa78d6674c0136cafca4f962448f9cea32199a51f5e354694dfb75d
=> test(storage): fix copy_configuration script

AmplifyPlugins/Storage/Tests/StorageHostApp/copy_configuration.sh
We require both files to be present, which is why the `else` block exists now to touch the file. The exit after copying the `amplifyconfiguration.json` cause it to finish and not run the block that copies/touch the `amplify_outputs.json` file
=> test(storage): fix copy_configuration script early exit

AmplifyPlugins/Storage/Tests/StorageHostApp/copy_configuration.sh
For the stress test workflow, we have not yet updated this to run against amplify_outputs config. However the test exits after it copies the configuration file. The script is written in a way that it looks like either only `AWSAmplifyStressTests-amplifyconfiguration.json` exists or `AWSS3StoragePluginTests-amplifyconfiguration.json` but not both. One easy fix here is to touch the outputs file when running in the context of the stress test (when `AWSAmplifyStressTests-amplifyconfiguration.json` exists)
=> test(storage): fix copy_configuration script for stress test

.github/workflows/canary.yml, .github/workflows/deploy_package.yml, .github/workflows/deploy_release.yml, .github/workflows/deploy_unstable.yml, .github/workflows/release_doc.yml
The release workflow failed when installing ruby on macos-latest (macos-14)
https://github.com/aws-amplify/amplify-swift/actions/runs/8843689240/job/24299009047
```
Error: The current runner (macos--arm64) was detected as self-hosted because the platform does not match a GitHub-hosted runner image (or that image is deprecated and no longer supported).
```
Related issue https://github.com/ruby/setup-ruby/issues/568 fixed in 1.171.0 https://github.com/ruby/setup-ruby/issues/568#issuecomment-1919283320 
This [test workflow](https://github.com/aws-amplify/amplify-swift/actions/runs/8835798609/job/24260846301) uses 1.171.0 and installs successfully. 
This PR does not update the canary workflow since it's not using macos-14, does not have the problem.
By submitting this pull request, I confirm …
=> chore: update set-up ruby 1.171.0

AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/AWSS3StoragePlugin+Configure.swift
During AWSS3StoragePlugin's `configure()`, it will validate the `defaultAccessLevel` value from the JSONValue configuration (amplifyconfiguration.json). This was previously done first before creating an `AWSS3StorageService`. When the Gen2 configuration logic was added, the refactoring resulted in a flipped sequence; create the `AWSS3StorageService` and then validate the `defaultAccessLevel`. This is an issue when the `defaultAccessLevel` is invalid and it throws an error after an instance of `AWSS3StorageService` has been created.
The issue:
1. `Amplify.configure()` with an invalid `defaultAccessLevel`. Internally it will create the `AWSS3StorageService`, and then throw.
2. The next test will call `Amplify.reset()`. It will do nothing since `storageService: AWS3StorageService` was never …
=> fix(storage): retrieve accesslevel before storage service

.github/composite_actions/get_platform_parameters/action.yml, .github/workflows/build_amplify_swift_platforms.yml, .github/workflows/build_minimum_supported_swift_platforms.yml, .github/workflows/build_scheme.yml, .swiftpm/xcode/xcshareddata/xcschemes/Amplify-Build.xcscheme
This PR fixes the `build_minimum_supported_swift_platforms.yml` workflow so that we build each platform for the minimum supported Xcode version on each PR and push to the `main` branch:
- For iOS and macOS, the minimum supported Xcode version is 14.1.
- For watchOS and tvOS, the minimum supported Xcode version is 14.3 We're using **14.3.1** as that is the one available in the [macos-13 GitHub runner](https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md#xcode).
Summary of changes:
- Creating a new target called `Amplify-Build` that only includes the Amplify plugins and no tests.
- Renaming `build-amplify-package` to `build-scheme` and making the scheme an argument
- Removing `continue-on-error` on the build step, as otherwise the workflow would report a …
=> chore: Adding workflow to build Amplify for minimum Xcode

AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Helpers/ConfigurationHelper.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/Support/ConfigurationHelperTests.swift
The JSON configuration expected by the Authenticator does not include the `"auth.plugin.awsCognitoAuthPlugin"` levels, so I'm removing them.
Also removing an unnecessary `try` that generated an Xcode warning. 
=> fix(Auth): Fixing the Gen2 json configuration used by the Authenticator

.github/workflows/unit_test.yml
This PR updates the unit test workflow to determine whether to gather and report coverage based on the value of a repository variable.
This allows us to enable/disable it without having to edit the files.
=> chore: Control coverage reporting through a repository variable

Amplify/Core/Configuration/AmplifyOutputsData.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Helpers/ConfigurationHelper.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/Support/ConfigurationHelperTests.swift
Related Android change https://github.com/aws-amplify/amplify-android/pull/2785
Schema https://github.com/aws-amplify/amplify-backend/blob/main/packages/client-config/src/client-config-schema/schema_v1.json#L102C1-L105C15
Backend reverted `cognitoDomain` and `customDomain` back to  `domain`.
=> fix(auth): gen2 config oauth domain

AmplifyPlugins/Storage/Tests/StorageHostApp/AWSS3StoragePluginIntegrationTests/AWSS3StoragePluginAccessLevelTests.swift, AmplifyPlugins/Storage/Tests/StorageHostApp/AWSS3StoragePluginIntegrationTests/AWSS3StoragePluginTestBase.swift, AmplifyPlugins/Storage/Tests/StorageHostApp/AWSS3StoragePluginIntegrationTests/AWSS3StoragePluginUploadMetadataTestCase.swift, AmplifyPlugins/Storage/Tests/StorageHostApp/AWSS3StoragePluginIntegrationTests/README.md
This mostly reverts some changes that were applied in the original config PR https://github.com/aws-amplify/amplify-swift/pull/3567
The provisioning steps were updated to use username as the username rather than email. So the test code that pivot on username or email is no longer needed (code that was added during the config PR). The same code works with both Gen1 and Gen2 provisioned backends.
=> test(storage): gen2 integ tests

AmplifyPlugins/Core/AWSPluginsCore/WebSocket/WebSocketClient.swift
In Swift, even if you declare an inner closure with a weak reference to self, the outer closure still has a strong reference to self, which can cause the strong reference cycle.
ref: https://github.com/apple/swift/issues/72391
=> fix(core): potential memory leak in WebSocketClient

AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/SPI/AWSPredictionsPlugin+Liveness.swift, AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/SPI/LivenessStreamingURL.swift, AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/Service/Challenge.swift, AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/Service/FaceLivenessSession.swift, AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/Service/FaceLivenessSessionRepresentable.swift, AmplifyPlugins/Predictions/Tests/AWSPredictionsPluginUnitTests/LivenessTests/LivenessChallengeTests.swift, AmplifyPlugins/Predictions/Tests/AWSPredictionsPluginUnitTests/LivenessTests/LivenessDecodingTests.swift
None 
Add unit tests and attempt count changes
=> chore(predictions): add attempt count changes and unit tests

AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/AWSAuthBaseTest.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/AuthDeleteUserTests/AuthDeleteUserTests.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/MFATests/TOTPSetupWhenAuthenticatedTests.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/MFATests/TOTPSetupWhenUnauthenticatedTests.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/README.md, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/ResetPasswordTests/AuthConfirmResetPasswordTests.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/ResetPasswordTests/AuthResetPasswordTests.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/SignInTests/AuthSRPSignInTests.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/SignUpTests/AuthConfirmSignUpTests.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/SignUpTests/AuthResendSignUpCodeTests.swift
- Updating Backend CDK code
- UserAttributes tests do not require verifying the email attribute. Although this isn't recommended, we are disabling this to be able to verify updating attributes in the integration test without having to confirm the code set to the email.
- Enabling device tracking
- Add additional steps for TOTP tests that require separate backend
- Update commands to latest
- Fix some test failure case assertions based on "Prevent user existence errors" enabled (this is recommended and Gen2 enables this by default). 
=> test(auth): gen2 integ tests

.github/workflows/deploy_package.yml, .github/workflows/deploy_release.yml, .github/workflows/deploy_unstable.yml
Reusable workflows don't have access to secrets unless they are explicitly inherited, which caused the coverage during release workflows to not work.
=> chore: fixing coverage token not accessible on releases [skip ci]

AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/InitialSync/ModelSyncedEventEmitter.swift
#3510 
- capturing `self` with weak reference in filter operator.
=> fix(datastore): memory leak in ModelSyncedEventEmitter

.github/CODEOWNERS
N/A
- Updates CODEOWNERS file to require admin approval for changing CODEOWNERS file (`/.github/CODEOWNERS`).
- Updates CODEOWNERS file to require admin approval for changing Xcode / OS runtime versions in CI/CD (`/.github/composite_actions/get_platform_parameters/action.yml`).
=> chore: require admin approval for codeowners and CI/CD versions

AmplifyPlugins/Logging/Tests/AWSCloudWatchLoggingPluginHostApp/AWSCloudWatchLoggingPluginIntegrationTests/AWSCloudWatchLoggingPluginGen2IntegrationTests.xctestplan, AmplifyPlugins/Logging/Tests/AWSCloudWatchLoggingPluginHostApp/AWSCloudWatchLoggingPluginIntegrationTests/AWSCloudWatchLoggingPluginIntegrationTests.swift, AmplifyPlugins/Logging/Tests/AWSCloudWatchLoggingPluginHostApp/AWSCloudWatchLoggingPluginIntegrationTests/README.md
- Add example of the logging config file (default to Verbose log level for the test to pass)
- Add CDK code of the provisioning for Gen2 backend
- fix configuration file naming and enable the rest of the logging integ tests
=> test(logging): gen2 integ tests

AmplifyPlugins/Auth/Tests/AuthHostedUIApp/AuthHostedUIAppUITests/Screen/SignInScreen.swift
There are some differences in how the auth with hostedUI was provisioned, compared to the latest steps in the README.md. The latest Gen1 and Gen2 provisioning resulted in a HostedUI webview that has "Email" as the textfield for the username input. We can either
1. Update Gen2 provisioning steps that results in the HostedUI view with Username as the textfield (unsure of how to do this).
2. Update Gen1 provisioning steps in the README.md that results in a HostedUI view that has Email as the text field. (this was done already in the README.md). And reprovision the Gen1 backend in the integration test account to apply these changes.
Since we have not yet reprovisioned the Gen1 backend, the integration tests are failing. This PR reverts the change to check for the Email textfield only for …
=> test(auth): fix Gen1 hostedUI textfield check

AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/Service/FaceLivenessSession.swift
Some customer Liveness sessions using the Amplify iOS SDK fail midway through the session with the error:
```
InvalidSignatureException: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
```
=> fix(predictions): update liveness websocket send event to be synchronous

AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/Service/FaceLivenessSession.swift
=> chore(predictions): update liveness websocket queue QoS

AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/SubscriptionSync/ReconcileAndLocalSave/ReconcileAndLocalSaveOperation.swift, AmplifyPlugins/DataStore/Tests/AWSDataStorePluginTests/Sync/SubscriptionSync/ReconcileAndLocalSaveOperationTests.swift
https://github.com/aws-amplify/amplify-swift/pull/2684
As we introduce lazy loading support in Datastore v2, the observe API requires the model instance in the stream to have accurate information for data related to lazy loading. However, the syncReceived hub event should still propagate the mutation event data from AppSync, which includes metadata such as `_version`, `_deleted`, and `_lastChangedAt`.
=> fix(datastore): propagate remote mutationEvents to Hub for sync received

AmplifyPlugins/API/Sources/AWSAPIPlugin/Core/AppSyncListDecoder.swift, AmplifyPlugins/API/Sources/AWSAPIPlugin/Core/AppSyncListPayload.swift, AmplifyPlugins/API/Sources/AWSAPIPlugin/Core/AppSyncListProvider.swift, AmplifyPlugins/API/Sources/AWSAPIPlugin/Core/AppSyncListResponse.swift, AmplifyPlugins/API/Sources/AWSAPIPlugin/Core/AppSyncModelDecoder.swift, AmplifyPlugins/API/Sources/AWSAPIPlugin/Core/AppSyncModelMetadata.swift, AmplifyPlugins/API/Sources/AWSAPIPlugin/Core/AppSyncModelProvider.swift, AmplifyPlugins/API/Sources/AWSAPIPlugin/Support/Decode/GraphQLResponseDecoder+DecodeData.swift, AmplifyPlugins/API/Sources/AWSAPIPlugin/Support/Utils/GraphQLRequest+toListQuery.swift, AmplifyPlugins/API/Tests/AWSAPIPluginTests/Core/AppSyncListDecoderTests.swift, AmplifyPlugins/API/Tests/AWSAPIPluginTests/Core/AppSyncListPayloadTests.swift, AmplifyPlugins/API/Tests/AWSAPIPluginTests/Core/AppSyncListProviderPaginationTests.swift, AmplifyPlugins/API/Tests/AWSAPIPluginTests/Core/AppSyncListProviderTests.swift, AmplifyPlugins/API/Tests/AWSAPIPluginTests/Core/AppSyncListResponseTests.swift, AmplifyPlugins/API/Tests/AWSAPIPluginTests/Core/AppSyncModelMetadataTests.swift, AmplifyPlugins/API/Tests/AWSAPIPluginTests/Support/Utils/GraphQLRequestToListQueryTests.swift, AmplifyPlugins/Core/AWSPluginsCore/Auth/AWSAuthorizationType.swift
https://github.com/aws-amplify/amplify-swift/issues/3677
Lazy Loading functionality is built on metadata passed to it during decoding. For example, the hasMany list will contain the parent's identifiers and the apiName to reconstruct the request when lazy loading. The belongsTo lazy model will contain its identifiers and the apiName used to when the child model was retrieved. 
The issue is with the new `authMode` parameter, the `authMode` was not being passed down to the lazy types (https://github.com/aws-amplify/amplify-swift/issues/3677#issuecomment-2108404457)
```swift
// default auth type is APIKey.
let message = try await Amplify.API.query(request: .get(Message.self, byId: id, authMode: .amazonCognitoUserPools)).get() // use userPool auth
let sender = try await message.sender  // …
```
=> fix(API): pass authMode used for lazy loading functionality

Package.swift, README.md
N/A
- Adds minimum supported Swift language version info in README.
=> chore: add swift version support blurb in readme

Amplify/Core/Support/AmplifyAsyncSequence.swift, Amplify/Core/Support/AmplifyAsyncThrowingSequence.swift, Amplify/Core/Support/TaskQueue.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/StateMachine/hierarchical-state-machine-swift/CancellableAsyncStream.swift
- use Swift 5.9 new API to create `AsyncStream` with contiuation, make code more predicatable
=> refactor: use makeStream for creating AsyncStream with continuation

AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/MutationSync/OutgoingMutationQueue/OutgoingMutationQueue.swift
- https://github.com/aws-amplify/amplify-swift/issues/3325
- https://github.com/aws-amplify/amplify-swift/issues/3467
- https://github.com/aws-amplify/amplify-swift/issues/3649
The crash reports indicate that a `SEGV_ACCERR` occurred due to an attempted dereference of a garbage pointer. In the implementation of the `OutgoingMutationQueue`, the `mutationDispatchQueue` was targeted to the concurrent global queue, with state transition actions being dispatched to this queue. This setup means that `starting` and `stopping` could trigger two state transite operations running concurrently. Specifically, the starting action needs to complete some I/O work, while the stopping action is cleaning up the operation queue, potentially causing a data race.
In this PR, we modified …
=> fix(datastore): change OutgoingMutationQueue use TaskQueue for state transitions

fastlane/Fastfile
During refactoring #3666 , we've moved file `AmplifyAWSServiceConfiguration.swift` from `AmplifyPluginsCore` to new package `InternalAmplifyCredential`. The new path for this file should be `AmplifyPlugins/Core/AmplifyCredentials/AmplifyAWSServiceConfiguration.swift`.
=> fix(ci): update unstable release file path in CI scripts

AmplifyPlugins/API/Sources/AWSAPIPlugin/AppSyncRealTimeClient/AppSyncRealTimeClient.swift
https://github.com/aws-amplify/amplify-swift/issues/3632
Currently, the `AppSyncRealTimeClient` disconnects the underlying websocket connection when it considers the connection stale. However, we need to maintain the connection for as long as possible. Therefore, change the action to reconnect.
=> fix(datastore): reconnect the AppSyncRealTimeClient once connection is stale

.swiftpm/xcode/xcshareddata/xcschemes/Amplify-Package.xcscheme
There are some unused, dangling modules appearing in the `Amplify-Package` target. These modules were renamed and should be removed from the `Amplify-Package` scheme.
=> chore: remove unused internal modules after renaming

Package.swift
- removing the `InternalAmplifyCredential` package, intended for internal use, from the products.
=> fix(core): remove InternalAmplifyCredentials from products

AmplifyPlugins/DataStore/Tests/DataStoreHostApp/AWSDataStorePluginIntegrationTests/DataStoreObserveQueryTests.swift
There are several flaky datastore integration tests related to the `observeQuery` API. The query snapshots are being observed multiple times within the test cases, whereas the assertion should only occur once.
This is expected behavior. During the test case setup, if a new record is created. The subsequent incoming mutation event from the AppSync server (with version 1) will be received, and a snapshot may be triggered by [the after-sync listener](https://github.com/aws-amplify/amplify-swift/blob/main/AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Subscribe/DataStoreObserveQueryOperation.swift#L248-L253).
=> test(datastore): fix broken datastore observeQuery integ tests

AmplifyTests/CoreTests/AmplifyPublisherTests.swift
Resolving compile error in Amplify Core unit tests when building with Xcode 16 beta 2.
=> chore: resolve build failure in Amplify Core unit test for Xcode 16 beta 2

Amplify/Categories/Storage/Operation/Request/StorageListRequest.swift, Amplify/Categories/Storage/Result/StorageListResult.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Service/Storage/AWSS3StorageService+ListBehavior.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/SubpathStategy+Delimiter.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Tasks/AWSS3StorageListObjectsTask.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/AWSS3StoragePluginAsyncBehaviorTests.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Tasks/AWSS3StorageListObjectsTaskTests.swift, AmplifyPlugins/Storage/Tests/StorageHostApp/AWSS3StoragePluginIntegrationTests/AWSS3StoragePluginListObjectsIntegrationTests.swift
This PR introduces the `subpathStrategy` parameter to `StorageListRequest.Options` and its corresponding `SubpathStrategy` enum type.
Using this field will affect the results included in the response:
- `subpathStrategy: .include`: Objects that are included in nested subpaths will be included in the response. **This is the default behaviour**
- `subpathStrategy: .exclude`: Objects that are included in nested subpaths are not included in the response, instead their subpaths are included in the `excludedSubpaths` list.
- `subpathStrategy: .exclude(delimitedBy:)`: Same as above, but it allows to set a custom character as delimiter for subpaths. The delimiter parameter defaults to `"/"`, which is the same as `.exclude`.
- https://github.com/aws-amplify/docs/pull/7831
By submitting this pull …
=> feat(Storage): Adding subpath strategy to the List operation

Gemfile, Gemfile.lock, api-dump/AWSDataStorePlugin.json, api-dump/AWSPluginsCore.json, api-dump/CoreMLPredictionsPlugin.json
This PR uses Xcodeproj's latest [main commit](https://github.com/CocoaPods/Xcodeproj/commit/fe55cf57badef2ca27fb9d4f801d9b834de1f871) so that its dependency to `rexml` can be upgraded.
We're doing this temporary until they release a proper new version, at which point we will point to that one.
=> chore: Temporary using xcodeproj's commit that bumps rexml

Gemfile.lock, canaries/example/Gemfile.lock
https://github.com/aws-amplify/amplify-swift/security/dependabot/13
https://github.com/aws-amplify/amplify-swift/security/dependabot/14
Upgrade CI dependency gem `rexml` to `>= 3.3.3`
=> chore(ci): upgrade dependency rexml version to 3.3.3

.github/workflows/issue_closed.yml
=> chore: Fix issue closed Action

Amplify/Categories/Storage/Operation/Request/StorageDownloadDataRequest.swift, Amplify/Categories/Storage/Operation/Request/StorageDownloadFileRequest.swift, Amplify/Categories/Storage/Operation/Request/StorageGetURLRequest.swift, Amplify/Categories/Storage/Operation/Request/StorageListRequest.swift, Amplify/Categories/Storage/Operation/Request/StorageRemoveRequest.swift, Amplify/Categories/Storage/Operation/Request/StorageUploadDataRequest.swift, Amplify/Categories/Storage/Operation/Request/StorageUploadFileRequest.swift, Amplify/Categories/Storage/StorageBucket.swift, api-dump/AWSDataStorePlugin.json, api-dump/AWSPluginsCore.json, api-dump/CoreMLPredictionsPlugin.json
This PR adds the new `StorageBucket` protocol and its default implementations.
It also adds an optional `bucket: StorageBucket` parameter to the existing Request.Options enums.
=> feat(Storage): Adding StorageBucket

Amplify/Core/Configuration/AmplifyOutputsData.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/AWSS3StoragePlugin+AsyncClientBehavior.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/AWSS3StoragePlugin+ClientBehavior.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/AWSS3StoragePlugin+Configure.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/AWSS3StoragePlugin+Reset.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/AWSS3StoragePlugin+StorageBucket.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/AWSS3StoragePlugin.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Operation/AWSS3StorageDownloadDataOperation.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Operation/AWSS3StorageDownloadFileOperation.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Operation/AWSS3StorageUploadDataOperation.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Operation/AWSS3StorageUploadFileOperation.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Service/Storage/AWSS3StorageService.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Service/Storage/AWSS3StorageServiceBehavior.swift, AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/StorageConfiguration.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/AWSS3StoragePluginResetTests.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/AWSS3StoragePluginTestBase.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/Support/Internal/AWSS3StorageOperations+StorageServiceProvider.swift, api-dump/AWSDataStorePlugin.json, api-dump/AWSPluginsCore.json, api-dump/CoreMLPredictionsPlugin.json
This PR makes the main changes in order to add support for multiple buckets to our existing **Storage** implementation.
The main changes are the following:
Added the new optional `buckets` array to the Storage configuration, plus a convenience initializer for testing purposes.
We have pretty much all of the service-related logic encapsulated inside the `AWSS3StorageServiceBehavior` protocol, which is implemented by `AWSS3StorageService`. This implementation, along its many related objects, heavily relies on the assumption of only one bucket and region.
To avoid a complete refactor, we will now have one storage service per bucket. S3 bucket names are globally unique, so we can store them in a dictionary using the bucket name as key for easy retrieval.
On plugin configuration we will only …
=> feat(Storage): Implementing support for multiple buckets

Amplify/Categories/Storage/StorageBucket.swift
This PR adds the `.fromOutputs(name:)` and `fromBucketInfo(_:)` factory extension methods to `Optiona<any StorageBucket>` as well.
This is desired because all public APIs that take a `bucket` have it as an optional parameter defaulting to nil. This meant that for customers there was no autocomplete suggestion when attempting to create the bucket:
**Before**:
**After**:
=> fix: Adding factory extensions for Optional StorageBucket

Amplify/Core/Configuration/AmplifyOutputsData.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/AWSCognitoAuthPlugin+AppSyncSigner.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/AWSCognitoAuthPluginAppSyncSignerTests.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthHostApp.xcodeproj/project.pbxproj, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/AppSyncSignerTests/AppSyncSignerTests.swift, AmplifyPlugins/Core/AWSPluginsCore/API/AWSAppSyncConfiguration.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/API/AWSAppSyncConfigurationTests.swift, AmplifyPlugins/Core/AmplifyCredentials/AmplifyAWSCredentialsProvider.swift, api-dump/AWSDataStorePlugin.json, api-dump/AWSPluginsCore.json, api-dump/CoreMLPredictionsPlugin.json
This PR adds the following public APIs to facilitate connectivity with AppSync. 
**AppSync signer**
Extension on AWSCognitoAuthPlugin to provide a static method to sign AppSync requests. This API receives an URLRequest and returns a signed URLRequest. 
**AWSAppSync configuration**
A new type vended from AWSPluginsCore as AWSAppSyncConfiguration. This configuration has the functionality to read `amplify_outputs.json` similar to `Amplify.configure(with: amplifyOutputs)` and provide properties related to AppSync endpoint configuration such as region, endpoint, apiKey.
=> feat: Add AppSync components 

AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Tasks/AWSS3StorageListObjectsTask.swift, AmplifyPlugins/Storage/Tests/AWSS3StoragePluginTests/AWSS3StoragePluginStorageBucketTests.swift, AmplifyPlugins/Storage/Tests/StorageHostApp/AWSS3StoragePluginIntegrationTests/AWSS3StoragePluginMultipleBucketTests.swift, AmplifyPlugins/Storage/Tests/StorageHostApp/AWSS3StoragePluginIntegrationTests/AWSS3StoragePluginTestBase.swift, AmplifyPlugins/Storage/Tests/StorageHostApp/StorageHostApp.xcodeproj/project.pbxproj, AmplifyPlugins/Storage/Tests/StorageHostApp/StorageStressTests/StorageStressTests.swift, api-dump/AWSDataStorePlugin.json, api-dump/AWSPluginsCore.json, api-dump/CoreMLPredictionsPlugin.json
This PR adds both unit and integration tests for the multibucket support.
**⚠️ Note**: As part of this work I noticed we were not populating `StorageListResult.Item.size` when using Gen2's `list` API, so I've fixed that as well.
=> test(Storage): Adding unit and integration tests

Amplify/Categories/Storage/Operation/Request/StorageDownloadDataRequest.swift, Amplify/Categories/Storage/Operation/Request/StorageDownloadFileRequest.swift, Amplify/Categories/Storage/Operation/Request/StorageGetURLRequest.swift, Amplify/Categories/Storage/Operation/Request/StorageListRequest.swift, Amplify/Categories/Storage/Operation/Request/StorageRemoveRequest.swift, Amplify/Categories/Storage/Operation/Request/StorageUploadDataRequest.swift, Amplify/Categories/Storage/Operation/Request/StorageUploadFileRequest.swift, Amplify/Categories/Storage/StorageBucket.swift
Adding a public extension on `Optional` is probably not a great idea, as we do not own that type.
So in order to provide better support for Xcode's suggestion, I've created initializers that take `some StorageBucket` and removed the `(any StorageBucket)? = nil` parameter.
Now all `Options` types will have an initializer that can take a `bucket: some StorageBucket` and one that doesn't take it, which internally defaults the property to `nil`.
I've also decided to ultimately exclude the `bucket` parameter from the old **deprecated** inits to discourage their usage: customers wanting to set `bucket` will need to use the new initializers (which support both Gen1 and Gen2 anyway).
--- 
As a side note, the reason why Xcode doesn't provide autocompletion when the parameter is defined as `any …
=> fix: Updating init parameters to some StorageBucket for autocompletion

Amplify/Categories/Storage/StorageCategory+ClientBehavior.swift
- https://github.com/aws-amplify/amplify-swift/issues/3860
When we introduced the new `path: StoragePath` parameters for the Storage APIs, we [deprecated the old ones using `key: String`](https://github.com/aws-amplify/amplify-swift/commit/0d13d9f3408f3e779899f7a0c3a15ffe6b57baff#diff-ffc8ecfb9d8e2abf8b86f9aeb48129d6b4404104be17a01c91b29bd00a528a2e). However, we only did so in the category protocol and not in the category implementation itself, which results in the warning not being propagated to the users because `Amplify.Storage` is not typed to the protocol, but rather to the actual implementation.
So in order to discourage the usage of these APIs and raise awareness of the new ones, I'm adding the deprecation annotations to the category as well. 
By submitting this pull request, I …
=> chore: Marking Storage's key-based API as deprecated in the Category implementation.

AmplifyPlugins/Notifications/Push/Sources/AWSPinpointPushNotificationsPlugin/AWSPinpointPushNotificationsPlugin+ClientBehaviour.swift, AmplifyPlugins/Notifications/Push/Sources/AWSPinpointPushNotificationsPlugin/AWSPinpointPushNotificationsPlugin+Configure.swift, AmplifyPlugins/Notifications/Push/Sources/AWSPinpointPushNotificationsPlugin/AWSPinpointPushNotificationsPlugin+Reset.swift, AmplifyPlugins/Notifications/Push/Sources/AWSPinpointPushNotificationsPlugin/AWSPinpointPushNotificationsPlugin+Types.swift, AmplifyPlugins/Notifications/Push/Sources/AWSPinpointPushNotificationsPlugin/Error/CommonRunTimeError+PushNotificationsErrorConvertible.swift, AmplifyPlugins/Notifications/Push/Sources/AWSPinpointPushNotificationsPlugin/Error/Pinpoint+PushNotificationsErrorConvertible.swift, AmplifyPlugins/Notifications/Push/Sources/AWSPinpointPushNotificationsPlugin/Error/PushNotificationsErrorConvertible.swift, AmplifyPlugins/Notifications/Push/Sources/AWSPinpointPushNotificationsPlugin/Extensions/PushNotificationUserInfo+Pinpoint.swift, AmplifyPlugins/Notifications/Push/Sources/AWSPinpointPushNotificationsPlugin/Support/Constants/PushNotificationsPluginErrorConstants.swift, AmplifyPlugins/Notifications/Push/Tests/AWSPinpointPushNotificationsPluginUnitTests/AWSPinpointPushNotificationsPluginAmplifyVersionableTests.swift, AmplifyPlugins/Notifications/Push/Tests/AWSPinpointPushNotificationsPluginUnitTests/AWSPinpointPushNotificationsPluginClientBehaviourTests.swift, AmplifyPlugins/Notifications/Push/Tests/AWSPinpointPushNotificationsPluginUnitTests/AWSPinpointPushNotificationsPluginConfigureTests.swift, AmplifyPlugins/Notifications/Push/Tests/AWSPinpointPushNotificationsPluginUnitTests/AWSPinpointPushNotificationsPluginResetTests.swift, AmplifyPlugins/Notifications/Push/Tests/AWSPinpointPushNotificationsPluginUnitTests/AWSPinpointPushNotificationsPluginTestBase.swift, AmplifyPlugins/Notifications/Push/Tests/AWSPinpointPushNotificationsPluginUnitTests/ErrorPushNotificationsTests.swift, AmplifyPlugins/Notifications/Push/Tests/AWSPinpointPushNotificationsPluginUnitTests/Mocks/MockAWSPinpoint.swift, AmplifyPlugins/Notifications/Push/Tests/AWSPinpointPushNotificationsPluginUnitTests/Mocks/MockRemoteNotifications.swift, AmplifyPlugins/Notifications/Push/Tests/PushNotificationHostApp/PushNotificationHostApp/ContentView.swift, AmplifyPlugins/Notifications/Push/Tests/PushNotificationHostApp/PushNotificationHostApp/PushNotificationHostAppApp.swift, AmplifyPlugins/Notifications/Push/Tests/PushNotificationHostApp/PushNotificationHostApp/TestConfigHelper.swift, AmplifyPlugins/Notifications/Push/Tests/PushNotificationHostApp/PushNotificationHostAppUITests/LocalServer.swift, AmplifyPlugins/Notifications/Push/Tests/PushNotificationHostApp/PushNotificationHostAppUITests/Notification.swift, AmplifyPlugins/Notifications/Push/Tests/PushNotificationHostApp/PushNotificationHostAppUITests/PushNotificationHostAppUITests.swift
Resolving SwiftFormat errors and warnings for the Notifications plugin.
=> chore(notifications): resolve swiftformat errors and warnings

AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Dependency/UploadPartInput+presignURL.swift
- https://github.com/aws-amplify/amplify-swift/issues/3877
Removing the `testable` annotation when importing `AWSS3` which was added because some types became `internal`. Instead, I'm replicating the types locally.
- https://github.com/aws-amplify/amplify-swift/actions/runs/10945539621
=> fix(Storage): Removing testable import on PresignURL extension

Gemfile.lock
Updating gem depedency and removing `webrick`
=> chore: remove webrick gem dependency

AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/SPI/LivenessStreamingURL.swift
None
We need to construct the correct streaming endpoint with correct base domain depending on the regions. Not all region belong to commercial partition so the base domain becomes different. We can keep adding new regions in this check to get the desired base domain in future.
=> fix(predictions): region handling for creating correct streaming endpoint from region

AmplifyPlugins/Geo/Sources/AWSLocationGeoPlugin/AWSLocationGeoPlugin+ClientBehavior.swift, AmplifyPlugins/Geo/Sources/AWSLocationGeoPlugin/AWSLocationGeoPlugin+Configure.swift, AmplifyPlugins/Geo/Sources/AWSLocationGeoPlugin/AWSLocationGeoPlugin+Reset.swift, AmplifyPlugins/Geo/Sources/AWSLocationGeoPlugin/Configuration/AWSLocationGeoPluginConfiguration.swift, AmplifyPlugins/Geo/Sources/AWSLocationGeoPlugin/Configuration/GeoPluginConfigError.swift, AmplifyPlugins/Geo/Sources/AWSLocationGeoPlugin/Dependency/AWSLocationBehavior.swift, AmplifyPlugins/Geo/Sources/AWSLocationGeoPlugin/Support/Constants/GeoPluginErrorConstants.swift, AmplifyPlugins/Geo/Sources/AWSLocationGeoPlugin/Support/Utils/GeoErrorConvertible.swift, AmplifyPlugins/Geo/Tests/AWSLocationGeoPluginTests/AWSLocationGeoPluginAmplifyVersionableTests.swift, AmplifyPlugins/Geo/Tests/AWSLocationGeoPluginTests/AWSLocationGeoPluginClientBehaviorTests.swift, AmplifyPlugins/Geo/Tests/AWSLocationGeoPluginTests/AWSLocationGeoPluginConfigureTests.swift, AmplifyPlugins/Geo/Tests/AWSLocationGeoPluginTests/AWSLocationGeoPluginResetTests.swift, AmplifyPlugins/Geo/Tests/AWSLocationGeoPluginTests/AWSLocationGeoPluginTestBase.swift, AmplifyPlugins/Geo/Tests/AWSLocationGeoPluginTests/Configuration/AWSLocationGeoPluginAmplifyOutputsConfigurationTests.swift, AmplifyPlugins/Geo/Tests/AWSLocationGeoPluginTests/Configuration/AWSLocationGeoPluginConfigurationTests.swift, AmplifyPlugins/Geo/Tests/AWSLocationGeoPluginTests/Mocks/MockAWSClientConfiguration.swift, AmplifyPlugins/Geo/Tests/AWSLocationGeoPluginTests/Mocks/MockAWSLocation+ClientBehavior.swift, AmplifyPlugins/Geo/Tests/AWSLocationGeoPluginTests/Mocks/MockAWSLocation.swift, AmplifyPlugins/Geo/Tests/AWSLocationGeoPluginTests/Support/Constants/GeoPluginTestConfig.swift, AmplifyPlugins/Geo/Tests/GeoHostApp/AWSLocationGeoPluginIntegrationTests/AWSLocationGeoPluginIntegrationTests.swift, AmplifyPlugins/Geo/Tests/GeoHostApp/GeoStressTests/GeoStressTests.swift
Resolving SwiftFormat errors and warnings for the Geo plugin.
=> chore(geo): resolve swiftformat errors and warnings

.github/composite_actions/run_xcodebuild/action.yml, .github/composite_actions/run_xcodebuild_test/action.yml
This PR replaces `xcpretty` with the faster `xcbeautify`. The change is done mainly because the latest version of `xcpretty` has an [annoying bug](https://github.com/xcpretty/xcpretty/issues/391) that fails to properly display the output when a test fails, rendering it pretty useless.
=> chore: Switching to xcbeautify instead of xcpretty

AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/Service/FaceLivenessSession.swift, AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/Service/WebSocketSession.swift
Customers have reported receiving intermittent `InvalidSignatureException` during liveness checks.
According to Apple docs, `URLSession` delegate queue should use a serial queue for delegate and completion handler callbacks. This PR updates the `URLSession` initializer with a serial queue.
Also, calls to `WebSocketSession` object APIs are put under a serial queue as well.
=> fix(predictions): use serial queue for WebSocketSession delegate queue

Package.resolved, Package.swift
This PR updates [aws-sdk-swift](https://github.com/awslabs/aws-sdk-swift) to 1.0.69, which makes it possible to enable C++ interoperability mode ([ref](https://github.com/awslabs/aws-crt-swift/releases/tag/v0.38.0)).
=> chore: Update aws-sdk-swift to 1.0.69

Amplify/Categories/Auth/Models/AccessGroup.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/AWSCognitoAuthPlugin+Configure.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/AWSCognitoAuthPlugin.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/ClientBehavior/AWSCognitoAuthPlugin+ClientBehavior.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/CredentialStorage/AWSCognitoAuthCredentialStore.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Models/AWSCognitoSecureStoragePreferences.swift, AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/AWSAuthFetchSessionTask.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ActionTests/CredentialStore/MockCredentialStoreBehavior.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ConfigurationTests/AWSCognitoAuthPluginAmplifyOutputsConfigTests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/ConfigurationTests/AWSCognitoAuthPluginConfigTests.swift, AmplifyPlugins/Auth/Tests/AWSCognitoAuthPluginUnitTests/Support/DefaultConfig.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthHostApp.xcodeproj/project.pbxproj, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/AWSAuthBaseTest.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/CredentialStore/CredentialStoreConfigurationTests.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthIntegrationTests/Helpers/AuthEnvironmentHelper.swift, AmplifyPlugins/Auth/Tests/AuthHostApp/AuthWatchApp.entitlements, AmplifyPlugins/Core/AWSPluginsCore/Keychain/KeychainStore.swift, AmplifyPlugins/Core/AWSPluginsCore/Keychain/KeychainStoreAttributes.swift, AmplifyPlugins/Core/AWSPluginsCore/Keychain/KeychainStoreMigrator.swift, AmplifyPlugins/Core/AWSPluginsCoreTests/Keychain/KeychainStoreAttributesTests.swift, AmplifyPlugins/Internal/Tests/InternalAWSPinpointUnitTests/Mocks/MockKeychainStore.swift, api-dump/AWSDataStorePlugin.json, api-dump/AWSPluginsCore.json, api-dump/CoreMLPredictionsPlugin.json
https://github.com/aws-amplify/amplify-swift/issues/2508
https://github.com/aws-amplify/amplify-swift/issues/3277
[![Integration Tests (Except DataStore & API)](https://github.com/aws-amplify/amplify-swift/actions/workflows/integ_test.yml/badge.svg?branch=harsh62%2Fkeychain-sharing-auth-plugin)](https://github.com/aws-amplify/amplify-swift/actions/workflows/integ_test.yml)
[![Integration Tests | DataStore - All](https://github.com/aws-amplify/amplify-swift/actions/workflows/integ_test_datastore.yml/badge.svg?branch=harsh62%2Fkeychain-sharing-auth-plugin)](https://github.com/aws-amplify/amplify-swift/actions/workflows/integ_test_datastore.yml)
[![Integration Tests | API - All](https://github.com/aws-amplify/amplify-swift/actions/workflows/integ_test_api.yml/badge.svg?branch=harsh62%2Fkeycha …
=> feat(auth): adding support for keychain sharing using app groups

.github/workflows/codeql.yml, .github/workflows/stress_test.yml
None
Update GH runner for stress tests and disable debug mode in code ql scanning
=> chore: update stress tests github runner

.github/workflows/build_scheme.yml, .github/workflows/integ_test_auth_webauthn.yml, .github/workflows/integ_test_push_notifications.yml, .github/workflows/run_integration_tests.yml, .github/workflows/run_unit_tests.yml, AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/Service/WebSocketSession.swift
https://github.com/aws-amplify/amplify-ui-swift-liveness/issues/189
AWS Amplify UI Liveness users with `en_TH` locale were observing crashes due to AWS server date being incorrectly formatted. This was occurring due to difference in parsing year in Buddhist Calendar vs. Gregorian calendar. Fix involves setting `en_US_POSIX` locale and GMT timezone in the date formatter.
https://developer.apple.com/library/archive/qa/qa1480/_index.html
=> fix(predictions): use UTC timezone in date formatter
